<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use WP_Error;
use WP_User;
use wpdb;

interface AdminUsers {
	/**
	 * Fetch a filtered list of user roles that the current user is
	 * allowed to edit.
	 *
	 * Simple function whose main purpose is to allow filtering of the
	 * list of roles in the $wp_roles object so that plugins can remove
	 * inappropriate ones depending on the situation or user making edits.
	 * Specifically because without filtering anyone with the edit_users
	 * capability can edit others to be administrators, even if they are
	 * only editors or authors. This filter allows admins to delegate
	 * user management.
	 *
	 * @since 2.8.0
	 *
	 * @return array[] Array of arrays containing role information.
	 */
	public function get_editable_roles();

	/**
	 * Retrieve user data and filter it.
	 *
	 * @since 2.0.5
	 *
	 * @param int $user_id User ID.
	 * @return WP_User|false WP_User object on success, false on failure.
	 */
	public function get_user_to_edit( $user_id );

	/**
	 * Retrieve the user's drafts.
	 *
	 * @since 2.0.0
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param int $user_id User ID.
	 * @return object[] The user's draft posts, with 'ID' and 'post_title' keys.
	 */
	public function get_users_drafts( $user_id );

	/**
	 * Delete user and optionally reassign posts and links to another user.
	 *
	 * Note that on a Multisite installation the user only gets removed from the site
	 * and does not get deleted from the database.
	 *
	 * If the `$reassign` parameter is not assigned to a user ID, then all posts will
	 * be deleted of that user. The action {@see 'delete_user'} that is passed the user ID
	 * being deleted will be run after the posts are either reassigned or deleted.
	 * The user meta will also be deleted that are for that user ID.
	 *
	 * @since 2.0.0
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param int $id       User ID.
	 * @param int $reassign Optional. Reassign posts and links to new User ID.
	 * @return bool True when finished.
	 */
	public function wp_delete_user( $id, $reassign = null );

	/**
	 * Remove all capabilities from user.
	 *
	 * @since 2.1.0
	 *
	 * @param int $id User ID.
	 */
	public function wp_revoke_user( $id );

	/**
	 * Checks if the Authorize Application Password request is valid.
	 *
	 * @since 5.6.0
	 * @since 6.2.0 Allow insecure HTTP connections for the local environment.
	 * @since 6.3.2 Validates the success and reject URLs to prevent `javascript` pseudo protocol from being executed.
	 *
	 * @param array   $request {
	 *     The array of request data. All arguments are optional and may be empty.
	 *
	 *     @type string $app_name    The suggested name of the application.
	 *     @type string $app_id      A UUID provided by the application to uniquely identify it.
	 *     @type string $success_url The URL the user will be redirected to after approving the application.
	 *     @type string $reject_url  The URL the user will be redirected to after rejecting the application.
	 * }
	 * @param WP_User $user The user authorizing the application.
	 * @return true|WP_Error True if the request is valid, a WP_Error object contains errors if not.
	 */
	public function wp_is_authorize_application_password_request_valid( $request, $user );

	/**
	 * Validates the redirect URL protocol scheme.
	 *
	 * The `http` scheme is allowed for loopback IP addresses (127.0.0.1, [::1])
	 * and local environments. The `javascript` and `data` protocols are always rejected.
	 *
	 * @since 6.3.2
	 *
	 * @param string $url The redirect URL to be validated.
	 * @return true|WP_Error True if the redirect URL is valid, a WP_Error object otherwise.
	 */
	public function wp_is_authorize_application_redirect_url_valid( $url );
}
