<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use Walker;
use WP_Error;
use WP_List_Table;
use WP_Locale;
use WP_Post;
use wpdb;

interface AdminTemplate {
	/**
	 * Tests support for compressing JavaScript from PHP.
	 *
	 * Outputs JavaScript that tests if compression from PHP works as expected
	 * and sets an option with the result. Has no effect when the current user
	 * is not an administrator. To run the test again the option 'can_compress_scripts'
	 * has to be deleted.
	 *
	 * @since 2.8.0
	 */
	public function compression_test();

	/**
	 * Outputs the modal window used for attaching media to posts or pages in the media-listing screen.
	 *
	 * @since 2.7.0
	 *
	 * @param string $found_action Optional. The value of the 'found_action' input field. Default empty string.
	 */
	public function find_posts_div( $found_action = '' );

	/**
	 * Adds hidden fields with the data for use in the inline editor for posts and pages.
	 *
	 * @since 2.7.0
	 *
	 * @param WP_Post $post Post object.
	 */
	public function get_inline_data( $post );

	/**
	 * Retrieves an array of media states from an attachment.
	 *
	 * @since 5.6.0
	 *
	 * @param WP_Post $post The attachment to retrieve states for.
	 * @return string[] Array of media state labels keyed by their state.
	 */
	public function get_media_states( $post );

	/**
	 * Retrieves an array of post states from a post.
	 *
	 * @since 5.3.0
	 *
	 * @param WP_Post $post The post to retrieve states for.
	 * @return string[] Array of post state labels keyed by their state.
	 */
	public function get_post_states( $post );

	/**
	 * Returns a submit button, with provided text and appropriate class.
	 *
	 * @since 3.1.0
	 *
	 * @param string       $text             Optional. The text of the button. Defaults to 'Save Changes'.
	 * @param string       $type             Optional. The type and CSS class(es) of the button. Core values
	 *                                       include 'primary', 'small', 'compact' and 'large'. Default 'primary large'.
	 * @param string       $name             Optional. The HTML name of the submit button. If no `id` attribute
	 *                                       is given in the `$other_attributes` parameter, `$name` will be used
	 *                                       as the button's `id`. Default 'submit'.
	 * @param bool         $wrap             Optional. True if the output button should be wrapped in a paragraph tag,
	 *                                       false otherwise. Default true.
	 * @param array|string $other_attributes Optional. Other attributes that should be output with the button,
	 *                                       mapping attributes to their values, e.g. `array( 'id' => 'search-submit' )`.
	 *                                       These key/value attribute pairs will be output as `attribute="value"`,
	 *                                       where attribute is the key. Attributes can also be provided as a string,
	 *                                       e.g. `id="search-submit"`, though the array format is generally preferred.
	 *                                       Default empty string.
	 * @return string Submit button HTML.
	 */
	public function get_submit_button( $text = '', $type = 'primary large', $name = 'submit', $wrap = true, $other_attributes = '' );

	/**
	 * Generic Iframe footer for use with Thickbox.
	 *
	 * @since 2.7.0
	 */
	public function iframe_footer();

	/**
	 * Generic Iframe header for use with Thickbox.
	 *
	 * @since 2.7.0
	 *
	 * @global string    $hook_suffix
	 * @global string    $admin_body_class
	 * @global string    $body_id
	 * @global WP_Locale $wp_locale        WordPress date and time locale object.
	 *
	 * @param string $title      Optional. Title of the Iframe page. Default empty.
	 * @param bool   $deprecated Not used.
	 */
	public function iframe_header( $title = '', $deprecated = false );

	/**
	 * Outputs a post's public meta data in the Custom Fields meta box.
	 *
	 * @since 1.2.0
	 *
	 * @param array[] $meta An array of meta data arrays keyed on 'meta_key' and 'meta_value'.
	 */
	public function list_meta( $meta );

	/**
	 * Prints the form in the Custom Fields meta box.
	 *
	 * @since 1.2.0
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param WP_Post $post Optional. The post being edited.
	 */
	public function meta_form( $post = null );

	/**
	 * Prints out option HTML elements for the page templates drop-down.
	 *
	 * @since 1.5.0
	 * @since 4.7.0 Added the `$post_type` parameter.
	 *
	 * @param string $default_template Optional. The template file name. Default empty.
	 * @param string $post_type        Optional. Post type to get templates for. Default 'page'.
	 */
	public function page_template_dropdown( $default_template = '', $post_type = 'page' );

	/**
	 * Prints out option HTML elements for the page parents drop-down.
	 *
	 * @since 1.5.0
	 * @since 4.4.0 `$post` argument was added.
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param int         $default_page Optional. The default page ID to be pre-selected. Default 0.
	 * @param int         $parent_page  Optional. The parent page ID. Default 0.
	 * @param int         $level        Optional. Page depth level. Default 0.
	 * @param int|WP_Post $post         Post ID or WP_Post object.
	 * @return void|false Void on success, false if the page has no children.
	 */
	public function parent_dropdown( $default_page = 0, $parent_page = 0, $level = 0, $post = null );

	/**
	 * Registers the default admin color schemes.
	 *
	 * Registers the initial set of eight color schemes in the Profile section
	 * of the dashboard which allows for styling the admin menu and toolbar.
	 *
	 * @see wp_admin_css_color()
	 *
	 * @since 3.0.0
	 */
	public function register_admin_color_schemes();

	/**
	 * Echoes a submit button, with provided text and appropriate class(es).
	 *
	 * @since 3.1.0
	 *
	 * @see get_submit_button()
	 *
	 * @param string       $text             Optional. The text of the button. Defaults to 'Save Changes'.
	 * @param string       $type             Optional. The type and CSS class(es) of the button. Core values
	 *                                       include 'primary', 'small', 'compact' and 'large'. Default 'primary'.
	 * @param string       $name             Optional. The HTML name of the submit button. If no `id` attribute
	 *                                       is given in the `$other_attributes` parameter, `$name` will be used
	 *                                       as the button's `id`. Default 'submit'.
	 * @param bool         $wrap             Optional. True if the output button should be wrapped in a paragraph tag,
	 *                                       false otherwise. Default true.
	 * @param array|string $other_attributes Optional. Other attributes that should be output with the button,
	 *                                       mapping attributes to their values, e.g. `array( 'id' => 'search-submit' )`.
	 *                                       These key/value attribute pairs will be output as `attribute="value"`,
	 *                                       where attribute is the key. Attributes can also be provided as a string,
	 *                                       e.g. `id="search-submit"`, though the array format is generally preferred.
	 *                                       Default empty string.
	 */
	public function submit_button( $text = '', $type = 'primary', $name = 'submit', $wrap = true, $other_attributes = '' );

	/**
	 * Displays the post password.
	 *
	 * The password is passed through esc_attr() to ensure that it is safe for placing in an HTML attribute.
	 *
	 * @since 2.7.0
	 */
	public function the_post_password();

	/**
	 * Prints out HTML form date elements for editing post or comment publish date.
	 *
	 * @since 0.71
	 * @since 4.4.0 Converted to use get_comment() instead of the global `$comment`.
	 *
	 * @global WP_Locale $wp_locale WordPress date and time locale object.
	 *
	 * @param int|bool $edit      Accepts 1|true for editing the date, 0|false for adding the date.
	 * @param int|bool $for_post  Accepts 1|true for applying the date to a post, 0|false for a comment.
	 * @param int      $tab_index The tabindex attribute to add. Default 0.
	 * @param int|bool $multi     Optional. Whether the additional fields and buttons should be added.
	 *                            Default 0|false.
	 */
	public function touch_time( $edit = 1, $for_post = 1, $tab_index = 0, $multi = 0 );

	/**
	 * Enqueues or directly prints a stylesheet link to the specified CSS file.
	 *
	 * "Intelligently" decides to enqueue or to print the CSS file. If the
	 * {@see 'wp_print_styles'} action has *not* yet been called, the CSS file will be
	 * enqueued. If the {@see 'wp_print_styles'} action has been called, the CSS link will
	 * be printed. Printing may be forced by passing true as the $force_echo
	 * (second) parameter.
	 *
	 * For backward compatibility with WordPress 2.3 calling method: If the $file
	 * (first) parameter does not correspond to a registered CSS file, we assume
	 * $file is a file relative to wp-admin/ without its ".css" extension. A
	 * stylesheet link to that generated URL is printed.
	 *
	 * @since 2.3.0
	 *
	 * @param string $file       Optional. Style handle name or file name (without ".css" extension) relative
	 *                           to wp-admin/. Defaults to 'wp-admin'.
	 * @param bool   $force_echo Optional. Force the stylesheet link to be printed rather than enqueued.
	 */
	public function wp_admin_css( $file = 'wp-admin', $force_echo = false );

	/**
	 * Registers an admin color scheme css file.
	 *
	 * Allows a plugin to register a new admin color scheme. For example:
	 *
	 *     wp_admin_css_color( 'classic', __( 'Classic' ), admin_url( "css/colors-classic.css" ), array(
	 *         '#07273E', '#14568A', '#D54E21', '#2683AE'
	 *     ) );
	 *
	 * @since 2.5.0
	 *
	 * @global array $_wp_admin_css_colors
	 *
	 * @param string $key    The unique key for this theme.
	 * @param string $name   The name of the theme.
	 * @param string $url    The URL of the CSS file containing the color scheme.
	 * @param array  $colors Optional. An array of CSS color definition strings which are used
	 *                       to give the user a feel for the theme.
	 * @param array  $icons {
	 *     Optional. CSS color definitions used to color any SVG icons.
	 *
	 *     @type string $base    SVG icon base color.
	 *     @type string $focus   SVG icon color on focus.
	 *     @type string $current SVG icon color of current admin menu link.
	 * }
	 */
	public function wp_admin_css_color( $key, $name, $url, $colors = array(), $icons = array() );

	/**
	 * Displays the URL of a WordPress admin CSS file.
	 *
	 * @see WP_Styles::_css_href() and its {@see 'style_loader_src'} filter.
	 *
	 * @since 2.3.0
	 *
	 * @param string $file file relative to wp-admin/ without its ".css" extension.
	 * @return string
	 */
	public function wp_admin_css_uri( $file = 'wp-admin' );

	/**
	 * Outputs an unordered list of checkbox input elements labeled with category names.
	 *
	 * @since 2.5.1
	 *
	 * @see wp_terms_checklist()
	 *
	 * @param int         $post_id              Optional. Post to generate a categories checklist for. Default 0.
	 *                                          $selected_cats must not be an array. Default 0.
	 * @param int         $descendants_and_self Optional. ID of the category to output along with its descendants.
	 *                                          Default 0.
	 * @param int[]|false $selected_cats        Optional. Array of category IDs to mark as checked. Default false.
	 * @param int[]|false $popular_cats         Optional. Array of category IDs to receive the "popular-category" class.
	 *                                          Default false.
	 * @param Walker      $walker               Optional. Walker object to use to build the output.
	 *                                          Default is a Walker_Category_Checklist instance.
	 * @param bool        $checked_ontop        Optional. Whether to move checked items out of the hierarchy and to
	 *                                          the top of the list. Default true.
	 */
	public function wp_category_checklist( $post_id = 0, $descendants_and_self = 0, $selected_cats = false, $popular_cats = false, $walker = null, $checked_ontop = true );

	/**
	 * Outputs the in-line comment reply-to form in the Comments list table.
	 *
	 * @since 2.7.0
	 *
	 * @global WP_List_Table $wp_list_table
	 *
	 * @param int    $position  Optional. The value of the 'position' input field. Default 1.
	 * @param bool   $checkbox  Optional. The value of the 'checkbox' input field. Default false.
	 * @param string $mode      Optional. If set to 'single', will use WP_Post_Comments_List_Table,
	 *                          otherwise WP_Comments_List_Table. Default 'single'.
	 * @param bool   $table_row Optional. Whether to use a table instead of a div element. Default true.
	 */
	public function wp_comment_reply( $position = 1, $checkbox = false, $mode = 'single', $table_row = true );

	/**
	 * Outputs 'undo move to Trash' text for comments.
	 *
	 * @since 2.9.0
	 */
	public function wp_comment_trashnotice();

	/**
	 * Prints out option HTML elements for role selectors.
	 *
	 * @since 2.1.0
	 * @since 7.0.0 Added $editable_roles parameter.
	 *
	 * @param string $selected       Slug for the role that should be already selected.
	 * @param array  $editable_roles Array of roles to include in the dropdown. Defaults to all
	 *                               roles the current user is allowed to edit.
	 */
	public function wp_dropdown_roles( $selected = '', $editable_roles = null );

	/**
	 * Default settings for heartbeat.
	 *
	 * Outputs the nonce used in the heartbeat XHR.
	 *
	 * @since 3.6.0
	 *
	 * @param array $settings
	 * @return array Heartbeat settings.
	 */
	public function wp_heartbeat_settings( $settings );

	/**
	 * Outputs the form used by the importers to accept the data to be imported.
	 *
	 * @since 2.0.0
	 *
	 * @param string $action The action attribute for the form.
	 */
	public function wp_import_upload_form( $action );

	/**
	 * Outputs a link category checklist element.
	 *
	 * @since 2.5.1
	 *
	 * @param int $link_id Optional. The link ID. Default 0.
	 */
	public function wp_link_category_checklist( $link_id = 0 );

	/**
	 * Retrieves a list of the most popular terms from the specified taxonomy.
	 *
	 * If the `$display` argument is true then the elements for a list of checkbox
	 * `<input>` elements labelled with the names of the selected terms is output.
	 * If the `$post_ID` global is not empty then the terms associated with that
	 * post will be marked as checked.
	 *
	 * @since 2.5.0
	 *
	 * @param string $taxonomy     Taxonomy to retrieve terms from.
	 * @param int    $default_term Optional. Not used.
	 * @param int    $number       Optional. Number of terms to retrieve. Default 10.
	 * @param bool   $display      Optional. Whether to display the list as well. Default true.
	 * @return int[] Array of popular term IDs.
	 */
	public function wp_popular_terms_checklist( $taxonomy, $default_term = 0, $number = 10, $display = true );

	/**
	 * Outputs a HTML element with a star rating for a given rating.
	 *
	 * Outputs a HTML element with the star rating exposed on a 0..5 scale in
	 * half star increments (ie. 1, 1.5, 2 stars). Optionally, if specified, the
	 * number of ratings may also be displayed by passing the $number parameter.
	 *
	 * @since 3.8.0
	 * @since 4.4.0 Introduced the `echo` parameter.
	 *
	 * @param array $args {
	 *     Optional. Array of star ratings arguments.
	 *
	 *     @type int|float $rating The rating to display, expressed in either a 0.5 rating increment,
	 *                             or percentage. Default 0.
	 *     @type string    $type   Format that the $rating is in. Valid values are 'rating' (default),
	 *                             or, 'percent'. Default 'rating'.
	 *     @type int       $number The number of ratings that makes up this rating. Default 0.
	 *     @type bool      $echo   Whether to echo the generated markup. False to return the markup instead
	 *                             of echoing it. Default true.
	 * }
	 * @return string Star rating HTML.
	 */
	public function wp_star_rating( $args = array() );

	/**
	 * Outputs an unordered list of checkbox input elements labelled with term names.
	 *
	 * Taxonomy-independent version of wp_category_checklist().
	 *
	 * @since 3.0.0
	 * @since 4.4.0 Introduced the `$echo` argument.
	 *
	 * @param int          $post_id Optional. Post ID. Default 0.
	 * @param array|string $args {
	 *     Optional. Array or string of arguments for generating a terms checklist. Default empty array.
	 *
	 *     @type int    $descendants_and_self ID of the category to output along with its descendants.
	 *                                        Default 0.
	 *     @type int[]  $selected_cats        Array of category IDs to mark as checked. Default false.
	 *     @type int[]  $popular_cats         Array of category IDs to receive the "popular-category" class.
	 *                                        Default false.
	 *     @type Walker $walker               Walker object to use to build the output. Default empty which
	 *                                        results in a Walker_Category_Checklist instance being used.
	 *     @type string $taxonomy             Taxonomy to generate the checklist for. Default 'category'.
	 *     @type bool   $checked_ontop        Whether to move checked items out of the hierarchy and to
	 *                                        the top of the list. Default true.
	 *     @type bool   $echo                 Whether to echo the generated markup. False to return the markup instead
	 *                                        of echoing it. Default true.
	 * }
	 * @return string HTML list of input elements.
	 */
	public function wp_terms_checklist( $post_id = 0, $args = array() );

	/**
	 * Displays the given administration message.
	 *
	 * @since 2.1.0
	 *
	 * @param string|WP_Error $message The message to display, or a WP_Error object.
	 */
	public function show_message( $message );

	/**
	 * Outputs an admin notice.
	 *
	 * @since 6.4.0
	 *
	 * @param string $message The message to output.
	 * @param array  $args {
	 *     Optional. An array of arguments for the admin notice. Default empty array.
	 *
	 *     @type string   $type               Optional. The type of admin notice.
	 *                                        For example, 'error', 'success', 'warning', 'info'.
	 *                                        Default empty string.
	 *     @type bool     $dismissible        Optional. Whether the admin notice is dismissible. Default false.
	 *     @type string   $id                 Optional. The value of the admin notice's ID attribute. Default empty string.
	 *     @type string[] $additional_classes Optional. A string array of class names. Default empty array.
	 *     @type string[] $attributes         Optional. Additional attributes for the notice div. Default empty array.
	 *     @type bool     $paragraph_wrap     Optional. Whether to wrap the message in paragraph tags. Default true.
	 * }
	 */
	public function wp_admin_notice( $message, $args = array() );

	/**
	 * Creates and returns the markup for an admin notice.
	 *
	 * @since 6.4.0
	 *
	 * @param string $message The message.
	 * @param array  $args {
	 *     Optional. An array of arguments for the admin notice. Default empty array.
	 *
	 *     @type string   $type               Optional. The type of admin notice.
	 *                                        For example, 'error', 'success', 'warning', 'info'.
	 *                                        Default empty string.
	 *     @type bool     $dismissible        Optional. Whether the admin notice is dismissible. Default false.
	 *     @type string   $id                 Optional. The value of the admin notice's ID attribute. Default empty string.
	 *     @type string[] $additional_classes Optional. A string array of class names. Default empty array.
	 *     @type string[] $attributes         Optional. Additional attributes for the notice div. Default empty array.
	 *     @type bool     $paragraph_wrap     Optional. Whether to wrap the message in paragraph tags. Default true.
	 * }
	 * @return string The markup for an admin notice.
	 */
	public function wp_get_admin_notice( $message, $args = array() );
}
