<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use WP_Error;
use WP_Post;
use WP_User;
use wpdb;

interface AdminPosts {
	/**
	 * Determines if a post exists based on title, content, date and type.
	 *
	 * @since 2.0.0
	 * @since 5.2.0 Added the `$type` parameter.
	 * @since 5.8.0 Added the `$status` parameter.
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param string $title   Post title.
	 * @param string $content Optional. Post content.
	 * @param string $date    Optional. Post date.
	 * @param string $type    Optional. Post type.
	 * @param string $status  Optional. Post status.
	 * @return int Post ID if post exists, 0 otherwise.
	 */
	public function post_exists( $title, $content = '', $date = '', $type = '', $status = '' );

	/**
	 * Returns default post information to use when populating the "Write Post" form.
	 *
	 * @since 2.0.0
	 *
	 * @param string $post_type    Optional. A post type string. Default 'post'.
	 * @param bool   $create_in_db Optional. Whether to insert the post into database. Default false.
	 * @return WP_Post Post object containing all the default post data as attributes
	 */
	public function get_default_post_to_edit( $post_type = 'post', $create_in_db = false );

	/**
	 * Returns all the possible statuses for a post type.
	 *
	 * @since 2.5.0
	 *
	 * @param string $type The post_type you want the statuses for. Default 'post'.
	 * @return string[] An array of all the statuses for the supplied post type.
	 */
	public function get_available_post_statuses( $type = 'post' );

	/**
	 * Creates a new post from the "Write Post" form using `$_POST` information.
	 *
	 * @since 2.1.0
	 *
	 * @global WP_User $current_user
	 *
	 * @return int|WP_Error Post ID on success, WP_Error on failure.
	 */
	public function wp_write_post();

	/**
	 * Calls wp_write_post() and handles the errors.
	 *
	 * @since 2.0.0
	 *
	 * @return int Post ID on success. Dies on failure.
	 */
	public function write_post();

	/**
	 * Updates an existing post with values provided in `$_POST`.
	 *
	 * If post data is passed as an argument, it is treated as an array of data
	 * keyed appropriately for turning into a post object.
	 *
	 * If post data is not passed, the `$_POST` global variable is used instead.
	 *
	 * @since 1.5.0
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param array|null $post_data Optional. The array of post data to process.
	 *                              Defaults to the `$_POST` superglobal.
	 * @return int Post ID.
	 */
	public function edit_post( $post_data = null );

	/**
	 * Processes the post data for the bulk editing of posts.
	 *
	 * Updates all bulk edited posts/pages, adding (but not removing) tags and
	 * categories. Skips pages when they would be their own parent or child.
	 *
	 * @since 2.7.0
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param array|null $post_data Optional. The array of post data to process.
	 *                              Defaults to the `$_POST` superglobal.
	 * @return array {
	 *     An array of updated, skipped, and locked post IDs.
	 *
	 *     @type int[] $updated An array of updated post IDs.
	 *     @type int[] $skipped An array of skipped post IDs.
	 *     @type int[] $locked  An array of locked post IDs.
	 * }
	 */
	public function bulk_edit_posts( $post_data = null );

	/**
	 * Creates autosave data for the specified post from `$_POST` data.
	 *
	 * @since 2.6.0
	 *
	 * @param array|int $post_data Associative array containing the post data, or integer post ID.
	 *                             If a numeric post ID is provided, will use the `$_POST` superglobal.
	 * @return int|WP_Error The autosave revision ID. WP_Error or 0 on error.
	 */
	public function wp_create_post_autosave( $post_data );

	/**
	 * Saves a post submitted with XHR.
	 *
	 * Intended for use with heartbeat and autosave.js
	 *
	 * @since 3.9.0
	 *
	 * @param array $post_data Associative array of the submitted post data.
	 * @return mixed The value 0 or WP_Error on failure. The saved post ID on success.
	 *               The ID can be the draft post_id or the autosave revision post_id.
	 */
	public function wp_autosave( $post_data );

	/**
	 * Saves a draft or manually autosaves for the purpose of showing a post preview.
	 *
	 * @since 2.7.0
	 *
	 * @return string URL to redirect to show the preview.
	 */
	public function post_preview();

	/**
	 * Redirects to previous page.
	 *
	 * @since 2.7.0
	 *
	 * @param int $post_id Optional. Post ID.
	 * @return never
	 */
	public function redirect_post( $post_id = 0 );

	/**
	 * Returns a sample permalink based on the post name.
	 *
	 * @since 2.5.0
	 *
	 * @param int|WP_Post $post  Post ID or post object.
	 * @param string|null $title Optional. Title to override the post's current title
	 *                           when generating the post name. Default null.
	 * @param string|null $name  Optional. Name to override the post name. Default null.
	 * @return array {
	 *     Array containing the sample permalink with placeholder for the post name, and the post name.
	 *
	 *     @type string $0 The permalink with placeholder for the post name.
	 *     @type string $1 The post name.
	 * }
	 */
	public function get_sample_permalink( $post, $title = null, $name = null );

	/**
	 * Returns the HTML of the sample permalink slug editor.
	 *
	 * @since 2.5.0
	 *
	 * @param int|WP_Post $post      Post ID or post object.
	 * @param string|null $new_title Optional. New title. Default null.
	 * @param string|null $new_slug  Optional. New slug. Default null.
	 * @return string The HTML of the sample permalink slug editor.
	 */
	public function get_sample_permalink_html( $post, $new_title = null, $new_slug = null );

	/**
	 * Determines whether the post is currently being edited by another user.
	 *
	 * @since 2.5.0
	 *
	 * @param int|WP_Post $post ID or object of the post to check for editing.
	 * @return int|false ID of the user with lock. False if the post does not exist, post is not locked,
	 *                   the user with lock does not exist, or the post is locked by current user.
	 */
	public function wp_check_post_lock( $post );

	/**
	 * Marks the post as currently being edited by the current user.
	 *
	 * @since 2.5.0
	 *
	 * @param int|WP_Post $post ID or object of the post being edited.
	 * @return array|false {
	 *     Array of the lock time and user ID. False if the post does not exist, or there
	 *     is no current user.
	 *
	 *     @type int $0 The current time as a Unix timestamp.
	 *     @type int $1 The ID of the current user.
	 * }
	 */
	public function wp_set_post_lock( $post );

	/**
	 * Runs the query to fetch the posts for listing on the edit posts page.
	 *
	 * @since 2.5.0
	 *
	 * @param array|false $q Optional. Array of query variables to use to build the query.
	 *                       Defaults to the `$_GET` superglobal.
	 * @return string[] An array of all the statuses for the queried post type.
	 */
	public function wp_edit_posts_query( $q = false );

	/**
	 * Returns the query variables for the current attachments request.
	 *
	 * @since 4.2.0
	 *
	 * @param array|false $q Optional. Array of query variables to use to build the query.
	 *                       Defaults to the `$_GET` superglobal.
	 * @return array The parsed query vars.
	 */
	public function wp_edit_attachments_query_vars( $q = false );

	/**
	 * Executes a query for attachments. An array of WP_Query arguments
	 * can be passed in, which will override the arguments set by this function.
	 *
	 * @since 2.5.0
	 *
	 * @param array|false $q Optional. Array of query variables to use to build the query.
	 *                       Defaults to the `$_GET` superglobal.
	 * @return array {
	 *     Array containing the post mime types and available post mime types.
	 *
	 *     @type array[]  $post_mime_types       Post mime types.
	 *     @type string[] $avail_post_mime_types Available post mime types.
	 * }
	 */
	public function wp_edit_attachments_query( $q = false );
}
