<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use WP_Locale;
use wpdb;

interface ArchiveTemplate {
	/**
	 * Gets number of days since the start of the week.
	 *
	 * @since 1.5.0
	 *
	 * @param int $num Number of day.
	 * @return float Days since the start of the week.
	 */
	public function calendar_week_mod( $num );

	/**
	 * Purges the cached results of get_calendar.
	 *
	 * @see get_calendar()
	 * @since 2.1.0
	 */
	public function delete_get_calendar_cache();

	/**
	 * Retrieves archive link content based on predefined or custom code.
	 *
	 * The format can be one of four styles. The 'link' for head element, 'option'
	 * for use in the select element, 'html' for use in list (either ol or ul HTML
	 * elements). Custom content is also supported using the before and after
	 * parameters.
	 *
	 * The 'link' format uses the `<link>` HTML element with the **archives**
	 * relationship. The before and after parameters are not used. The text
	 * parameter is used to describe the link.
	 *
	 * The 'option' format uses the option HTML element for use in select element.
	 * The value is the url parameter and the before and after parameters are used
	 * between the text description.
	 *
	 * The 'html' format, which is the default, uses the li HTML element for use in
	 * the list HTML elements. The before parameter is before the link and the after
	 * parameter is after the closing link.
	 *
	 * The custom format uses the before parameter before the link ('a' HTML
	 * element) and the after parameter after the closing link tag. If the above
	 * three values for the format are not used, then custom format is assumed.
	 *
	 * @since 1.0.0
	 * @since 5.2.0 Added the `$selected` parameter.
	 *
	 * @param string $url      URL to archive.
	 * @param string $text     Archive text description.
	 * @param string $format   Optional. Can be 'link', 'option', 'html', or custom. Default 'html'.
	 * @param string $before   Optional. Content to prepend to the description. Default empty.
	 * @param string $after    Optional. Content to append to the description. Default empty.
	 * @param bool   $selected Optional. Set to true if the current page is the selected archive page. Default false.
	 * @return string HTML link content for archive.
	 */
	public function get_archives_link( $url, $text, $format = 'html', $before = '', $after = '', $selected = false );

	/**
	 * Displays calendar with days that have posts as links.
	 *
	 * The calendar is cached, which will be retrieved, if it exists. If there are
	 * no posts for the month, then it will not be displayed.
	 *
	 * @since 1.0.0
	 * @since 6.8.0 Added the `$args` parameter, with backward compatibility
	 *              for the replaced `$initial` and `$display` parameters.
	 *
	 * @global wpdb      $wpdb      WordPress database abstraction object.
	 * @global int       $m
	 * @global int       $monthnum
	 * @global int       $year
	 * @global WP_Locale $wp_locale WordPress date and time locale object.
	 * @global array     $posts
	 *
	 * @param array $args {
	 *     Optional. Arguments for the `get_calendar` function.
	 *
	 *     @type bool   $initial   Whether to use initial calendar names. Default true.
	 *     @type bool   $display   Whether to display the calendar output. Default true.
	 *     @type string $post_type Optional. Post type. Default 'post'.
	 * }
	 * @return void|string Void if `$display` argument is true, calendar HTML if `$display` is false.
	 */
	public function get_calendar( $args = array() );

	/**
	 * Retrieves the description for an author, post type, or term archive.
	 *
	 * @since 4.1.0
	 * @since 4.7.0 Added support for author archives.
	 * @since 4.9.0 Added support for post type archives.
	 *
	 * @see term_description()
	 *
	 * @return string Archive description.
	 */
	public function get_the_archive_description();

	/**
	 * Retrieves the archive title based on the queried object.
	 *
	 * @since 4.1.0
	 * @since 5.5.0 The title part is wrapped in a `<span>` element.
	 *
	 * @return string Archive title.
	 */
	public function get_the_archive_title();

	/**
	 * Retrieves the description for a post type archive.
	 *
	 * @since 4.9.0
	 *
	 * @return string The post type description.
	 */
	public function get_the_post_type_description();

	/**
	 * Displays or retrieves title for a post type archive.
	 *
	 * This is optimized for archive.php and archive-{$post_type}.php template files
	 * for displaying the title of the post type.
	 *
	 * @since 3.1.0
	 *
	 * @param string $prefix  Optional. What to display before the title.
	 * @param bool   $display Optional. Whether to display or retrieve title. Default true.
	 * @return string|null Title when retrieving, null when displaying or on failure.
	 */
	public function post_type_archive_title( $prefix = '', $display = true );

	/**
	 * Displays or retrieves page title for category archive.
	 *
	 * Useful for category template files for displaying the category page title.
	 * The prefix does not automatically place a space between the prefix, so if
	 * there should be a space, the parameter value will need to have it at the end.
	 *
	 * @since 0.71
	 *
	 * @param string $prefix  Optional. What to display before the title.
	 * @param bool   $display Optional. Whether to display or retrieve title. Default true.
	 * @return string|null Title when retrieving.
	 */
	public function single_cat_title( $prefix = '', $display = true );

	/**
	 * Displays or retrieves page title for post archive based on date.
	 *
	 * Useful for when the template only needs to display the month and year,
	 * if either are available. The prefix does not automatically place a space
	 * between the prefix, so if there should be a space, the parameter value
	 * will need to have it at the end.
	 *
	 * @since 0.71
	 *
	 * @global WP_Locale $wp_locale WordPress date and time locale object.
	 *
	 * @param string $prefix  Optional. What to display before the title.
	 * @param bool   $display Optional. Whether to display or retrieve title. Default true.
	 * @return string|false|null False if there's no valid title for the month. Title when retrieving.
	 */
	public function single_month_title( $prefix = '', $display = true );

	/**
	 * Displays or retrieves page title for post.
	 *
	 * This is optimized for single.php template file for displaying the post title.
	 *
	 * It does not support placing the separator after the title, but by leaving the
	 * prefix parameter empty, you can set the title separator manually. The prefix
	 * does not automatically place a space between the prefix, so if there should
	 * be a space, the parameter value will need to have it at the end.
	 *
	 * @since 0.71
	 *
	 * @param string $prefix  Optional. What to display before the title.
	 * @param bool   $display Optional. Whether to display or retrieve title. Default true.
	 * @return string|null Title when retrieving.
	 */
	public function single_post_title( $prefix = '', $display = true );

	/**
	 * Displays or retrieves page title for tag post archive.
	 *
	 * Useful for tag template files for displaying the tag page title. The prefix
	 * does not automatically place a space between the prefix, so if there should
	 * be a space, the parameter value will need to have it at the end.
	 *
	 * @since 2.3.0
	 *
	 * @param string $prefix  Optional. What to display before the title.
	 * @param bool   $display Optional. Whether to display or retrieve title. Default true.
	 * @return string|null Title when retrieving.
	 */
	public function single_tag_title( $prefix = '', $display = true );

	/**
	 * Displays or retrieves page title for taxonomy term archive.
	 *
	 * Useful for taxonomy term template files for displaying the taxonomy term page title.
	 * The prefix does not automatically place a space between the prefix, so if there should
	 * be a space, the parameter value will need to have it at the end.
	 *
	 * @since 3.1.0
	 *
	 * @param string $prefix  Optional. What to display before the title.
	 * @param bool   $display Optional. Whether to display or retrieve title. Default true.
	 * @return string|null Title when retrieving.
	 */
	public function single_term_title( $prefix = '', $display = true );

	/**
	 * Displays category, tag, term, or author description.
	 *
	 * @since 4.1.0
	 *
	 * @see get_the_archive_description()
	 *
	 * @param string $before Optional. Content to prepend to the description. Default empty.
	 * @param string $after  Optional. Content to append to the description. Default empty.
	 */
	public function the_archive_description( $before = '', $after = '' );

	/**
	 * Displays the archive title based on the queried object.
	 *
	 * @since 4.1.0
	 *
	 * @see get_the_archive_title()
	 *
	 * @param string $before Optional. Content to prepend to the title. Default empty.
	 * @param string $after  Optional. Content to append to the title. Default empty.
	 */
	public function the_archive_title( $before = '', $after = '' );

	/**
	 * Displays archive links based on type and format.
	 *
	 * @since 1.2.0
	 * @since 4.4.0 The `$post_type` argument was added.
	 * @since 5.2.0 The `$year`, `$monthnum`, `$day`, and `$w` arguments were added.
	 *
	 * @see get_archives_link()
	 *
	 * @global wpdb      $wpdb      WordPress database abstraction object.
	 * @global WP_Locale $wp_locale WordPress date and time locale object.
	 *
	 * @param string|array $args {
	 *     Default archive links arguments. Optional.
	 *
	 *     @type string     $type            Type of archive to retrieve. Accepts 'daily', 'weekly', 'monthly',
	 *                                       'yearly', 'postbypost', or 'alpha'. Both 'postbypost' and 'alpha'
	 *                                       display the same archive link list as well as post titles instead
	 *                                       of displaying dates. The difference between the two is that 'alpha'
	 *                                       will order by post title and 'postbypost' will order by post date.
	 *                                       Default 'monthly'.
	 *     @type string|int $limit           Number of links to limit the query to. Default empty (no limit).
	 *     @type string     $format          Format each link should take using the $before and $after args.
	 *                                       Accepts 'link' (`<link>` tag), 'option' (`<option>` tag), 'html'
	 *                                       (`<li>` tag), or a custom format, which generates a link anchor
	 *                                       with $before preceding and $after succeeding. Default 'html'.
	 *     @type string     $before          Markup to prepend to the beginning of each link. Default empty.
	 *     @type string     $after           Markup to append to the end of each link. Default empty.
	 *     @type bool       $show_post_count Whether to display the post count alongside the link. Default false.
	 *     @type bool|int   $echo            Whether to echo or return the links list. Default 1|true to echo.
	 *     @type string     $order           Whether to use ascending or descending order. Accepts 'ASC', or 'DESC'.
	 *                                       Default 'DESC'.
	 *     @type string     $post_type       Post type. Default 'post'.
	 *     @type string     $year            Year. Default current year.
	 *     @type string     $monthnum        Month number. Default current month number.
	 *     @type string     $day             Day. Default current day.
	 *     @type string     $w               Week. Default current week.
	 * }
	 * @return void|string Void if 'echo' argument is true, archive links if 'echo' is false.
	 */
	public function wp_get_archives( $args = '' );
}
