<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use InvalidArgumentException;
use TypeError;
use WP_Error;
use WP_User;
use wpdb;

interface Auth {
	/**
	 * Returns a cryptographically secure hash of a message using a fast generic hash function.
	 *
	 * Use the wp_verify_fast_hash() function to verify the hash.
	 *
	 * This function does not salt the value prior to being hashed, therefore input to this function must originate from
	 * a random generator with sufficiently high entropy, preferably greater than 128 bits. This function is used internally
	 * in WordPress to hash security keys and application passwords which are generated with high entropy.
	 *
	 * Important:
	 *
	 *  - This function must not be used for hashing user-generated passwords. Use wp_hash_password() for that.
	 *  - This function must not be used for hashing other low-entropy input. Use wp_hash() for that.
	 *
	 * The BLAKE2b algorithm is used by Sodium to hash the message.
	 *
	 * @since 6.8.0
	 *
	 * @throws TypeError Thrown by Sodium if the message is not a string.
	 *
	 * @param string $message The message to hash.
	 * @return string The hash of the message.
	 */
	public function wp_fast_hash( string $message ): string;

	/**
	 * Checks whether a plaintext message matches the hashed value. Used to verify values hashed via wp_fast_hash().
	 *
	 * The function uses Sodium to hash the message and compare it to the hashed value. If the hash is not a generic hash,
	 * the hash is treated as a phpass portable hash in order to provide backward compatibility for passwords and security
	 * keys which were hashed using phpass prior to WordPress 6.8.0.
	 *
	 * @since 6.8.0
	 *
	 * @throws TypeError Thrown by Sodium if the message is not a string.
	 *
	 * @param string $message The plaintext message.
	 * @param string $hash    Hash of the message to check against.
	 * @return bool Whether the message matches the hashed message.
	 */
	public function wp_verify_fast_hash( string $message, string $hash ): bool;

	/**
	 * Authenticates and logs a user in with 'remember' capability.
	 *
	 * The credentials is an array that has 'user_login', 'user_password', and
	 * 'remember' indices. If the credentials is not given, then the log in form
	 * will be assumed and used if set.
	 *
	 * The various authentication cookies will be set by this function and will be
	 * set for a longer period depending on if the 'remember' credential is set to
	 * true.
	 *
	 * Note: wp_signon() doesn't handle setting the current user. This means that if the
	 * function is called before the {@see 'init'} hook is fired, is_user_logged_in() will
	 * evaluate as false until that point. If is_user_logged_in() is needed in conjunction
	 * with wp_signon(), wp_set_current_user() should be called explicitly.
	 *
	 * @since 2.5.0
	 *
	 * @global string $auth_secure_cookie
	 * @global wpdb   $wpdb               WordPress database abstraction object.
	 *
	 * @param array       $credentials {
	 *     Optional. User info in order to sign on.
	 *
	 *     @type string $user_login    Username.
	 *     @type string $user_password User password.
	 *     @type bool   $remember      Whether to 'remember' the user. Increases the time
	 *                                 that the cookie will be kept. Default false.
	 * }
	 * @param string|bool $secure_cookie Optional. Whether to use secure cookie.
	 * @return WP_User|WP_Error WP_User on success, WP_Error on failure.
	 */
	public function wp_signon( $credentials = array(), $secure_cookie = '' );

	/**
	 * Authenticates a user, confirming the login credentials are valid.
	 *
	 * @since 2.5.0
	 * @since 4.5.0 `$username` now accepts an email address.
	 *
	 * @param string $username User's username or email address.
	 * @param string $password User's password.
	 * @return WP_User|WP_Error WP_User object if the credentials are valid,
	 *                          otherwise WP_Error.
	 */
	public function wp_authenticate( $username, $password );

	/**
	 * Logs the current user out.
	 *
	 * @since 2.5.0
	 */
	public function wp_logout();

	/**
	 * Checks if a user is logged in, if not it redirects them to the login page.
	 *
	 * When this code is called from a page, it checks to see if the user viewing the page is logged in.
	 * If the user is not logged in, they are redirected to the login page. The user is redirected
	 * in such a way that, upon logging in, they will be sent directly to the page they were originally
	 * trying to access.
	 *
	 * @since 1.5.0
	 */
	public function auth_redirect();

	/**
	 * Sets the authentication cookies for a given user ID.
	 *
	 * The `$remember` parameter controls cookie persistence:
	 * - If true, the cookie is persistent (default 14 days, filterable via {@see 'auth_cookie_expiration'}).
	 * - If false, the cookie is a browser session cookie (expires when the browser closes).
	 *   Internally, {@see 'auth_cookie_expiration'} is still applied, to expire the login after
	 *   two days or when the browser is closed, whichever occurs first.
	 *
	 * @since 2.5.0
	 * @since 4.3.0 Added the `$token` parameter.
	 *
	 * @param int         $user_id  User ID.
	 * @param bool        $remember Whether to remember the user.
	 * @param bool|string $secure   Whether the auth cookie should only be sent over HTTPS. Default is an empty
	 *                              string which means the value of `is_ssl()` will be used.
	 * @param string      $token    Optional. User's session token to use for this cookie.
	 */
	public function wp_set_auth_cookie( $user_id, $remember = false, $secure = '', $token = '' );

	/**
	 * Removes all of the cookies associated with authentication.
	 *
	 * @since 2.5.0
	 */
	public function wp_clear_auth_cookie();

	/**
	 * Generates authentication cookie contents.
	 *
	 * @since 2.5.0
	 * @since 4.0.0 The `$token` parameter was added.
	 *
	 * @param int    $user_id    User ID.
	 * @param int    $expiration The time the cookie expires as a UNIX timestamp.
	 * @param string $scheme     Optional. The cookie scheme to use: 'auth', 'secure_auth', or 'logged_in'.
	 *                           Default 'auth'.
	 * @param string $token      User's session token to use for this cookie.
	 * @return string Authentication cookie contents. Empty string if user does not exist.
	 */
	public function wp_generate_auth_cookie( $user_id, $expiration, $scheme = 'auth', $token = '' );

	/**
	 * Parses a cookie into its components.
	 *
	 * @since 2.7.0
	 * @since 4.0.0 The `$token` element was added to the return value.
	 *
	 * @param string $cookie Authentication cookie.
	 * @param string $scheme Optional. The cookie scheme to use: 'auth', 'secure_auth', or 'logged_in'.
	 * @return string[]|false {
	 *     Authentication cookie components. None of the components should be assumed
	 *     to be valid as they come directly from a client-provided cookie value. If
	 *     the cookie value is malformed, false is returned.
	 *
	 *     @type string $username   User's username.
	 *     @type string $expiration The time the cookie expires as a UNIX timestamp.
	 *     @type string $token      User's session token used.
	 *     @type string $hmac       The security hash for the cookie.
	 *     @type string $scheme     The cookie scheme to use.
	 * }
	 */
	public function wp_parse_auth_cookie( $cookie = '', $scheme = '' );

	/**
	 * Validates authentication cookie.
	 *
	 * The checks include making sure that the authentication cookie is set and
	 * pulling in the contents (if $cookie is not used).
	 *
	 * Makes sure the cookie is not expired. Verifies the hash in cookie is what is
	 * should be and compares the two.
	 *
	 * @since 2.5.0
	 *
	 * @global int $login_grace_period
	 *
	 * @param string $cookie Optional. If used, will validate contents instead of cookie's.
	 * @param string $scheme Optional. The cookie scheme to use: 'auth', 'secure_auth', or 'logged_in'.
	 *                       Note: This does *not* default to 'auth' like other cookie functions.
	 * @return int|false User ID if valid cookie, false if invalid.
	 */
	public function wp_validate_auth_cookie( $cookie = '', $scheme = '' );

	/**
	 * Retrieves the current session token from the logged_in cookie.
	 *
	 * @since 4.0.0
	 *
	 * @return string Token.
	 */
	public function wp_get_session_token();

	/**
	 * Retrieves a list of sessions for the current user.
	 *
	 * @since 4.0.0
	 *
	 * @return array Array of sessions.
	 */
	public function wp_get_all_sessions();

	/**
	 * Removes the current session token from the database.
	 *
	 * @since 4.0.0
	 */
	public function wp_destroy_current_session();

	/**
	 * Removes all but the current session token for the current user for the database.
	 *
	 * @since 4.0.0
	 */
	public function wp_destroy_other_sessions();

	/**
	 * Removes all session tokens for the current user from the database.
	 *
	 * @since 4.0.0
	 */
	public function wp_destroy_all_sessions();

	/**
	 * Returns a salt to add to hashes.
	 *
	 * Salts are created using secret keys. Secret keys are located in two places:
	 * in the database and in the wp-config.php file. The secret key in the database
	 * is randomly generated and will be appended to the secret keys in wp-config.php.
	 *
	 * The secret keys in wp-config.php should be updated to strong, random keys to maximize
	 * security. Below is an example of how the secret key constants are defined.
	 * Do not paste this example directly into wp-config.php. Instead, have a
	 * {@link https://api.wordpress.org/secret-key/1.1/salt/ secret key created} just
	 * for you.
	 *
	 *     define('AUTH_KEY',         ' Xakm<o xQy rw4EMsLKM-?!T+,PFF})H4lzcW57AF0U@N@< >M%G4Yt>f`z]MON');
	 *     define('SECURE_AUTH_KEY',  'LzJ}op]mr|6+![P}Ak:uNdJCJZd>(Hx.-Mh#Tz)pCIU#uGEnfFz|f ;;eU%/U^O~');
	 *     define('LOGGED_IN_KEY',    '|i|Ux`9<p-h$aFf(qnT:sDO:D1P^wZ$$/Ra@miTJi9G;ddp_<q}6H1)o|a +&JCM');
	 *     define('NONCE_KEY',        '%:R{[P|,s.KuMltH5}cI;/k<Gx~j!f0I)m_sIyu+&NJZ)-iO>z7X>QYR0Z_XnZ@|');
	 *     define('AUTH_SALT',        'eZyT)-Naw]F8CwA*VaW#q*|.)g@o}||wf~@C-YSt}(dh_r6EbI#A,y|nU2{B#JBW');
	 *     define('SECURE_AUTH_SALT', '!=oLUTXh,QW=H `}`L|9/^4-3 STz},T(w}W<I`.JjPi)<Bmf1v,HpGe}T1:Xt7n');
	 *     define('LOGGED_IN_SALT',   '+XSqHc;@Q*K_b|Z?NC[3H!!EONbh.n<+=uKR:>*c(u`g~EJBf#8u#R{mUEZrozmm');
	 *     define('NONCE_SALT',       'h`GXHhD>SLWVfg1(1(N{;.V!MoE(SfbA_ksP@&`+AycHcAV$+?@3q+rxV{%^VyKT');
	 *
	 * Salting passwords helps against tools which has stored hashed values of
	 * common dictionary strings. The added values makes it harder to crack.
	 *
	 * @since 2.5.0
	 *
	 * @link https://api.wordpress.org/secret-key/1.1/salt/ Create secrets for wp-config.php
	 *
	 * @param string $scheme Authentication scheme (auth, secure_auth, logged_in, nonce).
	 * @return string Salt value
	 */
	public function wp_salt( $scheme = 'auth' );

	/**
	 * Gets the hash of the given string.
	 *
	 * The default algorithm is md5 but can be changed to any algorithm supported by
	 * `hash_hmac()`. Use the `hash_hmac_algos()` function to check the supported
	 * algorithms.
	 *
	 * @since 2.0.3
	 * @since 6.8.0 The `$algo` parameter was added.
	 *
	 * @throws InvalidArgumentException if the hashing algorithm is not supported.
	 *
	 * @param string $data   Plain text to hash.
	 * @param string $scheme Authentication scheme (auth, secure_auth, logged_in, nonce).
	 * @param string $algo   Hashing algorithm to use. Default: 'md5'.
	 * @return string Hash of $data.
	 */
	public function wp_hash( $data, $scheme = 'auth', $algo = 'md5' );
}
