<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

interface Avatars {
	/**
	 * Retrieves default data about the avatar.
	 *
	 * @since 4.2.0
	 * @since 6.7.0 Gravatar URLs always use HTTPS.
	 * @since 6.8.0 Gravatar URLs use the SHA-256 hashing algorithm.
	 *
	 * @param mixed $id_or_email The avatar to retrieve. Accepts a user ID, Gravatar SHA-256 or MD5 hash,
	 *                           user email, WP_User object, WP_Post object, or WP_Comment object.
	 * @param array $args {
	 *     Optional. Arguments to use instead of the default arguments.
	 *
	 *     @type int    $size           Height and width of the avatar in pixels. Default 96.
	 *     @type int    $height         Display height of the avatar in pixels. Defaults to $size.
	 *     @type int    $width          Display width of the avatar in pixels. Defaults to $size.
	 *     @type string $default        URL for the default image or a default type. Accepts:
	 *                                  - '404' (return a 404 instead of a default image)
	 *                                  - 'retro' (a 8-bit arcade-style pixelated face)
	 *                                  - 'robohash' (a robot)
	 *                                  - 'monsterid' (a monster)
	 *                                  - 'wavatar' (a cartoon face)
	 *                                  - 'identicon' (the "quilt", a geometric pattern)
	 *                                  - 'initials' (initials based avatar with background color)
	 *                                  - 'color' (generated background color)
	 *                                  - 'mystery', 'mm', or 'mysteryman' (The Oyster Man)
	 *                                  - 'blank' (transparent GIF)
	 *                                  - 'gravatar_default' (the Gravatar logo)
	 *                                  Default is the value of the 'avatar_default' option,
	 *                                  with a fallback of 'mystery'.
	 *     @type bool   $force_default  Whether to always show the default image, never the Gravatar.
	 *                                  Default false.
	 *     @type string $rating         What rating to display avatars up to. Accepts:
	 *                                  - 'G' (suitable for all audiences)
	 *                                  - 'PG' (possibly offensive, usually for audiences 13 and above)
	 *                                  - 'R' (intended for adult audiences above 17)
	 *                                  - 'X' (even more mature than above)
	 *                                  Default is the value of the 'avatar_rating' option.
	 *     @type string $scheme         URL scheme to use. See set_url_scheme() for accepted values.
	 *                                  For Gravatars this setting is ignored and HTTPS is used to avoid
	 *                                  unnecessary redirects. The setting is retained for systems using
	 *                                  the {@see 'pre_get_avatar_data'} filter to customize avatars.
	 *                                  Default null.
	 *     @type array  $processed_args When the function returns, the value will be the processed/sanitized $args
	 *                                  plus a "found_avatar" guess. Pass as a reference. Default null.
	 *     @type string $extra_attr     HTML attributes to insert in the IMG element. Is not sanitized.
	 *                                  Default empty.
	 * }
	 * @return array {
	 *     Along with the arguments passed in `$args`, this will contain a couple of extra arguments.
	 *
	 *     @type bool         $found_avatar True if an avatar was found for this user,
	 *                                      false or not set if none was found.
	 *     @type string|false $url          The URL of the avatar that was found, or false.
	 * }
	 */
	public function get_avatar_data( $id_or_email, $args = null );

	/**
	 * Retrieves the avatar URL.
	 *
	 * @since 4.2.0
	 *
	 * @param mixed $id_or_email The avatar to retrieve a URL for. Accepts a user ID, Gravatar SHA-256 or MD5 hash,
	 *                           user email, WP_User object, WP_Post object, or WP_Comment object.
	 * @param array $args {
	 *     Optional. Arguments to use instead of the default arguments.
	 *
	 *     @type int    $size           Height and width of the avatar in pixels. Default 96.
	 *     @type string $default        URL for the default image or a default type. Accepts:
	 *                                  - '404' (return a 404 instead of a default image)
	 *                                  - 'retro' (a 8-bit arcade-style pixelated face)
	 *                                  - 'robohash' (a robot)
	 *                                  - 'monsterid' (a monster)
	 *                                  - 'wavatar' (a cartoon face)
	 *                                  - 'identicon' (the "quilt", a geometric pattern)
	 *                                  - 'initials' (initials based avatar with background color)
	 *                                  - 'color' (generated background color)
	 *                                  - 'mystery', 'mm', or 'mysteryman' (The Oyster Man)
	 *                                  - 'blank' (transparent GIF)
	 *                                  - 'gravatar_default' (the Gravatar logo)
	 *                                  Default is the value of the 'avatar_default' option,
	 *                                  with a fallback of 'mystery'.
	 *     @type bool   $force_default  Whether to always show the default image, never the Gravatar.
	 *                                  Default false.
	 *     @type string $rating         What rating to display avatars up to. Accepts:
	 *                                  - 'G' (suitable for all audiences)
	 *                                  - 'PG' (possibly offensive, usually for audiences 13 and above)
	 *                                  - 'R' (intended for adult audiences above 17)
	 *                                  - 'X' (even more mature than above)
	 *                                  Default is the value of the 'avatar_rating' option.
	 *     @type string $scheme         URL scheme to use. See set_url_scheme() for accepted values.
	 *                                  Default null.
	 *     @type array  $processed_args When the function returns, the value will be the processed/sanitized $args
	 *                                  plus a "found_avatar" guess. Pass as a reference. Default null.
	 * }
	 * @return string|false The URL of the avatar on success, false on failure.
	 */
	public function get_avatar_url( $id_or_email, $args = null );

	/**
	 * Check if this comment type allows avatars to be retrieved.
	 *
	 * @since 5.1.0
	 *
	 * @param string $comment_type Comment type to check.
	 * @return bool Whether the comment type is allowed for retrieving avatars.
	 */
	public function is_avatar_comment_type( $comment_type );

	/**
	 * Retrieves the avatar `<img>` tag for a user, email address, MD5 hash, comment, or post.
	 *
	 * @since 2.5.0
	 * @since 4.2.0 Added the optional `$args` parameter.
	 * @since 5.5.0 Added the `loading` argument.
	 * @since 6.1.0 Added the `decoding` argument.
	 * @since 6.3.0 Added the `fetchpriority` argument.
	 *
	 * @param mixed  $id_or_email   The avatar to retrieve. Accepts a user ID, Gravatar MD5 hash,
	 *                              user email, WP_User object, WP_Post object, or WP_Comment object.
	 * @param int    $size          Optional. Height and width of the avatar in pixels. Default 96.
	 * @param string $default_value URL for the default image or a default type. Accepts:
	 *                              - '404' (return a 404 instead of a default image)
	 *                              - 'retro' (a 8-bit arcade-style pixelated face)
	 *                              - 'robohash' (a robot)
	 *                              - 'monsterid' (a monster)
	 *                              - 'wavatar' (a cartoon face)
	 *                              - 'identicon' (the "quilt", a geometric pattern)
	 *                              - 'initials' (initials based avatar with background color)
	 *                              - 'color' (generated background color)
	 *                              - 'mystery', 'mm', or 'mysteryman' (The Oyster Man)
	 *                              - 'blank' (transparent GIF)
	 *                              - 'gravatar_default' (the Gravatar logo)
	 *                              Default is the value of the 'avatar_default' option,
	 *                              with a fallback of 'mystery'.
	 * @param string $alt           Optional. Alternative text to use in the avatar image tag.
	 *                              Default empty.
	 * @param array  $args {
	 *     Optional. Extra arguments to retrieve the avatar.
	 *
	 *     @type int          $height        Display height of the avatar in pixels. Defaults to $size.
	 *     @type int          $width         Display width of the avatar in pixels. Defaults to $size.
	 *     @type bool         $force_default Whether to always show the default image, never the Gravatar.
	 *                                       Default false.
	 *     @type string       $rating        What rating to display avatars up to. Accepts:
	 *                                       - 'G' (suitable for all audiences)
	 *                                       - 'PG' (possibly offensive, usually for audiences 13 and above)
	 *                                       - 'R' (intended for adult audiences above 17)
	 *                                       - 'X' (even more mature than above)
	 *                                       Default is the value of the 'avatar_rating' option.
	 *     @type string       $scheme        URL scheme to use. See set_url_scheme() for accepted values.
	 *                                       Default null.
	 *     @type array|string $class         Array or string of additional classes to add to the img element.
	 *                                       Default null.
	 *     @type bool         $force_display Whether to always show the avatar - ignores the show_avatars option.
	 *                                       Default false.
	 *     @type string       $loading       Value for the `loading` attribute.
	 *                                       Default null.
	 *     @type string       $fetchpriority Value for the `fetchpriority` attribute.
	 *                                       Default null.
	 *     @type string       $decoding      Value for the `decoding` attribute.
	 *                                       Default null.
	 *     @type string       $extra_attr    HTML attributes to insert in the IMG element. Is not sanitized.
	 *                                       Default empty.
	 * }
	 * @return string|false `<img>` tag for the user's avatar. False on failure.
	 */
	public function get_avatar( $id_or_email, $size = 96, $default_value = '', $alt = '', $args = null );
}
