<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

interface BlockPatterns {
	/**
	 * Registers a new block pattern.
	 *
	 * @since 5.5.0
	 *
	 * @param string $pattern_name       Block pattern name including namespace.
	 * @param array  $pattern_properties List of properties for the block pattern.
	 *                                   See WP_Block_Patterns_Registry::register() for accepted arguments.
	 * @return bool True if the pattern was registered with success and false otherwise.
	 */
	public function register_block_pattern( $pattern_name, $pattern_properties );

	/**
	 * Unregisters a block pattern.
	 *
	 * @since 5.5.0
	 *
	 * @param string $pattern_name Block pattern name including namespace.
	 * @return bool True if the pattern was unregistered with success and false otherwise.
	 */
	public function unregister_block_pattern( $pattern_name );

	/**
	 * Registers a new pattern category.
	 *
	 * @since 5.5.0
	 *
	 * @param string $category_name       Pattern category name including namespace.
	 * @param array  $category_properties List of properties for the block pattern.
	 *                                    See WP_Block_Pattern_Categories_Registry::register() for
	 *                                    accepted arguments.
	 * @return bool True if the pattern category was registered with success and false otherwise.
	 */
	public function register_block_pattern_category( $category_name, $category_properties );

	/**
	 * Unregisters a pattern category.
	 *
	 * @since 5.5.0
	 *
	 * @param string $category_name Pattern category name including namespace.
	 * @return bool True if the pattern category was unregistered with success and false otherwise.
	 */
	public function unregister_block_pattern_category( $category_name );

	/**
	 * Replaces patterns in a block tree with their content.
	 *
	 * @since 6.6.0
	 * @since 7.0.0 Adds metadata to attributes of single-pattern container blocks.
	 *
	 * @param array $blocks An array blocks.
	 *
	 * @return array An array of blocks with patterns replaced by their content.
	 */
	public function resolve_pattern_blocks( $blocks );
}
