<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use WP_Error;
use WP_Term;

interface Categories {
	/**
	 * Retrieves a list of category objects.
	 *
	 * If you set the 'taxonomy' argument to 'link_category', the link categories
	 * will be returned instead.
	 *
	 * @since 2.1.0
	 *
	 * @see get_terms() Type of arguments that can be changed.
	 *
	 * @param string|array $args {
	 *     Optional. Arguments to retrieve categories. See get_terms() for additional options.
	 *
	 *     @type string $taxonomy Taxonomy to retrieve terms for. Default 'category'.
	 * }
	 * @return array List of category objects.
	 */
	public function get_categories( $args = '' );

	/**
	 * Retrieves category data given a category ID or category object.
	 *
	 * If you pass the $category parameter an object, which is assumed to be the
	 * category row object retrieved the database. It will cache the category data.
	 *
	 * If you pass $category an integer of the category ID, then that category will
	 * be retrieved from the database, if it isn't already cached, and pass it back.
	 *
	 * If you look at get_term(), then both types will be passed through several
	 * filters and finally sanitized based on the $filter parameter value.
	 *
	 * @since 1.5.1
	 *
	 * @param int|object $category Category ID or category row object.
	 * @param string     $output   Optional. The required return type. One of OBJECT, ARRAY_A, or ARRAY_N, which
	 *                             correspond to a WP_Term object, an associative array, or a numeric array,
	 *                             respectively. Default OBJECT.
	 * @param string     $filter   Optional. How to sanitize category fields. Default 'raw'.
	 * @return WP_Term|array|WP_Error|null Category data in type defined by $output parameter.
	 *                                     Returns a WP_Term object with backwards compatible property aliases filled in.
	 *                                     WP_Error if $category is empty, null if it does not exist.
	 */
	public function get_category( $category, $output = 'OBJECT', $filter = 'raw' );

	/**
	 * Retrieves a category based on URL containing the category slug.
	 *
	 * Breaks the $category_path parameter up to get the category slug.
	 *
	 * Tries to find the child path and will return it. If it doesn't find a
	 * match, then it will return the first category matching slug, if $full_match,
	 * is set to false. If it does not, then it will return null.
	 *
	 * It is also possible that it will return a WP_Error object on failure. Check
	 * for it when using this function.
	 *
	 * @since 2.1.0
	 *
	 * @param string $category_path URL containing category slugs.
	 * @param bool   $full_match    Optional. Whether full path should be matched.
	 * @param string $output        Optional. The required return type. One of OBJECT, ARRAY_A, or ARRAY_N, which
	 *                              correspond to a WP_Term object, an associative array, or a numeric array,
	 *                              respectively. Default OBJECT.
	 * @return WP_Term|array|WP_Error|null Type is based on $output value.
	 */
	public function get_category_by_path( $category_path, $full_match = true, $output = 'OBJECT' );

	/**
	 * Retrieves a category object by category slug.
	 *
	 * @since 2.3.0
	 *
	 * @param string $slug The category slug.
	 * @return object|false Category data object on success, false if not found.
	 */
	public function get_category_by_slug( $slug );

	/**
	 * Retrieves the ID of a category from its name.
	 *
	 * @since 1.0.0
	 *
	 * @param string $cat_name Category name.
	 * @return int Category ID on success, 0 if the category doesn't exist.
	 */
	public function get_cat_ID( $cat_name );

	/**
	 * Retrieves the name of a category from its ID.
	 *
	 * @since 1.0.0
	 *
	 * @param int $cat_id Category ID.
	 * @return string Category name, or an empty string if the category doesn't exist.
	 */
	public function get_cat_name( $cat_id );

	/**
	 * Checks if a category is an ancestor of another category.
	 *
	 * You can use either an ID or the category object for both parameters.
	 * If you use an integer, the category will be retrieved.
	 *
	 * @since 2.1.0
	 *
	 * @param int|object $cat1 ID or object to check if this is the parent category.
	 * @param int|object $cat2 The child category.
	 * @return bool Whether $cat2 is child of $cat1.
	 */
	public function cat_is_ancestor_of( $cat1, $cat2 );

	/**
	 * Checks whether a category exists.
	 *
	 * @since 2.0.0
	 *
	 * @see term_exists()
	 *
	 * @param int|string $cat_name        Category name.
	 * @param int        $category_parent Optional. ID of parent category.
	 * @return string|null Returns the category ID as a numeric string if the pairing exists, null if not.
	 */
	public function category_exists( $cat_name, $category_parent = null );

	/**
	 * Gets category object for given ID and 'edit' filter context.
	 *
	 * @since 2.0.0
	 *
	 * @param int $id
	 * @return object
	 */
	public function get_category_to_edit( $id );

	/**
	 * Adds a new category to the database if it does not already exist.
	 *
	 * @since 2.0.0
	 *
	 * @param string $category_name   Category name.
	 * @param int    $category_parent Optional. ID of parent category.
	 * @return int The ID of category term on success, or zero on failure.
	 */
	public function wp_create_category( $category_name, $category_parent = 0 );

	/**
	 * Creates categories for the given post.
	 *
	 * @since 2.0.0
	 *
	 * @param string[] $categories Array of category names to create.
	 * @param int      $post_id    Optional. The post ID. Default empty.
	 * @return int[] Array of IDs of categories assigned to the given post.
	 */
	public function wp_create_categories( $categories, $post_id = 0 );

	/**
	 * Updates an existing Category or creates a new Category.
	 *
	 * @since 2.0.0
	 * @since 2.5.0 $wp_error parameter was added.
	 * @since 3.0.0 The 'taxonomy' argument was added.
	 *
	 * @param array $catarr {
	 *     Array of arguments for inserting a new category.
	 *
	 *     @type int        $cat_ID               Category ID. A non-zero value updates an existing category.
	 *                                            Default 0.
	 *     @type string     $taxonomy             Taxonomy slug. Default 'category'.
	 *     @type string     $cat_name             Category name. Default empty.
	 *     @type string     $category_description Category description. Default empty.
	 *     @type string     $category_nicename    Category nice (display) name. Default empty.
	 *     @type int|string $category_parent      Category parent ID. Default empty.
	 * }
	 * @param bool  $wp_error Optional. Default false.
	 * @return int|WP_Error The ID number of the new or updated Category on success. Zero or a WP_Error on failure,
	 *                      depending on param `$wp_error`.
	 */
	public function wp_insert_category( $catarr, $wp_error = false );

	/**
	 * Aliases wp_insert_category() with minimal args.
	 *
	 * If you want to update only some fields of an existing category, call this
	 * function with only the new values set inside $catarr.
	 *
	 * @since 2.0.0
	 *
	 * @param array $catarr The 'cat_ID' value is required. All other keys are optional.
	 * @return int|false The ID number of the new or updated Category on success. Zero or FALSE on failure.
	 */
	public function wp_update_category( $catarr );

	/**
	 * Sanitizes category data based on context.
	 *
	 * @since 2.3.0
	 *
	 * @param object|array $category Category data.
	 * @param string       $context  Optional. Default 'display'.
	 * @return object|array Same type as $category with sanitized data for safe use.
	 */
	public function sanitize_category( $category, $context = 'display' );

	/**
	 * Sanitizes data in single category key field.
	 *
	 * @since 2.3.0
	 *
	 * @param string $field   Category key to sanitize.
	 * @param mixed  $value   Category value to sanitize.
	 * @param int    $cat_id  Category ID.
	 * @param string $context What filter to use, 'raw', 'display', etc.
	 * @return mixed Value after $value has been sanitized.
	 */
	public function sanitize_category_field( $field, $value, $cat_id, $context );

	/**
	 * Removes the category cache data based on ID.
	 *
	 * @since 2.1.0
	 *
	 * @param int $id Category ID
	 */
	public function clean_category_cache( $id );
}
