<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use DateTimeImmutable;
use DateTimeZone;
use WP_Locale;

interface Dates {
	/**
	 * Retrieves the current time based on specified type.
	 *
	 *  - The 'mysql' type will return the time in the format for MySQL DATETIME field.
	 *  - The 'timestamp' or 'U' types will return the current timestamp or a sum of timestamp
	 *    and timezone offset, depending on `$gmt`.
	 *  - Other strings will be interpreted as PHP date formats (e.g. 'Y-m-d').
	 *
	 * If `$gmt` is a truthy value then both types will use GMT time, otherwise the
	 * output is adjusted with the GMT offset for the site.
	 *
	 * @since 1.0.0
	 * @since 5.3.0 Now returns an integer if `$type` is 'U'. Previously a string was returned.
	 *
	 * @param string $type Type of time to retrieve. Accepts 'mysql', 'timestamp', 'U',
	 *                     or PHP date format string (e.g. 'Y-m-d').
	 * @param bool   $gmt  Optional. Whether to use GMT timezone. Default false.
	 * @return int|string Integer if `$type` is 'timestamp' or 'U', string otherwise.
	 */
	public function current_time( $type, $gmt = false );

	/**
	 * Retrieves the current time as an object using the site's timezone.
	 *
	 * @since 5.3.0
	 *
	 * @return DateTimeImmutable Date and time object.
	 */
	public function current_datetime();

	/**
	 * Retrieves the timezone of the site as a `DateTimeZone` object.
	 *
	 * Timezone can be based on a PHP timezone string or a ±HH:MM offset.
	 *
	 * @since 5.3.0
	 *
	 * @return DateTimeZone Timezone object.
	 */
	public function wp_timezone();

	/**
	 * Retrieves the timezone of the site as a string.
	 *
	 * Uses the `timezone_string` option to get a proper timezone name if available,
	 * otherwise falls back to a manual UTC ± offset.
	 *
	 * Example return values:
	 *
	 *  - 'Europe/Rome'
	 *  - 'America/North_Dakota/New_Salem'
	 *  - 'UTC'
	 *  - '-06:30'
	 *  - '+00:00'
	 *  - '+08:45'
	 *
	 * @since 5.3.0
	 *
	 * @return string PHP timezone name or a ±HH:MM offset.
	 */
	public function wp_timezone_string();

	/**
	 * Retrieves the date, in localized format.
	 *
	 * This is a newer function, intended to replace `date_i18n()` without legacy quirks in it.
	 *
	 * Note that, unlike `date_i18n()`, this function accepts a true Unix timestamp, not summed
	 * with timezone offset.
	 *
	 * @since 5.3.0
	 *
	 * @global WP_Locale $wp_locale WordPress date and time locale object.
	 *
	 * @param string            $format    PHP date format.
	 * @param int|null          $timestamp Optional. Unix timestamp. Defaults to current time.
	 * @param DateTimeZone|null $timezone  Optional. Timezone to output result in. Defaults to timezone
	 *                                     from site settings.
	 * @return string|false The date, translated if locale specifies it. False on invalid timestamp input.
	 */
	public function wp_date( $format, $timestamp = null, $timezone = null );

	/**
	 * Retrieves the date in localized format, based on a sum of Unix timestamp and
	 * timezone offset in seconds.
	 *
	 * If the locale specifies the locale month and weekday, then the locale will
	 * take over the format for the date. If it isn't, then the date format string
	 * will be used instead.
	 *
	 * Note that due to the way WP typically generates a sum of timestamp and offset
	 * with `strtotime()`, it implies offset added at a _current_ time, not at the time
	 * the timestamp represents. Storing such timestamps or calculating them differently
	 * will lead to invalid output.
	 *
	 * @since 0.71
	 * @since 5.3.0 Converted into a wrapper for wp_date().
	 *
	 * @param string   $format                Format to display the date.
	 * @param int|bool $timestamp_with_offset Optional. A sum of Unix timestamp and timezone offset
	 *                                        in seconds. Default false.
	 * @param bool     $gmt                   Optional. Whether to use GMT timezone. Only applies
	 *                                        if timestamp is not provided. Default false.
	 * @return string The date, translated if locale specifies it.
	 */
	public function date_i18n( $format, $timestamp_with_offset = false, $gmt = false );

	/**
	 * Converts given MySQL date string into a different format.
	 *
	 *  - `$format` should be a PHP date format string.
	 *  - 'U' and 'G' formats will return an integer sum of timestamp with timezone offset.
	 *  - `$date` is expected to be local time in MySQL format (`Y-m-d H:i:s`).
	 *
	 * Historically UTC time could be passed to the function to produce Unix timestamp.
	 *
	 * If `$translate` is true then the given date and format string will
	 * be passed to `wp_date()` for translation.
	 *
	 * @since 0.71
	 *
	 * @param string $format    Format of the date to return.
	 * @param string $date      Date string to convert.
	 * @param bool   $translate Whether the return date should be translated. Default true.
	 * @return string|int|false Integer if `$format` is 'U' or 'G', string otherwise.
	 *                          False on failure.
	 */
	public function mysql2date( $format, $date, $translate = true );

	/**
	 * Parses and formats a MySQL datetime (Y-m-d H:i:s) for ISO8601 (Y-m-d\TH:i:s).
	 *
	 * Explicitly strips timezones, as datetimes are not saved with any timezone
	 * information. Including any information on the offset could be misleading.
	 *
	 * Despite historical function name, the output does not conform to RFC3339 format,
	 * which must contain timezone.
	 *
	 * @since 4.4.0
	 *
	 * @param string $date_string Date string to parse and format.
	 * @return string Date formatted for ISO8601 without time zone.
	 */
	public function mysql_to_rfc3339( $date_string );

	/**
	 * Tests if the supplied date is valid for the Gregorian calendar.
	 *
	 * @since 3.5.0
	 *
	 * @link https://www.php.net/manual/en/function.checkdate.php
	 *
	 * @param int    $month       Month number.
	 * @param int    $day         Day number.
	 * @param int    $year        Year number.
	 * @param string $source_date The date to filter.
	 * @return bool True if valid date, false if not valid date.
	 */
	public function wp_checkdate( $month, $day, $year, $source_date );

	/**
	 * Gets the week start and end from the datetime or date string from MySQL.
	 *
	 * @since 0.71
	 *
	 * @param string     $mysqlstring   Date or datetime field type from MySQL.
	 * @param int|string $start_of_week Optional. Start of the week as an integer. Default empty string.
	 * @return int[] {
	 *     Week start and end dates as Unix timestamps.
	 *
	 *     @type int $start The week start date as a Unix timestamp.
	 *     @type int $end   The week end date as a Unix timestamp.
	 * }
	 */
	public function get_weekstartend( $mysqlstring, $start_of_week = '' );

	/**
	 * Determines if the date should be declined.
	 *
	 * If the locale specifies that month names require a genitive case in certain
	 * formats (like 'j F Y'), the month name will be replaced with a correct form.
	 *
	 * @since 4.4.0
	 * @since 5.4.0 The `$format` parameter was added.
	 *
	 * @global WP_Locale $wp_locale WordPress date and time locale object.
	 *
	 * @param string $date   Formatted date string.
	 * @param string $format Optional. Date format to check. Default empty string.
	 * @return string The date, declined if locale specifies it.
	 */
	public function wp_maybe_decline_date( $date, $format = '' );

	/**
	 * Converts a duration to human readable format.
	 *
	 * @since 5.1.0
	 *
	 * @param string $duration Duration will be in string format (HH:ii:ss) OR (ii:ss),
	 *                         with a possible prepended negative sign (-).
	 * @return string|false A human readable duration string, false on failure.
	 */
	public function human_readable_duration( $duration = '' );

	/**
	 * Gives a nicely-formatted list of timezone strings.
	 *
	 * @since 2.9.0
	 * @since 4.7.0 Added the `$locale` parameter.
	 *
	 * @param string $selected_zone Selected timezone.
	 * @param string $locale        Optional. Locale to load the timezones in. Default current site locale.
	 * @return string HTML select element for timezones.
	 */
	public function wp_timezone_choice( $selected_zone, $locale = null );

	/**
	 * Given a date in UTC or GMT timezone, returns that date in the timezone of the site.
	 *
	 * Requires a date in the Y-m-d H:i:s format.
	 * Default return format of 'Y-m-d H:i:s' can be overridden using the `$format` parameter.
	 *
	 * @since 1.2.0
	 *
	 * @param string $date_string The date to be converted, in UTC or GMT timezone.
	 * @param string $format      The format string for the returned date. Default 'Y-m-d H:i:s'.
	 * @return string Formatted version of the date, in the site's timezone.
	 */
	public function get_date_from_gmt( $date_string, $format = 'Y-m-d H:i:s' );

	/**
	 * Given a date in the timezone of the site, returns that date in UTC.
	 *
	 * Requires and returns a date in the Y-m-d H:i:s format.
	 * Return format can be overridden using the $format parameter.
	 *
	 * @since 1.2.0
	 *
	 * @param string $date_string The date to be converted, in the timezone of the site.
	 * @param string $format      The format string for the returned date. Default 'Y-m-d H:i:s'.
	 * @return string Formatted version of the date, in UTC.
	 */
	public function get_gmt_from_date( $date_string, $format = 'Y-m-d H:i:s' );

	/**
	 * Given an ISO 8601 (Ymd\TH:i:sO) date, returns a MySQL DateTime (Y-m-d H:i:s) format used by post_date[_gmt].
	 *
	 * @since 1.5.0
	 *
	 * @param string $date_string Date and time in ISO 8601 format {@link https://en.wikipedia.org/wiki/ISO_8601}.
	 * @param string $timezone    Optional. If set to 'gmt' returns the result in UTC. Default 'user'.
	 * @return string|false The date and time in MySQL DateTime format - Y-m-d H:i:s, or false on failure.
	 */
	public function iso8601_to_datetime( $date_string, $timezone = 'user' );

	/**
	 * Given an ISO 8601 timezone, returns its UTC offset in seconds.
	 *
	 * @since 1.5.0
	 *
	 * @param string $timezone Either 'Z' for 0 offset or '±hhmm'.
	 * @return int|float The offset in seconds.
	 */
	public function iso8601_timezone_to_offset( $timezone );

	/**
	 * Determines the difference between two timestamps.
	 *
	 * The difference is returned in a human-readable format such as "1 hour",
	 * "5 minutes", "2 days".
	 *
	 * @since 1.5.0
	 * @since 5.3.0 Added support for showing a difference in seconds.
	 *
	 * @param int $from Unix timestamp from which the difference begins.
	 * @param int $to   Optional. Unix timestamp to end the time difference. Default becomes time() if not set.
	 * @return string Human-readable time difference.
	 */
	public function human_time_diff( $from, $to = 0 );
}
