<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use WP_Locale;
use WP_Scripts;
use WP_Styles;

interface DocumentHead {
	/**
	 * Displays relational links for the posts adjacent to the current post for single post pages.
	 *
	 * This is meant to be attached to actions like 'wp_head'. Do not call this directly in plugins
	 * or theme templates.
	 *
	 * @since 3.0.0
	 * @since 5.6.0 No longer used in core.
	 *
	 * @see adjacent_posts_rel_link()
	 */
	public function adjacent_posts_rel_link_wp_head();

	/**
	 * Creates the generator XML or Comment for RSS, ATOM, etc.
	 *
	 * Returns the correct generator type for the requested output format. Allows
	 * for a plugin to filter generators on an individual basis using the
	 * {@see 'get_the_generator_$type'} filter.
	 *
	 * @since 2.5.0
	 *
	 * @param string $type The type of generator to return - (html|xhtml|atom|rss2|rdf|comment|export).
	 * @return string|null The HTML content for the generator.
	 */
	public function get_the_generator( $type = '' );

	/**
	 * Outputs rel=canonical for singular queries.
	 *
	 * @since 2.9.0
	 * @since 4.6.0 Adjusted to use `wp_get_canonical_url()`.
	 */
	public function rel_canonical();

	/**
	 * Displays the link to the Really Simple Discovery service endpoint.
	 *
	 * @link http://archipelago.phrasewise.com/rsd
	 * @since 2.0.0
	 */
	public function rsd_link();

	/**
	 * Displays the generator XML or Comment for RSS, ATOM, etc.
	 *
	 * Returns the correct generator type for the requested output format. Allows
	 * for a plugin to filter generators overall the {@see 'the_generator'} filter.
	 *
	 * @since 2.5.0
	 *
	 * @param string $type The type of generator to output - (html|xhtml|atom|rss2|rdf|comment|export).
	 */
	public function the_generator( $type );

	/**
	 * Fires the wp_body_open action.
	 *
	 * See {@see 'wp_body_open'}.
	 *
	 * @since 5.2.0
	 */
	public function wp_body_open();

	/**
	 * Retrieves a list of unique hosts of all enqueued scripts and styles.
	 *
	 * @since 4.6.0
	 *
	 * @global WP_Scripts $wp_scripts The WP_Scripts object for printing scripts.
	 * @global WP_Styles  $wp_styles  The WP_Styles object for printing styles.
	 *
	 * @return string[] A list of unique hosts of enqueued scripts and styles.
	 */
	public function wp_dependencies_unique_hosts();

	/**
	 * Fires the wp_footer action.
	 *
	 * See {@see 'wp_footer'}.
	 *
	 * @since 1.5.1
	 */
	public function wp_footer();

	/**
	 * Displays the XHTML generator that is generated on the wp_head hook.
	 *
	 * See {@see 'wp_head'}.
	 *
	 * @since 2.5.0
	 */
	public function wp_generator();

	/**
	 * Returns document title for the current page.
	 *
	 * @since 4.4.0
	 *
	 * @global int $page  Page number of a single post.
	 * @global int $paged Page number of a list of posts.
	 *
	 * @return string Tag with the document title.
	 */
	public function wp_get_document_title();

	/**
	 * Fires the wp_head action.
	 *
	 * See {@see 'wp_head'}.
	 *
	 * @since 1.2.0
	 */
	public function wp_head();

	/**
	 * Theme container function for the 'wp_meta' action.
	 *
	 * The {@see 'wp_meta'} action can have several purposes, depending on how you use it,
	 * but one purpose might have been to allow for theme switching.
	 *
	 * @since 1.5.0
	 *
	 * @link https://core.trac.wordpress.org/ticket/1458 Explanation of 'wp_meta' action.
	 */
	public function wp_meta();

	/**
	 * Prints resource preloads directives to browsers.
	 *
	 * Gives directive to browsers to preload specific resources that website will
	 * need very soon, this ensures that they are available earlier and are less
	 * likely to block the page's render. Preload directives should not be used for
	 * non-render-blocking elements, as then they would compete with the
	 * render-blocking ones, slowing down the render.
	 *
	 * These performance improving indicators work by using `<link rel="preload">`.
	 *
	 * @link https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload
	 * @link https://web.dev/preload-responsive-images/
	 *
	 * @since 6.1.0
	 */
	public function wp_preload_resources();

	/**
	 * Prints resource hints to browsers for pre-fetching, pre-rendering
	 * and pre-connecting to websites.
	 *
	 * Gives hints to browsers to prefetch specific pages or render them
	 * in the background, to perform DNS lookups or to begin the connection
	 * handshake (DNS, TCP, TLS) in the background.
	 *
	 * These performance improving indicators work by using `<link rel"…">`.
	 *
	 * @since 4.6.0
	 */
	public function wp_resource_hints();

	/**
	 * Displays the robots meta tag as necessary.
	 *
	 * Gathers robots directives to include for the current context, using the
	 * {@see 'wp_robots'} filter. The directives are then sanitized, and the
	 * robots meta tag is output if there is at least one relevant directive.
	 *
	 * @since 5.7.0
	 * @since 5.7.1 No longer prevents specific directives to occur together.
	 */
	public function wp_robots();

	/**
	 * Adds `max-image-preview:large` to the robots meta tag.
	 *
	 * This directive tells web robots that large image previews are allowed to be
	 * displayed, e.g. in search engines, unless the blog is marked as not being public.
	 *
	 * Typical usage is as a {@see 'wp_robots'} callback:
	 *
	 *     add_filter( 'wp_robots', 'wp_robots_max_image_preview_large' );
	 *
	 * @since 5.7.0
	 *
	 * @param array $robots Associative array of robots directives.
	 * @return array Filtered robots directives.
	 */
	public function wp_robots_max_image_preview_large( array $robots );

	/**
	 * Adds `noindex` to the robots meta tag.
	 *
	 * This directive tells web robots not to index the page content.
	 *
	 * Typical usage is as a {@see 'wp_robots'} callback:
	 *
	 *     add_filter( 'wp_robots', 'wp_robots_no_robots' );
	 *
	 * @since 5.7.0
	 *
	 * @param array $robots Associative array of robots directives.
	 * @return array Filtered robots directives.
	 */
	public function wp_robots_no_robots( array $robots );

	/**
	 * Adds `noindex` to the robots meta tag if required by the site configuration.
	 *
	 * If a blog is marked as not being public then noindex will be output to
	 * tell web robots not to index the page content. Add this to the
	 * {@see 'wp_robots'} filter.
	 *
	 * Typical usage is as a {@see 'wp_robots'} callback:
	 *
	 *     add_filter( 'wp_robots', 'wp_robots_noindex' );
	 *
	 * @since 5.7.0
	 *
	 * @see wp_robots_no_robots()
	 *
	 * @param array $robots Associative array of robots directives.
	 * @return array Filtered robots directives.
	 */
	public function wp_robots_noindex( array $robots );

	/**
	 * Adds `noindex` to the robots meta tag for embeds.
	 *
	 * Typical usage is as a {@see 'wp_robots'} callback:
	 *
	 *     add_filter( 'wp_robots', 'wp_robots_noindex_embeds' );
	 *
	 * @since 5.7.0
	 *
	 * @see wp_robots_no_robots()
	 *
	 * @param array $robots Associative array of robots directives.
	 * @return array Filtered robots directives.
	 */
	public function wp_robots_noindex_embeds( array $robots );

	/**
	 * Adds `noindex` to the robots meta tag if a search is being performed.
	 *
	 * If a search is being performed then noindex will be output to
	 * tell web robots not to index the page content. Add this to the
	 * {@see 'wp_robots'} filter.
	 *
	 * Typical usage is as a {@see 'wp_robots'} callback:
	 *
	 *     add_filter( 'wp_robots', 'wp_robots_noindex_search' );
	 *
	 * @since 5.7.0
	 *
	 * @see wp_robots_no_robots()
	 *
	 * @param array $robots Associative array of robots directives.
	 * @return array Filtered robots directives.
	 */
	public function wp_robots_noindex_search( array $robots );

	/**
	 * Adds `noindex` and `noarchive` to the robots meta tag.
	 *
	 * This directive tells web robots not to index or archive the page content and
	 * is recommended to be used for sensitive pages.
	 *
	 * Typical usage is as a {@see 'wp_robots'} callback:
	 *
	 *     add_filter( 'wp_robots', 'wp_robots_sensitive_page' );
	 *
	 * @since 5.7.0
	 *
	 * @param array $robots Associative array of robots directives.
	 * @return array Filtered robots directives.
	 */
	public function wp_robots_sensitive_page( array $robots );

	/**
	 * Sends a Link: rel=shortlink header if a shortlink is defined for the current page.
	 *
	 * Attached to the {@see 'wp'} action.
	 *
	 * @since 3.0.0
	 */
	public function wp_shortlink_header();

	/**
	 * Injects rel=shortlink into the head if a shortlink is defined for the current page.
	 *
	 * Attached to the {@see 'wp_head'} action.
	 *
	 * @since 3.0.0
	 */
	public function wp_shortlink_wp_head();

	/**
	 * Displays a referrer `strict-origin-when-cross-origin` meta tag.
	 *
	 * Outputs a referrer `strict-origin-when-cross-origin` meta tag that tells the browser not to send
	 * the full URL as a referrer to other sites when cross-origin assets are loaded.
	 *
	 * Typical usage is as a {@see 'wp_head'} callback:
	 *
	 *     add_action( 'wp_head', 'wp_strict_cross_origin_referrer' );
	 *
	 * @since 5.7.0
	 */
	public function wp_strict_cross_origin_referrer();

	/**
	 * Displays or retrieves page title for all areas of blog.
	 *
	 * By default, the page title will display the separator before the page title,
	 * so that the blog title will be before the page title. This is not good for
	 * title display, since the blog title shows up on most tabs and not what is
	 * important, which is the page that the user is looking at.
	 *
	 * There are also SEO benefits to having the blog title after or to the 'right'
	 * of the page title. However, it is mostly common sense to have the blog title
	 * to the right with most browsers supporting tabs. You can achieve this by
	 * using the seplocation parameter and setting the value to 'right'. This change
	 * was introduced around 2.5.0, in case backward compatibility of themes is
	 * important.
	 *
	 * @since 1.0.0
	 *
	 * @global WP_Locale $wp_locale WordPress date and time locale object.
	 *
	 * @param string $sep         Optional. How to separate the various items within the page title.
	 *                            Default '&raquo;'.
	 * @param bool   $display     Optional. Whether to display or retrieve title. Default true.
	 * @param string $seplocation Optional. Location of the separator (either 'left' or 'right').
	 * @return string|null String when `$display` is false, null otherwise.
	 */
	public function wp_title( $sep = '&raquo;', $display = true, $seplocation = '' );

	/**
	 * Returns the speculation rules configuration.
	 *
	 * @since 6.8.0
	 * @since 7.1.0 The `WP_SPECULATIVE_LOADING_DEFAULT_MODE` and `WP_SPECULATIVE_LOADING_DEFAULT_EAGERNESS` constants and
	 *              environment variables can now specify the default mode and eagerness, respectively.
	 *
	 * @see wp_get_speculation_rules_default_configuration()
	 *
	 * @return array<string, string>|null Associative array with 'mode' and 'eagerness' keys, or null if speculative
	 *                                    loading is disabled.
	 * @phpstan-return array{
	 *     mode: 'prefetch'|'prerender',
	 *     eagerness: 'conservative'|'moderate'|'eager',
	 * }|null
	 */
	public function wp_get_speculation_rules_configuration(): ?array;
}
