<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use WP_Error;
use WP_Theme;

interface FileEditor {
	/**
	 * Makes sure that the file that was requested to be edited is allowed to be edited.
	 *
	 * Function will die if you are not allowed to edit the file.
	 *
	 * @since 1.5.0
	 *
	 * @param string   $file          File the user is attempting to edit.
	 * @param string[] $allowed_files Optional. Array of allowed files to edit.
	 *                                `$file` must match an entry exactly.
	 * @return string|null Returns the file name on success, null in case of absolute Windows drive paths, and dies on failure.
	 */
	public function validate_file_to_edit( $file, $allowed_files = array() );

	/**
	 * Gets the description for standard WordPress theme files.
	 *
	 * @since 1.5.0
	 *
	 * @global array $wp_file_descriptions Theme file descriptions.
	 * @global array $allowed_files        List of allowed files.
	 *
	 * @param string $file Filesystem path or filename.
	 * @return string Description of file from $wp_file_descriptions or basename of $file if description doesn't exist.
	 *                Appends 'Page Template' to basename of $file if the file is a page template.
	 */
	public function get_file_description( $file );

	/**
	 * Attempts to edit a file for a theme or plugin.
	 *
	 * When editing a PHP file, loopback requests will be made to the admin and the homepage
	 * to attempt to see if there is a fatal error introduced. If so, the PHP change will be
	 * reverted.
	 *
	 * @since 4.9.0
	 *
	 * @param string[] $args {
	 *     Args. Note that all of the arg values are already unslashed. They are, however,
	 *     coming straight from `$_POST` and are not validated or sanitized in any way.
	 *
	 *     @type string $file       Relative path to file.
	 *     @type string $plugin     Path to the plugin file relative to the plugins directory.
	 *     @type string $theme      Theme being edited.
	 *     @type string $newcontent New content for the file.
	 *     @type string $nonce      Nonce.
	 * }
	 * @return true|WP_Error True on success or `WP_Error` on failure.
	 */
	public function wp_edit_theme_plugin_file( $args );

	/**
	 * Gets the list of file extensions that are editable in plugins.
	 *
	 * @since 4.9.0
	 *
	 * @param string $plugin Path to the plugin file relative to the plugins directory.
	 * @return string[] Array of editable file extensions.
	 */
	public function wp_get_plugin_file_editable_extensions( $plugin );

	/**
	 * Gets the list of file extensions that are editable for a given theme.
	 *
	 * @since 4.9.0
	 *
	 * @param WP_Theme $theme Theme object.
	 * @return string[] Array of editable file extensions.
	 */
	public function wp_get_theme_file_editable_extensions( $theme );

	/**
	 * Updates the "recently-edited" file for the plugin or theme file editor.
	 *
	 * @since 1.5.0
	 *
	 * @param string $file Path to the recently edited file.
	 */
	public function update_recently_edited( $file );
}
