<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

interface Forms {
	/**
	 * Displays all of the allowed tags in HTML format with attributes.
	 *
	 * This is useful for displaying in the comment area, which elements and
	 * attributes are supported. As well as any plugins which want to display it.
	 *
	 * @since 1.0.1
	 * @since 4.4.0 No longer used in core.
	 *
	 * @global array $allowedtags
	 *
	 * @return string HTML allowed tags entity encoded.
	 */
	public function allowed_tags();

	/**
	 * Outputs the HTML checked attribute.
	 *
	 * Compares the first two arguments and if identical marks as checked.
	 *
	 * @since 1.0.0
	 *
	 * @param mixed $checked One of the values to compare.
	 * @param mixed $current Optional. The other value to compare if not just true.
	 *                       Default true.
	 * @param bool  $display Optional. Whether to echo or just return the string.
	 *                       Default true.
	 * @return string HTML attribute or empty string.
	 */
	public function checked( $checked, $current = true, $display = true );

	/**
	 * Outputs the HTML disabled attribute.
	 *
	 * Compares the first two arguments and if identical marks as disabled.
	 *
	 * @since 3.0.0
	 *
	 * @param mixed $disabled One of the values to compare.
	 * @param mixed $current  Optional. The other value to compare if not just true.
	 *                        Default true.
	 * @param bool  $display  Optional. Whether to echo or just return the string.
	 *                        Default true.
	 * @return string HTML attribute or empty string.
	 */
	public function disabled( $disabled, $current = true, $display = true );

	/**
	 * Outputs the HTML selected attribute.
	 *
	 * Compares the first two arguments and if identical marks as selected.
	 *
	 * @since 1.0.0
	 *
	 * @param mixed $selected One of the values to compare.
	 * @param mixed $current  Optional. The other value to compare if not just true.
	 *                        Default true.
	 * @param bool  $display  Optional. Whether to echo or just return the string.
	 *                        Default true.
	 * @return string HTML attribute or empty string.
	 */
	public function selected( $selected, $current = true, $display = true );

	/**
	 * Retrieves the markup for an accessible toggle tip.
	 *
	 * Returns a button and an action triggered toggle tip with `$content`.
	 *
	 * @since 7.1.0
	 *
	 * @param string $content Plain-text tooltip content. An empty value returns an empty string.
	 * @param array  $args {
	 *     Optional. Arguments for building the tooltip.
	 *
	 *     @type string $id          Unique ID for the popover element. Default is a
	 *                               generated unique ID.
	 *     @type string $button      Existing `button` markup. Used instead of generated button.
	 *                               Default empty string.
	 *     @type string $label       Accessible label for the toggle button.
	 *                               Default 'Help', matching the default icon.
	 *                               Ignored for tooltips.
	 *     @type string $close_label Accessible label for the close button. Default 'Close'.
	 *     @type string $icon        Dashicons icon class for the toggle button.
	 *                               Default 'dashicons-editor-help'. Should match the control's
	 *                               visible label.
	 *     @type string $class       Additional class(es) for the wrapping element.
	 *                               Default empty.
	 * }
	 * @return string Toggletip HTML markup, or an empty string when no content is provided.
	 */
	public function wp_get_toggletip( $content, $args = array() );

	/**
	 * Retrieves the markup for an accessible tooltip.
	 *
	 * Returns a button with an accessible name popover hint.
	 *
	 * @since 7.1.0
	 *
	 * @param string $content Plain-text tooltip content. An empty value returns an empty string.
	 * @param array  $args {
	 *     Optional. Arguments for building the tooltip.
	 *
	 *     @type string $id          Unique ID for the popover element. Default is a
	 *                               generated unique ID.
	 *     @type string $button      Existing `button` or `a` markup. Used instead of generated button.
	 *                               Default empty string.
	 *     @type string $label       Not used for tooltips.
	 *     @type string $close_label Not used for tooltips.
	 *     @type string $icon        Dashicons icon class for the toggle button.
	 *                               Default 'dashicons-editor-help'. Should match the control's
	 *                               visible label.
	 *     @type string $class       Additional class(es) for the wrapping element.
	 *                               Default empty.
	 * }
	 * @return string Tooltip HTML markup, or an empty string when no content is provided.
	 */
	public function wp_get_tooltip( $content, $args = array() );

	/**
	 * Retrieves the markup for an accessible tooltip or toggletip.
	 *
	 * Returns a button and either a hover/focus triggered tooltip popover or an action
	 * triggered toggle tip. Enqueue the `wp-tooltip` style and script where it is used.
	 * Tooltips are used to show the accessible name of a control.
	 * Toggletips are used for longer supporting text explaining context.
	 *
	 * @since 7.1.0
	 *
	 * @param string $content Plain-text tooltip content. An empty value returns an empty string.
	 * @param array  $args {
	 *     Optional. Arguments for building the tooltip.
	 *
	 *     @type string $id          Unique ID for the popover element. Default is a
	 *                               generated unique ID.
	 *     @type string $button      Existing `button` or `a` markup. Used instead of generated button.
	 *                               Default empty string.
	 *     @type string $label       Accessible label for the toggle button.
	 *                               Default 'Help', matching the default icon.
	 *                               Ignored for tooltips.
	 *     @type string $close_label Accessible label for the close button. Default 'Close'.
	 *     @type string $icon        Dashicons icon class for the toggle button.
	 *                               Default 'dashicons-editor-help'. Should match the control's
	 *                               visible label.
	 *     @type string $class       Additional class(es) for the wrapping element.
	 *                               Default empty.
	 *     @type string $type        Type of tooltip: either `tooltip` or `toggletip`.
	 *                               Default 'tooltip'.
	 * }
	 * @return string Tooltip HTML markup, or an empty string when no content is provided.
	 */
	public function wp_get_tooltip_helper( $content, $args = array() );

	/**
	 * Outputs the HTML readonly attribute.
	 *
	 * Compares the first two arguments and if identical marks as readonly.
	 *
	 * @since 5.9.0
	 *
	 * @param mixed $readonly_value One of the values to compare.
	 * @param mixed $current        Optional. The other value to compare if not just true.
	 *                              Default true.
	 * @param bool  $display        Optional. Whether to echo or just return the string.
	 *                              Default true.
	 * @return string HTML attribute or empty string.
	 */
	public function wp_readonly( $readonly_value, $current = true, $display = true );

	/**
	 * Assigns a visual indicator for required form fields.
	 *
	 * @since 6.1.0
	 *
	 * @return string Indicator glyph wrapped in a `span` tag.
	 */
	public function wp_required_field_indicator();

	/**
	 * Creates a message to explain required form fields.
	 *
	 * @since 6.1.0
	 *
	 * @return string Message text and glyph wrapped in a `span` tag.
	 */
	public function wp_required_field_message();
}
