<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

interface Https {
	/**
	 * Determines if SSL is used.
	 *
	 * @since 2.6.0
	 * @since 4.6.0 Moved from functions.php to load.php.
	 *
	 * @return bool True if SSL, otherwise false.
	 */
	public function is_ssl();

	/**
	 * Determines whether to force SSL used for the Administration Screens.
	 *
	 * @since 2.6.0
	 *
	 * @param string|bool|null $force Optional. Whether to force SSL in admin screens. Default null.
	 * @return bool True if forced, false if not forced.
	 */
	public function force_ssl_admin( $force = null );

	/**
	 * Checks whether the website is using HTTPS.
	 *
	 * This is based on whether both the home and site URL are using HTTPS.
	 *
	 * @since 5.7.0
	 * @see wp_is_home_url_using_https()
	 * @see wp_is_site_url_using_https()
	 *
	 * @return bool True if using HTTPS, false otherwise.
	 */
	public function wp_is_using_https();

	/**
	 * Checks whether the current site URL is using HTTPS.
	 *
	 * @since 5.7.0
	 * @see home_url()
	 *
	 * @return bool True if using HTTPS, false otherwise.
	 */
	public function wp_is_home_url_using_https();

	/**
	 * Checks whether the current site's URL where WordPress is stored is using HTTPS.
	 *
	 * This checks the URL where WordPress application files (e.g. wp-blog-header.php or the wp-admin/ folder)
	 * are accessible.
	 *
	 * @since 5.7.0
	 * @see site_url()
	 *
	 * @return bool True if using HTTPS, false otherwise.
	 */
	public function wp_is_site_url_using_https();

	/**
	 * Checks whether HTTPS is supported for the server and domain.
	 *
	 * This function makes an HTTP request through `wp_get_https_detection_errors()`
	 * to check for HTTPS support. As this process can be resource-intensive,
	 * it should be used cautiously, especially in performance-sensitive environments,
	 * to avoid potential latency issues.
	 *
	 * @since 5.7.0
	 *
	 * @return bool True if HTTPS is supported, false otherwise.
	 */
	public function wp_is_https_supported();

	/**
	 * Checks whether WordPress should replace old HTTP URLs to the site with their HTTPS counterpart.
	 *
	 * If a WordPress site had its URL changed from HTTP to HTTPS, by default this will return `true`, causing WordPress to
	 * add frontend filters to replace insecure site URLs that may be present in older database content. The
	 * {@see 'wp_should_replace_insecure_home_url'} filter can be used to modify that behavior.
	 *
	 * @since 5.7.0
	 *
	 * @return bool True if insecure URLs should replaced, false otherwise.
	 */
	public function wp_should_replace_insecure_home_url();

	/**
	 * Replaces insecure HTTP URLs to the site in the given content, if configured to do so.
	 *
	 * This function replaces all occurrences of the HTTP version of the site's URL with its HTTPS counterpart, if
	 * determined via {@see wp_should_replace_insecure_home_url()}.
	 *
	 * @since 5.7.0
	 *
	 * @param string $content Content to replace URLs in.
	 * @return string Filtered content.
	 */
	public function wp_replace_insecure_home_url( $content );

	/**
	 * Update the 'home' and 'siteurl' option to use the HTTPS variant of their URL.
	 *
	 * If this update does not result in WordPress recognizing that the site is now using HTTPS (e.g. due to constants
	 * overriding the URLs used), the changes will be reverted. In such a case the function will return false.
	 *
	 * @since 5.7.0
	 *
	 * @return bool True on success, false on failure.
	 */
	public function wp_update_urls_to_https();
}
