<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

interface Identifiers {
	/**
	 * Generates a random UUID (version 4).
	 *
	 * @since 4.7.0
	 * @since 7.0.0 Uses wp_rand if available.
	 *
	 * @return string UUID.
	 */
	public function wp_generate_uuid4();

	/**
	 * Validates that a UUID is valid.
	 *
	 * @since 4.9.0
	 *
	 * @param mixed $uuid    UUID to check.
	 * @param int   $version Specify which version of UUID to check against. Default is none,
	 *                       to accept any UUID version. Otherwise, only version allowed is `4`.
	 * @return bool The string is a valid UUID or false on failure.
	 */
	public function wp_is_uuid( $uuid, $version = null );

	/**
	 * Gets unique ID.
	 *
	 * This is a PHP implementation of Underscore's uniqueId method. A static variable
	 * contains an integer that is incremented with each call. This number is returned
	 * with the optional prefix. As such the returned value is not universally unique,
	 * but it is unique across the life of the PHP process.
	 *
	 * @since 5.0.3
	 *
	 * @param string $prefix Prefix for the returned ID.
	 * @return string Unique ID.
	 */
	public function wp_unique_id( $prefix = '' );

	/**
	 * Generates an incremental ID that is independent per each different prefix.
	 *
	 * It is similar to `wp_unique_id`, but each prefix has its own internal ID
	 * counter to make each prefix independent from each other. The ID starts at 1
	 * and increments on each call. The returned value is not universally unique,
	 * but it is unique across the life of the PHP process and it's stable per
	 * prefix.
	 *
	 * @since 6.4.0
	 *
	 * @param string $prefix Optional. Prefix for the returned ID. Default empty string.
	 * @return string Incremental ID per prefix.
	 */
	public function wp_unique_prefixed_id( $prefix = '' );

	/**
	 * Generates a unique ID based on the structure and values of a given array.
	 *
	 * This function serializes the array into a JSON string and generates a hash
	 * that serves as a unique identifier. Optionally, a prefix can be added to
	 * the generated ID for context or categorization.
	 *
	 * @since 6.8.0
	 *
	 * @param array  $data   The input array to generate an ID from.
	 * @param string $prefix Optional. A prefix to prepend to the generated ID. Default empty string.
	 * @return string The generated unique ID for the array.
	 */
	public function wp_unique_id_from_values( array $data, string $prefix = '' ): string;
}
