<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

interface Json {
	/**
	 * Encodes a variable into JSON, with some confidence checks.
	 *
	 * @since 4.1.0
	 * @since 5.3.0 No longer handles support for PHP < 5.6.
	 * @since 6.5.0 The `$data` parameter has been renamed to `$value` and
	 *              the `$options` parameter to `$flags` for parity with PHP.
	 *
	 * @param mixed $value Variable (usually an array or object) to encode as JSON.
	 * @param int   $flags Optional. Options to be passed to json_encode(). Default 0.
	 * @param int   $depth Optional. Maximum depth to walk through $value. Must be
	 *                     greater than 0. Default 512.
	 * @return string|false The JSON encoded string, or false if it cannot be encoded.
	 */
	public function wp_json_encode( $value, $flags = 0, $depth = 512 );

	/**
	 * Reads and decodes a JSON file.
	 *
	 * @since 5.9.0
	 *
	 * @param string $filename Path to the JSON file.
	 * @param array  $options  {
	 *     Optional. Options to be used with `json_decode()`.
	 *
	 *     @type bool $associative Optional. When `true`, JSON objects will be returned as associative arrays.
	 *                             When `false`, JSON objects will be returned as objects. Default false.
	 * }
	 *
	 * @return mixed Returns the value encoded in JSON in appropriate PHP type.
	 *               `null` is returned if the file is not found, or its content can't be decoded.
	 */
	public function wp_json_file_decode( $filename, $options = array() );

	/**
	 * Sends a JSON response back to an Ajax request.
	 *
	 * @since 3.5.0
	 * @since 4.7.0 The `$status_code` parameter was added.
	 * @since 5.6.0 The `$flags` parameter was added.
	 *
	 * @param mixed $response    Variable (usually an array or object) to encode as JSON,
	 *                           then print and die.
	 * @param int   $status_code Optional. The HTTP status code to output. Default null.
	 * @param int   $flags       Optional. Options to be passed to json_encode(). Default 0.
	 * @return never
	 */
	public function wp_send_json( $response, $status_code = null, $flags = 0 );

	/**
	 * Sends a JSON response back to an Ajax request, indicating success.
	 *
	 * @since 3.5.0
	 * @since 4.7.0 The `$status_code` parameter was added.
	 * @since 5.6.0 The `$flags` parameter was added.
	 *
	 * @param mixed $value       Optional. Data to encode as JSON, then print and die. Default null.
	 * @param int   $status_code Optional. The HTTP status code to output. Default null.
	 * @param int   $flags       Optional. Options to be passed to json_encode(). Default 0.
	 * @return never
	 */
	public function wp_send_json_success( $value = null, $status_code = null, $flags = 0 );

	/**
	 * Sends a JSON response back to an Ajax request, indicating failure.
	 *
	 * If the `$value` parameter is a WP_Error object, the errors
	 * within the object are processed and output as an array of error
	 * codes and corresponding messages. All other types are output
	 * without further processing.
	 *
	 * @since 3.5.0
	 * @since 4.1.0 The `$value` parameter is now processed if a WP_Error object is passed in.
	 * @since 4.7.0 The `$status_code` parameter was added.
	 * @since 5.6.0 The `$flags` parameter was added.
	 *
	 * @param mixed $value       Optional. Data to encode as JSON, then print and die. Default null.
	 * @param int   $status_code Optional. The HTTP status code to output. Default null.
	 * @param int   $flags       Optional. Options to be passed to json_encode(). Default 0.
	 * @return never
	 */
	public function wp_send_json_error( $value = null, $status_code = null, $flags = 0 );

	/**
	 * Checks that a JSONP callback is a valid JavaScript callback name.
	 *
	 * Only allows alphanumeric characters and the dot character in callback
	 * function names. This helps to mitigate XSS attacks caused by directly
	 * outputting user input.
	 *
	 * @since 4.6.0
	 *
	 * @param string $callback Supplied JSONP callback function name.
	 * @return bool Whether the callback function name is valid.
	 */
	public function wp_check_jsonp_callback( $callback );

	/**
	 * Gets the JSON Schema keywords allowed for a given schema profile.
	 *
	 * Use this when preparing a schema that will be consumed outside of
	 * WordPress's server-side validation, such as by REST clients, frontend code,
	 * or AI providers.
	 *
	 * The 'rest-api' profile returns the subset of JSON Schema draft-04 keywords
	 * that the REST API has historically exposed. The 'draft-04' profile preserves
	 * the larger draft-04 vocabulary used by clients that can consume standalone
	 * schemas.
	 *
	 * Allowing a keyword to be exposed does not make WordPress validate or
	 * sanitize values against it.
	 *
	 * @since 7.1.0
	 *
	 * @param string $schema_profile Optional. Name of the schema profile to get keywords for.
	 *                               Accepts 'rest-api' or 'draft-04'. Any other value falls
	 *                               back to the 'rest-api' profile. Default 'rest-api'.
	 * @return string[] Allowed JSON Schema keywords.
	 */
	public function wp_get_json_schema_allowed_keywords( string $schema_profile = 'rest-api' ): array;

	/**
	 * Prepares a JSON Schema for clients.
	 *
	 * Use this before exposing a schema outside of WordPress's server-side
	 * validation, for example in REST responses, Ability metadata, or AI provider
	 * requests. The prepared schema uses forms that JSON Schema draft-04 clients
	 * can understand.
	 *
	 * WordPress-internal schema conveniences are converted or removed only where
	 * needed to keep the exposed schema valid for the selected profile.
	 *
	 * @since 7.1.0
	 *
	 * @param array<string, mixed> $schema         The schema array.
	 * @param string               $schema_profile Optional. Name of the schema profile
	 *                                             whose keywords should be preserved.
	 *                                             Default 'draft-04'.
	 * @return array<string, mixed> The prepared schema.
	 */
	public function wp_prepare_json_schema_for_client( array $schema, string $schema_profile = 'draft-04' ): array;
}
