<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

interface Mail {
	/**
	 * Sends an email, similar to PHP's mail function.
	 *
	 * A true return value does not automatically mean that the user received the
	 * email successfully. It just only means that the method used was able to
	 * process the request without any errors.
	 *
	 * The default content type is `text/plain` which does not allow using HTML.
	 * However, you can set the content type of the email by using the
	 * {@see 'wp_mail_content_type'} filter.
	 *
	 * The default charset is based on the charset used on the blog. The charset can
	 * be set using the {@see 'wp_mail_charset'} filter.
	 *
	 * When using the `$embeds` parameter to embed images for use in HTML emails,
	 * reference the embedded file in your HTML with a `cid:` URL whose value
	 * matches the file's Content-ID. By default, the Content-ID (`cid`) used for
	 * each embedded file is the key in the embeds array, unless modified via the
	 * {@see 'wp_mail_embed_args'} filter. For example:
	 *
	 * `<img src="cid:0" alt="Logo">`
	 * `<img src="cid:my-image" alt="Image">`
	 *
	 * You may also customize the Content-ID for each file by using the
	 * {@see 'wp_mail_embed_args'} filter and setting the `cid` value.
	 *
	 * @since 1.2.1
	 * @since 5.5.0 is_email() is used for email validation,
	 *              instead of PHPMailer's default validator.
	 * @since 6.9.0 The `$embeds` parameter was added.
	 * @since 6.9.0 Improved Content-Type header handling for multipart messages.
	 *
	 * @global \PHPMailer\PHPMailer\PHPMailer $phpmailer
	 *
	 * @param string|string[] $to          Array or comma-separated list of email addresses to send message.
	 * @param string          $subject     Email subject.
	 * @param string          $message     Message contents.
	 * @param string|string[] $headers     Optional. Additional headers.
	 * @param string|string[] $attachments Optional. Paths to files to attach.
	 * @param string|string[] $embeds      Optional. Paths to files to embed.
	 * @return bool Whether the email was sent successfully.
	 */
	public function wp_mail( $to, $subject, $message, $headers = '', $attachments = array(), $embeds = array() );
}
