<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use WP_User;

interface MimeTypes {
	/**
	 * Retrieves the list of mime types and file extensions.
	 *
	 * @since 3.5.0
	 * @since 4.2.0 Support was added for GIMP (.xcf) files.
	 * @since 4.9.2 Support was added for Flac (.flac) files.
	 * @since 4.9.6 Support was added for AAC (.aac) files.
	 * @since 6.8.0 Support was added for `audio/x-wav`.
	 *
	 * @return string[] Array of mime types keyed by the file extension regex corresponding to those types.
	 */
	public function wp_get_mime_types();

	/**
	 * Retrieves the list of allowed mime types and file extensions.
	 *
	 * @since 2.8.6
	 *
	 * @param int|WP_User $user Optional. User to check. Defaults to current user.
	 * @return string[] Array of mime types keyed by the file extension regex corresponding
	 *                  to those types.
	 */
	public function get_allowed_mime_types( $user = null );

	/**
	 * Retrieves the file type from the file name.
	 *
	 * You can optionally define the mime array, if needed.
	 *
	 * @since 2.0.4
	 *
	 * @param string        $filename File name or path.
	 * @param string[]|null $mimes    Optional. Array of allowed mime types keyed by their file extension regex.
	 *                                Defaults to the result of get_allowed_mime_types().
	 * @return array {
	 *     Values for the extension and mime type.
	 *
	 *     @type string|false $ext  File extension, or false if the file doesn't match a mime type.
	 *     @type string|false $type File mime type, or false if the file doesn't match a mime type.
	 * }
	 */
	public function wp_check_filetype( $filename, $mimes = null );

	/**
	 * Attempts to determine the real file type of a file.
	 *
	 * If unable to, the file name extension will be used to determine type.
	 *
	 * If it's determined that the extension does not match the file's real type,
	 * then the "proper_filename" value will be set with a proper filename and extension.
	 *
	 * Currently this function only supports renaming images validated via wp_get_image_mime().
	 *
	 * @since 3.0.0
	 *
	 * @param string        $file     Full path to the file.
	 * @param string        $filename The name of the file (may differ from $file due to $file being
	 *                                in a tmp directory).
	 * @param string[]|null $mimes    Optional. Array of allowed mime types keyed by their file extension regex.
	 *                                Defaults to the result of get_allowed_mime_types().
	 * @return array {
	 *     Values for the extension, mime type, and corrected filename.
	 *
	 *     @type string|false $ext             File extension, or false if the file doesn't match a mime type.
	 *     @type string|false $type            File mime type, or false if the file doesn't match a mime type.
	 *     @type string|false $proper_filename File name with its correct extension, or false if it cannot be determined.
	 * }
	 */
	public function wp_check_filetype_and_ext( $file, $filename, $mimes = null );

	/**
	 * Retrieves the list of common file extensions and their types.
	 *
	 * @since 4.6.0
	 *
	 * @return array[] Multi-dimensional array of file extensions types keyed by the type of file.
	 */
	public function wp_get_ext_types();

	/**
	 * Retrieves the file type based on the extension name.
	 *
	 * @since 2.5.0
	 *
	 * @param string $ext The extension to search.
	 * @return string|null The file type, example: audio, video, document, spreadsheet, etc.
	 */
	public function wp_ext2type( $ext );

	/**
	 * Returns the first matched extension for the mime type, as mapped from wp_get_mime_types().
	 *
	 * @since 5.8.1
	 *
	 * @param string $mime_type The mime type to search.
	 * @return string|false The first matching file extension, or false if no extensions are found
	 *                      for the given mime type.
	 */
	public function wp_get_default_extension_for_mime_type( $mime_type );

	/**
	 * Returns the real mime type of an image file.
	 *
	 * This depends on exif_imagetype() or getimagesize() to determine real mime types.
	 *
	 * @since 4.7.1
	 * @since 5.8.0 Added support for WebP images.
	 * @since 6.5.0 Added support for AVIF images.
	 * @since 6.7.0 Added support for HEIC images.
	 *
	 * @param string $file Full path to the file.
	 * @return string|false The actual mime type or false if the type cannot be determined.
	 */
	public function wp_get_image_mime( $file );

	/**
	 * Checks if a mime type is for a HEIC/HEIF image.
	 *
	 * @since 6.7.0
	 *
	 * @param string $mime_type The mime type to check.
	 * @return bool Whether the mime type is for a HEIC/HEIF image.
	 */
	public function wp_is_heic_image_mime_type( $mime_type );
}
