<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use WP_Error;
use WP_Site;
use WP_User;
use wpdb;

interface MultisiteUsers {
	/**
	 * Adds a user to a blog, along with specifying the user's role.
	 *
	 * Use the {@see 'add_user_to_blog'} action to fire an event when users are added to a blog.
	 *
	 * @since MU (3.0.0)
	 *
	 * @param int    $blog_id ID of the blog the user is being added to.
	 * @param int    $user_id ID of the user being added.
	 * @param string $role    User role.
	 * @return true|WP_Error True on success or a WP_Error object if the user doesn't exist
	 *                       or could not be added.
	 */
	public function add_user_to_blog( $blog_id, $user_id, $role );

	/**
	 * Removes a user from a blog.
	 *
	 * Use the {@see 'remove_user_from_blog'} action to fire an event when
	 * users are removed from a blog.
	 *
	 * Accepts an optional `$reassign` parameter, if you want to
	 * reassign the user's blog posts to another user upon removal.
	 *
	 * @since MU (3.0.0)
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param int $user_id  ID of the user being removed.
	 * @param int $blog_id  Optional. ID of the blog the user is being removed from. Default 0.
	 * @param int $reassign Optional. ID of the user to whom to reassign posts. Default 0.
	 * @return true|WP_Error True on success or a WP_Error object if the user doesn't exist.
	 */
	public function remove_user_from_blog( $user_id, $blog_id = 0, $reassign = 0 );

	/**
	 * Adds a user to a blog based on details from maybe_add_existing_user_to_blog().
	 *
	 * @since MU (3.0.0)
	 *
	 * @param array|false $details {
	 *     User details. Must at least contain values for the keys listed below.
	 *
	 *     @type int    $user_id The ID of the user being added to the current blog.
	 *     @type string $role    The role to be assigned to the user.
	 * }
	 * @return true|WP_Error|null True on success or a WP_Error object if the user doesn't exist
	 *                            or could not be added. Null if $details array was not provided.
	 */
	public function add_existing_user_to_blog( $details = false );

	/**
	 * Gets one of a user's active blogs.
	 *
	 * Returns the user's primary blog, if they have one and
	 * it is active. If it's inactive, function returns another
	 * active blog of the user. If none are found, the user
	 * is added as a Subscriber to the Dashboard Blog and that blog
	 * is returned.
	 *
	 * @since MU (3.0.0)
	 *
	 * @param int $user_id The unique ID of the user
	 * @return WP_Site|object|null|false The blog object
	 */
	public function get_active_blog_for_user( $user_id );

	/**
	 * Gets a user's most recent post.
	 *
	 * Walks through each of a user's blogs to find the post with
	 * the most recent post_date_gmt.
	 *
	 * @since MU (3.0.0)
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param int $user_id User ID.
	 * @return array Contains the blog_id, post_id, post_date_gmt, and post_gmt_ts.
	 */
	public function get_most_recent_post_of_user( $user_id );

	/**
	 * Determines whether a user is marked as a spammer, based on user login.
	 *
	 * @since MU (3.0.0)
	 *
	 * @param string|WP_User $user Optional. Defaults to current user. WP_User object,
	 *                             or user login name as a string.
	 * @return bool
	 */
	public function is_user_spammy( $user = null );

	/**
	 * Checks an email address against a list of banned domains.
	 *
	 * This function checks against the Banned Email Domains list
	 * at wp-admin/network/settings.php. The check is only run on
	 * self-registrations; user creation at wp-admin/network/users.php
	 * bypasses this check.
	 *
	 * @since MU (3.0.0)
	 *
	 * @param string $user_email The email provided by the user at registration.
	 * @return bool True when the email address is banned, false otherwise.
	 */
	public function is_email_address_unsafe( $user_email );

	/**
	 * Cleans the user cache for a specific user.
	 *
	 * @since 3.0.0
	 *
	 * @param int $id The user ID.
	 * @return int|false The ID of the refreshed user or false if the user does not exist.
	 */
	public function refresh_user_details( $id );

	/**
	 * Creates a user.
	 *
	 * This function runs when a user self-registers as well as when
	 * a Super Admin creates a new user. Hook to {@see 'wpmu_new_user'} for events
	 * that should affect all new users, but only on Multisite (otherwise
	 * use {@see 'user_register'}).
	 *
	 * @since MU (3.0.0)
	 *
	 * @param string $user_name The new user's login name.
	 * @param string $password  The new user's password.
	 * @param string $email     The new user's email address.
	 * @return int|false Returns false on failure, or int $user_id on success.
	 */
	public function wpmu_create_user( $user_name, $password, $email );

	/**
	 * Deletes a user and all of their posts from the network.
	 *
	 * This function:
	 *
	 * - Deletes all posts (of all post types) authored by the user on all sites on the network
	 * - Deletes all links owned by the user on all sites on the network
	 * - Removes the user from all sites on the network
	 * - Deletes the user from the database
	 *
	 * @since 3.0.0
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param int $id The user ID.
	 * @return bool True if the user was deleted, false otherwise.
	 */
	public function wpmu_delete_user( $id );

	/**
	 * Sanitizes and validates data required for a user sign-up.
	 *
	 * Verifies the validity and uniqueness of user names and user email addresses,
	 * and checks email addresses against allowed and disallowed domains provided by
	 * administrators.
	 *
	 * The {@see 'wpmu_validate_user_signup'} hook provides an easy way to modify the sign-up
	 * process. The value $result, which is passed to the hook, contains both the user-provided
	 * info and the error messages created by the function. {@see 'wpmu_validate_user_signup'}
	 * allows you to process the data in any way you'd like, and unset the relevant errors if
	 * necessary.
	 *
	 * @since MU (3.0.0)
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param string $user_name  The login name provided by the user.
	 * @param string $user_email The email provided by the user.
	 * @return array {
	 *     The array of user name, email, and the error messages.
	 *
	 *     @type string   $user_name     Sanitized and unique username.
	 *     @type string   $orig_username Original username.
	 *     @type string   $user_email    User email address.
	 *     @type WP_Error $errors        WP_Error object containing any errors found.
	 * }
	 */
	public function wpmu_validate_user_signup( $user_name, $user_email );

	/**
	 * Processes new site registrations.
	 *
	 * Checks the data provided by the user during blog signup. Verifies
	 * the validity and uniqueness of blog paths and domains.
	 *
	 * This function prevents the current user from registering a new site
	 * with a blogname equivalent to another user's login name. Passing the
	 * $user parameter to the function, where $user is the other user, is
	 * effectively an override of this limitation.
	 *
	 * Filter {@see 'wpmu_validate_blog_signup'} if you want to modify
	 * the way that WordPress validates new site signups.
	 *
	 * @since MU (3.0.0)
	 *
	 * @global wpdb   $wpdb   WordPress database abstraction object.
	 * @global string $domain
	 *
	 * @param string         $blogname   The site name provided by the user. Must be unique.
	 * @param string         $blog_title The site title provided by the user.
	 * @param WP_User|string $user       Optional. The user object to check against the new site name.
	 *                                   Default empty string.
	 * @return array {
	 *     Array of domain, path, site name, site title, user and error messages.
	 *
	 *     @type string         $domain     Domain for the site.
	 *     @type string         $path       Path for the site. Used in subdirectory installations.
	 *     @type string         $blogname   The unique site name (slug).
	 *     @type string         $blog_title Blog title.
	 *     @type string|WP_User $user       By default, an empty string. A user object if provided.
	 *     @type WP_Error       $errors     WP_Error containing any errors found.
	 * }
	 */
	public function wpmu_validate_blog_signup( $blogname, $blog_title, $user = '' );

	/**
	 * Records user signup information for future activation.
	 *
	 * This function is used when user registration is open but
	 * new site registration is not.
	 *
	 * @since MU (3.0.0)
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param string $user       The user's requested login name.
	 * @param string $user_email The user's email address.
	 * @param array  $meta       Optional. Signup meta data. Default empty array.
	 */
	public function wpmu_signup_user( $user, $user_email, $meta = array() );

	/**
	 * Records site signup information for future activation.
	 *
	 * @since MU (3.0.0)
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param string $domain     The requested domain.
	 * @param string $path       The requested path.
	 * @param string $title      The requested site title.
	 * @param string $user       The user's requested login name.
	 * @param string $user_email The user's email address.
	 * @param array  $meta       Optional. Signup meta data. By default, contains the requested privacy setting and lang_id.
	 */
	public function wpmu_signup_blog( $domain, $path, $title, $user, $user_email, $meta = array() );

	/**
	 * Activates a signup.
	 *
	 * Hook to {@see 'wpmu_activate_user'} or {@see 'wpmu_activate_blog'} for events
	 * that should happen only when users or sites are self-created (since
	 * those actions are not called when users and sites are created
	 * by a Super Admin).
	 *
	 * @since MU (3.0.0)
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param string $key The activation key provided to the user.
	 * @return array|WP_Error An array containing information about the activated user and/or blog.
	 * @phpstan-return array{
	 *     user_id: int,
	 *     password: string,
	 *     meta: array<string, mixed>,
	 * }|array{
	 *     blog_id: int,
	 *     user_id: int,
	 *     password: string,
	 *     title: string,
	 *     meta: array<string, mixed>,
	 * }|WP_Error
	 */
	public function wpmu_activate_signup( $key );

	/**
	 * Sends a confirmation request email to a user when they sign up for a new user account (without signing up for a site
	 * at the same time). The user account will not become active until the confirmation link is clicked.
	 *
	 * This is the notification function used when no new site has
	 * been requested.
	 *
	 * Filter {@see 'wpmu_signup_user_notification'} to bypass this function or
	 * replace it with your own notification behavior.
	 *
	 * Filter {@see 'wpmu_signup_user_notification_email'} and
	 * {@see 'wpmu_signup_user_notification_subject'} to change the content
	 * and subject line of the email sent to newly registered users.
	 *
	 * @since MU (3.0.0)
	 *
	 * @param string $user_login The user's login name.
	 * @param string $user_email The user's email address.
	 * @param string $key        The activation key created in wpmu_signup_user()
	 * @param array  $meta       Optional. Signup meta data. Default empty array.
	 * @return bool
	 */
	public function wpmu_signup_user_notification( $user_login, $user_email, $key, $meta = array() );

	/**
	 * Sends a confirmation request email to a user when they sign up for a new site. The new site will not become active
	 * until the confirmation link is clicked.
	 *
	 * This is the notification function used when site registration
	 * is enabled.
	 *
	 * Filter {@see 'wpmu_signup_blog_notification'} to bypass this function or
	 * replace it with your own notification behavior.
	 *
	 * Filter {@see 'wpmu_signup_blog_notification_email'} and
	 * {@see 'wpmu_signup_blog_notification_subject'} to change the content
	 * and subject line of the email sent to newly registered users.
	 *
	 * @since MU (3.0.0)
	 *
	 * @param string $domain     The new blog domain.
	 * @param string $path       The new blog path.
	 * @param string $title      The site title.
	 * @param string $user_login The user's login name.
	 * @param string $user_email The user's email address.
	 * @param string $key        The activation key created in wpmu_signup_blog().
	 * @param array  $meta       Optional. Signup meta data. By default, contains the requested privacy setting and lang_id.
	 * @return bool
	 */
	public function wpmu_signup_blog_notification( $domain, $path, $title, $user_login, $user_email, $key, $meta = array() );

	/**
	 * Notifies a user that their account activation has been successful.
	 *
	 * Filter {@see 'wpmu_welcome_user_notification'} to disable or bypass.
	 *
	 * Filter {@see 'update_welcome_user_email'} and {@see 'update_welcome_user_subject'} to
	 * modify the content and subject line of the notification email.
	 *
	 * @since MU (3.0.0)
	 *
	 * @param int    $user_id  User ID.
	 * @param string $password User password.
	 * @param array  $meta     Optional. Signup meta data. Default empty array.
	 * @return bool
	 */
	public function wpmu_welcome_user_notification( $user_id, $password, $meta = array() );

	/**
	 * Notifies the site administrator that their site activation was successful.
	 *
	 * Filter {@see 'wpmu_welcome_notification'} to disable or bypass.
	 *
	 * Filter {@see 'update_welcome_email'} and {@see 'update_welcome_subject'} to
	 * modify the content and subject line of the notification email.
	 *
	 * @since MU (3.0.0)
	 *
	 * @param int    $blog_id  Site ID.
	 * @param int    $user_id  User ID.
	 * @param string $password User password, or "N/A" if the user account is not new.
	 * @param string $title    Site title.
	 * @param array  $meta     Optional. Signup meta data. By default, contains the requested privacy setting and lang_id.
	 * @return bool Whether the email notification was sent.
	 */
	public function wpmu_welcome_notification( $blog_id, $user_id, $password, $title, $meta = array() );

	/**
	 * Notifies the network admin that a new user has been activated.
	 *
	 * Filter {@see 'newuser_notify_siteadmin'} to change the content of
	 * the notification email.
	 *
	 * @since MU (3.0.0)
	 *
	 * @param int $user_id The new user's ID.
	 * @return bool
	 */
	public function newuser_notify_siteadmin( $user_id );

	/**
	 * Notifies the network admin that a new site has been activated.
	 *
	 * Filter {@see 'newblog_notify_siteadmin'} to change the content of
	 * the notification email.
	 *
	 * @since MU (3.0.0)
	 * @since 5.1.0 $blog_id now supports input from the {@see 'wp_initialize_site'} action.
	 *
	 * @param WP_Site|int $blog_id    The new site's object or ID.
	 * @param string      $deprecated Not used.
	 * @return bool
	 */
	public function newblog_notify_siteadmin( $blog_id, $deprecated = '' );

	/**
	 * Notifies the Multisite network administrator that a new site was created.
	 *
	 * Filter {@see 'send_new_site_email'} to disable or bypass.
	 *
	 * Filter {@see 'new_site_email'} to filter the contents.
	 *
	 * @since 5.6.0
	 *
	 * @param int $site_id Site ID of the new site.
	 * @param int $user_id User ID of the administrator of the new site.
	 * @return bool Whether the email notification was sent.
	 */
	public function wpmu_new_site_admin_notification( $site_id, $user_id );
}
