<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use PasswordHash;
use WP_Error;
use WP_User;
use wpdb;

interface Passwords {
	/**
	 * Creates a hash of a plain text password.
	 *
	 * For integration with other applications, this function can be overwritten to
	 * instead use the other package password hashing algorithm.
	 *
	 * @since 2.5.0
	 * @since 6.8.0 The password is now hashed using bcrypt by default instead of phpass.
	 *
	 * @global PasswordHash $wp_hasher phpass object.
	 *
	 * @param string $password Plain text user password to hash.
	 * @return string The hash string of the password.
	 */
	public function wp_hash_password( $password );

	/**
	 * Checks a plaintext password against a hashed password.
	 *
	 * Note that this function may be used to check a value that is not a user password.
	 * A plugin may use this function to check a password of a different type, and there
	 * may not always be a user ID associated with the password.
	 *
	 * For integration with other applications, this function can be overwritten to
	 * instead use the other package password hashing algorithm.
	 *
	 * @since 2.5.0
	 * @since 6.8.0 Passwords in WordPress are now hashed with bcrypt by default. A
	 *              password that wasn't hashed with bcrypt will be checked with phpass.
	 *
	 * @global PasswordHash $wp_hasher phpass object. Used as a fallback for verifying
	 *                                 passwords that were hashed with phpass.
	 *
	 * @param string     $password Plaintext password.
	 * @param string     $hash     Hash of the password to check against.
	 * @param string|int $user_id  Optional. ID of a user associated with the password.
	 * @return bool False, if the $password does not match the hashed password.
	 */
	public function wp_check_password( $password, $hash, $user_id = '' );

	/**
	 * Checks whether a password hash needs to be rehashed.
	 *
	 * Passwords are hashed with bcrypt using the default cost. A password hashed in a prior version
	 * of WordPress may still be hashed with phpass and will need to be rehashed. If the default cost
	 * or algorithm is changed in PHP or WordPress then a password hashed in a previous version will
	 * need to be rehashed.
	 *
	 * Note that, just like wp_check_password(), this function may be used to check a value that is
	 * not a user password. A plugin may use this function to check a password of a different type,
	 * and there may not always be a user ID associated with the password.
	 *
	 * @since 6.8.0
	 *
	 * @global PasswordHash $wp_hasher phpass object.
	 *
	 * @param string     $hash    Hash of a password to check.
	 * @param string|int $user_id Optional. ID of a user associated with the password.
	 * @return bool Whether the hash needs to be rehashed.
	 */
	public function wp_password_needs_rehash( $hash, $user_id = '' );

	/**
	 * Updates the user's password with a new hashed one.
	 *
	 * For integration with other applications, this function can be overwritten to
	 * instead use the other package password checking algorithm.
	 *
	 * Please note: This function should be used sparingly and is really only meant for single-time
	 * application. Leveraging this improperly in a plugin or theme could result in an endless loop
	 * of password resets if precautions are not taken to ensure it does not execute on every page load.
	 *
	 * @since 2.5.0
	 * @since 6.8.0 The password is now hashed using bcrypt by default instead of phpass.
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param string $password The plaintext new user password.
	 * @param int    $user_id  User ID.
	 */
	public function wp_set_password( $password, $user_id );

	/**
	 * Generates a random password drawn from the defined set of characters.
	 *
	 * Uses wp_rand() to create passwords with far less predictability
	 * than similar native PHP functions like `rand()` or `mt_rand()`.
	 *
	 * @since 2.5.0
	 *
	 * @param int  $length              Optional. The length of password to generate. Default 12.
	 * @param bool $special_chars       Optional. Whether to include standard special characters.
	 *                                  Default true.
	 * @param bool $extra_special_chars Optional. Whether to include other special characters.
	 *                                  Used when generating secret keys and salts. Default false.
	 * @return string The random password.
	 */
	public function wp_generate_password( $length = 12, $special_chars = true, $extra_special_chars = false );

	/**
	 * Generates a random non-negative number.
	 *
	 * @since 2.6.2
	 * @since 4.4.0 Uses PHP7 random_int() or the random_compat library if available.
	 * @since 6.1.0 Returns zero instead of a random number if both `$min` and `$max` are zero.
	 *
	 * @global string $rnd_value
	 *
	 * @param int $min Optional. Lower limit for the generated number.
	 *                 Accepts positive integers or zero. Defaults to 0.
	 * @param int $max Optional. Upper limit for the generated number.
	 *                 Accepts positive integers. Defaults to 4294967295.
	 * @return int A random non-negative number between min and max.
	 */
	public function wp_rand( $min = null, $max = null );

	/**
	 * Gets the text suggesting how to create strong passwords.
	 *
	 * @since 4.1.0
	 *
	 * @return string The password hint text.
	 */
	public function wp_get_password_hint();

	/**
	 * Creates, stores, then returns a password reset key for user.
	 *
	 * @since 4.4.0
	 *
	 * @param WP_User $user User to retrieve password reset key for.
	 * @return string|WP_Error Password reset key on success. WP_Error on error.
	 */
	public function get_password_reset_key( $user );

	/**
	 * Retrieves a user row based on password reset key and login.
	 *
	 * A key is considered 'expired' if it exactly matches the value of the
	 * user_activation_key field, rather than being matched after going through the
	 * hashing process. This field is now hashed; old values are no longer accepted
	 * but have a different WP_Error code so good user feedback can be provided.
	 *
	 * @since 3.1.0
	 *
	 * @param string $key       The password reset key.
	 * @param string $login     The user login.
	 * @return WP_User|WP_Error WP_User object on success, WP_Error object for invalid or expired keys.
	 */
	public function check_password_reset_key( $key, $login );

	/**
	 * Handles resetting the user's password.
	 *
	 * @since 2.5.0
	 *
	 * @param WP_User $user     The user
	 * @param string  $new_pass New password for the user in plaintext
	 */
	public function reset_password( $user, $new_pass );

	/**
	 * Handles sending a password retrieval email to a user.
	 *
	 * @since 2.5.0
	 * @since 5.7.0 Added `$user_login` parameter.
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param string $user_login Optional. Username to send a password retrieval email for.
	 *                           Defaults to `$_POST['user_login']` if not set.
	 * @return true|WP_Error True when finished, WP_Error object on error.
	 */
	public function retrieve_password( $user_login = '' );

	/**
	 * Checks if password reset is allowed for a specific user.
	 *
	 * @since 6.3.0
	 *
	 * @param int|WP_User $user The user to check.
	 * @return bool|WP_Error True if allowed, false or WP_Error otherwise.
	 */
	public function wp_is_password_reset_allowed_for_user( $user );

	/**
	 * Checks if Application Passwords is supported.
	 *
	 * Application Passwords is supported only by sites using SSL or local environments
	 * but may be made available using the {@see 'wp_is_application_passwords_available'} filter.
	 *
	 * @since 5.9.0
	 *
	 * @return bool
	 */
	public function wp_is_application_passwords_supported();

	/**
	 * Checks if Application Passwords is globally available.
	 *
	 * By default, Application Passwords is available to all sites using SSL or to local environments.
	 * Use the {@see 'wp_is_application_passwords_available'} filter to adjust its availability.
	 *
	 * @since 5.6.0
	 *
	 * @return bool
	 */
	public function wp_is_application_passwords_available();

	/**
	 * Checks if Application Passwords is available for a specific user.
	 *
	 * By default all users can use Application Passwords. Use {@see 'wp_is_application_passwords_available_for_user'}
	 * to restrict availability to certain users.
	 *
	 * @since 5.6.0
	 *
	 * @param int|WP_User $user The user to check.
	 * @return bool
	 */
	public function wp_is_application_passwords_available_for_user( $user );
}
