<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use stdClass;
use WP_Error;
use WP_Post;
use WP_Taxonomy;
use wpdb;

interface PostAttachments {
	/**
	 * Retrieves attached file path based on attachment ID.
	 *
	 * By default the path will go through the {@see 'get_attached_file'} filter, but
	 * passing `true` to the `$unfiltered` argument will return the file path unfiltered.
	 *
	 * The function works by retrieving the `_wp_attached_file` post meta value.
	 * This is a convenience function to prevent looking up the meta name and provide
	 * a mechanism for sending the attached filename through a filter.
	 *
	 * @since 2.0.0
	 *
	 * @param int  $attachment_id Attachment ID.
	 * @param bool $unfiltered    Optional. Whether to skip the {@see 'get_attached_file'} filter.
	 *                            Default false.
	 * @return string|false The file path to where the attached file should be, false otherwise.
	 */
	public function get_attached_file( int $attachment_id, $unfiltered = false );

	/**
	 * Updates attachment file path based on attachment ID.
	 *
	 * Used to update the file path of the attachment, which uses post meta name
	 * `_wp_attached_file` to store the path of the attachment.
	 *
	 * @since 2.1.0
	 *
	 * @param int    $attachment_id Attachment ID.
	 * @param string $file          File path for the attachment.
	 * @return int|bool Meta ID if the `_wp_attached_file` key didn't exist for the attachment.
	 *                  True on successful update, false on failure or if the `$file` value passed
	 *                  to the function is the same as the one that is already in the database.
	 */
	public function update_attached_file( int $attachment_id, string $file );

	/**
	 * Counts number of attachments for the mime type(s).
	 *
	 * If you set the optional mime_type parameter, then an array will still be
	 * returned, but will only have the item you are looking for. It does not give
	 * you the number of attachments that are children of a post. You can get that
	 * by counting the number of children that post has.
	 *
	 * @since 2.5.0
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param string|string[] $mime_type Optional. Array or comma-separated list of
	 *                                   MIME patterns. Default empty.
	 * @return stdClass An object containing the attachment counts by mime type.
	 */
	public function wp_count_attachments( $mime_type = '' );

	/**
	 * Determines whether an attachment URI is local and really an attachment.
	 *
	 * For more information on this and similar theme functions, check out
	 * the {@link https://developer.wordpress.org/themes/basics/conditional-tags/
	 * Conditional Tags} article in the Theme Developer Handbook.
	 *
	 * @since 2.0.0
	 *
	 * @param string $url URL to check
	 * @return bool True on success, false on failure.
	 */
	public function is_local_attachment( $url );

	/**
	 * Inserts an attachment.
	 *
	 * If you set the 'ID' in the $args parameter, it will mean that you are
	 * updating and attempt to update the attachment. You can also set the
	 * attachment name or title by setting the key 'post_name' or 'post_title'.
	 *
	 * You can set the dates for the attachment manually by setting the 'post_date'
	 * and 'post_date_gmt' keys' values.
	 *
	 * By default, the comments will use the default settings for whether the
	 * comments are allowed. You can close them manually or keep them open by
	 * setting the value for the 'comment_status' key.
	 *
	 * @since 2.0.0
	 * @since 4.7.0 Added the `$wp_error` parameter to allow a WP_Error to be returned on failure.
	 * @since 5.6.0 Added the `$fire_after_hooks` parameter.
	 *
	 * @see wp_insert_post()
	 *
	 * @param string|array $args             Arguments for inserting an attachment.
	 * @param string|false $file             Optional. Filename. Default false.
	 * @param int          $parent_post_id   Optional. Parent post ID or 0 for no parent. Default 0.
	 * @param bool         $wp_error         Optional. Whether to return a WP_Error on failure. Default false.
	 * @param bool         $fire_after_hooks Optional. Whether to fire the after insert hooks. Default true.
	 * @return int|WP_Error The attachment ID on success. The value 0 or WP_Error on failure.
	 *
	 * @phpstan-return (
	 *     $wp_error is false ? int : int|WP_Error
	 * )
	 */
	public function wp_insert_attachment( $args, $file = false, $parent_post_id = 0, $wp_error = false, $fire_after_hooks = true );

	/**
	 * Trashes or deletes an attachment.
	 *
	 * When an attachment is permanently deleted, the file will also be removed.
	 * Deletion removes all post meta fields, taxonomy, comments, etc. associated
	 * with the attachment (except the main post).
	 *
	 * The attachment is moved to the Trash instead of permanently deleted unless Trash
	 * for media is disabled, item is already in the Trash, or $force_delete is true.
	 *
	 * @since 2.0.0
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param int  $post_id      Attachment ID.
	 * @param bool $force_delete Optional. Whether to bypass Trash and force deletion.
	 *                           Default false.
	 * @return WP_Post|false|null Post data on success, false or null on failure.
	 */
	public function wp_delete_attachment( $post_id, $force_delete = false );

	/**
	 * Deletes all files that belong to the given attachment.
	 *
	 * @since 4.9.7
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param int    $post_id      Attachment ID.
	 * @param array  $meta         The attachment's meta data.
	 * @param array  $backup_sizes The meta data for the attachment's backup images.
	 * @param string $file         Absolute path to the attachment's file.
	 * @return bool True on success, false on failure.
	 */
	public function wp_delete_attachment_files( $post_id, $meta, $backup_sizes, $file );

	/**
	 * Retrieves attachment metadata for attachment ID.
	 *
	 * @since 2.1.0
	 * @since 6.0.0 The `$filesize` value was added to the returned array.
	 * @since 7.1.0 `false` is now returned if the metadata is not an array, and when the result is
	 *              filtered the `sizes` key is always an array when present.
	 *
	 * @param int  $attachment_id Attachment post ID. Defaults to global $post.
	 * @param bool $unfiltered    Optional. If true, filters are not run. Default false.
	 * @return array|false {
	 *     Attachment metadata. False on failure.
	 *
	 *     @type int    $width      The width of the attachment.
	 *     @type int    $height     The height of the attachment.
	 *     @type string $file       The file path relative to `wp-content/uploads`.
	 *     @type array  $sizes      Keys are size slugs, each value is an array containing
	 *                              'file', 'width', 'height', and 'mime-type'.
	 *     @type array  $image_meta Image metadata.
	 *     @type int    $filesize   File size of the attachment.
	 * }
	 *
	 * @phpstan-return array{
	 *                     width?: int<1, max>,
	 *                     height?: int<1, max>,
	 *                     file?: non-empty-string,
	 *                     filesize?: int<0, max>,
	 *                     original_image?: non-empty-string,
	 *                     source_image?: non-empty-string,
	 *                     sizes?: array<non-empty-string, array{
	 *                                                         file: non-empty-string,
	 *                                                         width: int<1, max>,
	 *                                                         height: int<1, max>,
	 *                                                         'mime-type': non-empty-string,
	 *                                                         filesize?: int<0, max>,
	 *                                                         ...
	 *                                                     }>,
	 *                     image_meta?: array{
	 *                                      aperture: numeric-string|int,
	 *                                      credit: string,
	 *                                      camera: string,
	 *                                      caption: string,
	 *                                      created_timestamp: numeric-string|int,
	 *                                      copyright: string,
	 *                                      focal_length: numeric-string|int,
	 *                                      iso: numeric-string|int,
	 *                                      shutter_speed: numeric-string|int,
	 *                                      title: string,
	 *                                      orientation: numeric-string|int,
	 *                                      keywords: list<string>,
	 *                                      alt: string,
	 *                                  },
	 *                     ...
	 *                 }|false
	 */
	public function wp_get_attachment_metadata( $attachment_id = 0, $unfiltered = false );

	/**
	 * Updates metadata for an attachment.
	 *
	 * @since 2.1.0
	 *
	 * @param int   $attachment_id Attachment post ID.
	 * @param array $data          Attachment meta data.
	 * @return int|bool Whether the metadata was successfully updated.
	 *                  True on success, the Meta ID if the key didn't exist.
	 *                  False if $post is invalid, on failure, or if $data is the same as the existing metadata.
	 */
	public function wp_update_attachment_metadata( $attachment_id, $data );

	/**
	 * Retrieves the URL for an attachment.
	 *
	 * @since 2.1.0
	 *
	 * @global string $pagenow The filename of the current screen.
	 *
	 * @param int $attachment_id Optional. Attachment post ID. Defaults to global $post.
	 * @return string|false Attachment URL, otherwise false.
	 */
	public function wp_get_attachment_url( $attachment_id = 0 );

	/**
	 * Retrieves the caption for an attachment.
	 *
	 * @since 4.6.0
	 *
	 * @param int $post_id Optional. Attachment ID. Default is the ID of the global `$post`.
	 * @return string|false Attachment caption on success, false on failure.
	 */
	public function wp_get_attachment_caption( $post_id = 0 );

	/**
	 * Retrieves thumbnail for an attachment.
	 * Note that this works only for the (very) old image metadata style where 'thumb' was set,
	 * and the 'sizes' array did not exist. This function returns false for the newer image metadata style
	 * despite that 'thumbnail' is present in the 'sizes' array.
	 *
	 * @since 2.1.0
	 * @deprecated 6.1.0
	 *
	 * @param int $post_id Optional. Attachment ID. Default is the ID of the global `$post`.
	 * @return string|false Thumbnail file path on success, false on failure.
	 */
	public function wp_get_attachment_thumb_file( $post_id = 0 );

	/**
	 * Retrieves URL for an attachment thumbnail.
	 *
	 * @since 2.1.0
	 * @since 6.1.0 Changed to use wp_get_attachment_image_url().
	 *
	 * @param int $post_id Optional. Attachment ID. Default is the ID of the global `$post`.
	 * @return string|false Thumbnail URL on success, false on failure.
	 */
	public function wp_get_attachment_thumb_url( $post_id = 0 );

	/**
	 * Verifies an attachment is of a given type.
	 *
	 * @since 4.2.0
	 *
	 * @param string      $type Attachment type. Accepts `image`, `audio`, `video`, or a file extension.
	 * @param int|WP_Post $post Optional. Attachment ID or object. Default is global $post.
	 * @return bool True if an accepted type or a matching file extension, false otherwise.
	 */
	public function wp_attachment_is( $type, $post = null );

	/**
	 * Determines whether an attachment is an image.
	 *
	 * For more information on this and similar theme functions, check out
	 * the {@link https://developer.wordpress.org/themes/basics/conditional-tags/
	 * Conditional Tags} article in the Theme Developer Handbook.
	 *
	 * @since 2.1.0
	 * @since 4.2.0 Modified into wrapper for wp_attachment_is() and
	 *              allowed WP_Post object to be passed.
	 *
	 * @param int|WP_Post $post Optional. Attachment ID or object. Default is global $post.
	 * @return bool Whether the attachment is an image.
	 */
	public function wp_attachment_is_image( $post = null );

	/**
	 * Will clean the attachment in the cache.
	 *
	 * Cleaning means delete from the cache. Optionally will clean the term
	 * object cache associated with the attachment ID.
	 *
	 * This function will not run if $_wp_suspend_cache_invalidation is not empty.
	 *
	 * @since 3.0.0
	 *
	 * @global bool $_wp_suspend_cache_invalidation
	 *
	 * @param int  $id          The attachment ID in the cache to clean.
	 * @param bool $clean_terms Optional. Whether to clean terms cache. Default false.
	 */
	public function clean_attachment_cache( $id, $clean_terms = false );

	/**
	 * Tries to convert an attachment URL into a post ID.
	 *
	 * @since 4.0.0
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @param string $url The URL to resolve.
	 * @return int The found post ID, or 0 on failure.
	 */
	public function attachment_url_to_postid( $url );

	/**
	 * Retrieves media attached to the passed post.
	 *
	 * @since 3.6.0
	 *
	 * @param string      $type Mime type.
	 * @param int|WP_Post $post Optional. Post ID or WP_Post object. Default is global $post.
	 * @return WP_Post[] Array of media attached to the given post.
	 */
	public function get_attached_media( $type, $post = 0 );

	/**
	 * Retrieves taxonomies attached to given the attachment.
	 *
	 * @since 2.5.0
	 * @since 4.7.0 Introduced the `$output` parameter.
	 *
	 * @param int|array|object $attachment Attachment ID, data array, or data object.
	 * @param string           $output     Output type. 'names' to return an array of taxonomy names,
	 *                                     or 'objects' to return an array of taxonomy objects.
	 *                                     Default is 'names'.
	 * @return string[]|WP_Taxonomy[] List of taxonomies or taxonomy names. Empty array on failure.
	 */
	public function get_attachment_taxonomies( $attachment, $output = 'names' );

	/**
	 * Retrieves all of the taxonomies that are registered for attachments.
	 *
	 * Handles mime-type-specific taxonomies such as attachment:image and attachment:video.
	 *
	 * @since 3.5.0
	 *
	 * @see get_taxonomies()
	 *
	 * @param string $output Optional. The type of taxonomy output to return. Accepts 'names' or 'objects'.
	 *                       Default 'names'.
	 * @return string[]|WP_Taxonomy[] Array of names or objects of registered taxonomies for attachments.
	 */
	public function get_taxonomies_for_attachments( $output = 'names' );

	/**
	 * Returns useful keys to use to lookup data from an attachment's stored metadata.
	 *
	 * @since 3.9.0
	 *
	 * @param WP_Post $attachment The current attachment, provided for context.
	 * @param string  $context    Optional. The context. Accepts 'edit', 'display'. Default 'display'.
	 * @return string[] Key/value pairs of field keys to labels.
	 */
	public function wp_get_attachment_id3_keys( $attachment, $context = 'display' );

	/**
	 * Maybe attempts to generate attachment metadata, if missing.
	 *
	 * @since 3.9.0
	 *
	 * @param WP_Post $attachment Attachment object.
	 */
	public function wp_maybe_generate_attachment_metadata( $attachment );

	/**
	 * Prepares an attachment post object for JS, where it is expected
	 * to be JSON-encoded and fit into an Attachment model.
	 *
	 * @since 3.5.0
	 *
	 * @param int|WP_Post $attachment Attachment ID or object.
	 * @return array|null {
	 *     Array of attachment details, or null if the parameter does not correspond to an attachment.
	 *
	 *     @type string $alt                   Alt text of the attachment.
	 *     @type string $author                ID of the attachment author, as a string.
	 *     @type string $authorName            Name of the attachment author.
	 *     @type string $caption               Caption for the attachment.
	 *     @type array  $compat                Containing item and meta.
	 *     @type string $context               Context, whether it's used as the site icon for example.
	 *     @type int    $date                  Uploaded date, timestamp in milliseconds.
	 *     @type string $dateFormatted         Formatted date (e.g. June 29, 2018).
	 *     @type string $description           Description of the attachment.
	 *     @type string $editLink              URL to the edit page for the attachment.
	 *     @type string $filename              File name of the attachment.
	 *     @type string $filesizeHumanReadable Filesize of the attachment in human readable format (e.g. 1 MB).
	 *     @type int    $filesizeInBytes       Filesize of the attachment in bytes.
	 *     @type int    $height                If the attachment is an image, represents the height of the image in pixels.
	 *     @type string $icon                  Icon URL of the attachment (e.g. /wp-includes/images/media/archive.png).
	 *     @type int    $id                    ID of the attachment.
	 *     @type string $link                  URL to the attachment.
	 *     @type int    $menuOrder             Menu order of the attachment post.
	 *     @type array  $meta                  Meta data for the attachment.
	 *     @type string $mime                  Mime type of the attachment (e.g. image/jpeg or application/zip).
	 *     @type int    $modified              Last modified, timestamp in milliseconds.
	 *     @type string $name                  Name, same as title of the attachment.
	 *     @type array  $nonces                Nonces for update, delete and edit.
	 *     @type string $orientation           If the attachment is an image, represents the image orientation
	 *                                         (landscape or portrait).
	 *     @type array  $sizes                 If the attachment is an image, contains an array of arrays
	 *                                         for the images sizes: thumbnail, medium, large, and full.
	 *     @type string $status                Post status of the attachment (usually 'inherit').
	 *     @type string $subtype               Mime subtype of the attachment (usually the last part, e.g. jpeg or zip).
	 *     @type string $title                 Title of the attachment (usually slugified file name without the extension).
	 *     @type string $type                  Type of the attachment (usually first part of the mime type, e.g. image).
	 *     @type int    $uploadedTo            Parent post to which the attachment was uploaded.
	 *     @type string $uploadedToLink        URL to the edit page of the parent post of the attachment.
	 *     @type string $uploadedToTitle       Post title of the parent of the attachment.
	 *     @type string $url                   Direct URL to the attachment file (from wp-content).
	 *     @type int    $width                 If the attachment is an image, represents the width of the image in pixels.
	 * }
	 */
	public function wp_prepare_attachment_for_js( $attachment );
}
