<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use WP_Post;
use WP_Query;

interface PostThumbnails {
	/**
	 * Retrieves the post thumbnail ID.
	 *
	 * @since 2.9.0
	 * @since 4.4.0 `$post` can be a post ID or WP_Post object.
	 * @since 5.5.0 The return value for a non-existing post
	 *              was changed to false instead of an empty string.
	 *
	 * @param int|WP_Post|null $post Optional. Post ID or WP_Post object. Default is global `$post`.
	 * @return int|false Post thumbnail ID (which can be 0 if the thumbnail is not set),
	 *                   or false if the post does not exist.
	 */
	public function get_post_thumbnail_id( $post = null );

	/**
	 * Retrieves the post thumbnail.
	 *
	 * When a theme adds 'post-thumbnail' support, a special 'post-thumbnail' image size
	 * is registered, which differs from the 'thumbnail' image size managed via the
	 * Settings > Media screen.
	 *
	 * When using the_post_thumbnail() or related functions, the 'post-thumbnail' image
	 * size is used by default, though a different size can be specified instead as needed.
	 *
	 * @since 2.9.0
	 * @since 4.4.0 `$post` can be a post ID or WP_Post object.
	 *
	 * @param int|WP_Post|null $post Optional. Post ID or WP_Post object.  Default is global `$post`.
	 * @param string|int[]     $size Optional. Image size. Accepts any registered image size name, or an array of
	 *                               width and height values in pixels (in that order). Default 'post-thumbnail'.
	 * @param string|array     $attr Optional. Query string or array of attributes. Default empty.
	 * @return string The post thumbnail image tag.
	 */
	public function get_the_post_thumbnail( $post = null, $size = 'post-thumbnail', $attr = '' );

	/**
	 * Returns the post thumbnail caption.
	 *
	 * @since 4.6.0
	 *
	 * @param int|WP_Post|null $post Optional. Post ID or WP_Post object. Default is global `$post`.
	 * @return string Post thumbnail caption.
	 */
	public function get_the_post_thumbnail_caption( $post = null );

	/**
	 * Returns the post thumbnail URL.
	 *
	 * @since 4.4.0
	 *
	 * @param int|WP_Post|null $post Optional. Post ID or WP_Post object.  Default is global `$post`.
	 * @param string|int[]     $size Optional. Registered image size to retrieve the source for or a flat array
	 *                               of height and width dimensions. Default 'post-thumbnail'.
	 * @return string|false Post thumbnail URL or false if no image is available. If `$size` does not match
	 *                      any registered image size, the original image URL will be returned.
	 */
	public function get_the_post_thumbnail_url( $post = null, $size = 'post-thumbnail' );

	/**
	 * Determines whether a post has an image attached.
	 *
	 * For more information on this and similar theme functions, check out
	 * the {@link https://developer.wordpress.org/themes/basics/conditional-tags/
	 * Conditional Tags} article in the Theme Developer Handbook.
	 *
	 * @since 2.9.0
	 * @since 4.4.0 `$post` can be a post ID or WP_Post object.
	 *
	 * @param int|WP_Post|null $post Optional. Post ID or WP_Post object. Default is global `$post`.
	 * @return bool Whether the post has an image attached.
	 */
	public function has_post_thumbnail( $post = null );

	/**
	 * Displays the post thumbnail.
	 *
	 * When a theme adds 'post-thumbnail' support, a special 'post-thumbnail' image size
	 * is registered, which differs from the 'thumbnail' image size managed via the
	 * Settings > Media screen.
	 *
	 * When using the_post_thumbnail() or related functions, the 'post-thumbnail' image
	 * size is used by default, though a different size can be specified instead as needed.
	 *
	 * @since 2.9.0
	 *
	 * @see get_the_post_thumbnail()
	 *
	 * @param string|int[] $size Optional. Image size. Accepts any registered image size name, or an array of
	 *                           width and height values in pixels (in that order). Default 'post-thumbnail'.
	 * @param string|array $attr Optional. Query string or array of attributes. Default empty.
	 */
	public function the_post_thumbnail( $size = 'post-thumbnail', $attr = '' );

	/**
	 * Displays the post thumbnail caption.
	 *
	 * @since 4.6.0
	 *
	 * @param int|WP_Post|null $post Optional. Post ID or WP_Post object. Default is global `$post`.
	 */
	public function the_post_thumbnail_caption( $post = null );

	/**
	 * Displays the post thumbnail URL.
	 *
	 * @since 4.4.0
	 *
	 * @param string|int[] $size Optional. Image size to use. Accepts any valid image size,
	 *                           or an array of width and height values in pixels (in that order).
	 *                           Default 'post-thumbnail'.
	 */
	public function the_post_thumbnail_url( $size = 'post-thumbnail' );

	/**
	 * Updates cache for thumbnails in the current loop.
	 *
	 * @since 3.2.0
	 *
	 * @global WP_Query $wp_query WordPress Query object.
	 *
	 * @param WP_Query|null $wp_query Optional. A WP_Query instance. Defaults to the $wp_query global.
	 */
	public function update_post_thumbnail_cache( $wp_query = null );

	/**
	 * Registers an image size for the post thumbnail.
	 *
	 * @since 2.9.0
	 *
	 * @see add_image_size() for details on cropping behavior.
	 *
	 * @param int        $width  Image width in pixels.
	 * @param int        $height Image height in pixels.
	 * @param bool|array $crop   {
	 *     Optional. Image cropping behavior. If false, the image will be scaled (default).
	 *     If true, image will be cropped to the specified dimensions using center positions.
	 *     If an array, the image will be cropped using the array to specify the crop location:
	 *
	 *     @type string $0 The x crop position. Accepts 'left', 'center', or 'right'.
	 *     @type string $1 The y crop position. Accepts 'top', 'center', or 'bottom'.
	 * }
	 */
	public function set_post_thumbnail_size( $width = 0, $height = 0, $crop = false );
}
