<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use WP_Error;
use WP_Post;

interface Revisions {
	/**
	 * Gets a post revision.
	 *
	 * @since 2.6.0
	 *
	 * @param int|WP_Post $post   Post ID or post object.
	 * @param string      $output Optional. The required return type. One of OBJECT, ARRAY_A, or ARRAY_N, which
	 *                            correspond to a WP_Post object, an associative array, or a numeric array,
	 *                            respectively. Default OBJECT.
	 * @param string      $filter Optional sanitization filter. See sanitize_post(). Default 'raw'.
	 * @return WP_Post|array|null WP_Post (or array) on success, or null on failure.
	 *
	 * @phpstan-param int|WP_Post $post
	 * @phpstan-param 'OBJECT'|'ARRAY_A'|'ARRAY_N' $output
	 * @phpstan-param 'raw'|'edit'|'db'|'display' $filter
	 * @phpstan-return (
	 *     $output is 'ARRAY_A' ? non-empty-array<string, mixed>|null : (
	 *         $output is 'ARRAY_N' ? non-empty-array<int, mixed>|null : (
	 *             WP_Post|null
	 *         )
	 *     )
	 * )
	 */
	public function wp_get_post_revision( &$post, $output = 'OBJECT', $filter = 'raw' );

	/**
	 * Returns all revisions of specified post.
	 *
	 * @since 2.6.0
	 *
	 * @see get_children()
	 *
	 * @param int|WP_Post $post Optional. Post ID or WP_Post object. Default is global `$post`.
	 * @param array|null  $args Optional. Arguments for retrieving post revisions. Default null.
	 * @return WP_Post[]|int[] Array of revision objects or IDs, or an empty array if none.
	 */
	public function wp_get_post_revisions( $post = 0, $args = null );

	/**
	 * Returns the latest revision ID and count of revisions for a post.
	 *
	 * @since 6.1.0
	 *
	 * @param int|WP_Post $post Optional. Post ID or WP_Post object. Default is global $post.
	 * @return array|WP_Error {
	 *     Returns associative array with latest revision ID and total count,
	 *     or a WP_Error if the post does not exist or revisions are not enabled.
	 *
	 *     @type int $latest_id The latest revision post ID or 0 if no revisions exist.
	 *     @type int $count     The total count of revisions for the given post.
	 * }
	 */
	public function wp_get_latest_revision_id_and_total_count( $post = 0 );

	/**
	 * Returns the url for viewing and potentially restoring revisions of a given post.
	 *
	 * @since 5.9.0
	 *
	 * @param int|WP_Post $post Optional. Post ID or WP_Post object. Default is global `$post`.
	 * @return string|null The URL for editing revisions on the given post, otherwise null.
	 */
	public function wp_get_post_revisions_url( $post = 0 );

	/**
	 * Determines if the specified post is a revision.
	 *
	 * @since 2.6.0
	 *
	 * @param int|WP_Post $post Post ID or post object.
	 * @return int|false ID of revision's parent on success, false if not a revision.
	 */
	public function wp_is_post_revision( $post );

	/**
	 * Retrieves the autosaved data of the specified post.
	 *
	 * Returns a post object with the information that was autosaved for the specified post.
	 * If the optional $user_id is passed, returns the autosave for that user, otherwise
	 * returns the latest autosave.
	 *
	 * @since 2.6.0
	 *
	 * @param int $post_id The post ID.
	 * @param int $user_id Optional. The post author ID. Default 0.
	 * @return WP_Post|false The autosaved data or false on failure or when no autosave exists.
	 */
	public function wp_get_post_autosave( $post_id, $user_id = 0 );

	/**
	 * Determines if the specified post is an autosave.
	 *
	 * @since 2.6.0
	 *
	 * @param int|WP_Post $post Post ID or post object.
	 * @return int|false ID of autosave's parent on success, false if not a revision.
	 */
	public function wp_is_post_autosave( $post );

	/**
	 * Determines whether revisions are enabled for a given post.
	 *
	 * @since 3.6.0
	 *
	 * @param WP_Post $post The post object.
	 * @return bool True if number of revisions to keep isn't zero, false otherwise.
	 */
	public function wp_revisions_enabled( $post );

	/**
	 * Determines how many revisions to retain for a given post.
	 *
	 * By default, an infinite number of revisions are kept.
	 *
	 * The constant WP_POST_REVISIONS can be set in wp-config to specify the limit
	 * of revisions to keep.
	 *
	 * @since 3.6.0
	 *
	 * @param WP_Post $post The post object.
	 * @return int The number of revisions to keep.
	 */
	public function wp_revisions_to_keep( $post );

	/**
	 * Determine which post meta fields should be revisioned.
	 *
	 * @since 6.4.0
	 *
	 * @param string $post_type The post type being revisioned.
	 * @return array An array of meta keys to be revisioned.
	 */
	public function wp_post_revision_meta_keys( $post_type );

	/**
	 * Creates a revision for the current version of a post.
	 *
	 * Typically used immediately after a post update, as every update is a revision,
	 * and the most recent revision always matches the current post.
	 *
	 * @since 2.6.0
	 *
	 * @param int $post_id The ID of the post to save as a revision.
	 * @return int|WP_Error|null Null or 0 if error, new revision ID, if success.
	 */
	public function wp_save_post_revision( $post_id );

	/**
	 * Restores a post to the specified revision.
	 *
	 * Can restore a past revision using all fields of the post revision, or only selected fields.
	 *
	 * @since 2.6.0
	 *
	 * @param int|WP_Post $revision Revision ID or revision object.
	 * @param array       $fields   Optional. What fields to restore from. Defaults to all.
	 * @return int|false|null Null if error, false if no fields to restore, (int) post ID if success.
	 */
	public function wp_restore_post_revision( $revision, $fields = null );

	/**
	 * Deletes a revision.
	 *
	 * Deletes the row from the posts table corresponding to the specified revision.
	 *
	 * @since 2.6.0
	 *
	 * @param int|WP_Post $revision Revision ID or revision object.
	 * @return WP_Post|false|null Null or false if error, deleted post object if success.
	 */
	public function wp_delete_post_revision( $revision );

	/**
	 * Displays a human readable HTML representation of the difference between two strings.
	 *
	 * The Diff is available for getting the changes between versions. The output is
	 * HTML, so the primary use is for displaying the changes. If the two strings
	 * are equivalent, then an empty string will be returned.
	 *
	 * @since 2.6.0
	 *
	 * @see wp_parse_args() Used to change defaults to user defined settings.
	 * @uses Text_Diff
	 * @uses WP_Text_Diff_Renderer_Table
	 *
	 * @param string       $left_string  "old" (left) version of string.
	 * @param string       $right_string "new" (right) version of string.
	 * @param string|array $args {
	 *     Associative array of options to pass to WP_Text_Diff_Renderer_Table().
	 *
	 *     @type string $title           Titles the diff in a manner compatible
	 *                                   with the output. Default empty.
	 *     @type string $title_left      Change the HTML to the left of the title.
	 *                                   Default empty.
	 *     @type string $title_right     Change the HTML to the right of the title.
	 *                                   Default empty.
	 *     @type bool   $show_split_view True for split view (two columns), false for
	 *                                   un-split view (single column). Default true.
	 * }
	 * @return string Empty string if strings are equivalent or HTML with differences.
	 */
	public function wp_text_diff( $left_string, $right_string, $args = null );
}
