<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use DOMDocument;
use WP;
use WP_Query;
use WP_Rewrite;
use wpdb;

interface Rewrite {
	/**
	 * Returns whether the server is running Apache with the mod_rewrite module loaded.
	 *
	 * @since 2.0.0
	 *
	 * @return bool Whether the server is running Apache with the mod_rewrite module loaded.
	 */
	public function got_mod_rewrite();

	/**
	 * Returns whether the server supports URL rewriting.
	 *
	 * Detects Apache's mod_rewrite, IIS 7.0+ permalink support, and nginx.
	 *
	 * @since 3.7.0
	 *
	 * @global bool $is_nginx
	 * @global bool $is_caddy
	 *
	 * @return bool Whether the server supports URL rewriting.
	 */
	public function got_url_rewrite();

	/**
	 * Updates the htaccess file with the current rules if it is writable.
	 *
	 * Always writes to the file if it exists and is writable to ensure that we
	 * blank out old rules.
	 *
	 * @since 1.5.0
	 *
	 * @global WP_Rewrite $wp_rewrite WordPress rewrite component.
	 *
	 * @return bool|null True on write success, false on failure. Null in multisite.
	 */
	public function save_mod_rewrite_rules();

	/**
	 * Extracts strings from between the BEGIN and END markers in the .htaccess file.
	 *
	 * @since 1.5.0
	 *
	 * @param string $filename Filename to extract the strings from.
	 * @param string $marker   The marker to extract the strings from.
	 * @return string[] An array of strings from a file (.htaccess) from between BEGIN and END markers.
	 */
	public function extract_from_markers( $filename, $marker );

	/**
	 * Inserts an array of strings into a file (.htaccess), placing it between
	 * BEGIN and END markers.
	 *
	 * Replaces existing marked info. Retains surrounding
	 * data. Creates file if none exists.
	 *
	 * @since 1.5.0
	 *
	 * @param string       $filename  Filename to alter.
	 * @param string       $marker    The marker to alter.
	 * @param array|string $insertion The new content to insert.
	 * @return bool True on write success, false on failure.
	 */
	public function insert_with_markers( $filename, $marker, $insertion );

	/**
	 * Updates the IIS web.config file with the current rules if it is writable.
	 * If the permalinks do not require rewrite rules then the rules are deleted from the web.config file.
	 *
	 * @since 2.8.0
	 *
	 * @global WP_Rewrite $wp_rewrite WordPress rewrite component.
	 *
	 * @return bool|null True on write success, false on failure. Null in multisite.
	 */
	public function iis7_save_url_rewrite_rules();

	/**
	 * Checks if rewrite rule for WordPress already exists in the IIS 7+ configuration file.
	 *
	 * @since 2.8.0
	 *
	 * @param string $filename The file path to the configuration file.
	 * @return bool Whether the rule exists.
	 */
	public function iis7_rewrite_rule_exists( $filename );

	/**
	 * Adds WordPress rewrite rule to the IIS 7+ configuration file.
	 *
	 * @since 2.8.0
	 *
	 * @param string $filename     The file path to the configuration file.
	 * @param string $rewrite_rule The XML fragment with URL Rewrite rule.
	 * @return bool Whether the rule was added.
	 */
	public function iis7_add_rewrite_rule( $filename, $rewrite_rule );

	/**
	 * Deletes WordPress rewrite rule from web.config file if it exists there.
	 *
	 * @since 2.8.0
	 *
	 * @param string $filename Name of the configuration file.
	 * @return bool Whether the rule was deleted.
	 */
	public function iis7_delete_rewrite_rule( $filename );

	/**
	 * Saves the XML document into a file.
	 *
	 * @since 2.8.0
	 *
	 * @param DOMDocument $doc      The DOMDocument object to save.
	 * @param string      $filename The file path to save the XML document to.
	 */
	public function saveDomDocument( $doc, $filename );

	/**
	 * Adds a rewrite rule that transforms a URL structure to a set of query vars.
	 *
	 * Any value in the $after parameter that isn't 'bottom' will result in the rule
	 * being placed at the top of the rewrite rules.
	 *
	 * @since 2.1.0
	 * @since 4.4.0 Array support was added to the `$query` parameter.
	 *
	 * @global WP_Rewrite $wp_rewrite WordPress rewrite component.
	 *
	 * @param string       $regex Regular expression to match request against.
	 * @param string|array $query The corresponding query vars for this rewrite rule.
	 * @param string       $after Optional. Priority of the new rule. Accepts 'top'
	 *                            or 'bottom'. Default 'bottom'.
	 */
	public function add_rewrite_rule( $regex, $query, $after = 'bottom' );

	/**
	 * Adds a new rewrite tag (like %postname%).
	 *
	 * The `$query` parameter is optional. If it is omitted you must ensure that you call
	 * this on, or before, the {@see 'init'} hook. This is because `$query` defaults to
	 * `$tag=`, and for this to work a new query var has to be added.
	 *
	 * @since 2.1.0
	 *
	 * @global WP_Rewrite $wp_rewrite WordPress rewrite component.
	 * @global WP         $wp         Current WordPress environment instance.
	 *
	 * @param string $tag   Name of the new rewrite tag.
	 * @param string $regex Regular expression to substitute the tag for in rewrite rules.
	 * @param string $query Optional. String to append to the rewritten query. Must end in '='. Default empty.
	 */
	public function add_rewrite_tag( $tag, $regex, $query = '' );

	/**
	 * Removes an existing rewrite tag (like %postname%).
	 *
	 * @since 4.5.0
	 *
	 * @global WP_Rewrite $wp_rewrite WordPress rewrite component.
	 *
	 * @param string $tag Name of the rewrite tag.
	 */
	public function remove_rewrite_tag( $tag );

	/**
	 * Adds a permalink structure.
	 *
	 * @since 3.0.0
	 *
	 * @see WP_Rewrite::add_permastruct()
	 * @global WP_Rewrite $wp_rewrite WordPress rewrite component.
	 *
	 * @param string $name   Name for permalink structure.
	 * @param string $struct Permalink structure.
	 * @param array  $args   Optional. Arguments for building the rules from the permalink structure,
	 *                       see WP_Rewrite::add_permastruct() for full details. Default empty array.
	 */
	public function add_permastruct( $name, $struct, $args = array() );

	/**
	 * Removes a permalink structure.
	 *
	 * Can only be used to remove permastructs that were added using add_permastruct().
	 * Built-in permastructs cannot be removed.
	 *
	 * @since 4.5.0
	 *
	 * @see WP_Rewrite::remove_permastruct()
	 * @global WP_Rewrite $wp_rewrite WordPress rewrite component.
	 *
	 * @param string $name Name for permalink structure.
	 */
	public function remove_permastruct( $name );

	/**
	 * Adds an endpoint, like /trackback/.
	 *
	 * Adding an endpoint creates extra rewrite rules for each of the matching
	 * places specified by the provided bitmask. For example:
	 *
	 *     add_rewrite_endpoint( 'json', EP_PERMALINK | EP_PAGES );
	 *
	 * will add a new rewrite rule ending with "json(/(.*))?/?$" for every permastruct
	 * that describes a permalink (post) or page. This is rewritten to "json=$match"
	 * where $match is the part of the URL matched by the endpoint regex (e.g. "foo" in
	 * "[permalink]/json/foo/").
	 *
	 * A new query var with the same name as the endpoint will also be created.
	 *
	 * When specifying $places ensure that you are using the EP_* constants (or a
	 * combination of them using the bitwise OR operator) as their values are not
	 * guaranteed to remain static (especially `EP_ALL`).
	 *
	 * Be sure to flush the rewrite rules - see flush_rewrite_rules() - when your plugin gets
	 * activated and deactivated.
	 *
	 * @since 2.1.0
	 * @since 4.3.0 Added support for skipping query var registration by passing `false` to `$query_var`.
	 *
	 * @global WP_Rewrite $wp_rewrite WordPress rewrite component.
	 *
	 * @param string      $name      Name of the endpoint.
	 * @param int         $places    Endpoint mask describing the places the endpoint should be added.
	 *                               Accepts a mask of:
	 *                               - `EP_ALL`
	 *                               - `EP_NONE`
	 *                               - `EP_ALL_ARCHIVES`
	 *                               - `EP_ATTACHMENT`
	 *                               - `EP_AUTHORS`
	 *                               - `EP_CATEGORIES`
	 *                               - `EP_COMMENTS`
	 *                               - `EP_DATE`
	 *                               - `EP_DAY`
	 *                               - `EP_MONTH`
	 *                               - `EP_PAGES`
	 *                               - `EP_PERMALINK`
	 *                               - `EP_ROOT`
	 *                               - `EP_SEARCH`
	 *                               - `EP_TAGS`
	 *                               - `EP_YEAR`
	 * @param string|bool $query_var Name of the corresponding query variable. Pass `false` to skip registering a query_var
	 *                               for this endpoint. Defaults to the value of `$name`.
	 */
	public function add_rewrite_endpoint( $name, $places, $query_var = true );

	/**
	 * Adds a new feed type like /atom1/.
	 *
	 * @since 2.1.0
	 *
	 * @global WP_Rewrite $wp_rewrite WordPress rewrite component.
	 *
	 * @param string   $feedname Feed name. Should not start with '_'.
	 * @param callable $callback Callback to run on feed display.
	 * @return string Feed action name.
	 */
	public function add_feed( $feedname, $callback );

	/**
	 * Removes rewrite rules and then recreate rewrite rules.
	 *
	 * @since 3.0.0
	 *
	 * @global WP_Rewrite $wp_rewrite WordPress rewrite component.
	 *
	 * @param bool $hard Whether to update .htaccess (hard flush) or just update
	 *                   rewrite_rules option (soft flush). Default is true (hard).
	 */
	public function flush_rewrite_rules( $hard = true );

	/**
	 * Examines a URL and try to determine the post ID it represents.
	 *
	 * Checks are supposedly from the hosted site blog.
	 *
	 * @since 1.0.0
	 *
	 * @global WP_Rewrite $wp_rewrite WordPress rewrite component.
	 * @global WP         $wp         Current WordPress environment instance.
	 *
	 * @param string $url Permalink to check.
	 * @return int Post ID, or 0 on failure.
	 */
	public function url_to_postid( $url );

	/**
	 * Resolves numeric slugs that collide with date permalinks.
	 *
	 * Permalinks of posts with numeric slugs can sometimes look to WP_Query::parse_query()
	 * like a date archive, as when your permalink structure is `/%year%/%postname%/` and
	 * a post with post_name '05' has the URL `/2015/05/`.
	 *
	 * This function detects conflicts of this type and resolves them in favor of the
	 * post permalink.
	 *
	 * Note that, since 4.3.0, wp_unique_post_slug() prevents the creation of post slugs
	 * that would result in a date archive conflict. The resolution performed in this
	 * function is primarily for legacy content, as well as cases when the admin has changed
	 * the site's permalink structure in a way that introduces URL conflicts.
	 *
	 * @since 4.3.0
	 *
	 * @param array $query_vars Optional. Query variables for setting up the loop, as determined in
	 *                          WP::parse_request(). Default empty array.
	 * @return array Returns the original array of query vars, with date/post conflicts resolved.
	 */
	public function wp_resolve_numeric_slug_conflicts( $query_vars = array() );

	/**
	 * Redirects incoming links to the proper URL based on the site url.
	 *
	 * Search engines consider www.somedomain.com and somedomain.com to be two
	 * different URLs when they both go to the same location. This SEO enhancement
	 * prevents penalty for duplicate content by redirecting all incoming links to
	 * one or the other.
	 *
	 * Prevents redirection for feeds, trackbacks, searches, and
	 * admin URLs. Does not redirect on non-pretty-permalink-supporting IIS 7+,
	 * page/post previews, WP admin, Trackbacks, robots.txt, favicon.ico, searches,
	 * or on POST requests.
	 *
	 * Will also attempt to find the correct link when a user enters a URL that does
	 * not exist based on exact WordPress query. Will instead try to parse the URL
	 * or query in an attempt to figure the correct page to go to.
	 *
	 * @since 2.3.0
	 *
	 * @global WP_Rewrite $wp_rewrite WordPress rewrite component.
	 * @global bool       $is_IIS
	 * @global WP_Query   $wp_query   WordPress Query object.
	 * @global wpdb       $wpdb       WordPress database abstraction object.
	 * @global WP         $wp         Current WordPress environment instance.
	 *
	 * @param string $requested_url Optional. The URL that was requested, used to
	 *                              figure if redirect is needed.
	 * @param bool   $do_redirect   Optional. Redirect to the new URL.
	 * @return string|null The string of the URL, if redirect needed. Never returns if a redirect occurs, depending on $do_redirect.
	 * @phpstan-return ( $do_redirect is true ? null : string|null )
	 */
	public function redirect_canonical( $requested_url = null, $do_redirect = true );

	/**
	 * Attempts to guess the correct URL for a 404 request based on query vars.
	 *
	 * @since 2.3.0
	 *
	 * @global wpdb $wpdb WordPress database abstraction object.
	 *
	 * @return string|false The correct URL if one is found. False on failure.
	 */
	public function redirect_guess_404_permalink();
}
