<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

interface Serialization {
	/**
	 * Serializes data, if needed.
	 *
	 * @since 2.0.5
	 *
	 * @param string|array|object $data Data that might be serialized.
	 * @return mixed A scalar data.
	 */
	public function maybe_serialize( $data );

	/**
	 * Unserializes data only if it was serialized.
	 *
	 * @since 2.0.0
	 *
	 * @param string $data Data that might be unserialized.
	 * @return mixed Unserialized data can be any type.
	 */
	public function maybe_unserialize( $data );

	/**
	 * Checks value to find if it was serialized.
	 *
	 * If $data is not a string, then returned value will always be false.
	 * Serialized data is always a string.
	 *
	 * @since 2.0.5
	 * @since 6.1.0 Added Enum support.
	 *
	 * @param string $data   Value to check to see if was serialized.
	 * @param bool   $strict Optional. Whether to be strict about the end of the string. Default true.
	 * @return bool False if not serialized and true if it was.
	 */
	public function is_serialized( $data, $strict = true );

	/**
	 * Checks whether serialized data is of string type.
	 *
	 * @since 2.0.5
	 *
	 * @param string $data Serialized data.
	 * @return bool False if not a serialized string, true if it is.
	 */
	public function is_serialized_string( $data );
}
