<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

interface Settings {
	/**
	 * Registers a settings error to be displayed to the user.
	 *
	 * Part of the Settings API. Use this to show messages to users about settings validation
	 * problems, missing settings or anything else.
	 *
	 * Settings errors should be added inside the $sanitize_callback function defined in
	 * register_setting() for a given setting to give feedback about the submission.
	 *
	 * By default messages will show immediately after the submission that generated the error.
	 * Additional calls to settings_errors() can be used to show errors even when the settings
	 * page is first accessed.
	 *
	 * @since 3.0.0
	 * @since 5.3.0 Added `warning` and `info` as possible values for `$type`.
	 *
	 * @global array[] $wp_settings_errors Storage array of errors registered during this pageload
	 *
	 * @param string $setting Slug title of the setting to which this error applies.
	 * @param string $code    Slug-name to identify the error. Used as part of 'id' attribute in HTML output.
	 * @param string $message The formatted message text to display to the user (will be shown inside styled
	 *                        `<div>` and `<p>` tags).
	 * @param string $type    Optional. Message type, controls HTML class. Possible values include 'error',
	 *                        'success', 'warning', 'info'. Default 'error'.
	 */
	public function add_settings_error( $setting, $code, $message, $type = 'error' );

	/**
	 * Adds a new field to a section of a settings page.
	 *
	 * Part of the Settings API. Use this to define a settings field that will show
	 * as part of a settings section inside a settings page. The fields are shown using
	 * do_settings_fields() in do_settings_sections().
	 *
	 * The $callback argument should be the name of a function that echoes out the
	 * HTML input tags for this setting field. Use get_option() to retrieve existing
	 * values to show.
	 *
	 * @since 2.7.0
	 * @since 4.2.0 The `$class` argument was added.
	 *
	 * @global array $wp_settings_fields Storage array of settings fields and info about their pages/sections.
	 *
	 * @param string   $id       Slug-name to identify the field. Used in the 'id' attribute of tags.
	 * @param string   $title    Formatted title of the field. Shown as the label for the field
	 *                           during output.
	 * @param callable $callback Function that fills the field with the desired form inputs. The
	 *                           function should echo its output.
	 * @param string   $page     The slug-name of the settings page on which to show the section
	 *                           (general, reading, writing, ...).
	 * @param string   $section  Optional. The slug-name of the section of the settings page
	 *                           in which to show the box. Default 'default'.
	 * @param array    $args {
	 *     Optional. Extra arguments that get passed to the callback function.
	 *
	 *     @type string $label_for When supplied, the setting title will be wrapped
	 *                             in a `<label>` element, its `for` attribute populated
	 *                             with this value.
	 *     @type string $class     CSS Class to be added to the `<tr>` element when the
	 *                             field is output.
	 * }
	 */
	public function add_settings_field( $id, $title, $callback, $page, $section = 'default', $args = array() );

	/**
	 * Adds a new section to a settings page.
	 *
	 * Part of the Settings API. Use this to define new settings sections for an admin page.
	 * Show settings sections in your admin page callback function with do_settings_sections().
	 * Add settings fields to your section with add_settings_field().
	 *
	 * The $callback argument should be the name of a function that echoes out any
	 * content you want to show at the top of the settings section before the actual
	 * fields. It can output nothing if you want.
	 *
	 * @since 2.7.0
	 * @since 6.1.0 Added an `$args` parameter for the section's HTML wrapper and class name.
	 *
	 * @global array $wp_settings_sections Storage array of all settings sections added to admin pages.
	 *
	 * @param string   $id       Slug-name to identify the section. Used in the 'id' attribute of tags.
	 * @param string   $title    Formatted title of the section. Shown as the heading for the section.
	 * @param callable $callback Function that displays any content at the top of the section (between heading and fields).
	 * @param string   $page     The slug-name of the settings page on which to show the section. Built-in pages include
	 *                           'general', 'reading', 'writing', 'discussion', 'media', etc. Create your own using
	 *                           add_options_page();
	 * @param array    $args     {
	 *     Arguments used to create the settings section.
	 *
	 *     @type string $before_section HTML content to prepend to the section's HTML output.
	 *                                  Receives the section's class name as `%s`. Default empty.
	 *     @type string $after_section  HTML content to append to the section's HTML output. Default empty.
	 *     @type string $section_class  The class name to use for the section. Default empty.
	 * }
	 */
	public function add_settings_section( $id, $title, $callback, $page, $args = array() );

	/**
	 * Prints out the settings fields for a particular settings section.
	 *
	 * Part of the Settings API. Use this in a settings page to output
	 * a specific section. Should normally be called by do_settings_sections()
	 * rather than directly.
	 *
	 * @since 2.7.0
	 *
	 * @global array $wp_settings_fields Storage array of settings fields and their pages/sections.
	 *
	 * @param string $page Slug title of the admin page whose settings fields you want to show.
	 * @param string $section Slug title of the settings section whose fields you want to show.
	 */
	public function do_settings_fields( $page, $section );

	/**
	 * Prints out all settings sections added to a particular settings page.
	 *
	 * Part of the Settings API. Use this in a settings page callback function
	 * to output all the sections and fields that were added to that $page with
	 * add_settings_section() and add_settings_field()
	 *
	 * @since 2.7.0
	 *
	 * @global array $wp_settings_sections Storage array of all settings sections added to admin pages.
	 * @global array $wp_settings_fields Storage array of settings fields and info about their pages/sections.
	 *
	 * @param string $page The slug name of the page whose settings sections you want to output.
	 */
	public function do_settings_sections( $page );

	/**
	 * Fetches settings errors registered by add_settings_error().
	 *
	 * Checks the $wp_settings_errors array for any errors declared during the current
	 * pageload and returns them.
	 *
	 * If changes were just submitted ($_GET['settings-updated']) and settings errors were saved
	 * to the 'settings_errors' transient then those errors will be returned instead. This
	 * is used to pass errors back across pageloads.
	 *
	 * Use the $sanitize argument to manually re-sanitize the option before returning errors.
	 * This is useful if you have errors or notices you want to show even when the user
	 * hasn't submitted data (i.e. when they first load an options page, or in the {@see 'admin_notices'}
	 * action hook).
	 *
	 * @since 3.0.0
	 *
	 * @global array[] $wp_settings_errors Storage array of errors registered during this pageload
	 *
	 * @param string $setting  Optional. Slug title of a specific setting whose errors you want.
	 * @param bool   $sanitize Optional. Whether to re-sanitize the setting value before returning errors.
	 * @return array[] {
	 *     Array of settings error arrays.
	 *
	 *     @type array ...$0 {
	 *         Associative array of setting error data.
	 *
	 *         @type string $setting Slug title of the setting to which this error applies.
	 *         @type string $code    Slug-name to identify the error. Used as part of 'id' attribute in HTML output.
	 *         @type string $message The formatted message text to display to the user (will be shown inside styled
	 *                               `<div>` and `<p>` tags).
	 *         @type string $type    Optional. Message type, controls HTML class. Possible values include 'error',
	 *                               'success', 'warning', 'info'. Default 'error'.
	 *     }
	 * }
	 */
	public function get_settings_errors( $setting = '', $sanitize = false );

	/**
	 * Displays settings errors registered by add_settings_error().
	 *
	 * Part of the Settings API. Outputs a div for each error retrieved by
	 * get_settings_errors().
	 *
	 * This is called automatically after a settings page based on the
	 * Settings API is submitted. Errors should be added during the validation
	 * callback function for a setting defined in register_setting().
	 *
	 * The $sanitize option is passed into get_settings_errors() and will
	 * re-run the setting sanitization
	 * on its current value.
	 *
	 * The $hide_on_update option will cause errors to only show when the settings
	 * page is first loaded. if the user has already saved new values it will be
	 * hidden to avoid repeating messages already shown in the default error
	 * reporting after submission. This is useful to show general errors like
	 * missing settings when the user arrives at the settings page.
	 *
	 * @since 3.0.0
	 * @since 5.3.0 Legacy `error` and `updated` CSS classes are mapped to
	 *              `notice-error` and `notice-success`.
	 *
	 * @param string $setting        Optional slug title of a specific setting whose errors you want.
	 * @param bool   $sanitize       Whether to re-sanitize the setting value before returning errors.
	 * @param bool   $hide_on_update If set to true errors will not be shown if the settings page has
	 *                               already been submitted.
	 */
	public function settings_errors( $setting = '', $sanitize = false, $hide_on_update = false );
}
