<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

interface SiteHealth {
	/**
	 * Gets the URL to learn more about updating the PHP version the site is running on.
	 *
	 * This URL can be overridden by specifying an environment variable `WP_UPDATE_PHP_URL` or by using the
	 * {@see 'wp_update_php_url'} filter. Providing an empty string is not allowed and will result in the
	 * default URL being used. Furthermore the page the URL links to should preferably be localized in the
	 * site language.
	 *
	 * @since 5.1.0
	 *
	 * @return string URL to learn more about updating PHP.
	 */
	public function wp_get_update_php_url();

	/**
	 * Returns the default annotation for the web hosting altering the "Update PHP" page URL.
	 *
	 * This function is to be used after {@see wp_get_update_php_url()} to return a consistent
	 * annotation if the web host has altered the default "Update PHP" page URL.
	 *
	 * @since 5.2.0
	 *
	 * @return string Update PHP page annotation. An empty string if no custom URLs are provided.
	 */
	public function wp_get_update_php_annotation();

	/**
	 * Prints the default annotation for the web host altering the "Update PHP" page URL.
	 *
	 * This function is to be used after {@see wp_get_update_php_url()} to display a consistent
	 * annotation if the web host has altered the default "Update PHP" page URL.
	 *
	 * @since 5.1.0
	 * @since 5.2.0 Added the `$before` and `$after` parameters.
	 * @since 6.4.0 Added the `$display` parameter.
	 *
	 * @param string $before  Markup to output before the annotation. Default `<p class="description">`.
	 * @param string $after   Markup to output after the annotation. Default `</p>`.
	 * @param bool   $display Whether to echo or return the markup. Default `true` for echo.
	 *
	 * @return string|null Update PHP page annotation if available and $display is false, null otherwise.
	 */
	public function wp_update_php_annotation( $before = '<p class="description">', $after = '</p>', $display = true );

	/**
	 * Gets the URL for directly updating the PHP version the site is running on.
	 *
	 * A URL will only be returned if the `WP_DIRECT_UPDATE_PHP_URL` environment variable is specified or
	 * by using the {@see 'wp_direct_php_update_url'} filter. This allows hosts to send users directly to
	 * the page where they can update PHP to a newer version.
	 *
	 * @since 5.1.1
	 *
	 * @return string URL for directly updating PHP or empty string.
	 */
	public function wp_get_direct_php_update_url();

	/**
	 * Displays a button directly linking to a PHP update process.
	 *
	 * This provides hosts with a way for users to be sent directly to their PHP update process.
	 *
	 * The button is only displayed if a URL is returned by `wp_get_direct_php_update_url()`.
	 *
	 * @since 5.1.1
	 */
	public function wp_direct_php_update_button();

	/**
	 * Gets the URL to learn more about updating the site to use HTTPS.
	 *
	 * This URL can be overridden by specifying an environment variable `WP_UPDATE_HTTPS_URL` or by using the
	 * {@see 'wp_update_https_url'} filter. Providing an empty string is not allowed and will result in the
	 * default URL being used. Furthermore the page the URL links to should preferably be localized in the
	 * site language.
	 *
	 * @since 5.7.0
	 *
	 * @return string URL to learn more about updating to HTTPS.
	 */
	public function wp_get_update_https_url();

	/**
	 * Gets the URL for directly updating the site to use HTTPS.
	 *
	 * A URL will only be returned if the `WP_DIRECT_UPDATE_HTTPS_URL` environment variable is specified or
	 * by using the {@see 'wp_direct_update_https_url'} filter. This allows hosts to send users directly to
	 * the page where they can update their site to use HTTPS.
	 *
	 * @since 5.7.0
	 *
	 * @return string URL for directly updating to HTTPS or empty string.
	 */
	public function wp_get_direct_update_https_url();
}
