<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use WP_Customize_Manager;
use WP_Error;
use WP_Filesystem_Base;
use WP_Locale;
use WP_Paused_Extensions_Storage;
use WP_Post;
use WP_Theme;

interface Themes {
	/**
	 * Retrieves theme installer pages from the WordPress.org Themes API.
	 *
	 * It is possible for a theme to override the Themes API result with three
	 * filters. Assume this is for themes, which can extend on the Theme Info to
	 * offer more choices. This is very powerful and must be used with care, when
	 * overriding the filters.
	 *
	 * The first filter, {@see 'themes_api_args'}, is for the args and gives the action
	 * as the second parameter. The hook for {@see 'themes_api_args'} must ensure that
	 * an object is returned.
	 *
	 * The second filter, {@see 'themes_api'}, allows a plugin to override the WordPress.org
	 * Theme API entirely. If `$action` is 'query_themes', 'theme_information', or 'feature_list',
	 * an object MUST be passed. If `$action` is 'hot_tags', an array should be passed.
	 *
	 * Finally, the third filter, {@see 'themes_api_result'}, makes it possible to filter the
	 * response object or array, depending on the `$action` type.
	 *
	 * Supported arguments per action:
	 *
	 * | Argument Name      | 'query_themes' | 'theme_information' | 'hot_tags' | 'feature_list'   |
	 * | -------------------| :------------: | :-----------------: | :--------: | :--------------: |
	 * | `$slug`            | No             |  Yes                | No         | No               |
	 * | `$per_page`        | Yes            |  No                 | No         | No               |
	 * | `$page`            | Yes            |  No                 | No         | No               |
	 * | `$number`          | No             |  No                 | Yes        | No               |
	 * | `$search`          | Yes            |  No                 | No         | No               |
	 * | `$tag`             | Yes            |  No                 | No         | No               |
	 * | `$author`          | Yes            |  No                 | No         | No               |
	 * | `$user`            | Yes            |  No                 | No         | No               |
	 * | `$browse`          | Yes            |  No                 | No         | No               |
	 * | `$locale`          | Yes            |  Yes                | No         | No               |
	 * | `$fields`          | Yes            |  Yes                | No         | No               |
	 *
	 * @since 2.8.0
	 *
	 * @param string       $action API action to perform: Accepts 'query_themes', 'theme_information',
	 *                             'hot_tags' or 'feature_list'.
	 * @param array|object $args   {
	 *     Optional. Array or object of arguments to serialize for the Themes API. Default empty array.
	 *
	 *     @type string  $slug     The theme slug. Default empty.
	 *     @type int     $per_page Number of themes per page. Default 24.
	 *     @type int     $page     Number of current page. Default 1.
	 *     @type int     $number   Number of tags to be queried.
	 *     @type string  $search   A search term. Default empty.
	 *     @type string  $tag      Tag to filter themes. Default empty.
	 *     @type string  $author   Username of an author to filter themes. Default empty.
	 *     @type string  $user     Username to query for their favorites. Default empty.
	 *     @type string  $browse   Browse view: 'featured', 'popular', 'updated', 'favorites'.
	 *     @type string  $locale   Locale to provide context-sensitive results. Default is the value of get_locale().
	 *     @type array   $fields   {
	 *         Array of fields which should or should not be returned.
	 *
	 *         @type bool $description        Whether to return the theme full description. Default false.
	 *         @type bool $sections           Whether to return the theme readme sections: description, installation,
	 *                                        FAQ, screenshots, other notes, and changelog. Default false.
	 *         @type bool $rating             Whether to return the rating in percent and total number of ratings.
	 *                                        Default false.
	 *         @type bool $ratings            Whether to return the number of rating for each star (1-5). Default false.
	 *         @type bool $downloaded         Whether to return the download count. Default false.
	 *         @type bool $downloadlink       Whether to return the download link for the package. Default false.
	 *         @type bool $last_updated       Whether to return the date of the last update. Default false.
	 *         @type bool $tags               Whether to return the assigned tags. Default false.
	 *         @type bool $homepage           Whether to return the theme homepage link. Default false.
	 *         @type bool $screenshots        Whether to return the screenshots. Default false.
	 *         @type int  $screenshot_count   Number of screenshots to return. Default 1.
	 *         @type bool $screenshot_url     Whether to return the URL of the first screenshot. Default false.
	 *         @type bool $photon_screenshots Whether to return the screenshots via Photon. Default false.
	 *         @type bool $template           Whether to return the slug of the parent theme. Default false.
	 *         @type bool $parent             Whether to return the slug, name and homepage of the parent theme. Default false.
	 *         @type bool $versions           Whether to return the list of all available versions. Default false.
	 *         @type bool $theme_url          Whether to return theme's URL. Default false.
	 *         @type bool $extended_author    Whether to return nicename or nicename and display name. Default false.
	 *     }
	 * }
	 * @return object|array|WP_Error Response object or array on success, WP_Error on failure. See the
	 *         {@link https://developer.wordpress.org/reference/functions/themes_api/ function reference article}
	 *         for more information on the make-up of possible return objects depending on the value of `$action`.
	 */
	public function themes_api( $action, $args = array() );

	/**
	 * Retrieves list of WordPress theme features (aka theme tags).
	 *
	 * @since 3.1.0
	 * @since 3.2.0 Added 'Gray' color and 'Featured Image Header', 'Featured Images',
	 *              'Full Width Template', and 'Post Formats' features.
	 * @since 3.5.0 Added 'Flexible Header' feature.
	 * @since 3.8.0 Renamed 'Width' filter to 'Layout'.
	 * @since 3.8.0 Renamed 'Fixed Width' and 'Flexible Width' options
	 *              to 'Fixed Layout' and 'Fluid Layout'.
	 * @since 3.8.0 Added 'Accessibility Ready' feature and 'Responsive Layout' option.
	 * @since 3.9.0 Combined 'Layout' and 'Columns' filters.
	 * @since 4.6.0 Removed 'Colors' filter.
	 * @since 4.6.0 Added 'Grid Layout' option.
	 *              Removed 'Fixed Layout', 'Fluid Layout', and 'Responsive Layout' options.
	 * @since 4.6.0 Added 'Custom Logo' and 'Footer Widgets' features.
	 *              Removed 'Blavatar' feature.
	 * @since 4.6.0 Added 'Blog', 'E-Commerce', 'Education', 'Entertainment', 'Food & Drink',
	 *              'Holiday', 'News', 'Photography', and 'Portfolio' subjects.
	 *              Removed 'Photoblogging' and 'Seasonal' subjects.
	 * @since 4.9.0 Reordered the filters from 'Layout', 'Features', 'Subject'
	 *              to 'Subject', 'Features', 'Layout'.
	 * @since 4.9.0 Removed 'BuddyPress', 'Custom Menu', 'Flexible Header',
	 *              'Front Page Posting', 'Microformats', 'RTL Language Support',
	 *              'Threaded Comments', and 'Translation Ready' features.
	 * @since 5.5.0 Added 'Block Editor Patterns', 'Block Editor Styles',
	 *              and 'Full Site Editing' features.
	 * @since 5.5.0 Added 'Wide Blocks' layout option.
	 * @since 5.8.1 Added 'Template Editing' feature.
	 * @since 6.1.1 Replaced 'Full Site Editing' feature name with 'Site Editor'.
	 * @since 6.2.0 Added 'Style Variations' feature.
	 *
	 * @param bool $api Optional. Whether try to fetch tags from the WordPress.org API. Defaults to true.
	 * @return array Array of features keyed by category with translations keyed by slug.
	 */
	public function get_theme_feature_list( $api = true );

	/**
	 * Prepares themes for JavaScript.
	 *
	 * @since 3.8.0
	 *
	 * @param WP_Theme[] $themes Optional. Array of theme objects to prepare.
	 *                           Defaults to all allowed themes.
	 *
	 * @return array An associative array of theme data, sorted by name.
	 */
	public function wp_prepare_themes_for_js( $themes = null );

	/**
	 * Gets the page templates available in this theme.
	 *
	 * @since 1.5.0
	 * @since 4.7.0 Added the `$post_type` parameter.
	 *
	 * @param WP_Post|null $post      Optional. The post being edited, provided for context.
	 * @param string       $post_type Optional. Post type to get the templates for. Default 'page'.
	 * @return string[] Array of template file names keyed by the template header name.
	 */
	public function get_page_templates( $post = null, $post_type = 'page' );

	/**
	 * Removes a theme.
	 *
	 * @since 2.8.0
	 *
	 * @global WP_Filesystem_Base $wp_filesystem WordPress filesystem subclass.
	 *
	 * @param string $stylesheet Stylesheet of the theme to delete.
	 * @param string $redirect   Redirect to page when complete.
	 * @return bool|null|WP_Error True on success, false if `$stylesheet` is empty, WP_Error on failure.
	 *                            Null if filesystem credentials are required to proceed.
	 */
	public function delete_theme( $stylesheet, $redirect = '' );

	/**
	 * Determines whether a theme is technically active but was paused while
	 * loading.
	 *
	 * For more information on this and similar theme functions, check out
	 * the {@link https://developer.wordpress.org/themes/basics/conditional-tags/
	 * Conditional Tags} article in the Theme Developer Handbook.
	 *
	 * @since 5.2.0
	 *
	 * @global WP_Paused_Extensions_Storage $_paused_themes
	 *
	 * @param string $theme Path to the theme directory relative to the themes directory.
	 * @return bool True, if in the list of paused themes. False, not in the list.
	 */
	public function is_theme_paused( $theme );

	/**
	 * Gets the error that was recorded for a paused theme.
	 *
	 * @since 5.2.0
	 *
	 * @global WP_Paused_Extensions_Storage $_paused_themes
	 *
	 * @param string $theme Path to the theme directory relative to the themes
	 *                      directory.
	 * @return array|false Array of error information as it was returned by
	 *                     `error_get_last()`, or false if none was recorded.
	 */
	public function wp_get_theme_error( $theme );

	/**
	 * Tries to resume a single theme.
	 *
	 * If a redirect was provided and a functions.php file was found, we first ensure that
	 * functions.php file does not throw fatal errors anymore.
	 *
	 * The way it works is by setting the redirection to the error before trying to
	 * include the file. If the theme fails, then the redirection will not be overwritten
	 * with the success message and the theme will not be resumed.
	 *
	 * @since 5.2.0
	 *
	 * @global string $wp_stylesheet_path Path to current theme's stylesheet directory.
	 * @global string $wp_template_path   Path to current theme's template directory.
	 *
	 * @param string $theme    Single theme to resume.
	 * @param string $redirect Optional. URL to redirect to. Default empty string.
	 * @return bool|WP_Error True on success, false if `$theme` was not paused,
	 *                       `WP_Error` on failure.
	 */
	public function resume_theme( $theme, $redirect = '' );

	/**
	 * Gets a WP_Theme object for a theme.
	 *
	 * @since 3.4.0
	 *
	 * @global string[] $wp_theme_directories
	 *
	 * @param string $stylesheet Optional. Directory name for the theme. Defaults to active theme.
	 * @param string $theme_root Optional. Absolute path of the theme root to look in.
	 *                           If not specified, get_raw_theme_root() is used to calculate
	 *                           the theme root for the $stylesheet provided (or active theme).
	 * @return WP_Theme Theme object. Be sure to check the object's exists() method
	 *                  if you need to confirm the theme's existence.
	 */
	public function wp_get_theme( $stylesheet = '', $theme_root = '' );

	/**
	 * Returns an array of WP_Theme objects based on the arguments.
	 *
	 * Despite advances over get_themes(), this function is quite expensive, and grows
	 * linearly with additional themes. Stick to wp_get_theme() if possible.
	 *
	 * @since 3.4.0
	 *
	 * @global string[] $wp_theme_directories
	 *
	 * @param array $args {
	 *     Optional. The search arguments.
	 *
	 *     @type mixed $errors  True to return themes with errors, false to return
	 *                          themes without errors, null to return all themes.
	 *                          Default false.
	 *     @type mixed $allowed (Multisite) True to return only allowed themes for a site.
	 *                          False to return only disallowed themes for a site.
	 *                          'site' to return only site-allowed themes.
	 *                          'network' to return only network-allowed themes.
	 *                          Null to return all themes. Default null.
	 *     @type int   $blog_id (Multisite) The blog ID used to calculate which themes
	 *                          are allowed. Default 0, synonymous for the current blog.
	 * }
	 * @return WP_Theme[] Array of WP_Theme objects.
	 */
	public function wp_get_themes( $args = array() );

	/**
	 * Returns whether the active theme is a block-based theme or not.
	 *
	 * @since 5.9.0
	 *
	 * @global string[] $wp_theme_directories
	 *
	 * @return bool Whether the active theme is a block-based theme or not.
	 */
	public function wp_is_block_theme();

	/**
	 * Whether a child theme is in use.
	 *
	 * @since 3.0.0
	 * @since 6.5.0 Makes use of global template variables.
	 *
	 * @global string $wp_stylesheet_path Path to current theme's stylesheet directory.
	 * @global string $wp_template_path   Path to current theme's template directory.
	 *
	 * @return bool True if a child theme is in use, false otherwise.
	 */
	public function is_child_theme();

	/**
	 * Switches the theme.
	 *
	 * Accepts one argument: $stylesheet of the theme. It also accepts an additional function signature
	 * of two arguments: $template then $stylesheet. This is for backward compatibility.
	 *
	 * @since 2.5.0
	 *
	 * @global string[]             $wp_theme_directories
	 * @global WP_Customize_Manager $wp_customize
	 * @global array                $sidebars_widgets
	 * @global array                $wp_registered_sidebars
	 *
	 * @param string $stylesheet Stylesheet name.
	 */
	public function switch_theme( $stylesheet );

	/**
	 * Checks that the active theme has the required files.
	 *
	 * Standalone themes need to have a `templates/index.html` or `index.php` template file.
	 * Child themes need to have a `Template` header in the `style.css` stylesheet.
	 *
	 * Does not initially check the default theme, which is the fallback and should always exist.
	 * But if it doesn't exist, it'll fall back to the latest core default theme that does exist.
	 * Will switch theme to the fallback theme if active theme does not validate.
	 *
	 * You can use the {@see 'validate_current_theme'} filter to return false to disable
	 * this functionality.
	 *
	 * @since 1.5.0
	 * @since 6.0.0 Removed the requirement for block themes to have an `index.php` template.
	 *
	 * @see WP_DEFAULT_THEME
	 *
	 * @return bool
	 */
	public function validate_current_theme();

	/**
	 * Validates the theme requirements for WordPress version and PHP version.
	 *
	 * Uses the information from `Requires at least` and `Requires PHP` headers
	 * defined in the theme's `style.css` file.
	 *
	 * @since 5.5.0
	 * @since 5.8.0 Removed support for using `readme.txt` as a fallback.
	 *
	 * @param string $stylesheet Directory name for the theme.
	 * @return true|WP_Error True if requirements are met, WP_Error on failure.
	 */
	public function validate_theme_requirements( $stylesheet );

	/**
	 * Clears the cache held by get_theme_roots() and WP_Theme.
	 *
	 * @since 3.5.0
	 * @param bool $clear_update_cache Whether to clear the theme updates cache.
	 */
	public function wp_clean_themes_cache( $clear_update_cache = true );

	/**
	 * Retrieves name of the current stylesheet.
	 *
	 * The theme name that is currently set as the front end theme.
	 *
	 * For all intents and purposes, the template name and the stylesheet name
	 * are going to be the same for most cases.
	 *
	 * @since 1.5.0
	 *
	 * @return string Stylesheet name.
	 */
	public function get_stylesheet();

	/**
	 * Retrieves stylesheet directory path for the active theme.
	 *
	 * @since 1.5.0
	 * @since 6.4.0 Memoizes filter execution so that it only runs once for the current theme.
	 * @since 6.4.2 Memoization removed.
	 *
	 * @return string Path to active theme's stylesheet directory.
	 */
	public function get_stylesheet_directory();

	/**
	 * Retrieves stylesheet directory URI for the active theme.
	 *
	 * @since 1.5.0
	 *
	 * @return string URI to active theme's stylesheet directory.
	 */
	public function get_stylesheet_directory_uri();

	/**
	 * Retrieves stylesheet URI for the active theme.
	 *
	 * The stylesheet file name is 'style.css' which is appended to the stylesheet directory URI path.
	 * See get_stylesheet_directory_uri().
	 *
	 * @since 1.5.0
	 *
	 * @return string URI to active theme's stylesheet.
	 */
	public function get_stylesheet_uri();

	/**
	 * Retrieves the localized stylesheet URI.
	 *
	 * The stylesheet directory for the localized stylesheet files are located, by
	 * default, in the base theme directory. The name of the locale file will be the
	 * locale followed by '.css'. If that does not exist, then the text direction
	 * stylesheet will be checked for existence, for example 'ltr.css'.
	 *
	 * The theme may change the location of the stylesheet directory by either using
	 * the {@see 'stylesheet_directory_uri'} or {@see 'locale_stylesheet_uri'} filters.
	 *
	 * If you want to change the location of the stylesheet files for the entire
	 * WordPress workflow, then change the former. If you just have the locale in a
	 * separate folder, then change the latter.
	 *
	 * @since 2.1.0
	 *
	 * @global WP_Locale $wp_locale WordPress date and time locale object.
	 *
	 * @return string URI to active theme's localized stylesheet.
	 */
	public function get_locale_stylesheet_uri();

	/**
	 * Retrieves name of the active theme.
	 *
	 * @since 1.5.0
	 *
	 * @return string Template name.
	 */
	public function get_template();

	/**
	 * Retrieves template directory path for the active theme.
	 *
	 * @since 1.5.0
	 * @since 6.4.0 Memoizes filter execution so that it only runs once for the current theme.
	 * @since 6.4.1 Memoization removed.
	 *
	 * @return string Path to active theme's template directory.
	 */
	public function get_template_directory();

	/**
	 * Retrieves template directory URI for the active theme.
	 *
	 * @since 1.5.0
	 *
	 * @return string URI to active theme's template directory.
	 */
	public function get_template_directory_uri();

	/**
	 * Retrieves path to themes directory.
	 *
	 * Does not have trailing slash.
	 *
	 * @since 1.5.0
	 *
	 * @global string[] $wp_theme_directories
	 *
	 * @param string $stylesheet_or_template Optional. The stylesheet or template name of the theme.
	 *                                       Default is to leverage the main theme root.
	 * @return string Themes directory path.
	 */
	public function get_theme_root( $stylesheet_or_template = '' );

	/**
	 * Retrieves URI for themes directory.
	 *
	 * Does not have trailing slash.
	 *
	 * @since 1.5.0
	 *
	 * @global string[] $wp_theme_directories
	 *
	 * @param string $stylesheet_or_template Optional. The stylesheet or template name of the theme.
	 *                                       Default is to leverage the main theme root.
	 * @param string $theme_root             Optional. The theme root for which calculations will be based,
	 *                                       preventing the need for a get_raw_theme_root() call. Default empty.
	 * @return string Themes directory URI.
	 */
	public function get_theme_root_uri( $stylesheet_or_template = '', $theme_root = '' );

	/**
	 * Gets the raw theme root relative to the content directory with no filters applied.
	 *
	 * @since 3.1.0
	 *
	 * @global string[] $wp_theme_directories
	 *
	 * @param string $stylesheet_or_template The stylesheet or template name of the theme.
	 * @param bool   $skip_cache             Optional. Whether to skip the cache.
	 *                                       Defaults to false, meaning the cache is used.
	 * @return string Theme root.
	 */
	public function get_raw_theme_root( $stylesheet_or_template, $skip_cache = false );

	/**
	 * Retrieves theme roots.
	 *
	 * @since 2.9.0
	 *
	 * @global string[] $wp_theme_directories
	 *
	 * @return array|string An array of theme roots keyed by template/stylesheet
	 *                      or a single theme root if all themes have the same root.
	 */
	public function get_theme_roots();

	/**
	 * Registers a directory that contains themes.
	 *
	 * @since 2.9.0
	 *
	 * @global string[] $wp_theme_directories
	 *
	 * @param string $directory Either the full filesystem path to a theme folder
	 *                          or a folder within WP_CONTENT_DIR.
	 * @return bool True if successfully registered a directory that contains themes,
	 *              false if the directory does not exist.
	 */
	public function register_theme_directory( $directory );

	/**
	 * Searches all registered theme directories for complete and valid themes.
	 *
	 * @since 2.9.0
	 *
	 * @global string[] $wp_theme_directories
	 *
	 * @param bool $force Optional. Whether to force a new directory scan. Default false.
	 * @return array|false Valid themes found on success, false on failure.
	 */
	public function search_theme_directories( $force = false );

	/**
	 * Retrieves theme modification value for the active theme.
	 *
	 * If the modification name does not exist and `$default_value` is a string, then the
	 * default will be passed through the {@link https://www.php.net/sprintf sprintf()}
	 * PHP function with the template directory URI as the first value and the
	 * stylesheet directory URI as the second value.
	 *
	 * @since 2.1.0
	 *
	 * @param string $name          Theme modification name.
	 * @param mixed  $default_value Optional. Theme modification default value. Default false.
	 * @return mixed Theme modification value.
	 */
	public function get_theme_mod( $name, $default_value = false );

	/**
	 * Retrieves all theme modifications.
	 *
	 * @since 3.1.0
	 * @since 5.9.0 The return value is always an array.
	 *
	 * @return array Theme modifications.
	 */
	public function get_theme_mods();

	/**
	 * Updates theme modification value for the active theme.
	 *
	 * @since 2.1.0
	 * @since 5.6.0 A return value was added.
	 *
	 * @param string $name  Theme modification name.
	 * @param mixed  $value Theme modification value.
	 * @return bool True if the value was updated, false otherwise.
	 */
	public function set_theme_mod( $name, $value );

	/**
	 * Removes theme modification name from active theme list.
	 *
	 * If removing the name also removes all elements, then the entire option
	 * will be removed.
	 *
	 * @since 2.1.0
	 *
	 * @param string $name Theme modification name.
	 */
	public function remove_theme_mod( $name );

	/**
	 * Removes theme modifications option for the active theme.
	 *
	 * @since 2.1.0
	 */
	public function remove_theme_mods();

	/**
	 * Registers theme support for a given feature.
	 *
	 * Must be called in the theme's functions.php file to work.
	 * If attached to a hook, it must be {@see 'after_setup_theme'}.
	 * The {@see 'init'} hook may be too late for some features.
	 *
	 * Example usage:
	 *
	 *     add_theme_support( 'title-tag' );
	 *     add_theme_support( 'custom-logo', array(
	 *         'height' => 480,
	 *         'width'  => 720,
	 *     ) );
	 *
	 * @since 2.9.0
	 * @since 3.4.0 The `custom-header-uploads` feature was deprecated.
	 * @since 3.6.0 The `html5` feature was added.
	 * @since 3.6.1 The `html5` feature requires an array of types to be passed. Defaults to
	 *              'comment-list', 'comment-form', 'search-form' for backward compatibility.
	 * @since 3.9.0 The `html5` feature now also accepts 'gallery' and 'caption'.
	 * @since 4.1.0 The `title-tag` feature was added.
	 * @since 4.5.0 The `customize-selective-refresh-widgets` feature was added.
	 * @since 4.7.0 The `starter-content` feature was added.
	 * @since 5.0.0 The `responsive-embeds`, `align-wide`, `dark-editor-style`, `disable-custom-colors`,
	 *              `disable-custom-font-sizes`, `editor-color-palette`, `editor-font-sizes`,
	 *              `editor-styles`, and `wp-block-styles` features were added.
	 * @since 5.3.0 The `html5` feature now also accepts 'script' and 'style'.
	 * @since 5.3.0 Formalized the existing and already documented `...$args` parameter
	 *              by adding it to the function signature.
	 * @since 5.4.0 The `disable-custom-gradients` feature limits to default gradients or gradients added
	 *              through `editor-gradient-presets` theme support.
	 * @since 5.5.0 The `core-block-patterns` feature was added and is enabled by default.
	 * @since 5.5.0 The `custom-logo` feature now also accepts 'unlink-homepage-logo'.
	 * @since 5.6.0 The `post-formats` feature warns if no array is passed as the second parameter.
	 * @since 5.8.0 The `widgets-block-editor` feature enables the Widgets block editor.
	 * @since 5.8.0 The `block-templates` feature indicates whether a theme uses block-based templates.
	 * @since 6.0.0 The `html5` feature warns if no array is passed as the second parameter.
	 * @since 6.1.0 The `block-template-parts` feature allows to edit any reusable template part from site editor.
	 * @since 6.1.0 The `disable-layout-styles` feature disables the default layout styles.
	 * @since 6.3.0 The `link-color` feature allows to enable the link color setting.
	 * @since 6.3.0 The `border` feature allows themes without theme.json to add border styles to blocks.
	 * @since 6.5.0 The `appearance-tools` feature enables a few design tools for blocks,
	 *              see `WP_Theme_JSON::APPEARANCE_TOOLS_OPT_INS` for a complete list.
	 * @since 6.6.0 The `editor-spacing-sizes` feature was added.
	 * @since 7.0.0 The `html5` feature's 'script' and 'style' arguments are deprecated and unused.
	 *
	 * @global array $_wp_theme_features
	 *
	 * @param string $feature The feature being added. Likely core values include:
	 *                          - 'admin-bar'
	 *                          - 'align-wide'
	 *                          - 'appearance-tools'
	 *                          - 'automatic-feed-links'
	 *                          - 'block-templates'
	 *                          - 'block-template-parts'
	 *                          - 'border'
	 *                          - 'core-block-patterns'
	 *                          - 'custom-background'
	 *                          - 'custom-header'
	 *                          - 'custom-line-height'
	 *                          - 'custom-logo'
	 *                          - 'customize-selective-refresh-widgets'
	 *                          - 'custom-spacing'
	 *                          - 'custom-units'
	 *                          - 'dark-editor-style'
	 *                          - 'disable-custom-colors'
	 *                          - 'disable-custom-font-sizes'
	 *                          - 'disable-custom-gradients'
	 *                          - 'disable-layout-styles'
	 *                          - 'editor-color-palette'
	 *                          - 'editor-gradient-presets'
	 *                          - 'editor-font-sizes'
	 *                          - 'editor-spacing-sizes'
	 *                          - 'editor-styles'
	 *                          - 'featured-content'
	 *                          - 'html5'
	 *                          - 'link-color'
	 *                          - 'menus'
	 *                          - 'post-formats'
	 *                          - 'post-thumbnails'
	 *                          - 'responsive-embeds'
	 *                          - 'starter-content'
	 *                          - 'title-tag'
	 *                          - 'widgets'
	 *                          - 'widgets-block-editor'
	 *                          - 'wp-block-styles'
	 * @param mixed  ...$args Optional extra arguments to pass along with certain features.
	 * @return void|false Void on success, false on failure.
	 */
	public function add_theme_support( $feature, ...$args );

	/**
	 * Allows a theme to de-register its support of a certain feature
	 *
	 * Should be called in the theme's functions.php file. Generally would
	 * be used for child themes to override support from the parent theme.
	 *
	 * @since 3.0.0
	 *
	 * @see add_theme_support()
	 *
	 * @param string $feature The feature being removed. See add_theme_support() for the list
	 *                        of possible values.
	 * @return bool Whether feature was removed.
	 */
	public function remove_theme_support( $feature );

	/**
	 * Checks a theme's support for a given feature.
	 *
	 * Example usage:
	 *
	 *     current_theme_supports( 'custom-logo' );
	 *     current_theme_supports( 'html5', 'comment-form' );
	 *
	 * @since 2.9.0
	 * @since 5.3.0 Formalized the existing and already documented `...$args` parameter
	 *              by adding it to the function signature.
	 *
	 * @global array $_wp_theme_features
	 *
	 * @param string $feature The feature being checked. See add_theme_support() for the list
	 *                        of possible values.
	 * @param mixed  ...$args Optional extra arguments to be checked against certain features.
	 * @return bool True if the active theme supports the feature, false otherwise.
	 */
	public function current_theme_supports( $feature, ...$args );

	/**
	 * Gets the theme support arguments passed when registering that support.
	 *
	 * Example usage:
	 *
	 *     get_theme_support( 'custom-logo' );
	 *     get_theme_support( 'custom-header', 'width' );
	 *
	 * @since 3.1.0
	 * @since 5.3.0 Formalized the existing and already documented `...$args` parameter
	 *              by adding it to the function signature.
	 *
	 * @global array $_wp_theme_features
	 *
	 * @param string $feature The feature to check. See add_theme_support() for the list
	 *                        of possible values.
	 * @param mixed  ...$args Optional extra arguments to be checked against certain features.
	 * @return mixed The array of extra arguments or the value for the registered feature.
	 */
	public function get_theme_support( $feature, ...$args );

	/**
	 * Checks a theme's support for a given feature before loading the functions which implement it.
	 *
	 * @since 2.9.0
	 *
	 * @param string $feature The feature being checked. See add_theme_support() for the list
	 *                        of possible values.
	 * @param string $file    Path to the file.
	 * @return bool True if the active theme supports the supplied feature, false otherwise.
	 */
	public function require_if_theme_supports( $feature, $file );

	/**
	 * Registers a theme feature for use in add_theme_support().
	 *
	 * This does not indicate that the active theme supports the feature, it only describes
	 * the feature's supported options.
	 *
	 * @since 5.5.0
	 *
	 * @see add_theme_support()
	 *
	 * @global array $_wp_registered_theme_features
	 *
	 * @param string $feature The name uniquely identifying the feature. See add_theme_support()
	 *                        for the list of possible values.
	 * @param array  $args {
	 *     Data used to describe the theme.
	 *
	 *     @type string     $type         The type of data associated with this feature.
	 *                                    Valid values are 'string', 'boolean', 'integer',
	 *                                    'number', 'array', and 'object'. Defaults to 'boolean'.
	 *     @type bool       $variadic     Does this feature utilize the variadic support
	 *                                    of add_theme_support(), or are all arguments specified
	 *                                    as the second parameter. Must be used with the "array" type.
	 *     @type string     $description  A short description of the feature. Included in
	 *                                    the Themes REST API schema. Intended for developers.
	 *     @type bool|array $show_in_rest {
	 *         Whether this feature should be included in the Themes REST API endpoint.
	 *         Defaults to not being included. When registering an 'array' or 'object' type,
	 *         this argument must be an array with the 'schema' key.
	 *
	 *         @type array    $schema           Specifies the JSON Schema definition describing
	 *                                          the feature. If any objects in the schema do not include
	 *                                          the 'additionalProperties' keyword, it is set to false.
	 *         @type string   $name             An alternate name to be used as the property name
	 *                                          in the REST API.
	 *         @type callable $prepare_callback A function used to format the theme support in the REST API.
	 *                                          Receives the raw theme support value.
	 *      }
	 * }
	 * @return true|WP_Error True if the theme feature was successfully registered, a WP_Error object if not.
	 */
	public function register_theme_feature( $feature, $args = array() );

	/**
	 * Gets the registration config for a theme feature.
	 *
	 * @since 5.5.0
	 *
	 * @global array $_wp_registered_theme_features
	 *
	 * @param string $feature The feature name. See add_theme_support() for the list
	 *                        of possible values.
	 * @return array|null The registration args, or null if the feature was not registered.
	 */
	public function get_registered_theme_feature( $feature );

	/**
	 * Gets the list of registered theme features.
	 *
	 * @since 5.5.0
	 *
	 * @global array $_wp_registered_theme_features
	 *
	 * @return array[] List of theme features, keyed by their name.
	 */
	public function get_registered_theme_features();

	/**
	 * Adds callback for custom TinyMCE editor stylesheets.
	 *
	 * The parameter $stylesheet is the name of the stylesheet, relative to
	 * the theme root. It also accepts an array of stylesheets.
	 * It is optional and defaults to 'editor-style.css'.
	 *
	 * This function automatically adds another stylesheet with -rtl prefix, e.g. editor-style-rtl.css.
	 * If that file doesn't exist, it is removed before adding the stylesheet(s) to TinyMCE.
	 * If an array of stylesheets is passed to add_editor_style(),
	 * RTL is only added for the first stylesheet.
	 *
	 * Since version 3.4 the TinyMCE body has .rtl CSS class.
	 * It is a better option to use that class and add any RTL styles to the main stylesheet.
	 *
	 * @since 3.0.0
	 *
	 * @global array $editor_styles
	 *
	 * @param array|string $stylesheet Optional. Stylesheet name or array thereof, relative to theme root.
	 *                                 Defaults to 'editor-style.css'
	 */
	public function add_editor_style( $stylesheet = 'editor-style.css' );

	/**
	 * Removes all visual editor stylesheets.
	 *
	 * @since 3.1.0
	 *
	 * @global array $editor_styles
	 *
	 * @return bool True on success, false if there were no stylesheets to remove.
	 */
	public function remove_editor_styles();

	/**
	 * Retrieves any registered editor stylesheet URLs.
	 *
	 * @since 4.0.0
	 *
	 * @global array $editor_styles Registered editor stylesheets
	 *
	 * @return string[] If registered, a list of editor stylesheet URLs.
	 */
	public function get_editor_stylesheets();

	/**
	 * Registers a selection of default headers to be displayed by the custom header admin UI.
	 *
	 * @since 3.0.0
	 *
	 * @global array $_wp_default_headers
	 *
	 * @param array $headers Array of headers keyed by a string ID. The IDs point to arrays
	 *                       containing 'url', 'thumbnail_url', and 'description' keys.
	 */
	public function register_default_headers( $headers );

	/**
	 * Unregisters default headers.
	 *
	 * This function must be called after register_default_headers() has already added the
	 * header you want to remove.
	 *
	 * @see register_default_headers()
	 * @since 3.0.0
	 *
	 * @global array $_wp_default_headers
	 *
	 * @param string|array $header The header string id (key of array) to remove, or an array thereof.
	 * @return bool|null A single header returns true on success, false on failure.
	 *                   There is currently no return value for multiple headers.
	 */
	public function unregister_default_headers( $header );

	/**
	 * Gets the header images uploaded for the active theme.
	 *
	 * @since 3.2.0
	 *
	 * @return array
	 */
	public function get_uploaded_header_images();

	/**
	 * Expands a theme's starter content configuration using core-provided data.
	 *
	 * @since 4.7.0
	 *
	 * @return array Array of starter content.
	 */
	public function get_theme_starter_content();

	/**
	 * Fetches the saved Custom CSS content for rendering.
	 *
	 * @since 4.7.0
	 *
	 * @param string $stylesheet Optional. A theme object stylesheet name. Defaults to the active theme.
	 * @return string The Custom CSS Post content.
	 */
	public function wp_get_custom_css( $stylesheet = '' );

	/**
	 * Fetches the `custom_css` post for a given theme.
	 *
	 * @since 4.7.0
	 *
	 * @param string $stylesheet Optional. A theme object stylesheet name. Defaults to the active theme.
	 * @return WP_Post|null The custom_css post or null if none exists.
	 */
	public function wp_get_custom_css_post( $stylesheet = '' );

	/**
	 * Updates the `custom_css` post for a given theme.
	 *
	 * Inserts a `custom_css` post when one doesn't yet exist.
	 *
	 * @since 4.7.0
	 *
	 * @param string $css CSS, stored in `post_content`.
	 * @param array  $args {
	 *     Args.
	 *
	 *     @type string $preprocessed Optional. Pre-processed CSS, stored in `post_content_filtered`.
	 *                                Normally empty string.
	 *     @type string $stylesheet   Optional. Stylesheet (child theme) to update.
	 *                                Defaults to active theme/stylesheet.
	 * }
	 * @return WP_Post|WP_Error Post on success, error on failure.
	 */
	public function wp_update_custom_css_post( $css, $args = array() );

	/**
	 * Whether the site is being previewed in the Customizer.
	 *
	 * @since 4.0.0
	 *
	 * @global WP_Customize_Manager $wp_customize Customizer instance.
	 *
	 * @return bool True if the site is being previewed in the Customizer, false otherwise.
	 */
	public function is_customize_preview();

	/**
	 * Returns a URL to load the Customizer.
	 *
	 * @since 3.4.0
	 *
	 * @param string $stylesheet Optional. Theme to customize. Defaults to active theme.
	 *                           The theme's stylesheet will be urlencoded if necessary.
	 * @return string
	 */
	public function wp_customize_url( $stylesheet = '' );

	/**
	 * Prints a script to check whether or not the Customizer is supported,
	 * and apply either the no-customize-support or customize-support class
	 * to the body.
	 *
	 * This function MUST be called inside the body tag.
	 *
	 * Ideally, call this function immediately after the body tag is opened.
	 * This prevents a flash of unstyled content.
	 *
	 * It is also recommended that you add the "no-customize-support" class
	 * to the body tag by default.
	 *
	 * @since 3.4.0
	 * @since 4.7.0 Support for IE8 and below is explicitly removed via conditional comments.
	 * @since 5.5.0 IE8 and older are no longer supported.
	 */
	public function wp_customize_support_script();
}
