<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use WP_Rewrite;

interface Urls {
	/**
	 * Retrieves the URL to the admin area for the current site.
	 *
	 * @since 2.6.0
	 *
	 * @param string $path   Optional. Path relative to the admin URL. Default empty.
	 * @param string $scheme The scheme to use. Default is 'admin', which obeys force_ssl_admin() and is_ssl().
	 *                       'http' or 'https' can be passed to force those schemes.
	 * @return string Admin URL link with optional path appended.
	 */
	public function admin_url( $path = '', $scheme = 'admin' );

	/**
	 * Retrieves the URL to the content directory.
	 *
	 * @since 2.6.0
	 *
	 * @param string $path Optional. Path relative to the content URL. Default empty.
	 * @return string Content URL link with optional path appended.
	 */
	public function content_url( $path = '' );

	/**
	 * Retrieves the URL to the admin area for a given site.
	 *
	 * @since 3.0.0
	 *
	 * @param int|null $blog_id Optional. Site ID. Default null (current site).
	 * @param string   $path    Optional. Path relative to the admin URL. Default empty.
	 * @param string   $scheme  Optional. The scheme to use. Accepts 'http' or 'https',
	 *                          to force those schemes. Default 'admin', which obeys
	 *                          force_ssl_admin() and is_ssl().
	 * @return string Admin URL link with optional path appended.
	 */
	public function get_admin_url( $blog_id = null, $path = '', $scheme = 'admin' );

	/**
	 * Retrieves the URL to the user's dashboard.
	 *
	 * If a user does not belong to any site, the global user dashboard is used. If the user
	 * belongs to the current site, the dashboard for the current site is returned. If the user
	 * cannot edit the current site, the dashboard to the user's primary site is returned.
	 *
	 * @since 3.1.0
	 *
	 * @param int    $user_id Optional. User ID. Defaults to current user.
	 * @param string $path    Optional path relative to the dashboard. Use only paths known to
	 *                        both site and user admins. Default empty.
	 * @param string $scheme  The scheme to use. Default is 'admin', which obeys force_ssl_admin()
	 *                        and is_ssl(). 'http' or 'https' can be passed to force those schemes.
	 * @return string Dashboard URL link with optional path appended.
	 */
	public function get_dashboard_url( $user_id = 0, $path = '', $scheme = 'admin' );

	/**
	 * Retrieves the URL to the user's profile editor.
	 *
	 * @since 3.1.0
	 *
	 * @param int    $user_id Optional. User ID. Defaults to current user.
	 * @param string $scheme  Optional. The scheme to use. Default is 'admin', which obeys force_ssl_admin()
	 *                        and is_ssl(). 'http' or 'https' can be passed to force those schemes.
	 * @return string Dashboard URL link with optional path appended.
	 */
	public function get_edit_profile_url( $user_id = 0, $scheme = 'admin' );

	/**
	 * Retrieves the URL for a given site where the front end is accessible.
	 *
	 * Returns the 'home' option with the appropriate protocol. The protocol will be 'https'
	 * if is_ssl() evaluates to true; otherwise, it will be the same as the 'home' option.
	 * If `$scheme` is 'http' or 'https', is_ssl() is overridden.
	 *
	 * @since 3.0.0
	 *
	 * @param int|null    $blog_id Optional. Site ID. Default null (current site).
	 * @param string      $path    Optional. Path relative to the home URL. Default empty.
	 * @param string|null $scheme  Optional. Scheme to give the home URL context. Accepts
	 *                             'http', 'https', 'relative', 'rest', or null. Default null.
	 * @return string Home URL link with optional path appended.
	 */
	public function get_home_url( $blog_id = null, $path = '', $scheme = null );

	/**
	 * Retrieves the URL to the privacy policy page.
	 *
	 * @since 4.9.6
	 *
	 * @return string The URL to the privacy policy page. Empty string if it doesn't exist.
	 */
	public function get_privacy_policy_url();

	/**
	 * Retrieves the URL for a given site where WordPress application files
	 * (e.g. wp-blog-header.php or the wp-admin/ folder) are accessible.
	 *
	 * Returns the 'site_url' option with the appropriate protocol, 'https' if
	 * is_ssl() and 'http' otherwise. If `$scheme` is 'http' or 'https',
	 * `is_ssl()` is overridden.
	 *
	 * @since 3.0.0
	 *
	 * @param int|null    $blog_id Optional. Site ID. Default null (current site).
	 * @param string      $path    Optional. Path relative to the site URL. Default empty.
	 * @param string|null $scheme  Optional. Scheme to give the site URL context. Accepts
	 *                             'http', 'https', 'login', 'login_post', 'admin', or
	 *                             'relative'. Default null.
	 * @return string Site URL link with optional path appended.
	 */
	public function get_site_url( $blog_id = null, $path = '', $scheme = null );

	/**
	 * Returns the privacy policy link with formatting, when applicable.
	 *
	 * @since 4.9.6
	 * @since 6.2.0 Added 'privacy-policy' rel attribute.
	 *
	 * @param string $before Optional. Display before privacy policy link. Default empty.
	 * @param string $after  Optional. Display after privacy policy link. Default empty.
	 * @return string Markup for the link and surrounding elements. Empty string if it
	 *                doesn't exist.
	 */
	public function get_the_privacy_policy_link( $before = '', $after = '' );

	/**
	 * Retrieves the URL for the current site where the front end is accessible.
	 *
	 * Returns the 'home' option with the appropriate protocol. The protocol will be 'https'
	 * if is_ssl() evaluates to true; otherwise, it will be the same as the 'home' option.
	 * If `$scheme` is 'http' or 'https', is_ssl() is overridden.
	 *
	 * @since 3.0.0
	 *
	 * @param string      $path   Optional. Path relative to the home URL. Default empty.
	 * @param string|null $scheme Optional. Scheme to give the home URL context. Accepts
	 *                            'http', 'https', 'relative', 'rest', or null. Default null.
	 * @return string Home URL link with optional path appended.
	 */
	public function home_url( $path = '', $scheme = null );

	/**
	 * Retrieves the URL to the includes directory.
	 *
	 * @since 2.6.0
	 *
	 * @param string      $path   Optional. Path relative to the includes URL. Default empty.
	 * @param string|null $scheme Optional. Scheme to give the includes URL context. Accepts
	 *                            'http', 'https', or 'relative'. Default null.
	 * @return string Includes URL link with optional path appended.
	 */
	public function includes_url( $path = '', $scheme = null );

	/**
	 * Retrieves the URL to the admin area for the network.
	 *
	 * @since 3.0.0
	 *
	 * @param string $path   Optional path relative to the admin URL. Default empty.
	 * @param string $scheme Optional. The scheme to use. Default is 'admin', which obeys force_ssl_admin()
	 *                       and is_ssl(). 'http' or 'https' can be passed to force those schemes.
	 * @return string Admin URL link with optional path appended.
	 */
	public function network_admin_url( $path = '', $scheme = 'admin' );

	/**
	 * Retrieves the home URL for the current network.
	 *
	 * Returns the home URL with the appropriate protocol, 'https' is_ssl()
	 * and 'http' otherwise. If `$scheme` is 'http' or 'https', `is_ssl()` is
	 * overridden.
	 *
	 * @since 3.0.0
	 *
	 * @param string      $path   Optional. Path relative to the home URL. Default empty.
	 * @param string|null $scheme Optional. Scheme to give the home URL context. Accepts
	 *                            'http', 'https', or 'relative'. Default null.
	 * @return string Home URL link with optional path appended.
	 */
	public function network_home_url( $path = '', $scheme = null );

	/**
	 * Retrieves the site URL for the current network.
	 *
	 * Returns the site URL with the appropriate protocol, 'https' if
	 * is_ssl() and 'http' otherwise. If $scheme is 'http' or 'https', is_ssl() is
	 * overridden.
	 *
	 * @since 3.0.0
	 *
	 * @see set_url_scheme()
	 *
	 * @param string      $path   Optional. Path relative to the site URL. Default empty.
	 * @param string|null $scheme Optional. Scheme to give the site URL context. Accepts
	 *                            'http', 'https', or 'relative'. Default null.
	 * @return string Site URL link with optional path appended.
	 */
	public function network_site_url( $path = '', $scheme = null );

	/**
	 * Retrieves a URL within the plugins or mu-plugins directory.
	 *
	 * Defaults to the plugins directory URL if no arguments are supplied.
	 *
	 * @since 2.6.0
	 *
	 * @param string $path   Optional. Extra path appended to the end of the URL, including
	 *                       the relative directory if $plugin is supplied. Default empty.
	 * @param string $plugin Optional. A full path to a file inside a plugin or mu-plugin.
	 *                       The URL will be relative to its directory. Default empty.
	 *                       Typically this is done by passing `__FILE__` as the argument.
	 * @return string Plugins URL link with optional paths appended.
	 */
	public function plugins_url( $path = '', $plugin = '' );

	/**
	 * Retrieves the URL to the admin area for either the current site or the network depending on context.
	 *
	 * @since 3.1.0
	 *
	 * @param string $path   Optional. Path relative to the admin URL. Default empty.
	 * @param string $scheme Optional. The scheme to use. Default is 'admin', which obeys force_ssl_admin()
	 *                       and is_ssl(). 'http' or 'https' can be passed to force those schemes.
	 * @return string Admin URL link with optional path appended.
	 */
	public function self_admin_url( $path = '', $scheme = 'admin' );

	/**
	 * Sets the scheme for a URL.
	 *
	 * @since 3.4.0
	 * @since 4.4.0 The 'rest' scheme was added.
	 *
	 * @param string      $url    Absolute URL that includes a scheme
	 * @param string|null $scheme Optional. Scheme to give $url. Currently 'http', 'https', 'login',
	 *                            'login_post', 'admin', 'relative', 'rest', 'rpc', or null. Default null.
	 * @return string URL with chosen scheme.
	 */
	public function set_url_scheme( $url, $scheme = null );

	/**
	 * Retrieves the URL for the current site where WordPress application files
	 * (e.g. wp-blog-header.php or the wp-admin/ folder) are accessible.
	 *
	 * Returns the 'site_url' option with the appropriate protocol, 'https' if
	 * is_ssl() and 'http' otherwise. If $scheme is 'http' or 'https', is_ssl() is
	 * overridden.
	 *
	 * @since 3.0.0
	 *
	 * @param string      $path   Optional. Path relative to the site URL. Default empty.
	 * @param string|null $scheme Optional. Scheme to give the site URL context. See set_url_scheme().
	 * @return string Site URL link with optional path appended.
	 */
	public function site_url( $path = '', $scheme = null );

	/**
	 * Displays the privacy policy link with formatting, when applicable.
	 *
	 * @since 4.9.6
	 *
	 * @param string $before Optional. Display before privacy policy link. Default empty.
	 * @param string $after  Optional. Display after privacy policy link. Default empty.
	 */
	public function the_privacy_policy_link( $before = '', $after = '' );

	/**
	 * Retrieves the URL to the admin area for the current user.
	 *
	 * @since 3.0.0
	 *
	 * @param string $path   Optional. Path relative to the admin URL. Default empty.
	 * @param string $scheme Optional. The scheme to use. Default is 'admin', which obeys force_ssl_admin()
	 *                       and is_ssl(). 'http' or 'https' can be passed to force those schemes.
	 * @return string Admin URL link with optional path appended.
	 */
	public function user_admin_url( $path = '', $scheme = 'admin' );

	/**
	 * Retrieves a trailing-slashed string if the site is set for adding trailing slashes.
	 *
	 * Conditionally adds a trailing slash if the permalink structure has a trailing
	 * slash, strips the trailing slash if not. The string is passed through the
	 * {@see 'user_trailingslashit'} filter. Will remove trailing slash from string, if
	 * site is not set to have them.
	 *
	 * @since 2.2.0
	 *
	 * @global WP_Rewrite $wp_rewrite WordPress rewrite component.
	 *
	 * @param string $url         URL with or without a trailing slash.
	 * @param string $type_of_url Optional. The type of URL being considered (e.g. single, category, etc)
	 *                            for use in the filter. Default empty string.
	 * @return string The URL with the trailing slash appended or stripped.
	 */
	public function user_trailingslashit( $url, $type_of_url = '' );

	/**
	 * Returns an array of URL hosts which are considered to be internal hosts.
	 *
	 * By default the list of internal hosts is comprised of the host name of
	 * the site's home_url() (as parsed by wp_parse_url()).
	 *
	 * This list is used when determining if a specified URL is a link to a page on
	 * the site itself or a link offsite (to an external host). This is used, for
	 * example, when determining if the "nofollow" attribute should be applied to a
	 * link.
	 *
	 * @see wp_is_internal_link
	 *
	 * @since 6.2.0
	 *
	 * @return string[] An array of URL hosts.
	 */
	public function wp_internal_hosts();

	/**
	 * Determines whether or not the specified URL is of a host included in the internal hosts list.
	 *
	 * @see wp_internal_hosts()
	 *
	 * @since 6.2.0
	 *
	 * @param string $link The URL to test.
	 * @return bool Returns true for internal URLs and false for all other URLs.
	 */
	public function wp_is_internal_link( $link );
}
