<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

use WP_Rewrite;

interface Urls {
	/**
	 * Retrieves the URL to the admin area for the current site.
	 *
	 * @since 2.6.0
	 *
	 * @param string $path   Optional. Path relative to the admin URL. Default empty.
	 * @param string $scheme The scheme to use. Default is 'admin', which obeys force_ssl_admin() and is_ssl().
	 *                       'http' or 'https' can be passed to force those schemes.
	 * @return string Admin URL link with optional path appended.
	 */
	public function admin_url( $path = '', $scheme = 'admin' );

	/**
	 * Retrieves the URL to the content directory.
	 *
	 * @since 2.6.0
	 *
	 * @param string $path Optional. Path relative to the content URL. Default empty.
	 * @return string Content URL link with optional path appended.
	 */
	public function content_url( $path = '' );

	/**
	 * Retrieves the URL to the admin area for a given site.
	 *
	 * @since 3.0.0
	 *
	 * @param int|null $blog_id Optional. Site ID. Default null (current site).
	 * @param string   $path    Optional. Path relative to the admin URL. Default empty.
	 * @param string   $scheme  Optional. The scheme to use. Accepts 'http' or 'https',
	 *                          to force those schemes. Default 'admin', which obeys
	 *                          force_ssl_admin() and is_ssl().
	 * @return string Admin URL link with optional path appended.
	 */
	public function get_admin_url( $blog_id = null, $path = '', $scheme = 'admin' );

	/**
	 * Retrieves the URL to the user's dashboard.
	 *
	 * If a user does not belong to any site, the global user dashboard is used. If the user
	 * belongs to the current site, the dashboard for the current site is returned. If the user
	 * cannot edit the current site, the dashboard to the user's primary site is returned.
	 *
	 * @since 3.1.0
	 *
	 * @param int    $user_id Optional. User ID. Defaults to current user.
	 * @param string $path    Optional path relative to the dashboard. Use only paths known to
	 *                        both site and user admins. Default empty.
	 * @param string $scheme  The scheme to use. Default is 'admin', which obeys force_ssl_admin()
	 *                        and is_ssl(). 'http' or 'https' can be passed to force those schemes.
	 * @return string Dashboard URL link with optional path appended.
	 */
	public function get_dashboard_url( $user_id = 0, $path = '', $scheme = 'admin' );

	/**
	 * Retrieves the URL to the user's profile editor.
	 *
	 * @since 3.1.0
	 *
	 * @param int    $user_id Optional. User ID. Defaults to current user.
	 * @param string $scheme  Optional. The scheme to use. Default is 'admin', which obeys force_ssl_admin()
	 *                        and is_ssl(). 'http' or 'https' can be passed to force those schemes.
	 * @return string Dashboard URL link with optional path appended.
	 */
	public function get_edit_profile_url( $user_id = 0, $scheme = 'admin' );

	/**
	 * Retrieves the URL for a given site where the front end is accessible.
	 *
	 * Returns the 'home' option with the appropriate protocol. The protocol will be 'https'
	 * if is_ssl() evaluates to true; otherwise, it will be the same as the 'home' option.
	 * If `$scheme` is 'http' or 'https', is_ssl() is overridden.
	 *
	 * @since 3.0.0
	 *
	 * @param int|null    $blog_id Optional. Site ID. Default null (current site).
	 * @param string      $path    Optional. Path relative to the home URL. Default empty.
	 * @param string|null $scheme  Optional. Scheme to give the home URL context. Accepts
	 *                             'http', 'https', 'relative', 'rest', or null. Default null.
	 * @return string Home URL link with optional path appended.
	 */
	public function get_home_url( $blog_id = null, $path = '', $scheme = null );

	/**
	 * Retrieves the URL to the privacy policy page.
	 *
	 * @since 4.9.6
	 *
	 * @return string The URL to the privacy policy page. Empty string if it doesn't exist.
	 */
	public function get_privacy_policy_url();

	/**
	 * Retrieves the URL for a given site where WordPress application files
	 * (e.g. wp-blog-header.php or the wp-admin/ folder) are accessible.
	 *
	 * Returns the 'site_url' option with the appropriate protocol, 'https' if
	 * is_ssl() and 'http' otherwise. If `$scheme` is 'http' or 'https',
	 * `is_ssl()` is overridden.
	 *
	 * @since 3.0.0
	 *
	 * @param int|null    $blog_id Optional. Site ID. Default null (current site).
	 * @param string      $path    Optional. Path relative to the site URL. Default empty.
	 * @param string|null $scheme  Optional. Scheme to give the site URL context. Accepts
	 *                             'http', 'https', 'login', 'login_post', 'admin', or
	 *                             'relative'. Default null.
	 * @return string Site URL link with optional path appended.
	 */
	public function get_site_url( $blog_id = null, $path = '', $scheme = null );

	/**
	 * Returns the privacy policy link with formatting, when applicable.
	 *
	 * @since 4.9.6
	 * @since 6.2.0 Added 'privacy-policy' rel attribute.
	 *
	 * @param string $before Optional. Display before privacy policy link. Default empty.
	 * @param string $after  Optional. Display after privacy policy link. Default empty.
	 * @return string Markup for the link and surrounding elements. Empty string if it
	 *                doesn't exist.
	 */
	public function get_the_privacy_policy_link( $before = '', $after = '' );

	/**
	 * Retrieves the URL for the current site where the front end is accessible.
	 *
	 * Returns the 'home' option with the appropriate protocol. The protocol will be 'https'
	 * if is_ssl() evaluates to true; otherwise, it will be the same as the 'home' option.
	 * If `$scheme` is 'http' or 'https', is_ssl() is overridden.
	 *
	 * @since 3.0.0
	 *
	 * @param string      $path   Optional. Path relative to the home URL. Default empty.
	 * @param string|null $scheme Optional. Scheme to give the home URL context. Accepts
	 *                            'http', 'https', 'relative', 'rest', or null. Default null.
	 * @return string Home URL link with optional path appended.
	 */
	public function home_url( $path = '', $scheme = null );

	/**
	 * Retrieves the URL to the includes directory.
	 *
	 * @since 2.6.0
	 *
	 * @param string      $path   Optional. Path relative to the includes URL. Default empty.
	 * @param string|null $scheme Optional. Scheme to give the includes URL context. Accepts
	 *                            'http', 'https', or 'relative'. Default null.
	 * @return string Includes URL link with optional path appended.
	 */
	public function includes_url( $path = '', $scheme = null );

	/**
	 * Retrieves the URL to the admin area for the network.
	 *
	 * @since 3.0.0
	 *
	 * @param string $path   Optional path relative to the admin URL. Default empty.
	 * @param string $scheme Optional. The scheme to use. Default is 'admin', which obeys force_ssl_admin()
	 *                       and is_ssl(). 'http' or 'https' can be passed to force those schemes.
	 * @return string Admin URL link with optional path appended.
	 */
	public function network_admin_url( $path = '', $scheme = 'admin' );

	/**
	 * Retrieves the home URL for the current network.
	 *
	 * Returns the home URL with the appropriate protocol, 'https' is_ssl()
	 * and 'http' otherwise. If `$scheme` is 'http' or 'https', `is_ssl()` is
	 * overridden.
	 *
	 * @since 3.0.0
	 *
	 * @param string      $path   Optional. Path relative to the home URL. Default empty.
	 * @param string|null $scheme Optional. Scheme to give the home URL context. Accepts
	 *                            'http', 'https', or 'relative'. Default null.
	 * @return string Home URL link with optional path appended.
	 */
	public function network_home_url( $path = '', $scheme = null );

	/**
	 * Retrieves the site URL for the current network.
	 *
	 * Returns the site URL with the appropriate protocol, 'https' if
	 * is_ssl() and 'http' otherwise. If $scheme is 'http' or 'https', is_ssl() is
	 * overridden.
	 *
	 * @since 3.0.0
	 *
	 * @see set_url_scheme()
	 *
	 * @param string      $path   Optional. Path relative to the site URL. Default empty.
	 * @param string|null $scheme Optional. Scheme to give the site URL context. Accepts
	 *                            'http', 'https', or 'relative'. Default null.
	 * @return string Site URL link with optional path appended.
	 */
	public function network_site_url( $path = '', $scheme = null );

	/**
	 * Retrieves a URL within the plugins or mu-plugins directory.
	 *
	 * Defaults to the plugins directory URL if no arguments are supplied.
	 *
	 * @since 2.6.0
	 *
	 * @param string $path   Optional. Extra path appended to the end of the URL, including
	 *                       the relative directory if $plugin is supplied. Default empty.
	 * @param string $plugin Optional. A full path to a file inside a plugin or mu-plugin.
	 *                       The URL will be relative to its directory. Default empty.
	 *                       Typically this is done by passing `__FILE__` as the argument.
	 * @return string Plugins URL link with optional paths appended.
	 */
	public function plugins_url( $path = '', $plugin = '' );

	/**
	 * Retrieves the URL to the admin area for either the current site or the network depending on context.
	 *
	 * @since 3.1.0
	 *
	 * @param string $path   Optional. Path relative to the admin URL. Default empty.
	 * @param string $scheme Optional. The scheme to use. Default is 'admin', which obeys force_ssl_admin()
	 *                       and is_ssl(). 'http' or 'https' can be passed to force those schemes.
	 * @return string Admin URL link with optional path appended.
	 */
	public function self_admin_url( $path = '', $scheme = 'admin' );

	/**
	 * Sets the scheme for a URL.
	 *
	 * @since 3.4.0
	 * @since 4.4.0 The 'rest' scheme was added.
	 *
	 * @param string      $url    Absolute URL that includes a scheme
	 * @param string|null $scheme Optional. Scheme to give $url. Currently 'http', 'https', 'login',
	 *                            'login_post', 'admin', 'relative', 'rest', 'rpc', or null. Default null.
	 * @return string URL with chosen scheme.
	 */
	public function set_url_scheme( $url, $scheme = null );

	/**
	 * Retrieves the URL for the current site where WordPress application files
	 * (e.g. wp-blog-header.php or the wp-admin/ folder) are accessible.
	 *
	 * Returns the 'site_url' option with the appropriate protocol, 'https' if
	 * is_ssl() and 'http' otherwise. If $scheme is 'http' or 'https', is_ssl() is
	 * overridden.
	 *
	 * @since 3.0.0
	 *
	 * @param string      $path   Optional. Path relative to the site URL. Default empty.
	 * @param string|null $scheme Optional. Scheme to give the site URL context. See set_url_scheme().
	 * @return string Site URL link with optional path appended.
	 */
	public function site_url( $path = '', $scheme = null );

	/**
	 * Displays the privacy policy link with formatting, when applicable.
	 *
	 * @since 4.9.6
	 *
	 * @param string $before Optional. Display before privacy policy link. Default empty.
	 * @param string $after  Optional. Display after privacy policy link. Default empty.
	 */
	public function the_privacy_policy_link( $before = '', $after = '' );

	/**
	 * Retrieves the URL to the admin area for the current user.
	 *
	 * @since 3.0.0
	 *
	 * @param string $path   Optional. Path relative to the admin URL. Default empty.
	 * @param string $scheme Optional. The scheme to use. Default is 'admin', which obeys force_ssl_admin()
	 *                       and is_ssl(). 'http' or 'https' can be passed to force those schemes.
	 * @return string Admin URL link with optional path appended.
	 */
	public function user_admin_url( $path = '', $scheme = 'admin' );

	/**
	 * Retrieves a trailing-slashed string if the site is set for adding trailing slashes.
	 *
	 * Conditionally adds a trailing slash if the permalink structure has a trailing
	 * slash, strips the trailing slash if not. The string is passed through the
	 * {@see 'user_trailingslashit'} filter. Will remove trailing slash from string, if
	 * site is not set to have them.
	 *
	 * @since 2.2.0
	 *
	 * @global WP_Rewrite $wp_rewrite WordPress rewrite component.
	 *
	 * @param string $url         URL with or without a trailing slash.
	 * @param string $type_of_url Optional. The type of URL being considered (e.g. single, category, etc)
	 *                            for use in the filter. Default empty string.
	 * @return string The URL with the trailing slash appended or stripped.
	 */
	public function user_trailingslashit( $url, $type_of_url = '' );

	/**
	 * Returns an array of URL hosts which are considered to be internal hosts.
	 *
	 * By default the list of internal hosts is comprised of the host name of
	 * the site's home_url() (as parsed by wp_parse_url()).
	 *
	 * This list is used when determining if a specified URL is a link to a page on
	 * the site itself or a link offsite (to an external host). This is used, for
	 * example, when determining if the "nofollow" attribute should be applied to a
	 * link.
	 *
	 * @see wp_is_internal_link
	 *
	 * @since 6.2.0
	 *
	 * @return string[] An array of URL hosts.
	 */
	public function wp_internal_hosts();

	/**
	 * Determines whether or not the specified URL is of a host included in the internal hosts list.
	 *
	 * @see wp_internal_hosts()
	 *
	 * @since 6.2.0
	 *
	 * @param string $link The URL to test.
	 * @return bool Returns true for internal URLs and false for all other URLs.
	 */
	public function wp_is_internal_link( $link );

	/**
	 * Determines whether to force SSL on content.
	 *
	 * @since 2.8.5
	 *
	 * @param bool|null $force Optional. Whether to force SSL in admin screens. Default null.
	 * @return bool True if forced, false if not forced.
	 */
	public function force_ssl_content( $force = null );

	/**
	 * Formats a URL to use https.
	 *
	 * Useful as a filter.
	 *
	 * @since 2.8.5
	 *
	 * @param string $url URL.
	 * @return string URL with https as the scheme.
	 */
	public function filter_SSL( $url );

	/**
	 * Retrieves a modified URL query string.
	 *
	 * You can rebuild the URL and append query variables to the URL query by using this function.
	 * There are two ways to use this function; either a single key and value, or an associative array.
	 *
	 * Using a single key and value:
	 *
	 *     add_query_arg( 'key', 'value', 'http://example.com' );
	 *
	 * Using an associative array:
	 *
	 *     add_query_arg( array(
	 *         'key1' => 'value1',
	 *         'key2' => 'value2',
	 *     ), 'http://example.com' );
	 *
	 * Omitting the URL from either use results in the current URL being used
	 * (the value of `$_SERVER['REQUEST_URI']`).
	 *
	 * Values are expected to be encoded appropriately with urlencode() or rawurlencode().
	 *
	 * Setting any query variable's value to boolean false removes the key (see remove_query_arg()).
	 *
	 * Important: The return value of add_query_arg() is not escaped by default. Output should be
	 * late-escaped with esc_url() or similar to help prevent vulnerability to cross-site scripting
	 * (XSS) attacks.
	 *
	 * @since 1.5.0
	 * @since 5.3.0 Formalized the existing and already documented parameters
	 *              by adding `...$args` to the function signature.
	 *
	 * @param string|array $key   Either a query variable key, or an associative array of query variables.
	 * @param string       $value Optional. Either a query variable value, or a URL to act upon.
	 * @param string       $url   Optional. A URL to act upon.
	 * @return string New URL query string (unescaped).
	 */
	public function add_query_arg( ...$args );

	/**
	 * Removes an item or items from a query string.
	 *
	 * Important: The return value of remove_query_arg() is not escaped by default. Output should be
	 * late-escaped with esc_url() or similar to help prevent vulnerability to cross-site scripting
	 * (XSS) attacks.
	 *
	 * @since 1.5.0
	 *
	 * @param string|string[] $key   Query key or keys to remove.
	 * @param false|string    $query Optional. When false uses the current URL. Default false.
	 * @return string New URL query string.
	 */
	public function remove_query_arg( $key, $query = false );

	/**
	 * Builds a URL query based on an associative or indexed array.
	 *
	 * This is a convenient function for easily building URL queries.
	 * It sets the separator to '&' and uses the _http_build_query() function.
	 *
	 * Unlike PHP's native http_build_query(), this function does NOT URL-encode
	 * the keys or values. Callers are responsible for encoding values beforehand
	 * with urlencode() or rawurlencode(), or late-escaping the output with
	 * esc_url() before use.
	 *
	 * @since 2.3.0
	 *
	 * @see _http_build_query() Used to build the query.
	 * @link https://www.php.net/manual/en/function.http-build-query.php for more on what
	 *       http_build_query() does.
	 *
	 * @param array $data Array of key/value pairs to build the query from.
	 * @return string Query string, without URL encoding applied.
	 */
	public function build_query( $data );

	/**
	 * Returns an array of single-use query variable names that can be removed from a URL.
	 *
	 * @since 4.4.0
	 *
	 * @return string[] An array of query variable names to remove from the URL.
	 */
	public function wp_removable_query_args();

	/**
	 * Uses RegEx to extract URLs from arbitrary content.
	 *
	 * @since 3.7.0
	 * @since 6.0.0 Fixes support for HTML entities (Trac 30580).
	 *
	 * @param string $content Content to extract URLs from.
	 * @return string[] Array of URLs found in passed string.
	 */
	public function wp_extract_urls( $content );

	/**
	 * Retrieves a list of protocols to allow in HTML attributes.
	 *
	 * @since 3.3.0
	 * @since 4.3.0 Added 'webcal' to the protocols array.
	 * @since 4.7.0 Added 'urn' to the protocols array.
	 * @since 5.3.0 Added 'sms' to the protocols array.
	 * @since 5.6.0 Added 'irc6' and 'ircs' to the protocols array.
	 *
	 * @see wp_kses()
	 * @see esc_url()
	 *
	 * @return string[] Array of allowed protocols. Defaults to an array containing 'http', 'https',
	 *                  'ftp', 'ftps', 'mailto', 'news', 'irc', 'irc6', 'ircs', 'gopher', 'nntp', 'feed',
	 *                  'telnet', 'mms', 'rtsp', 'sms', 'svn', 'tel', 'fax', 'xmpp', 'webcal', and 'urn'.
	 *                  This covers all common link protocols, except for 'javascript' which should not
	 *                  be allowed for untrusted users.
	 */
	public function wp_allowed_protocols();

	/**
	 * Guesses the URL for the site.
	 *
	 * Will remove wp-admin links to retrieve only return URLs not in the wp-admin
	 * directory.
	 *
	 * @since 2.6.0
	 *
	 * @return string The guessed URL.
	 */
	public function wp_guess_url();

	/**
	 * A wrapper for PHP's parse_url() function that handles consistency in the return values
	 * across PHP versions.
	 *
	 * Across various PHP versions, schemeless URLs containing a ":" in the query
	 * are being handled inconsistently. This function works around those differences.
	 *
	 * @since 4.4.0
	 * @since 4.7.0 The `$component` parameter was added for parity with PHP's `parse_url()`.
	 *
	 * @link https://www.php.net/manual/en/function.parse-url.php
	 *
	 * @param string $url       The URL to parse.
	 * @param int    $component The specific component to retrieve. Use one of the PHP
	 *                          predefined constants to specify which one.
	 *                          Defaults to -1 (= return all parts as an array).
	 * @return mixed False on parse failure; Array of URL components on success;
	 *               When a specific component has been requested: null if the component
	 *               doesn't exist in the given URL; a string or - in the case of
	 *               PHP_URL_PORT - integer when it does. See parse_url()'s return values.
	 *
	 * @phpstan-param int<-1, 7> $component
	 * @phpstan-return (
	 *     $component is -1
	 *         ? false|array{
	 *               scheme?: string,
	 *               host?: string,
	 *               port?: int<0, 65535>,
	 *               user?: string,
	 *               pass?: string,
	 *               path?: string,
	 *               query?: string,
	 *               fragment?: string,
	 *           }
	 *         : (
	 *             $component is 2
	 *                 ? int<0, 65535>|null
	 *                 : string|null
	 *         )
	 * )
	 */
	public function wp_parse_url( $url, $component = -1 );

	/**
	 * Strips the #fragment from a URL, if one is present.
	 *
	 * @since 4.4.0
	 *
	 * @param string $url The URL to strip.
	 * @return string The altered URL.
	 */
	public function strip_fragment_from_url( $url );

	/**
	 * Converts full URL paths to absolute paths.
	 *
	 * Removes the http or https protocols and the domain. Keeps the path '/' at the
	 * beginning, so it isn't a true relative link, but from the web root base.
	 *
	 * @since 2.1.0
	 * @since 4.1.0 Support was added for relative URLs.
	 *
	 * @param string $link Full URL path.
	 * @return string Absolute path.
	 */
	public function wp_make_link_relative( $link );

	/**
	 * Shortens a URL, to be used as link text.
	 *
	 * @since 1.2.0
	 * @since 4.4.0 Moved to wp-includes/formatting.php from wp-admin/includes/misc.php and added $length param.
	 *
	 * @param string $url    URL to shorten.
	 * @param int    $length Optional. Maximum length of the shortened URL. Default 35 characters.
	 * @return string Shortened URL.
	 */
	public function url_shorten( $url, $length = 35 );

	/**
	 * Encodes the Unicode values to be used in the URI.
	 *
	 * @since 1.5.0
	 * @since 5.8.3 Added the `encode_ascii_characters` parameter.
	 *
	 * @param string $utf8_string             String to encode.
	 * @param int    $length                  Max length of the string.
	 * @param bool   $encode_ascii_characters Whether to encode ascii characters such as < " '
	 * @return string String with Unicode encoded for URI.
	 */
	public function utf8_uri_encode( $utf8_string, $length = 0, $encode_ascii_characters = false );

	/**
	 * Parses a string into variables to be stored in an array.
	 *
	 * @since 2.2.1
	 *
	 * @param string $input_string The string to be parsed.
	 * @param array  $result       Variables will be stored in this array.
	 */
	public function wp_parse_str( $input_string, &$result );
}
