<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpAbilities implements Abilities {
	/**
	 * @inheritDoc
	 */
	public function wp_register_ability( string $name, array $args ): ?\WP_Ability {
		return wp_register_ability( $name, $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_unregister_ability( string $name ): ?\WP_Ability {
		return wp_unregister_ability( $name );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_has_ability( string $name ): bool {
		return wp_has_ability( $name );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_ability( string $name ): ?\WP_Ability {
		return wp_get_ability( $name );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_abilities( array $args = array() ): array {
		return wp_get_abilities( $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_register_ability_category( string $slug, array $args ): ?\WP_Ability_Category {
		return wp_register_ability_category( $slug, $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_unregister_ability_category( string $slug ): ?\WP_Ability_Category {
		return wp_unregister_ability_category( $slug );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_has_ability_category( string $slug ): bool {
		return wp_has_ability_category( $slug );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_ability_category( string $slug ): ?\WP_Ability_Category {
		return wp_get_ability_category( $slug );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_ability_categories(): array {
		return wp_get_ability_categories();
	}
}
