<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpAdminBar implements AdminBar {
	/**
	 * @inheritDoc
	 */
	public function is_admin_bar_showing() {
		return is_admin_bar_showing();
	}

	/**
	 * @inheritDoc
	 */
	public function show_admin_bar( $show ) {
		show_admin_bar( $show );
	}
}
