<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpAdminPosts implements AdminPosts {
	/**
	 * @inheritDoc
	 */
	public function post_exists( $title, $content = '', $date = '', $type = '', $status = '' ) {
		return post_exists( $title, $content, $date, $type, $status );
	}

	/**
	 * @inheritDoc
	 */
	public function get_default_post_to_edit( $post_type = 'post', $create_in_db = false ) {
		return get_default_post_to_edit( $post_type, $create_in_db );
	}

	/**
	 * @inheritDoc
	 */
	public function get_available_post_statuses( $type = 'post' ) {
		return get_available_post_statuses( $type );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_write_post() {
		return wp_write_post();
	}

	/**
	 * @inheritDoc
	 */
	public function write_post() {
		return write_post();
	}

	/**
	 * @inheritDoc
	 */
	public function edit_post( $post_data = null ) {
		return edit_post( $post_data );
	}

	/**
	 * @inheritDoc
	 */
	public function bulk_edit_posts( $post_data = null ) {
		return bulk_edit_posts( $post_data );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_create_post_autosave( $post_data ) {
		return wp_create_post_autosave( $post_data );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_autosave( $post_data ) {
		return wp_autosave( $post_data );
	}

	/**
	 * @inheritDoc
	 */
	public function post_preview() {
		return post_preview();
	}

	/**
	 * @inheritDoc
	 */
	public function redirect_post( $post_id = 0 ) {
		redirect_post( $post_id );
	}

	/**
	 * @inheritDoc
	 */
	public function get_sample_permalink( $post, $title = null, $name = null ) {
		return get_sample_permalink( $post, $title, $name );
	}

	/**
	 * @inheritDoc
	 */
	public function get_sample_permalink_html( $post, $new_title = null, $new_slug = null ) {
		return get_sample_permalink_html( $post, $new_title, $new_slug );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_check_post_lock( $post ) {
		return wp_check_post_lock( $post );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_set_post_lock( $post ) {
		return wp_set_post_lock( $post );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_edit_posts_query( $q = false ) {
		return wp_edit_posts_query( $q );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_edit_attachments_query_vars( $q = false ) {
		return wp_edit_attachments_query_vars( $q );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_edit_attachments_query( $q = false ) {
		return wp_edit_attachments_query( $q );
	}
}
