<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpBlockEditor implements BlockEditor {
	/**
	 * @inheritDoc
	 */
	public function get_block_editor_settings( array $custom_settings, $block_editor_context ) {
		return get_block_editor_settings( $custom_settings, $block_editor_context );
	}

	/**
	 * @inheritDoc
	 */
	public function get_default_block_editor_settings() {
		return get_default_block_editor_settings();
	}

	/**
	 * @inheritDoc
	 */
	public function get_classic_theme_supports_block_editor_settings() {
		return get_classic_theme_supports_block_editor_settings();
	}

	/**
	 * @inheritDoc
	 */
	public function get_legacy_widget_block_editor_settings() {
		return get_legacy_widget_block_editor_settings();
	}

	/**
	 * @inheritDoc
	 */
	public function get_block_editor_theme_styles() {
		return get_block_editor_theme_styles();
	}

	/**
	 * @inheritDoc
	 */
	public function get_allowed_block_types( $block_editor_context ) {
		return get_allowed_block_types( $block_editor_context );
	}

	/**
	 * @inheritDoc
	 */
	public function get_block_categories( $post_or_block_editor_context ) {
		return get_block_categories( $post_or_block_editor_context );
	}

	/**
	 * @inheritDoc
	 */
	public function get_default_block_categories() {
		return get_default_block_categories();
	}

	/**
	 * @inheritDoc
	 */
	public function block_editor_rest_api_preload( array $preload_paths, $block_editor_context ) {
		block_editor_rest_api_preload( $preload_paths, $block_editor_context );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_entity_view_config( $kind, $name ) {
		return wp_get_entity_view_config( $kind, $name );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_entity_view_config_hook_name( $kind, $name ) {
		return wp_get_entity_view_config_hook_name( $kind, $name );
	}
}
