<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpConnectors implements Connectors {
	/**
	 * @inheritDoc
	 */
	public function wp_is_connector_registered( string $id ): bool {
		return wp_is_connector_registered( $id );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_connector( string $id ): ?array {
		return wp_get_connector( $id );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_connectors(): array {
		return wp_get_connectors();
	}
}
