<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpDocumentHead implements DocumentHead {
	/**
	 * @inheritDoc
	 */
	public function adjacent_posts_rel_link_wp_head() {
		adjacent_posts_rel_link_wp_head();
	}

	/**
	 * @inheritDoc
	 */
	public function get_the_generator( $type = '' ) {
		return get_the_generator( $type );
	}

	/**
	 * @inheritDoc
	 */
	public function rel_canonical() {
		rel_canonical();
	}

	/**
	 * @inheritDoc
	 */
	public function rsd_link() {
		rsd_link();
	}

	/**
	 * @inheritDoc
	 */
	public function the_generator( $type ) {
		the_generator( $type );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_body_open() {
		wp_body_open();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_dependencies_unique_hosts() {
		return wp_dependencies_unique_hosts();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_footer() {
		wp_footer();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_generator() {
		wp_generator();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_document_title() {
		return wp_get_document_title();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_head() {
		wp_head();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_meta() {
		wp_meta();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_preload_resources() {
		wp_preload_resources();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_resource_hints() {
		wp_resource_hints();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_robots() {
		wp_robots();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_robots_max_image_preview_large( array $robots ) {
		return wp_robots_max_image_preview_large( $robots );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_robots_no_robots( array $robots ) {
		return wp_robots_no_robots( $robots );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_robots_noindex( array $robots ) {
		return wp_robots_noindex( $robots );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_robots_noindex_embeds( array $robots ) {
		return wp_robots_noindex_embeds( $robots );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_robots_noindex_search( array $robots ) {
		return wp_robots_noindex_search( $robots );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_robots_sensitive_page( array $robots ) {
		return wp_robots_sensitive_page( $robots );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_shortlink_header() {
		wp_shortlink_header();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_shortlink_wp_head() {
		wp_shortlink_wp_head();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_strict_cross_origin_referrer() {
		wp_strict_cross_origin_referrer();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_title( $sep = '&raquo;', $display = true, $seplocation = '' ) {
		return wp_title( $sep, $display, $seplocation );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_speculation_rules_configuration(): ?array {
		return wp_get_speculation_rules_configuration();
	}
}
