<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpEditor implements Editor {
	/**
	 * @inheritDoc
	 */
	public function user_can_richedit() {
		return user_can_richedit();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_default_editor() {
		return wp_default_editor();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_editor( $content, $editor_id, $settings = array() ) {
		wp_editor( $content, $editor_id, $settings );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_enqueue_code_editor( $args ) {
		return wp_enqueue_code_editor( $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_enqueue_editor() {
		wp_enqueue_editor();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_code_editor_settings( $args ) {
		return wp_get_code_editor_settings( $args );
	}

	/**
	 * @inheritDoc
	 */
	public function get_block_editor_server_block_settings() {
		return get_block_editor_server_block_settings();
	}

	/**
	 * @inheritDoc
	 */
	public function use_block_editor_for_post( $post ) {
		return use_block_editor_for_post( $post );
	}

	/**
	 * @inheritDoc
	 */
	public function use_block_editor_for_post_type( $post_type ) {
		return use_block_editor_for_post_type( $post_type );
	}
}
