<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpErrors implements Errors {
	/**
	 * @inheritDoc
	 */
	public function is_wp_error( $thing ) {
		return is_wp_error( $thing );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_die( $message = '', $title = '', $args = array() ) {
		wp_die( $message, $title, $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_trigger_error( $function_name, $message, $error_level = E_USER_NOTICE ) {
		wp_trigger_error( $function_name, $message, $error_level );
	}

	/**
	 * @inheritDoc
	 */
	public function dead_db() {
		dead_db();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_debug_backtrace_summary( $ignore_class = null, $skip_frames = 0, $pretty = true ) {
		return wp_debug_backtrace_summary( $ignore_class, $skip_frames, $pretty );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_is_fatal_error_handler_enabled() {
		return wp_is_fatal_error_handler_enabled();
	}

	/**
	 * @inheritDoc
	 */
	public function is_protected_endpoint() {
		return is_protected_endpoint();
	}

	/**
	 * @inheritDoc
	 */
	public function is_protected_ajax_action() {
		return is_protected_ajax_action();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_is_recovery_mode() {
		return wp_is_recovery_mode();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_recovery_mode() {
		return wp_recovery_mode();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_paused_plugins() {
		return wp_paused_plugins();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_paused_themes() {
		return wp_paused_themes();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_extension_error_description( $error ) {
		return wp_get_extension_error_description( $error );
	}
}
