<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpEscaping implements Escaping {
	/**
	 * @inheritDoc
	 */
	public function esc_html( $text ) {
		return esc_html( $text );
	}

	/**
	 * @inheritDoc
	 */
	public function esc_attr( $text ) {
		return esc_attr( $text );
	}

	/**
	 * @inheritDoc
	 */
	public function esc_textarea( $text ) {
		return esc_textarea( $text );
	}

	/**
	 * @inheritDoc
	 */
	public function esc_js( $text ) {
		return esc_js( $text );
	}

	/**
	 * @inheritDoc
	 */
	public function esc_xml( $text ) {
		return esc_xml( $text );
	}

	/**
	 * @inheritDoc
	 */
	public function esc_url( $url, $protocols = null, $_context = 'display' ) {
		return esc_url( $url, $protocols, $_context );
	}

	/**
	 * @inheritDoc
	 */
	public function esc_url_raw( $url, $protocols = null ) {
		return esc_url_raw( $url, $protocols );
	}

	/**
	 * @inheritDoc
	 */
	public function esc_sql( $data ) {
		return esc_sql( $data );
	}

	/**
	 * @inheritDoc
	 */
	public function tag_escape( $tag_name ) {
		return tag_escape( $tag_name );
	}
}
