<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpFileEditor implements FileEditor {
	/**
	 * @inheritDoc
	 */
	public function validate_file_to_edit( $file, $allowed_files = array() ) {
		return validate_file_to_edit( $file, $allowed_files );
	}

	/**
	 * @inheritDoc
	 */
	public function get_file_description( $file ) {
		return get_file_description( $file );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_edit_theme_plugin_file( $args ) {
		return wp_edit_theme_plugin_file( $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_plugin_file_editable_extensions( $plugin ) {
		return wp_get_plugin_file_editable_extensions( $plugin );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_theme_file_editable_extensions( $theme ) {
		return wp_get_theme_file_editable_extensions( $theme );
	}

	/**
	 * @inheritDoc
	 */
	public function update_recently_edited( $file ) {
		update_recently_edited( $file );
	}
}
