<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpHttp implements Http {
	/**
	 * @inheritDoc
	 */
	public function status_header( $code, $description = '' ) {
		status_header( $code, $description );
	}

	/**
	 * @inheritDoc
	 */
	public function get_status_header_desc( $code ) {
		return get_status_header_desc( $code );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_server_protocol() {
		return wp_get_server_protocol();
	}

	/**
	 * @inheritDoc
	 */
	public function nocache_headers() {
		nocache_headers();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_nocache_headers() {
		return wp_get_nocache_headers();
	}

	/**
	 * @inheritDoc
	 */
	public function cache_javascript_headers() {
		cache_javascript_headers();
	}

	/**
	 * @inheritDoc
	 */
	public function send_nosniff_header() {
		send_nosniff_header();
	}

	/**
	 * @inheritDoc
	 */
	public function send_frame_options_header() {
		send_frame_options_header();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_http_headers( $url, $deprecated = false ) {
		return wp_get_http_headers( $url, $deprecated );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_remote_fopen( $uri ) {
		return wp_remote_fopen( $uri );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_remote_request( $url, $args = array() ) {
		return wp_remote_request( $url, $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_remote_get( $url, $args = array() ) {
		return wp_remote_get( $url, $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_remote_post( $url, $args = array() ) {
		return wp_remote_post( $url, $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_remote_head( $url, $args = array() ) {
		return wp_remote_head( $url, $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_safe_remote_request( $url, $args = array() ) {
		return wp_safe_remote_request( $url, $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_safe_remote_get( $url, $args = array() ) {
		return wp_safe_remote_get( $url, $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_safe_remote_post( $url, $args = array() ) {
		return wp_safe_remote_post( $url, $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_safe_remote_head( $url, $args = array() ) {
		return wp_safe_remote_head( $url, $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_remote_retrieve_headers( $response ) {
		return wp_remote_retrieve_headers( $response );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_remote_retrieve_header( $response, $header ) {
		return wp_remote_retrieve_header( $response, $header );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_remote_retrieve_response_code( $response ) {
		return wp_remote_retrieve_response_code( $response );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_remote_retrieve_response_message( $response ) {
		return wp_remote_retrieve_response_message( $response );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_remote_retrieve_body( $response ) {
		return wp_remote_retrieve_body( $response );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_remote_retrieve_cookies( $response ) {
		return wp_remote_retrieve_cookies( $response );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_remote_retrieve_cookie( $response, $name ) {
		return wp_remote_retrieve_cookie( $response, $name );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_remote_retrieve_cookie_value( $response, $name ) {
		return wp_remote_retrieve_cookie_value( $response, $name );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_http_supports( $capabilities = array(), $url = null ) {
		return wp_http_supports( $capabilities, $url );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_http_validate_url( $url ) {
		return wp_http_validate_url( $url );
	}

	/**
	 * @inheritDoc
	 */
	public function get_http_origin() {
		return get_http_origin();
	}

	/**
	 * @inheritDoc
	 */
	public function get_allowed_http_origins() {
		return get_allowed_http_origins();
	}

	/**
	 * @inheritDoc
	 */
	public function is_allowed_http_origin( $origin = null ) {
		return is_allowed_http_origin( $origin );
	}

	/**
	 * @inheritDoc
	 */
	public function send_origin_headers() {
		return send_origin_headers();
	}
}
