<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpKses implements Kses {
	/**
	 * @inheritDoc
	 */
	public function wp_kses( $content, $allowed_html, $allowed_protocols = array() ) {
		return wp_kses( $content, $allowed_html, $allowed_protocols );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_post( $data ) {
		return wp_kses_post( $data );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_post_deep( $data ) {
		return wp_kses_post_deep( $data );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_data( $data ) {
		return wp_kses_data( $data );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_allowed_html( $context = '' ) {
		return wp_kses_allowed_html( $context );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_uri_attributes() {
		return wp_kses_uri_attributes();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_filter_kses( $data ) {
		return wp_filter_kses( $data );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_filter_post_kses( $data ) {
		return wp_filter_post_kses( $data );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_filter_nohtml_kses( $data ) {
		return wp_filter_nohtml_kses( $data );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_filter_global_styles_post( $data ) {
		return wp_filter_global_styles_post( $data );
	}

	/**
	 * @inheritDoc
	 */
	public function kses_init() {
		kses_init();
	}

	/**
	 * @inheritDoc
	 */
	public function kses_init_filters() {
		kses_init_filters();
	}

	/**
	 * @inheritDoc
	 */
	public function kses_remove_filters() {
		kses_remove_filters();
	}

	/**
	 * @inheritDoc
	 */
	public function safecss_filter_attr( $css, $deprecated = '' ) {
		return safecss_filter_attr( $css, $deprecated );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_hook( $content, $allowed_html, $allowed_protocols ) {
		return wp_kses_hook( $content, $allowed_html, $allowed_protocols );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_version() {
		return wp_kses_version();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_split( $content, $allowed_html, $allowed_protocols ) {
		return wp_kses_split( $content, $allowed_html, $allowed_protocols );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_attr( $element, $attr, $allowed_html, $allowed_protocols ) {
		return wp_kses_attr( $element, $attr, $allowed_html, $allowed_protocols );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_attr_check( &$name, &$value, &$whole, $vless, $element, $allowed_html ) {
		return wp_kses_attr_check( $name, $value, $whole, $vless, $element, $allowed_html );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_one_attr( $attr, $element ) {
		return wp_kses_one_attr( $attr, $element );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_hair( $attr, $allowed_protocols ) {
		return wp_kses_hair( $attr, $allowed_protocols );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_hair_parse( $attr ) {
		return wp_kses_hair_parse( $attr );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_attr_parse( $element ) {
		return wp_kses_attr_parse( $element );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_check_attr_val( $value, $vless, $checkname, $checkvalue ) {
		return wp_kses_check_attr_val( $value, $vless, $checkname, $checkvalue );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_bad_protocol( $content, $allowed_protocols ) {
		return wp_kses_bad_protocol( $content, $allowed_protocols );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_bad_protocol_once( $content, $allowed_protocols, $count = 1 ) {
		return wp_kses_bad_protocol_once( $content, $allowed_protocols, $count );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_no_null( $content, $options = null ) {
		return wp_kses_no_null( $content, $options );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_stripslashes( $content ) {
		return wp_kses_stripslashes( $content );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_array_lc( $inarray ) {
		return wp_kses_array_lc( $inarray );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_normalize_entities( $content, $context = 'html' ) {
		return wp_kses_normalize_entities( $content, $context );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_kses_decode_entities( $content ) {
		return wp_kses_decode_entities( $content );
	}

	/**
	 * @inheritDoc
	 */
	public function valid_unicode( $i ) {
		return valid_unicode( $i );
	}
}
