<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpLogin implements Login {
	/**
	 * @inheritDoc
	 */
	public function wp_login_form( $args = array() ) {
		return wp_login_form( $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_login_url( $redirect = '', $force_reauth = false ) {
		return wp_login_url( $redirect, $force_reauth );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_loginout( $redirect = '', $display = true ) {
		return wp_loginout( $redirect, $display );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_logout_url( $redirect = '' ) {
		return wp_logout_url( $redirect );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_lostpassword_url( $redirect = '' ) {
		return wp_lostpassword_url( $redirect );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_register( $before = '<li>', $after = '</li>', $display = true ) {
		return wp_register( $before, $after, $display );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_registration_url() {
		return wp_registration_url();
	}
}
