<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpMedia implements Media {
	/**
	 * @inheritDoc
	 */
	public function add_image_size( $name, $width = 0, $height = 0, $crop = false ) {
		add_image_size( $name, $width, $height, $crop );
	}

	/**
	 * @inheritDoc
	 */
	public function has_image_size( $name ) {
		return has_image_size( $name );
	}

	/**
	 * @inheritDoc
	 */
	public function remove_image_size( $name ) {
		return remove_image_size( $name );
	}

	/**
	 * @inheritDoc
	 */
	public function get_intermediate_image_sizes() {
		return get_intermediate_image_sizes();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_additional_image_sizes() {
		return wp_get_additional_image_sizes();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_registered_image_subsizes(): array {
		return wp_get_registered_image_subsizes();
	}

	/**
	 * @inheritDoc
	 */
	public function image_downsize( $id, $size = 'medium' ) {
		return image_downsize( $id, $size );
	}

	/**
	 * @inheritDoc
	 */
	public function image_get_intermediate_size( $post_id, $size = 'thumbnail' ) {
		return image_get_intermediate_size( $post_id, $size );
	}

	/**
	 * @inheritDoc
	 */
	public function image_constrain_size_for_editor( $width, $height, $size = 'medium', $context = null ) {
		return image_constrain_size_for_editor( $width, $height, $size, $context );
	}

	/**
	 * @inheritDoc
	 */
	public function image_hwstring( $width, $height ) {
		return image_hwstring( $width, $height );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_constrain_dimensions( $current_width, $current_height, $max_width = 0, $max_height = 0 ) {
		return wp_constrain_dimensions( $current_width, $current_height, $max_width, $max_height );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_expand_dimensions( $example_width, $example_height, $max_width, $max_height ) {
		return wp_expand_dimensions( $example_width, $example_height, $max_width, $max_height );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_image_matches_ratio( $source_width, $source_height, $target_width, $target_height ) {
		return wp_image_matches_ratio( $source_width, $source_height, $target_width, $target_height );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_image_src_get_dimensions( $image_src, $image_meta, $attachment_id = 0 ) {
		return wp_image_src_get_dimensions( $image_src, $image_meta, $attachment_id );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_image_file_matches_image_meta( $image_location, $image_meta, $attachment_id = 0 ) {
		return wp_image_file_matches_image_meta( $image_location, $image_meta, $attachment_id );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_attachment_image_src( $attachment_id, $size = 'thumbnail', $icon = false ) {
		return wp_get_attachment_image_src( $attachment_id, $size, $icon );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_attachment_image_url( $attachment_id, $size = 'thumbnail', $icon = false ) {
		return wp_get_attachment_image_url( $attachment_id, $size, $icon );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_attachment_image_srcset( $attachment_id, $size = 'medium', $image_meta = null ) {
		return wp_get_attachment_image_srcset( $attachment_id, $size, $image_meta );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_attachment_image_sizes( $attachment_id, $size = 'medium', $image_meta = null ) {
		return wp_get_attachment_image_sizes( $attachment_id, $size, $image_meta );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_calculate_image_srcset( $size_array, $image_src, $image_meta, $attachment_id = 0 ) {
		return wp_calculate_image_srcset( $size_array, $image_src, $image_meta, $attachment_id );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_calculate_image_sizes( $size, $image_src = null, $image_meta = null, $attachment_id = 0 ) {
		return wp_calculate_image_sizes( $size, $image_src, $image_meta, $attachment_id );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_sizes_attribute_includes_valid_auto( string $sizes_attr ): bool {
		return wp_sizes_attribute_includes_valid_auto( $sizes_attr );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_loading_optimization_attributes( $tag_name, $attr, $context ) {
		return wp_get_loading_optimization_attributes( $tag_name, $attr, $context );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_lazy_loading_enabled( $tag_name, $context ) {
		return wp_lazy_loading_enabled( $tag_name, $context );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_omit_loading_attr_threshold( $force = false ) {
		return wp_omit_loading_attr_threshold( $force );
	}

	/**
	 * @inheritDoc
	 */
	public function get_media_embedded_in_content( $content, $types = null ) {
		return get_media_embedded_in_content( $content, $types );
	}

	/**
	 * @inheritDoc
	 */
	public function get_post_galleries( $post, $html = true ) {
		return get_post_galleries( $post, $html );
	}

	/**
	 * @inheritDoc
	 */
	public function get_post_gallery( $post = 0, $html = true ) {
		return get_post_gallery( $post, $html );
	}

	/**
	 * @inheritDoc
	 */
	public function get_post_galleries_images( $post = 0 ) {
		return get_post_galleries_images( $post );
	}

	/**
	 * @inheritDoc
	 */
	public function get_post_gallery_images( $post = 0 ) {
		return get_post_gallery_images( $post );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_max_upload_size() {
		return wp_max_upload_size();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_audio_extensions() {
		return wp_get_audio_extensions();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_video_extensions() {
		return wp_get_video_extensions();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_enqueue_media( $args = array() ) {
		wp_enqueue_media( $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_plupload_default_settings() {
		wp_plupload_default_settings();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_is_client_side_media_processing_enabled(): bool {
		return wp_is_client_side_media_processing_enabled();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_chromium_major_version(): ?int {
		return wp_get_chromium_major_version();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_add_crossorigin_attributes( string $html ): string {
		return wp_add_crossorigin_attributes( $html );
	}
}
