<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpMeta implements Meta {
	/**
	 * @inheritDoc
	 */
	public function get_metadata( $meta_type, $object_id, $meta_key = '', $single = false ) {
		return get_metadata( $meta_type, $object_id, $meta_key, $single );
	}

	/**
	 * @inheritDoc
	 */
	public function get_metadata_raw( $meta_type, $object_id, $meta_key = '', $single = false ) {
		return get_metadata_raw( $meta_type, $object_id, $meta_key, $single );
	}

	/**
	 * @inheritDoc
	 */
	public function get_metadata_default( $meta_type, $object_id, $meta_key, $single = false ) {
		return get_metadata_default( $meta_type, $object_id, $meta_key, $single );
	}

	/**
	 * @inheritDoc
	 */
	public function add_metadata( $meta_type, $object_id, $meta_key, $meta_value, $unique = false ) {
		return add_metadata( $meta_type, $object_id, $meta_key, $meta_value, $unique );
	}

	/**
	 * @inheritDoc
	 */
	public function update_metadata( $meta_type, $object_id, $meta_key, $meta_value, $prev_value = '' ) {
		return update_metadata( $meta_type, $object_id, $meta_key, $meta_value, $prev_value );
	}

	/**
	 * @inheritDoc
	 */
	public function delete_metadata( $meta_type, $object_id, $meta_key, $meta_value = '', $delete_all = false ) {
		return delete_metadata( $meta_type, $object_id, $meta_key, $meta_value, $delete_all );
	}

	/**
	 * @inheritDoc
	 */
	public function metadata_exists( $meta_type, $object_id, $meta_key ) {
		return metadata_exists( $meta_type, $object_id, $meta_key );
	}

	/**
	 * @inheritDoc
	 */
	public function get_metadata_by_mid( $meta_type, $meta_id ) {
		return get_metadata_by_mid( $meta_type, $meta_id );
	}

	/**
	 * @inheritDoc
	 */
	public function update_metadata_by_mid( $meta_type, $meta_id, $meta_value, $meta_key = false ) {
		return update_metadata_by_mid( $meta_type, $meta_id, $meta_value, $meta_key );
	}

	/**
	 * @inheritDoc
	 */
	public function delete_metadata_by_mid( $meta_type, $meta_id ) {
		return delete_metadata_by_mid( $meta_type, $meta_id );
	}

	/**
	 * @inheritDoc
	 */
	public function update_meta_cache( $meta_type, $object_ids ) {
		return update_meta_cache( $meta_type, $object_ids );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_metadata_lazyloader() {
		return wp_metadata_lazyloader();
	}

	/**
	 * @inheritDoc
	 */
	public function get_meta_sql( $meta_query, $type, $primary_table, $primary_id_column, $context = null ) {
		return get_meta_sql( $meta_query, $type, $primary_table, $primary_id_column, $context );
	}

	/**
	 * @inheritDoc
	 */
	public function is_protected_meta( $meta_key, $meta_type = '' ) {
		return is_protected_meta( $meta_key, $meta_type );
	}

	/**
	 * @inheritDoc
	 */
	public function sanitize_meta( $meta_key, $meta_value, $object_type, $object_subtype = '' ) {
		return sanitize_meta( $meta_key, $meta_value, $object_type, $object_subtype );
	}

	/**
	 * @inheritDoc
	 */
	public function register_meta( $object_type, $meta_key, $args, $deprecated = null ) {
		return register_meta( $object_type, $meta_key, $args, $deprecated );
	}

	/**
	 * @inheritDoc
	 */
	public function unregister_meta_key( $object_type, $meta_key, $object_subtype = '' ) {
		return unregister_meta_key( $object_type, $meta_key, $object_subtype );
	}

	/**
	 * @inheritDoc
	 */
	public function registered_meta_key_exists( $object_type, $meta_key, $object_subtype = '' ) {
		return registered_meta_key_exists( $object_type, $meta_key, $object_subtype );
	}

	/**
	 * @inheritDoc
	 */
	public function get_registered_meta_keys( $object_type, $object_subtype = '' ) {
		return get_registered_meta_keys( $object_type, $object_subtype );
	}

	/**
	 * @inheritDoc
	 */
	public function get_registered_metadata( $object_type, $object_id, $meta_key = '' ) {
		return get_registered_metadata( $object_type, $object_id, $meta_key );
	}

	/**
	 * @inheritDoc
	 */
	public function get_object_subtype( $object_type, $object_id ) {
		return get_object_subtype( $object_type, $object_id );
	}
}
