<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpMetaBoxes implements MetaBoxes {
	/**
	 * @inheritDoc
	 */
	public function add_meta_box( $id, $title, $callback, $screen = null, $context = 'advanced', $priority = 'default', $callback_args = null ) {
		add_meta_box( $id, $title, $callback, $screen, $context, $priority, $callback_args );
	}

	/**
	 * @inheritDoc
	 */
	public function do_accordion_sections( $screen, $context, $data_object ) {
		return do_accordion_sections( $screen, $context, $data_object );
	}

	/**
	 * @inheritDoc
	 */
	public function do_block_editor_incompatible_meta_box( $data_object, $box ) {
		do_block_editor_incompatible_meta_box( $data_object, $box );
	}

	/**
	 * @inheritDoc
	 */
	public function do_meta_boxes( $screen, $context, $data_object ) {
		return do_meta_boxes( $screen, $context, $data_object );
	}

	/**
	 * @inheritDoc
	 */
	public function remove_meta_box( $id, $screen, $context ) {
		remove_meta_box( $id, $screen, $context );
	}

	/**
	 * @inheritDoc
	 */
	public function postbox_classes( $box_id, $screen_id ) {
		return postbox_classes( $box_id, $screen_id );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_add_dashboard_widget( $widget_id, $widget_name, $callback, $control_callback = null, $callback_args = null, $context = 'normal', $priority = 'core' ) {
		wp_add_dashboard_widget( $widget_id, $widget_name, $callback, $control_callback, $callback_args, $context, $priority );
	}
}
