<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpMediaTemplate implements MediaTemplate {
	/**
	 * @inheritDoc
	 */
	public function wp_print_media_templates() {
		wp_print_media_templates();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_underscore_audio_template() {
		wp_underscore_audio_template();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_underscore_video_template() {
		wp_underscore_video_template();
	}
}
