<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpNavMenus implements NavMenus {
	/**
	 * @inheritDoc
	 */
	public function walk_nav_menu_tree( $items, $depth, $args ) {
		return walk_nav_menu_tree( $items, $depth, $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_nav_menu( $args = array() ) {
		return wp_nav_menu( $args );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_nav_menu_remove_menu_item_has_children_class( $classes, $menu_item, $args = false, $depth = false ) {
		return wp_nav_menu_remove_menu_item_has_children_class( $classes, $menu_item, $args, $depth );
	}
}
