<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpPostThumbnails implements PostThumbnails {
	/**
	 * @inheritDoc
	 */
	public function get_post_thumbnail_id( $post = null ) {
		return get_post_thumbnail_id( $post );
	}

	/**
	 * @inheritDoc
	 */
	public function get_the_post_thumbnail( $post = null, $size = 'post-thumbnail', $attr = '' ) {
		return get_the_post_thumbnail( $post, $size, $attr );
	}

	/**
	 * @inheritDoc
	 */
	public function get_the_post_thumbnail_caption( $post = null ) {
		return get_the_post_thumbnail_caption( $post );
	}

	/**
	 * @inheritDoc
	 */
	public function get_the_post_thumbnail_url( $post = null, $size = 'post-thumbnail' ) {
		return get_the_post_thumbnail_url( $post, $size );
	}

	/**
	 * @inheritDoc
	 */
	public function has_post_thumbnail( $post = null ) {
		return has_post_thumbnail( $post );
	}

	/**
	 * @inheritDoc
	 */
	public function the_post_thumbnail( $size = 'post-thumbnail', $attr = '' ) {
		the_post_thumbnail( $size, $attr );
	}

	/**
	 * @inheritDoc
	 */
	public function the_post_thumbnail_caption( $post = null ) {
		the_post_thumbnail_caption( $post );
	}

	/**
	 * @inheritDoc
	 */
	public function the_post_thumbnail_url( $size = 'post-thumbnail' ) {
		the_post_thumbnail_url( $size );
	}

	/**
	 * @inheritDoc
	 */
	public function update_post_thumbnail_cache( $wp_query = null ) {
		update_post_thumbnail_cache( $wp_query );
	}
}
