<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpPostFormats implements PostFormats {
	/**
	 * @inheritDoc
	 */
	public function get_post_format( $post = null ) {
		return get_post_format( $post );
	}

	/**
	 * @inheritDoc
	 */
	public function has_post_format( $format = array(), $post = null ) {
		return has_post_format( $format, $post );
	}

	/**
	 * @inheritDoc
	 */
	public function set_post_format( $post, $format ) {
		return set_post_format( $post, $format );
	}

	/**
	 * @inheritDoc
	 */
	public function get_post_format_slugs() {
		return get_post_format_slugs();
	}

	/**
	 * @inheritDoc
	 */
	public function get_post_format_strings() {
		return get_post_format_strings();
	}

	/**
	 * @inheritDoc
	 */
	public function get_post_format_string( $slug ) {
		return get_post_format_string( $slug );
	}

	/**
	 * @inheritDoc
	 */
	public function get_post_format_link( $format ) {
		return get_post_format_link( $format );
	}
}
