<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpRestApi implements RestApi {
	/**
	 * @inheritDoc
	 */
	public function register_rest_route( $route_namespace, $route, $args = array(), $override = false ) {
		return register_rest_route( $route_namespace, $route, $args, $override );
	}

	/**
	 * @inheritDoc
	 */
	public function register_rest_field( $object_type, $attribute, $args = array() ) {
		register_rest_field( $object_type, $attribute, $args );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_get_server() {
		return rest_get_server();
	}

	/**
	 * @inheritDoc
	 */
	public function rest_do_request( $request ) {
		return rest_do_request( $request );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_ensure_request( $request ) {
		return rest_ensure_request( $request );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_ensure_response( $response ) {
		return rest_ensure_response( $response );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_convert_error_to_response( $error ) {
		return rest_convert_error_to_response( $error );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_authorization_required_code() {
		return rest_authorization_required_code();
	}

	/**
	 * @inheritDoc
	 */
	public function rest_get_authenticated_app_password() {
		return rest_get_authenticated_app_password();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_is_rest_endpoint() {
		return wp_is_rest_endpoint();
	}

	/**
	 * @inheritDoc
	 */
	public function rest_get_url_prefix() {
		return rest_get_url_prefix();
	}

	/**
	 * @inheritDoc
	 */
	public function get_rest_url( $blog_id = null, $path = '/', $scheme = 'rest' ) {
		return get_rest_url( $blog_id, $path, $scheme );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_url( $path = '', $scheme = 'rest' ) {
		return rest_url( $path, $scheme );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_get_route_for_post( $post ) {
		return rest_get_route_for_post( $post );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_get_route_for_post_type_items( $post_type ) {
		return rest_get_route_for_post_type_items( $post_type );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_get_route_for_term( $term ) {
		return rest_get_route_for_term( $term );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_get_route_for_taxonomy_items( $taxonomy ) {
		return rest_get_route_for_taxonomy_items( $taxonomy );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_get_queried_resource_route() {
		return rest_get_queried_resource_route();
	}

	/**
	 * @inheritDoc
	 */
	public function rest_preload_api_request( $memo, $path ) {
		return rest_preload_api_request( $memo, $path );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_parse_embed_param( $embed ) {
		return rest_parse_embed_param( $embed );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_filter_response_by_context( $response_data, $schema, $context ) {
		return rest_filter_response_by_context( $response_data, $schema, $context );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_is_field_included( $field, $fields ) {
		return rest_is_field_included( $field, $fields );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_get_avatar_sizes() {
		return rest_get_avatar_sizes();
	}

	/**
	 * @inheritDoc
	 */
	public function rest_get_avatar_urls( $id_or_email ) {
		return rest_get_avatar_urls( $id_or_email );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_parse_date( $date, $force_utc = false ) {
		return rest_parse_date( $date, $force_utc );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_get_date_with_gmt( $date, $is_utc = false ) {
		return rest_get_date_with_gmt( $date, $is_utc );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_parse_hex_color( $color ) {
		return rest_parse_hex_color( $color );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_is_ip_address( $ip ) {
		return rest_is_ip_address( $ip );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_is_boolean( $maybe_bool ) {
		return rest_is_boolean( $maybe_bool );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_is_integer( $maybe_integer ): bool {
		return rest_is_integer( $maybe_integer );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_is_array( $maybe_array ) {
		return rest_is_array( $maybe_array );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_is_object( $maybe_object ) {
		return rest_is_object( $maybe_object );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_sanitize_boolean( $value ) {
		return rest_sanitize_boolean( $value );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_sanitize_array( $maybe_array ) {
		return rest_sanitize_array( $maybe_array );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_sanitize_object( $maybe_object ) {
		return rest_sanitize_object( $maybe_object );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_parse_request_arg( $value, $request, $param ) {
		return rest_parse_request_arg( $value, $request, $param );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_sanitize_request_arg( $value, $request, $param ) {
		return rest_sanitize_request_arg( $value, $request, $param );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_validate_request_arg( $value, $request, $param ) {
		return rest_validate_request_arg( $value, $request, $param );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_get_endpoint_args_for_schema( $schema, $method = 'POST' ) {
		return rest_get_endpoint_args_for_schema( $schema, $method );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_get_allowed_schema_keywords() {
		return rest_get_allowed_schema_keywords();
	}

	/**
	 * @inheritDoc
	 */
	public function rest_default_additional_properties_to_false( $schema ) {
		return rest_default_additional_properties_to_false( $schema );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_validate_value_from_schema( $value, $args, $param = '' ) {
		return rest_validate_value_from_schema( $value, $args, $param );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_sanitize_value_from_schema( $value, $args, $param = '' ) {
		return rest_sanitize_value_from_schema( $value, $args, $param );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_validate_array_value_from_schema( $value, $args, $param ) {
		return rest_validate_array_value_from_schema( $value, $args, $param );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_validate_object_value_from_schema( $value, $args, $param ) {
		return rest_validate_object_value_from_schema( $value, $args, $param );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_validate_null_value_from_schema( $value, $param ) {
		return rest_validate_null_value_from_schema( $value, $param );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_validate_boolean_value_from_schema( $value, $param ) {
		return rest_validate_boolean_value_from_schema( $value, $param );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_validate_number_value_from_schema( $value, $args, $param ) {
		return rest_validate_number_value_from_schema( $value, $args, $param );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_validate_string_value_from_schema( $value, $args, $param ) {
		return rest_validate_string_value_from_schema( $value, $args, $param );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_validate_integer_value_from_schema( $value, $args, $param ) {
		return rest_validate_integer_value_from_schema( $value, $args, $param );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_validate_enum( $value, $args, $param ) {
		return rest_validate_enum( $value, $args, $param );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_validate_json_schema_pattern( $pattern, $value ) {
		return rest_validate_json_schema_pattern( $pattern, $value );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_validate_array_contains_unique_items( $input_array ) {
		return rest_validate_array_contains_unique_items( $input_array );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_get_best_type_for_value( $value, $types ) {
		return rest_get_best_type_for_value( $value, $types );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_handle_multi_type_schema( $value, $args, $param = '' ) {
		return rest_handle_multi_type_schema( $value, $args, $param );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_find_matching_pattern_property_schema( $property, $args ) {
		return rest_find_matching_pattern_property_schema( $property, $args );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_find_any_matching_schema( $value, $args, $param ) {
		return rest_find_any_matching_schema( $value, $args, $param );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_find_one_matching_schema( $value, $args, $param, $stop_after_first_match = false ) {
		return rest_find_one_matching_schema( $value, $args, $param, $stop_after_first_match );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_get_combining_operation_error( $value, $param, $errors ) {
		return rest_get_combining_operation_error( $value, $param, $errors );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_format_combining_operation_error( $param, $error ) {
		return rest_format_combining_operation_error( $param, $error );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_are_values_equal( $value1, $value2 ) {
		return rest_are_values_equal( $value1, $value2 );
	}

	/**
	 * @inheritDoc
	 */
	public function rest_stabilize_value( $value ) {
		return rest_stabilize_value( $value );
	}
}
