<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpSettings implements Settings {
	/**
	 * @inheritDoc
	 */
	public function add_settings_error( $setting, $code, $message, $type = 'error' ) {
		add_settings_error( $setting, $code, $message, $type );
	}

	/**
	 * @inheritDoc
	 */
	public function add_settings_field( $id, $title, $callback, $page, $section = 'default', $args = array() ) {
		add_settings_field( $id, $title, $callback, $page, $section, $args );
	}

	/**
	 * @inheritDoc
	 */
	public function add_settings_section( $id, $title, $callback, $page, $args = array() ) {
		add_settings_section( $id, $title, $callback, $page, $args );
	}

	/**
	 * @inheritDoc
	 */
	public function do_settings_fields( $page, $section ) {
		do_settings_fields( $page, $section );
	}

	/**
	 * @inheritDoc
	 */
	public function do_settings_sections( $page ) {
		do_settings_sections( $page );
	}

	/**
	 * @inheritDoc
	 */
	public function get_settings_errors( $setting = '', $sanitize = false ) {
		return get_settings_errors( $setting, $sanitize );
	}

	/**
	 * @inheritDoc
	 */
	public function settings_errors( $setting = '', $sanitize = false, $hide_on_update = false ) {
		settings_errors( $setting, $sanitize, $hide_on_update );
	}

	/**
	 * @inheritDoc
	 */
	public function register_setting( $option_group, $option_name, $args = array() ) {
		register_setting( $option_group, $option_name, $args );
	}

	/**
	 * @inheritDoc
	 */
	public function unregister_setting( $option_group, $option_name, $deprecated = '' ) {
		unregister_setting( $option_group, $option_name, $deprecated );
	}

	/**
	 * @inheritDoc
	 */
	public function get_registered_settings() {
		return get_registered_settings();
	}
}
