<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpSearch implements Search {
	/**
	 * @inheritDoc
	 */
	public function get_search_form( $args = array() ) {
		return get_search_form( $args );
	}

	/**
	 * @inheritDoc
	 */
	public function get_search_link( $query = '' ) {
		return get_search_link( $query );
	}

	/**
	 * @inheritDoc
	 */
	public function get_search_query( $escaped = true ) {
		return get_search_query( $escaped );
	}

	/**
	 * @inheritDoc
	 */
	public function the_search_query() {
		the_search_query();
	}
}
