<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpSiteHealth implements SiteHealth {
	/**
	 * @inheritDoc
	 */
	public function wp_get_update_php_url() {
		return wp_get_update_php_url();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_update_php_annotation() {
		return wp_get_update_php_annotation();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_update_php_annotation( $before = '<p class="description">', $after = '</p>', $display = true ) {
		return wp_update_php_annotation( $before, $after, $display );
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_direct_php_update_url() {
		return wp_get_direct_php_update_url();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_direct_php_update_button() {
		wp_direct_php_update_button();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_update_https_url() {
		return wp_get_update_https_url();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_get_direct_update_https_url() {
		return wp_get_direct_update_https_url();
	}
}
