<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpThemeTemplate implements ThemeTemplate {
	/**
	 * @inheritDoc
	 */
	public function get_custom_header() {
		return get_custom_header();
	}

	/**
	 * @inheritDoc
	 */
	public function has_custom_header() {
		return has_custom_header();
	}

	/**
	 * @inheritDoc
	 */
	public function get_custom_header_markup() {
		return get_custom_header_markup();
	}

	/**
	 * @inheritDoc
	 */
	public function the_custom_header_markup() {
		the_custom_header_markup();
	}

	/**
	 * @inheritDoc
	 */
	public function has_header_image() {
		return has_header_image();
	}

	/**
	 * @inheritDoc
	 */
	public function get_header_image() {
		return get_header_image();
	}

	/**
	 * @inheritDoc
	 */
	public function header_image() {
		header_image();
	}

	/**
	 * @inheritDoc
	 */
	public function get_header_image_tag( $attr = array() ) {
		return get_header_image_tag( $attr );
	}

	/**
	 * @inheritDoc
	 */
	public function the_header_image_tag( $attr = array() ) {
		the_header_image_tag( $attr );
	}

	/**
	 * @inheritDoc
	 */
	public function get_random_header_image() {
		return get_random_header_image();
	}

	/**
	 * @inheritDoc
	 */
	public function is_random_header_image( $type = 'any' ) {
		return is_random_header_image( $type );
	}

	/**
	 * @inheritDoc
	 */
	public function display_header_text() {
		return display_header_text();
	}

	/**
	 * @inheritDoc
	 */
	public function get_header_textcolor() {
		return get_header_textcolor();
	}

	/**
	 * @inheritDoc
	 */
	public function header_textcolor() {
		header_textcolor();
	}

	/**
	 * @inheritDoc
	 */
	public function has_header_video() {
		return has_header_video();
	}

	/**
	 * @inheritDoc
	 */
	public function is_header_video_active() {
		return is_header_video_active();
	}

	/**
	 * @inheritDoc
	 */
	public function get_header_video_url() {
		return get_header_video_url();
	}

	/**
	 * @inheritDoc
	 */
	public function the_header_video_url() {
		the_header_video_url();
	}

	/**
	 * @inheritDoc
	 */
	public function get_header_video_settings() {
		return get_header_video_settings();
	}

	/**
	 * @inheritDoc
	 */
	public function get_background_color() {
		return get_background_color();
	}

	/**
	 * @inheritDoc
	 */
	public function background_color() {
		background_color();
	}

	/**
	 * @inheritDoc
	 */
	public function get_background_image() {
		return get_background_image();
	}

	/**
	 * @inheritDoc
	 */
	public function background_image() {
		background_image();
	}
}
