<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpTransient implements Transient {
	/**
	 * @inheritDoc
	 */
	public function get_transient( string $transient ) {
		return get_transient( $transient );
	}

	/**
	 * @inheritDoc
	 */
	public function set_transient( string $transient, $value, int $expiration = 0 ): bool {
		return set_transient( $transient, $value, $expiration );
	}

	/**
	 * @inheritDoc
	 */
	public function delete_transient( string $transient ): bool {
		return delete_transient( $transient );
	}

	/**
	 * @inheritDoc
	 */
	public function get_site_transient( $transient ) {
		return get_site_transient( $transient );
	}

	/**
	 * @inheritDoc
	 */
	public function set_site_transient( $transient, $value, $expiration = 0 ) {
		return set_site_transient( $transient, $value, $expiration );
	}

	/**
	 * @inheritDoc
	 */
	public function delete_site_transient( $transient ) {
		return delete_site_transient( $transient );
	}

	/**
	 * @inheritDoc
	 */
	public function delete_expired_transients( $force_db = false ) {
		delete_expired_transients( $force_db );
	}
}
