<?php declare( strict_types=1 );

// Generated by bin/wpal fix from wpal.map.php and api/wordpress.json. Do not edit.

namespace Merkushin\Wpal\Service;

final class WpUserSettings implements UserSettings {
	/**
	 * @inheritDoc
	 */
	public function get_user_setting( $name, $default_value = false ) {
		return get_user_setting( $name, $default_value );
	}

	/**
	 * @inheritDoc
	 */
	public function set_user_setting( $name, $value ) {
		return set_user_setting( $name, $value );
	}

	/**
	 * @inheritDoc
	 */
	public function delete_user_setting( $names ) {
		return delete_user_setting( $names );
	}

	/**
	 * @inheritDoc
	 */
	public function get_all_user_settings() {
		return get_all_user_settings();
	}

	/**
	 * @inheritDoc
	 */
	public function delete_all_user_settings() {
		delete_all_user_settings();
	}

	/**
	 * @inheritDoc
	 */
	public function wp_user_settings() {
		wp_user_settings();
	}
}
