<?php declare( strict_types=1 );
/**
 * Where WordPress functions belong in WPAL. `bin/wpal fix` generates `src/Service` from this file and the
 * WordPress snapshot in `api/wordpress.json`; `bin/wpal coverage` reports on it.
 *
 * - `services`: generated services and the WordPress functions they wrap, in order.
 * - `planned`: where functions will go once they're moved into `services`.
 * - `types`: native types `Service` declares although WordPress doesn't. Kept so existing implementations stay
 *   compatible; never add new ones.
 * - `extendable`: `Wp*` classes that stay non-final because they shipped that way.
 * - `ignore`, `ignore_files`: functions WPAL deliberately doesn't wrap. Private (`_`-prefixed or `@access private`)
 *   and deprecated functions are ignored automatically.
 *
 * Everything else shows up as untriaged.
 */

return [
	// Service => WordPress function names, in the order the methods are generated.
	'services'     => [
		'Abilities'       => [
			'wp_register_ability', 'wp_unregister_ability', 'wp_has_ability', 'wp_get_ability', 'wp_get_abilities',
			'wp_register_ability_category', 'wp_unregister_ability_category', 'wp_has_ability_category',
			'wp_get_ability_category', 'wp_get_ability_categories',
		],
		'AdminBar'        => [
			'is_admin_bar_showing', 'show_admin_bar',
		],
		'AdminPosts'      => [
			'post_exists', 'get_default_post_to_edit', 'get_available_post_statuses', 'wp_write_post', 'write_post',
			'edit_post', 'bulk_edit_posts', 'wp_create_post_autosave', 'wp_autosave', 'post_preview', 'redirect_post',
			'get_sample_permalink', 'get_sample_permalink_html', 'wp_check_post_lock', 'wp_set_post_lock',
			'wp_edit_posts_query', 'wp_edit_attachments_query_vars', 'wp_edit_attachments_query',
		],
		// Admin screens: form widgets and page chrome from wp-admin/includes/template.php.
		'AdminTemplate'   => [
			'compression_test', 'find_posts_div', 'get_inline_data', 'get_media_states', 'get_post_states',
			'get_submit_button', 'iframe_footer', 'iframe_header', 'list_meta', 'meta_form', 'page_template_dropdown',
			'parent_dropdown', 'register_admin_color_schemes', 'submit_button', 'the_post_password', 'touch_time',
			'wp_admin_css', 'wp_admin_css_color', 'wp_admin_css_uri', 'wp_category_checklist', 'wp_comment_reply',
			'wp_comment_trashnotice', 'wp_dropdown_roles', 'wp_heartbeat_settings', 'wp_import_upload_form',
			'wp_link_category_checklist', 'wp_popular_terms_checklist', 'wp_star_rating', 'wp_terms_checklist',
			'show_message', 'wp_admin_notice', 'wp_get_admin_notice',
		],
		'AdminUsers'      => [
			'get_editable_roles', 'get_user_to_edit', 'get_users_drafts', 'wp_delete_user', 'wp_revoke_user',
			'wp_is_authorize_application_password_request_valid', 'wp_is_authorize_application_redirect_url_valid',
		],
		'Ai'              => [
			'wp_ai_client_prompt', 'wp_supports_ai',
		],
		'ArchiveTemplate' => [
			'calendar_week_mod', 'delete_get_calendar_cache', 'get_archives_link', 'get_calendar',
			'get_the_archive_description', 'get_the_archive_title', 'get_the_post_type_description',
			'post_type_archive_title', 'single_cat_title', 'single_month_title', 'single_post_title',
			'single_tag_title', 'single_term_title', 'the_archive_description', 'the_archive_title', 'wp_get_archives',
		],
		'Arrays'          => [
			'wp_parse_args', 'wp_parse_list', 'wp_parse_id_list', 'wp_parse_slug_list', 'wp_array_slice_assoc',
			'wp_is_numeric_array', 'wp_recursive_ksort', 'wp_filter_object_list', 'wp_list_filter', 'wp_list_pluck',
			'wp_list_sort', 'wp_fuzzy_number_match',
		],
		'Assets'          => [
			'wp_enqueue_script', 'wp_add_inline_script', 'wp_enqueue_style', 'add_thickbox', 'wp_register_script',
			'wp_register_style', 'wp_dequeue_script', 'wp_dequeue_style', 'wp_deregister_script', 'wp_deregister_style',
			'wp_script_is', 'wp_style_is', 'wp_add_inline_style', 'wp_localize_script', 'wp_set_script_translations',
			'wp_script_add_data', 'wp_style_add_data', 'wp_print_scripts', 'wp_print_styles', 'wp_scripts', 'wp_styles',
			'wp_get_script_tag', 'wp_print_script_tag', 'wp_get_inline_script_tag', 'wp_print_inline_script_tag',
			'wp_get_script_polyfill', 'wp_scripts_get_suffix', 'wp_print_head_scripts', 'wp_print_footer_scripts',
			'wp_enqueue_block_style', 'wp_enqueue_block_support_styles', 'wp_should_load_separate_core_block_assets',
			'wp_should_load_block_assets_on_demand', 'wp_should_load_block_editor_scripts_and_styles',
			'wp_js_dataset_name', 'wp_html_custom_data_attribute_name', 'wp_script_modules',
			'wp_register_script_module', 'wp_enqueue_script_module', 'wp_dequeue_script_module',
			'wp_deregister_script_module', 'wp_set_script_module_translations',
		],
		'Auth'            => [
			'wp_fast_hash', 'wp_verify_fast_hash', 'wp_signon', 'wp_authenticate', 'wp_logout', 'auth_redirect',
			'wp_set_auth_cookie', 'wp_clear_auth_cookie', 'wp_generate_auth_cookie', 'wp_parse_auth_cookie',
			'wp_validate_auth_cookie', 'wp_get_session_token', 'wp_get_all_sessions', 'wp_destroy_current_session',
			'wp_destroy_other_sessions', 'wp_destroy_all_sessions', 'wp_salt', 'wp_hash',
		],
		'AuthorTemplate'  => [
			'get_author_posts_url', 'get_the_author', 'get_the_author_link', 'get_the_author_meta',
			'get_the_author_posts', 'get_the_author_posts_link', 'get_the_modified_author', 'is_multi_author',
			'the_author', 'the_author_link', 'the_author_meta', 'the_author_posts', 'the_author_posts_link',
			'the_modified_author', 'wp_list_authors', 'wp_list_users', 'wp_dropdown_users',
		],
		'Avatars'         => [
			'get_avatar_data', 'get_avatar_url', 'is_avatar_comment_type', 'get_avatar',
		],
		'BlockBindings'   => [
			'register_block_bindings_source', 'unregister_block_bindings_source',
			'get_all_registered_block_bindings_sources', 'get_block_bindings_source',
			'get_block_bindings_supported_attributes',
		],
		'BlockEditor'     => [
			'get_block_editor_settings', 'get_default_block_editor_settings',
			'get_classic_theme_supports_block_editor_settings', 'get_legacy_widget_block_editor_settings',
			'get_block_editor_theme_styles', 'get_allowed_block_types', 'get_block_categories',
			'get_default_block_categories', 'block_editor_rest_api_preload', 'wp_get_entity_view_config',
			'wp_get_entity_view_config_hook_name',
		],
		'BlockPatterns'   => [
			'register_block_pattern', 'unregister_block_pattern', 'register_block_pattern_category',
			'unregister_block_pattern_category', 'resolve_pattern_blocks',
		],
		'BlockSupports'   => [
			'wp_get_block_style_variation_name_from_class', 'wp_get_block_style_variation_name_from_registered_style',
			'wp_get_layout_container_values', 'wp_get_layout_child_values', 'wp_get_child_layout_style_rules',
			'wp_sanitize_block_gap_value', 'wp_get_typography_font_size_value', 'wp_get_typography_value_and_unit',
			'wp_typography_get_preset_inline_style_value', 'wp_get_block_state_style_rules',
			'wp_get_block_state_unique_class', 'wp_get_block_state_element_selectors', 'wp_get_root_state_style',
			'wp_get_state_style_groups', 'wp_add_state_style_group', 'wp_add_block_state_style_rule',
			'wp_build_state_selector', 'wp_split_selector_list', 'wp_normalize_state_style_for_css_output',
			'wp_normalize_state_preset_vars', 'wp_get_state_declarations_with_background_resets',
			'wp_get_state_declarations_with_fallback_border_styles',
			'wp_get_state_style_with_fallback_dimension_styles',
		],
		'BlockTemplates'  => [
			'block_footer_area', 'block_header_area', 'block_template_part', 'get_allowed_block_template_part_areas',
			'get_block_file_template', 'get_block_template', 'get_block_templates', 'get_block_theme_folders',
			'get_default_block_template_types', 'get_template_hierarchy', 'locate_block_template',
			'register_block_template', 'unregister_block_template', 'wp_generate_block_templates_export_file',
			'wp_is_theme_directory_ignored', 'wp_render_empty_block_template_warning',
			'wp_set_unique_slug_on_create_template_part',
		],
		'Blocks'          => [
			'register_block_type', 'register_block_type_from_metadata', 'unregister_block_type',
			'wp_register_block_metadata_collection', 'wp_register_block_types_from_metadata_collection',
			'get_block_metadata_i18n_schema', 'get_dynamic_block_names', 'block_has_support', 'block_version',
			'register_block_style', 'unregister_block_style', 'register_block_script_handle',
			'register_block_script_module_id', 'register_block_style_handle', 'generate_block_asset_handle',
			'get_block_asset_url', 'remove_block_asset_path_prefix', 'has_blocks', 'has_block', 'parse_blocks',
			'wp_get_first_block', 'render_block', 'do_blocks', 'get_block_wrapper_attributes', 'serialize_block',
			'serialize_blocks', 'serialize_block_attributes', 'get_comment_delimited_block_content',
			'strip_core_block_namespace', 'filter_block_content', 'filter_block_kses', 'filter_block_kses_value',
			'filter_block_core_template_part_attributes', 'excerpt_remove_blocks', 'excerpt_remove_footnotes',
			'get_hooked_blocks', 'insert_hooked_blocks_into_rest_response', 'build_query_vars_from_query_block',
			'build_comment_query_vars_from_block', 'get_query_pagination_arrow', 'get_comments_pagination_arrow',
		],
		'Bookmarks'       => [
			'wp_list_bookmarks', 'get_bookmark', 'get_bookmark_field', 'get_bookmarks', 'get_link_to_edit',
			'get_default_link_to_edit', 'wp_insert_link', 'wp_update_link', 'wp_delete_link', 'wp_get_link_cats',
			'wp_set_link_cats', 'sanitize_bookmark', 'sanitize_bookmark_field', 'clean_bookmark_cache',
		],
		'Cache'           => [
			'wp_using_ext_object_cache', 'wp_suspend_cache_addition', 'wp_suspend_cache_invalidation',
			'wp_cache_get_last_changed', 'wp_cache_set_last_changed', 'wp_cache_add', 'wp_cache_add_multiple',
			'wp_cache_replace', 'wp_cache_set', 'wp_cache_set_multiple', 'wp_cache_get', 'wp_cache_get_multiple',
			'wp_cache_delete', 'wp_cache_delete_multiple', 'wp_cache_incr', 'wp_cache_decr', 'wp_cache_get_salted',
			'wp_cache_set_salted', 'wp_cache_get_multiple_salted', 'wp_cache_set_multiple_salted', 'wp_cache_flush',
			'wp_cache_flush_runtime', 'wp_cache_flush_group', 'wp_cache_supports', 'wp_cache_add_global_groups',
			'wp_cache_add_non_persistent_groups', 'wp_cache_switch_to_blog',
		],
		'Capabilities'    => [
			'map_meta_cap', 'current_user_can', 'current_user_can_for_blog', 'author_can', 'user_can', 'wp_roles',
			'get_role', 'add_role', 'remove_role', 'get_super_admins', 'is_super_admin', 'grant_super_admin',
			'revoke_super_admin', 'wp_maybe_grant_install_languages_cap', 'wp_maybe_grant_resume_extensions_caps',
			'wp_maybe_grant_site_health_caps', 'current_user_can_for_site', 'user_can_for_site',
		],
		'Categories'      => [
			'get_categories', 'get_category', 'get_category_by_path', 'get_category_by_slug', 'get_cat_ID',
			'get_cat_name', 'cat_is_ancestor_of', 'category_exists', 'get_category_to_edit', 'wp_create_category',
			'wp_create_categories', 'wp_insert_category', 'wp_update_category', 'sanitize_category',
			'sanitize_category_field', 'clean_category_cache',
		],
		'CommentTemplate' => [
			'cancel_comment_reply_link', 'comment_author', 'comment_author_email', 'comment_author_email_link',
			'comment_author_IP', 'comment_author_link', 'comment_author_url', 'comment_author_url_link',
			'comment_class', 'comment_date', 'comment_excerpt', 'comment_form', 'comment_form_title', 'comment_ID',
			'comment_id_fields', 'comment_reply_link', 'comment_text', 'comment_time', 'comment_type', 'comments_link',
			'comments_number', 'comments_open', 'comments_popup_link', 'comments_template',
			'get_cancel_comment_reply_link', 'get_comment_author', 'get_comment_author_email',
			'get_comment_author_email_link', 'get_comment_author_IP', 'get_comment_author_link',
			'get_comment_author_url', 'get_comment_author_url_link', 'get_comment_class', 'get_comment_date',
			'get_comment_excerpt', 'get_comment_ID', 'get_comment_id_fields', 'get_comment_link',
			'get_comment_reply_link', 'get_comment_text', 'get_comment_time', 'get_comment_type', 'get_comments_link',
			'get_comments_number', 'get_comments_number_text', 'get_post_reply_link', 'get_trackback_url', 'pings_open',
			'post_reply_link', 'trackback_rdf', 'trackback_url', 'wp_comment_form_unfiltered_html_nonce',
			'wp_list_comments',
		],
		'Comments'        => [
			'check_comment', 'get_approved_comments', 'get_comment', 'get_comments', 'get_comment_statuses',
			'get_default_comment_status', 'get_lastcommentmodified', 'get_comment_count', 'add_comment_meta',
			'delete_comment_meta', 'get_comment_meta', 'update_comment_meta',
			'wp_queue_comments_for_comment_meta_lazyload', 'wp_set_comment_cookies', 'sanitize_comment_cookies',
			'wp_allow_comment', 'check_comment_flood_db', 'wp_check_comment_flood', 'separate_comments',
			'get_comment_pages_count', 'get_page_of_comment', 'wp_get_comment_fields_max_lengths',
			'wp_check_comment_data_max_lengths', 'wp_check_comment_disallowed_list', 'wp_count_comments',
			'wp_delete_comment', 'wp_trash_comment', 'wp_untrash_comment', 'wp_spam_comment', 'wp_unspam_comment',
			'wp_get_comment_status', 'wp_transition_comment_status', 'wp_get_current_commenter',
			'wp_get_unapproved_comment_author_email', 'wp_insert_comment', 'wp_filter_comment',
			'wp_throttle_comment_flood', 'wp_new_comment', 'wp_new_comment_notify_moderator',
			'wp_new_comment_notify_postauthor', 'wp_set_comment_status', 'wp_update_comment',
			'wp_defer_comment_counting', 'wp_update_comment_count', 'wp_update_comment_count_now',
			'discover_pingback_server_uri', 'do_all_pings', 'do_all_pingbacks', 'do_all_enclosures',
			'do_all_trackbacks', 'do_trackbacks', 'generic_ping', 'pingback', 'privacy_ping_filter', 'trackback',
			'weblog_ping', 'pingback_ping_source_uri', 'xmlrpc_pingback_error', 'clean_comment_cache',
			'update_comment_cache', 'wp_handle_comment_submission', 'wp_register_comment_personal_data_exporter',
			'wp_comments_personal_data_exporter', 'wp_register_comment_personal_data_eraser',
			'wp_comments_personal_data_eraser', 'wp_cache_set_comments_last_changed', '_wp_batch_update_comment_type',
			'_wp_check_for_scheduled_update_comment_type', 'comment_exists', 'get_comment_to_edit',
			'get_pending_comments_num', 'wp_check_comment_data', 'wp_lazyload_comment_meta',
			'wp_should_disable_pings_for_environment', 'wp_get_note_mentioned_user_ids', 'wp_send_note_notification',
			'wp_notify_postauthor', 'wp_notify_moderator',
		],
		'Connectors'      => [
			'wp_is_connector_registered', 'wp_get_connector', 'wp_get_connectors',
		],
		'Cron'            => [
			'wp_schedule_single_event', 'wp_schedule_event', 'wp_reschedule_event', 'wp_unschedule_event',
			'wp_clear_scheduled_hook', 'wp_unschedule_hook', 'wp_get_scheduled_event', 'wp_next_scheduled',
			'spawn_cron', 'wp_get_schedules', 'wp_get_schedule', 'wp_get_ready_cron_jobs',
		],
		'Database'        => [
			'dbDelta', 'maybe_create_table', 'maybe_add_column', 'maybe_convert_table_to_utf8mb4', 'add_clean_index',
			'drop_index',
		],
		'Dates'           => [
			'current_time', 'current_datetime', 'wp_timezone', 'wp_timezone_string', 'wp_date', 'date_i18n',
			'mysql2date', 'mysql_to_rfc3339', 'wp_checkdate', 'get_weekstartend', 'wp_maybe_decline_date',
			'human_readable_duration', 'wp_timezone_choice', 'get_date_from_gmt', 'get_gmt_from_date',
			'iso8601_to_datetime', 'iso8601_timezone_to_offset', 'human_time_diff',
		],
		// What goes in <head> and around the page: wp_head(), titles, resource hints, robots.
		'DocumentHead'    => [
			'adjacent_posts_rel_link_wp_head', 'get_the_generator', 'rel_canonical', 'rsd_link', 'the_generator',
			'wp_body_open', 'wp_dependencies_unique_hosts', 'wp_footer', 'wp_generator', 'wp_get_document_title',
			'wp_head', 'wp_meta', 'wp_preload_resources', 'wp_resource_hints', 'wp_robots',
			'wp_robots_max_image_preview_large', 'wp_robots_no_robots', 'wp_robots_noindex', 'wp_robots_noindex_embeds',
			'wp_robots_noindex_search', 'wp_robots_sensitive_page', 'wp_shortlink_header', 'wp_shortlink_wp_head',
			'wp_strict_cross_origin_referrer', 'wp_title', 'wp_get_speculation_rules_configuration',
		],
		'EditLinks'       => [
			'edit_bookmark_link', 'edit_comment_link', 'edit_post_link', 'edit_tag_link', 'edit_term_link',
			'get_delete_post_link', 'get_edit_bookmark_link', 'get_edit_comment_link', 'get_edit_post_link',
			'get_edit_tag_link', 'get_edit_term_link', 'get_edit_user_link',
		],
		'Editor'          => [
			'user_can_richedit', 'wp_default_editor', 'wp_editor', 'wp_enqueue_code_editor', 'wp_enqueue_editor',
			'wp_get_code_editor_settings', 'get_block_editor_server_block_settings', 'use_block_editor_for_post',
			'use_block_editor_for_post_type',
		],
		'EmbedTemplate'   => [
			'the_embed_site_title', 'the_excerpt_embed', 'print_embed_comments_button', 'print_embed_sharing_button',
			'print_embed_sharing_dialog',
		],
		'Embeds'          => [
			'wp_oembed_get', 'wp_embed_defaults', 'wp_embed_register_handler', 'wp_embed_unregister_handler',
			'wp_oembed_add_provider', 'wp_oembed_remove_provider', 'get_oembed_endpoint_url',
			'get_oembed_response_data', 'get_oembed_response_data_for_url', 'wp_oembed_ensure_format',
			'get_post_embed_url', 'get_post_embed_html',
		],
		'Emoji'           => [
			'convert_smilies', 'wp_encode_emoji', 'wp_staticize_emoji',
		],
		'Environment'     => [
			'wp_get_environment_type', 'wp_get_development_mode', 'wp_is_development_mode', 'wp_get_wp_version',
			'is_wp_version_compatible', 'is_php_version_compatible', 'is_blog_installed', 'wp_installing',
			'wp_is_maintenance_mode', 'is_admin', 'is_blog_admin', 'is_network_admin', 'is_user_admin', 'is_login',
			'wp_doing_ajax', 'wp_doing_cron', 'wp_is_serving_rest_request', 'wp_is_json_request', 'wp_is_jsonp_request',
			'wp_is_xml_request', 'wp_is_json_media_type', 'wp_using_themes', 'wp_is_mobile',
			'wp_is_site_protected_by_basic_auth', 'wp_is_ini_value_changeable', 'wp_convert_hr_to_bytes',
			'wp_raise_memory_limit', 'apache_mod_loaded', 'iis7_supports_permalinks', 'is_lighttpd_before_150',
			'is_utf8_charset', 'mbstring_binary_safe_encoding', 'reset_mbstring_encoding', 'get_num_queries',
			'timer_float', 'timer_stop',
		],
		'Errors'          => [
			'is_wp_error', 'wp_die', 'wp_trigger_error', 'dead_db', 'wp_debug_backtrace_summary',
			'wp_is_fatal_error_handler_enabled', 'is_protected_endpoint', 'is_protected_ajax_action',
			'wp_is_recovery_mode', 'wp_recovery_mode', 'wp_paused_plugins', 'wp_paused_themes',
			'wp_get_extension_error_description',
		],
		'Escaping'        => [
			'esc_html', 'esc_attr', 'esc_textarea', 'esc_js', 'esc_xml', 'esc_url', 'esc_url_raw', 'esc_sql',
			'tag_escape',
		],
		// Feed links, plus the template tags feed templates use (wp-includes/feed.php).
		'Feeds'           => [
			'atom_enclosure', 'atom_site_icon', 'bloginfo_rss', 'comment_author_rss', 'comment_guid', 'comment_link',
			'comment_text_rss', 'comments_link_feed', 'feed_content_type', 'feed_links', 'feed_links_extra',
			'fetch_feed', 'get_author_feed_link', 'get_bloginfo_rss', 'get_category_feed_link',
			'get_comment_author_rss', 'get_comment_guid', 'get_default_feed', 'get_feed_build_date', 'get_feed_link',
			'get_post_comments_feed_link', 'get_post_type_archive_feed_link', 'get_search_comments_feed_link',
			'get_search_feed_link', 'get_self_link', 'get_tag_feed_link', 'get_term_feed_link', 'get_the_category_rss',
			'get_the_content_feed', 'get_the_title_rss', 'get_wp_title_rss', 'html_type_rss', 'post_comments_feed_link',
			'prep_atom_text_construct', 'rss2_site_icon', 'rss_enclosure', 'self_link', 'the_category_rss',
			'the_content_feed', 'the_excerpt_rss', 'the_feed_link', 'the_permalink_rss', 'the_title_rss',
			'wp_title_rss', 'do_feed',
		],
		'FileEditor'      => [
			'validate_file_to_edit', 'get_file_description', 'wp_edit_theme_plugin_file',
			'wp_get_plugin_file_editable_extensions', 'wp_get_theme_file_editable_extensions', 'update_recently_edited',
		],
		'Filesystem'      => [
			'WP_Filesystem', 'request_filesystem_credentials', 'get_filesystem_method',
			'wp_print_request_filesystem_credentials_modal', 'get_home_path', 'list_files', 'copy_dir', 'move_dir',
			'wp_tempnam', 'download_url', 'verify_file_md5', 'verify_file_signature', 'wp_trusted_keys', 'unzip_file',
			'wp_zip_file_is_valid', 'wp_handle_upload', 'wp_handle_sideload', 'wp_opcache_invalidate',
			'wp_opcache_invalidate_directory', 'get_temp_dir', 'path_is_absolute', 'path_join', 'wp_normalize_path',
			'wp_is_stream', 'validate_file', 'wp_mkdir_p', 'wp_is_writable', 'win_is_writable', 'wp_filesize',
			'get_dirsize', 'recurse_dirsize', 'clean_dirsize_cache', 'wp_delete_file', 'wp_delete_file_from_directory',
			'wp_unique_filename', 'get_file_data', 'wp_is_file_mod_allowed', 'wp_upload_dir', 'wp_get_upload_dir',
			'wp_upload_bits',
		],
		'Fonts'           => [
			'wp_font_dir', 'wp_get_font_dir', 'wp_print_font_faces', 'wp_print_font_faces_from_style_variations',
			'wp_register_font_collection', 'wp_unregister_font_collection',
		],
		'Formatting'      => [
			'wpautop', 'shortcode_unautop', 'wptexturize', 'capital_P_dangit', 'convert_chars',
			'convert_invalid_entities', 'ent2ncr', 'htmlentities2', 'wp_specialchars_decode', 'normalize_whitespace',
			'remove_accents', 'wp_strip_all_tags', 'balanceTags', 'force_balance_tags', 'format_for_editor',
			'format_to_edit', 'wp_trim_words', 'wp_trim_excerpt', 'wp_html_excerpt', 'make_clickable',
			'get_url_in_content', 'links_add_base_url', 'links_add_target', 'wp_rel_nofollow', 'wp_rel_ugc',
			'antispambot', 'wp_html_split', 'get_html_split_regex', 'wp_replace_in_html_tags', 'wp_spaces_regexp',
			'wp_check_invalid_utf8', 'wp_is_valid_utf8', 'wp_scrub_utf8', 'wp_has_noncharacters', 'wp_iso_descrambler',
			'wp_slash', 'wp_unslash', 'stripslashes_deep', 'stripslashes_from_strings_only', 'backslashit', 'map_deep',
			'urlencode_deep', 'rawurlencode_deep', 'urldecode_deep', 'trailingslashit', 'untrailingslashit',
			'wp_basename', 'zeroise', 'wp_sprintf', 'wp_sprintf_l',
		],
		// Small form helpers: checked(), selected(), required-field markers, tooltips.
		'Forms'           => [
			'allowed_tags', 'checked', 'disabled', 'selected', 'wp_get_toggletip', 'wp_get_tooltip',
			'wp_get_tooltip_helper', 'wp_readonly', 'wp_required_field_indicator', 'wp_required_field_message',
		],
		'GlobalStyles'    => [
			'wp_get_global_settings', 'wp_get_global_styles', 'wp_get_global_stylesheet',
			'wp_add_global_styles_for_blocks', 'wp_get_block_css_selector', 'wp_theme_get_element_class_name',
			'wp_theme_has_theme_json', 'wp_clean_theme_json_cache', 'wp_get_theme_data_custom_templates',
			'wp_get_theme_data_template_parts', 'wp_get_theme_directory_pattern_slugs',
		],
		'Hooks'           => [
			'add_filter', 'apply_filters', 'apply_filters_ref_array', 'has_filter', 'remove_filter',
			'remove_all_filters', 'current_filter', 'doing_filter', 'add_action', 'do_action', 'do_action_ref_array',
			'has_action', 'remove_action', 'remove_all_actions', 'current_action', 'doing_action', 'did_action',
			'apply_filters_deprecated', 'do_action_deprecated', 'did_filter',
		],
		'Http'            => [
			'status_header', 'get_status_header_desc', 'wp_get_server_protocol', 'nocache_headers',
			'wp_get_nocache_headers', 'cache_javascript_headers', 'send_nosniff_header', 'send_frame_options_header',
			'wp_get_http_headers', 'wp_remote_fopen', 'wp_remote_request', 'wp_remote_get', 'wp_remote_post',
			'wp_remote_head', 'wp_safe_remote_request', 'wp_safe_remote_get', 'wp_safe_remote_post',
			'wp_safe_remote_head', 'wp_remote_retrieve_headers', 'wp_remote_retrieve_header',
			'wp_remote_retrieve_response_code', 'wp_remote_retrieve_response_message', 'wp_remote_retrieve_body',
			'wp_remote_retrieve_cookies', 'wp_remote_retrieve_cookie', 'wp_remote_retrieve_cookie_value',
			'wp_http_supports', 'wp_http_validate_url', 'get_http_origin', 'get_allowed_http_origins',
			'is_allowed_http_origin', 'send_origin_headers',
		],
		'Https'           => [
			'is_ssl', 'force_ssl_admin', 'wp_is_using_https', 'wp_is_home_url_using_https',
			'wp_is_site_url_using_https', 'wp_is_https_supported', 'wp_should_replace_insecure_home_url',
			'wp_replace_insecure_home_url', 'wp_update_urls_to_https',
		],
		'Icons'           => [
			'wp_get_icon', 'wp_register_icon', 'wp_unregister_icon', 'wp_register_icon_collection',
			'wp_unregister_icon_collection',
		],
		'Identifiers'     => [
			'wp_generate_uuid4', 'wp_is_uuid', 'wp_unique_id', 'wp_unique_prefixed_id', 'wp_unique_id_from_values',
		],
		'Images'          => [
			'wp_get_image_editor', 'wp_image_editor_supports', 'image_resize_dimensions',
			'image_make_intermediate_size', 'wp_getimagesize', 'wp_get_webp_info', 'wp_get_avif_info',
			'wp_get_image_encode_quality', 'is_gd_image', 'wp_imagecreatetruecolor', 'file_is_valid_image',
			'file_is_displayable_image', 'load_image_to_edit', 'wp_generate_attachment_metadata',
			'wp_create_image_subsizes', 'wp_get_missing_image_subsizes', 'wp_update_image_subsizes', 'wp_crop_image',
			'wp_copy_parent_attachment_properties', 'wp_read_image_metadata', 'wp_get_image_alttext', 'wp_exif_date2ts',
			'wp_exif_frac2dec', 'image_edit_apply_changes', 'wp_save_image_file', 'wp_stream_image',
		],
		'Importers'       => [
			'register_importer', 'get_importers', 'wp_get_popular_importers', 'wp_import_handle_upload',
			'wp_import_cleanup', 'get_cli_args', 'export_wp',
		],
		'Interactivity'   => [
			'wp_interactivity', 'wp_interactivity_state', 'wp_interactivity_config', 'wp_interactivity_get_context',
			'wp_interactivity_get_element', 'wp_interactivity_data_wp_context', 'wp_interactivity_process_directives',
		],
		'Json'            => [
			'wp_json_encode', 'wp_json_file_decode', 'wp_send_json', 'wp_send_json_success', 'wp_send_json_error',
			'wp_check_jsonp_callback', 'wp_get_json_schema_allowed_keywords', 'wp_prepare_json_schema_for_client',
		],
		'Kses'            => [
			'wp_kses', 'wp_kses_post', 'wp_kses_post_deep', 'wp_kses_data', 'wp_kses_allowed_html',
			'wp_kses_uri_attributes', 'wp_filter_kses', 'wp_filter_post_kses', 'wp_filter_nohtml_kses',
			'wp_filter_global_styles_post', 'kses_init', 'kses_init_filters', 'kses_remove_filters',
			'safecss_filter_attr', 'wp_kses_hook', 'wp_kses_version', 'wp_kses_split', 'wp_kses_attr',
			'wp_kses_attr_check', 'wp_kses_one_attr', 'wp_kses_hair', 'wp_kses_hair_parse', 'wp_kses_attr_parse',
			'wp_kses_check_attr_val', 'wp_kses_bad_protocol', 'wp_kses_bad_protocol_once', 'wp_kses_no_null',
			'wp_kses_stripslashes', 'wp_kses_array_lc', 'wp_kses_normalize_entities', 'wp_kses_decode_entities',
			'valid_unicode',
		],
		'Localization'    => [
			'get_locale', 'get_user_locale', 'determine_locale', 'translate', 'before_last_bar',
			'translate_with_gettext_context', '__', 'esc_attr__', 'esc_html__', '_e', 'esc_attr_e', 'esc_html_e', '_x',
			'_ex', 'esc_attr_x', 'esc_html_x', '_n', '_nx', '_n_noop', '_nx_noop', 'translate_nooped_plural',
			'load_textdomain', 'unload_textdomain', 'load_default_textdomain', 'load_plugin_textdomain',
			'load_muplugin_textdomain', 'load_theme_textdomain', 'load_child_theme_textdomain',
			'load_script_textdomain', 'load_script_translations', '_load_textdomain_just_in_time',
			'_get_path_to_translation', '_get_path_to_translation_from_lang_dir', 'get_translations_for_domain',
			'is_textdomain_loaded', 'translate_user_role', 'get_available_languages', 'wp_get_installed_translations',
			'wp_get_pomo_file_data', 'wp_dropdown_languages', 'is_rtl', 'switch_to_locale', 'restore_previous_locale',
			'restore_current_locale', 'is_locale_switched', 'translate_settings_using_i18n_schema', 'format_code_lang',
			'number_format_i18n', 'size_format', 'has_translation', 'load_script_module_textdomain',
			'switch_to_user_locale', 'wp_get_l10n_php_file_data', 'wp_get_list_item_separator',
			'wp_get_word_count_type', 'translations_api', 'wp_get_available_translations',
			'wp_can_install_language_pack', 'wp_download_language_pack',
		],
		'Login'           => [
			'wp_login_form', 'wp_login_url', 'wp_loginout', 'wp_logout_url', 'wp_lostpassword_url', 'wp_register',
			'wp_registration_url',
		],
		'Mail'            => [
			'wp_mail',
		],
		'Media'           => [
			'add_image_size', 'has_image_size', 'remove_image_size', 'get_intermediate_image_sizes',
			'wp_get_additional_image_sizes', 'wp_get_registered_image_subsizes', 'image_downsize',
			'image_get_intermediate_size', 'image_constrain_size_for_editor', 'image_hwstring',
			'wp_constrain_dimensions', 'wp_expand_dimensions', 'wp_image_matches_ratio', 'wp_image_src_get_dimensions',
			'wp_image_file_matches_image_meta', 'wp_get_attachment_image_src', 'wp_get_attachment_image_url',
			'wp_get_attachment_image_srcset', 'wp_get_attachment_image_sizes', 'wp_calculate_image_srcset',
			'wp_calculate_image_sizes', 'wp_sizes_attribute_includes_valid_auto',
			'wp_get_loading_optimization_attributes', 'wp_lazy_loading_enabled', 'wp_omit_loading_attr_threshold',
			'get_media_embedded_in_content', 'get_post_galleries', 'get_post_gallery', 'get_post_galleries_images',
			'get_post_gallery_images', 'wp_max_upload_size', 'wp_get_audio_extensions', 'wp_get_video_extensions',
			'wp_enqueue_media', 'wp_plupload_default_settings', 'wp_is_client_side_media_processing_enabled',
			'wp_get_chromium_major_version', 'wp_add_crossorigin_attributes',
		],
		'MediaTemplate'   => [
			'wp_print_media_templates', 'wp_underscore_audio_template', 'wp_underscore_video_template',
			'wp_get_attachment_image', 'get_image_tag', 'wp_filter_content_tags', 'wp_image_add_srcset_and_sizes',
			'wp_img_tag_add_srcset_and_sizes_attr', 'wp_img_tag_add_width_and_height_attr',
			'wp_img_tag_add_loading_optimization_attrs', 'wp_img_tag_add_auto_sizes', 'wp_iframe_tag_add_loading_attr',
			'gallery_shortcode', 'img_caption_shortcode', 'wp_audio_shortcode', 'wp_video_shortcode',
			'wp_playlist_shortcode', 'wp_playlist_scripts', 'wp_underscore_playlist_templates',
		],
		'MediaUpload'     => [
			'media_handle_upload', 'media_handle_sideload', 'media_sideload_image', 'wp_read_audio_metadata',
			'wp_read_video_metadata', 'wp_add_id3_tag_data', 'wp_get_media_creation_timestamp', 'media_buttons',
			'get_upload_iframe_src', 'wp_iframe', 'media_upload_tabs', 'the_media_upload_tabs', 'media_upload_header',
			'media_upload_form', 'get_attachment_fields_to_edit', 'get_compat_media_markup', 'get_image_send_to_editor',
			'media_send_to_editor',
		],
		'Meta'            => [
			'get_metadata', 'get_metadata_raw', 'get_metadata_default', 'add_metadata', 'update_metadata',
			'delete_metadata', 'metadata_exists', 'get_metadata_by_mid', 'update_metadata_by_mid',
			'delete_metadata_by_mid', 'update_meta_cache', 'wp_metadata_lazyloader', 'get_meta_sql',
			'is_protected_meta', 'sanitize_meta', 'register_meta', 'unregister_meta_key', 'registered_meta_key_exists',
			'get_registered_meta_keys', 'get_registered_metadata', 'get_object_subtype',
		],
		'MetaBoxes'       => [
			'add_meta_box', 'do_accordion_sections', 'do_block_editor_incompatible_meta_box', 'do_meta_boxes',
			'remove_meta_box', 'postbox_classes', 'wp_add_dashboard_widget',
		],
		'MimeTypes'       => [
			'wp_get_mime_types', 'get_allowed_mime_types', 'wp_check_filetype', 'wp_check_filetype_and_ext',
			'wp_get_ext_types', 'wp_ext2type', 'wp_get_default_extension_for_mime_type', 'wp_get_image_mime',
			'wp_is_heic_image_mime_type',
		],
		'MultisiteUsers'  => [
			'add_user_to_blog', 'remove_user_from_blog', 'add_existing_user_to_blog', 'get_active_blog_for_user',
			'get_most_recent_post_of_user', 'is_user_spammy', 'is_email_address_unsafe', 'refresh_user_details',
			'wpmu_create_user', 'wpmu_delete_user', 'wpmu_validate_user_signup', 'wpmu_validate_blog_signup',
			'wpmu_signup_user', 'wpmu_signup_blog', 'wpmu_activate_signup', 'wpmu_signup_user_notification',
			'wpmu_signup_blog_notification', 'wpmu_welcome_user_notification', 'wpmu_welcome_notification',
			'newuser_notify_siteadmin', 'newblog_notify_siteadmin', 'wpmu_new_site_admin_notification',
		],
		'NavMenus'        => [
			'walk_nav_menu_tree', 'wp_nav_menu', 'wp_nav_menu_remove_menu_item_has_children_class',
			'register_nav_menus', 'register_nav_menu', 'unregister_nav_menu', 'get_registered_nav_menus',
			'get_nav_menu_locations', 'has_nav_menu', 'wp_map_nav_menu_locations', 'is_nav_menu', 'is_nav_menu_item',
			'wp_get_nav_menus', 'wp_get_nav_menu_object', 'wp_get_nav_menu_name', 'wp_get_nav_menu_items',
			'wp_get_associated_nav_menu_items', 'wp_setup_nav_menu_item', 'update_menu_item_cache',
			'wp_create_nav_menu', 'wp_update_nav_menu_object', 'wp_delete_nav_menu', 'wp_update_nav_menu_item',
		],
		// Moving between posts, pages of posts and pages of comments.
		'Navigation'      => [
			'adjacent_post_link', 'adjacent_posts_rel_link', 'get_adjacent_post', 'get_adjacent_post_link',
			'get_adjacent_post_rel_link', 'get_boundary_post', 'get_comments_pagenum_link', 'get_next_comments_link',
			'get_next_post', 'get_next_post_link', 'get_next_posts_link', 'get_next_posts_page_link',
			'get_pagenum_link', 'get_posts_nav_link', 'get_previous_comments_link', 'get_previous_post',
			'get_previous_post_link', 'get_previous_posts_link', 'get_previous_posts_page_link',
			'get_the_comments_navigation', 'get_the_comments_pagination', 'get_the_post_navigation',
			'get_the_posts_navigation', 'get_the_posts_pagination', 'next_comments_link', 'next_post_link',
			'next_post_rel_link', 'next_posts', 'next_posts_link', 'paginate_comments_links', 'paginate_links',
			'posts_nav_link', 'prev_post_rel_link', 'previous_comments_link', 'previous_post_link', 'previous_posts',
			'previous_posts_link', 'the_comments_navigation', 'the_comments_pagination', 'the_post_navigation',
			'the_posts_navigation', 'the_posts_pagination', 'wp_link_pages', 'get_adjacent_image_link',
			'get_previous_image_link', 'get_next_image_link', 'adjacent_image_link', 'previous_image_link',
			'next_image_link',
		],
		'Networks'        => [
			'get_network', 'get_networks', 'get_network_by_path', 'get_current_site', 'is_subdomain_install',
			'can_edit_network', 'wp_is_large_network', 'get_blog_count', 'get_sitestats', 'wp_update_network_counts',
			'wp_update_network_site_counts', 'wp_update_network_user_counts', 'update_network_cache',
			'clean_network_cache', 'get_current_network_id', 'get_main_network_id', 'is_main_network',
		],
		'Nonces'          => [
			'wp_nonce_url', 'wp_nonce_field', 'wp_nonce_ays', 'wp_referer_field', 'wp_original_referer_field',
			'wp_get_referer', 'wp_get_raw_referer', 'wp_get_original_referer', 'wp_create_nonce', 'wp_verify_nonce',
			'wp_nonce_tick', 'check_admin_referer', 'check_ajax_referer',
		],
		'Options'         => [
			'get_option', 'get_options', 'add_option', 'update_option', 'delete_option', 'wp_load_alloptions',
			'wp_prime_option_caches', 'wp_set_option_autoload', 'wp_set_options_autoload',
			'wp_set_option_autoload_values', 'wp_protect_special_option', 'get_site_option', 'add_site_option',
			'update_site_option', 'delete_site_option', 'wp_prime_site_option_caches', 'wp_load_core_site_options',
			'get_network_option', 'add_network_option', 'update_network_option', 'delete_network_option',
			'wp_prime_network_option_caches', 'form_option', 'wp_prime_option_caches_by_group',
			'wp_autoload_values_to_autoload',
		],
		'Passwords'       => [
			'wp_hash_password', 'wp_check_password', 'wp_password_needs_rehash', 'wp_set_password',
			'wp_generate_password', 'wp_rand', 'wp_get_password_hint', 'get_password_reset_key',
			'check_password_reset_key', 'reset_password', 'retrieve_password', 'wp_is_password_reset_allowed_for_user',
			'wp_is_application_passwords_supported', 'wp_is_application_passwords_available',
			'wp_is_application_passwords_available_for_user',
		],
		'Permalinks'      => [
			'get_attachment_link', 'get_category_link', 'get_day_link', 'get_month_link', 'get_page_link',
			'get_permalink', 'get_post_permalink', 'get_post_type_archive_link', 'get_preview_post_link',
			'get_tag_link', 'get_the_permalink', 'get_year_link', 'permalink_anchor', 'the_permalink', 'the_shortlink',
			'wp_force_plain_post_permalink', 'wp_get_canonical_url', 'wp_get_shortlink',
		],
		'Plugins'         => [
			'plugin_basename', 'wp_register_plugin_realpath', 'plugin_dir_path', 'plugin_dir_url',
			'register_activation_hook', 'register_deactivation_hook', 'register_uninstall_hook', 'get_plugin_data',
			'_get_plugin_data_markup_translate', 'get_plugin_files', 'get_plugins', 'get_mu_plugins',
			'_sort_uname_callback', 'get_dropins', '_get_dropins', 'is_plugin_active', 'is_plugin_inactive',
			'is_plugin_active_for_network', 'is_network_only_plugin', 'activate_plugin', 'deactivate_plugins',
			'activate_plugins', 'delete_plugins', 'validate_active_plugins', 'validate_plugin',
			'validate_plugin_requirements', 'is_uninstallable_plugin', 'uninstall_plugin', 'add_menu_page',
			'add_submenu_page', 'add_management_page', 'add_options_page', 'add_theme_page', 'add_plugins_page',
			'add_users_page', 'add_dashboard_page', 'add_posts_page', 'add_media_page', 'add_links_page',
			'add_pages_page', 'add_comments_page', 'remove_menu_page', 'remove_submenu_page', 'menu_page_url',
			'get_admin_page_parent', 'get_admin_page_title', 'get_plugin_page_hook', 'get_plugin_page_hookname',
			'user_can_access_admin_page', 'option_update_filter', 'add_allowed_options', 'remove_allowed_options',
			'settings_fields', 'wp_clean_plugins_cache', 'plugin_sandbox_scrape', 'wp_add_privacy_policy_content',
			'is_plugin_paused', 'wp_get_plugin_error', 'resume_plugin', 'paused_plugins_notice',
			'deactivated_plugins_notice', 'plugins_api', 'install_plugin_install_status', 'wp_get_plugin_action_button',
			'install_popular_tags',
		],
		'PostAttachments' => [
			'get_attached_file', 'update_attached_file', 'wp_count_attachments', 'is_local_attachment',
			'wp_insert_attachment', 'wp_delete_attachment', 'wp_delete_attachment_files', 'wp_get_attachment_metadata',
			'wp_update_attachment_metadata', 'wp_get_attachment_url', 'wp_get_attachment_caption',
			'wp_get_attachment_thumb_file', 'wp_get_attachment_thumb_url', 'wp_attachment_is', 'wp_attachment_is_image',
			'clean_attachment_cache', 'attachment_url_to_postid', 'get_attached_media', 'get_attachment_taxonomies',
			'get_taxonomies_for_attachments', 'wp_get_attachment_id3_keys', 'wp_maybe_generate_attachment_metadata',
			'wp_prepare_attachment_for_js',
		],
		'PostFormats'     => [
			'get_post_format', 'has_post_format', 'set_post_format', 'get_post_format_slugs', 'get_post_format_strings',
			'get_post_format_string', 'get_post_format_link',
		],
		'PostMeta'        => [
			'add_post_meta', 'delete_post_meta', 'get_post_meta', 'update_post_meta', 'delete_post_meta_by_key',
			'register_post_meta', 'unregister_post_meta', 'get_post_custom', 'get_post_custom_keys',
			'get_post_custom_values', 'update_postmeta_cache', 'add_meta', 'update_meta', 'delete_meta', 'has_meta',
			'get_post_meta_by_id', 'get_meta_keys',
		],
		'PostStatuses'    => [
			'get_post_status', 'get_post_statuses', 'get_page_statuses', 'register_post_status',
			'get_post_status_object', 'get_post_stati', 'is_post_status_viewable',
		],
		'PostTemplate'    => [
			'body_class', 'get_body_class', 'get_page_template_slug', 'get_post_class', 'get_post_datetime',
			'get_post_modified_time', 'get_post_parent', 'get_post_time', 'get_post_timestamp', 'get_the_content',
			'get_the_date', 'get_the_excerpt', 'get_the_guid', 'get_the_ID', 'get_the_modified_date',
			'get_the_modified_time', 'get_the_password_form', 'get_the_time', 'get_the_title', 'has_excerpt',
			'has_post_parent', 'is_page_template', 'post_class', 'post_custom', 'post_password_required',
			'prepend_attachment', 'the_attachment_link', 'the_content', 'the_date', 'the_date_xml', 'the_excerpt',
			'the_guid', 'the_ID', 'the_modified_date', 'the_modified_time', 'the_time', 'the_title',
			'the_title_attribute', 'the_weekday', 'the_weekday_date', 'walk_page_dropdown_tree', 'walk_page_tree',
			'wp_dropdown_pages', 'wp_get_attachment_link', 'wp_list_pages', 'wp_list_post_revisions', 'wp_page_menu',
			'wp_post_revision_title', 'wp_post_revision_title_expanded', 'is_new_day',
		],
		'PostThumbnails'  => [
			'get_post_thumbnail_id', 'get_the_post_thumbnail', 'get_the_post_thumbnail_caption',
			'get_the_post_thumbnail_url', 'has_post_thumbnail', 'the_post_thumbnail', 'the_post_thumbnail_caption',
			'the_post_thumbnail_url', 'update_post_thumbnail_cache', 'set_post_thumbnail_size',
		],
		'PostTypes'       => [
			'is_post_type_hierarchical', 'post_type_exists', 'get_post_type', 'get_post_type_object', 'get_post_types',
			'register_post_type', 'unregister_post_type', 'get_post_type_capabilities', 'add_post_type_support',
			'remove_post_type_support', 'get_all_post_type_supports', 'post_type_supports', 'get_post_types_by_support',
			'set_post_type', 'is_post_type_viewable', 'create_initial_post_types',
		],
		'Posts'           => [
			'get_children', 'get_extended', 'get_post', 'get_post_ancestors', 'get_post_field', 'get_post_mime_type',
			'is_post_publicly_viewable', 'get_posts', 'is_sticky', 'sanitize_post', 'sanitize_post_field', 'stick_post',
			'unstick_post', 'wp_count_posts', 'get_post_mime_types', 'wp_match_mime_types', 'wp_post_mime_type_where',
			'wp_delete_post', 'wp_trash_post', 'wp_untrash_post', 'wp_trash_post_comments', 'wp_untrash_post_comments',
			'wp_get_post_categories', 'wp_get_post_tags', 'wp_get_post_terms', 'wp_get_recent_posts', 'wp_insert_post',
			'wp_update_post', 'wp_publish_post', 'check_and_publish_future_post', 'wp_resolve_post_date',
			'wp_unique_post_slug', 'wp_add_post_tags', 'wp_set_post_tags', 'wp_set_post_terms',
			'wp_set_post_categories', 'wp_transition_post_status', 'wp_after_insert_post', 'add_ping', 'get_enclosed',
			'get_pung', 'get_to_ping', 'trackback_url_list', 'get_all_page_ids', 'get_page', 'get_page_by_path',
			'get_page_by_title', 'get_page_children', 'get_page_hierarchy', 'get_page_uri', 'get_pages',
			'wp_mime_type_icon', 'wp_check_for_changed_slugs', 'wp_check_for_changed_dates',
			'get_private_posts_cap_sql', 'get_posts_by_author_sql', 'get_lastpostdate', 'get_lastpostmodified',
			'update_post_cache', 'clean_post_cache', 'update_post_caches', 'wp_get_post_parent_id',
			'wp_check_post_hierarchy_for_loops', 'set_post_thumbnail', 'delete_post_thumbnail', 'wp_delete_auto_drafts',
			'wp_queue_posts_for_term_meta_lazyload', 'wp_cache_set_posts_last_changed', 'get_available_post_mime_types',
			'wp_get_original_image_path', 'wp_get_original_image_url', 'wp_untrash_post_set_previous_status',
			'is_post_embeddable', 'update_post_author_caches', 'update_post_parent_caches', 'do_enclose',
		],
		'Privacy'         => [
			'wp_privacy_generate_personal_data_export_group_html', 'wp_privacy_send_personal_data_export_email',
			'wp_privacy_anonymize_data', 'wp_privacy_anonymize_ip', 'wp_privacy_exports_dir', 'wp_privacy_exports_url',
			'wp_create_user_request', 'wp_get_user_request', 'wp_send_user_request', 'wp_generate_user_request_key',
			'wp_validate_user_request_key', 'wp_user_request_action_description',
		],
		'Query'           => [
			'get_query_var', 'set_query_var', 'query_posts', 'wp_reset_query', 'wp_reset_postdata',
			'get_queried_object', 'get_queried_object_id', 'is_main_query', 'have_posts', 'in_the_loop', 'rewind_posts',
			'the_post', 'setup_postdata', 'generate_postdata', 'have_comments', 'the_comment', 'is_404', 'is_archive',
			'is_attachment', 'is_author', 'is_category', 'is_comment_feed', 'is_date', 'is_day', 'is_embed',
			'is_favicon', 'is_feed', 'is_front_page', 'is_home', 'is_month', 'is_page', 'is_paged',
			'is_post_type_archive', 'is_preview', 'is_privacy_policy', 'is_robots', 'is_search', 'is_single',
			'is_singular', 'is_sitemap', 'is_tag', 'is_tax', 'is_time', 'is_trackback', 'is_year',
		],
		'Redirects'       => [
			'wp_redirect', 'wp_safe_redirect', 'wp_sanitize_redirect', 'wp_validate_redirect',
		],
		'RestApi'         => [
			'register_rest_route', 'register_rest_field', 'rest_get_server', 'rest_do_request', 'rest_ensure_request',
			'rest_ensure_response', 'rest_convert_error_to_response', 'rest_authorization_required_code',
			'rest_get_authenticated_app_password', 'wp_is_rest_endpoint', 'rest_get_url_prefix', 'get_rest_url',
			'rest_url', 'rest_get_route_for_post', 'rest_get_route_for_post_type_items', 'rest_get_route_for_term',
			'rest_get_route_for_taxonomy_items', 'rest_get_queried_resource_route', 'rest_preload_api_request',
			'rest_parse_embed_param', 'rest_filter_response_by_context', 'rest_is_field_included',
			'rest_get_avatar_sizes', 'rest_get_avatar_urls', 'rest_parse_date', 'rest_get_date_with_gmt',
			'rest_parse_hex_color', 'rest_is_ip_address', 'rest_is_boolean', 'rest_is_integer', 'rest_is_array',
			'rest_is_object', 'rest_sanitize_boolean', 'rest_sanitize_array', 'rest_sanitize_object',
			'rest_parse_request_arg', 'rest_sanitize_request_arg', 'rest_validate_request_arg',
			'rest_get_endpoint_args_for_schema', 'rest_get_allowed_schema_keywords',
			'rest_default_additional_properties_to_false', 'rest_validate_value_from_schema',
			'rest_sanitize_value_from_schema', 'rest_validate_array_value_from_schema',
			'rest_validate_object_value_from_schema', 'rest_validate_null_value_from_schema',
			'rest_validate_boolean_value_from_schema', 'rest_validate_number_value_from_schema',
			'rest_validate_string_value_from_schema', 'rest_validate_integer_value_from_schema', 'rest_validate_enum',
			'rest_validate_json_schema_pattern', 'rest_validate_array_contains_unique_items',
			'rest_get_best_type_for_value', 'rest_handle_multi_type_schema',
			'rest_find_matching_pattern_property_schema', 'rest_find_any_matching_schema',
			'rest_find_one_matching_schema', 'rest_get_combining_operation_error',
			'rest_format_combining_operation_error', 'rest_are_values_equal', 'rest_stabilize_value',
		],
		'Revisions'       => [
			'wp_get_post_revision', 'wp_get_post_revisions', 'wp_get_latest_revision_id_and_total_count',
			'wp_get_post_revisions_url', 'wp_is_post_revision', 'wp_get_post_autosave', 'wp_is_post_autosave',
			'wp_revisions_enabled', 'wp_revisions_to_keep', 'wp_post_revision_meta_keys', 'wp_save_post_revision',
			'wp_restore_post_revision', 'wp_delete_post_revision', 'wp_text_diff',
		],
		'Rewrite'         => [
			'got_mod_rewrite', 'got_url_rewrite', 'save_mod_rewrite_rules', 'extract_from_markers',
			'insert_with_markers', 'iis7_save_url_rewrite_rules', 'iis7_rewrite_rule_exists', 'iis7_add_rewrite_rule',
			'iis7_delete_rewrite_rule', 'saveDomDocument', 'add_rewrite_rule', 'add_rewrite_tag', 'remove_rewrite_tag',
			'add_permastruct', 'remove_permastruct', 'add_rewrite_endpoint', 'add_feed', 'flush_rewrite_rules',
			'url_to_postid', 'wp_resolve_numeric_slug_conflicts', 'redirect_canonical', 'redirect_guess_404_permalink',
		],
		'Sanitization'    => [
			'absint', 'wp_validate_boolean', 'bool_from_yn', 'add_magic_quotes', 'sanitize_text_field',
			'sanitize_textarea_field', 'sanitize_key', 'sanitize_title', 'sanitize_title_for_query',
			'sanitize_title_with_dashes', 'sanitize_user', 'sanitize_email', 'is_email', 'sanitize_url',
			'sanitize_file_name', 'sanitize_html_class', 'sanitize_mime_type', 'sanitize_locale_name',
			'sanitize_option', 'sanitize_sql_orderby', 'sanitize_trackback_urls', 'sanitize_hex_color',
			'sanitize_hex_color_no_hash', 'maybe_hash_hex_color',
		],
		'Screen'          => [
			'get_current_screen', 'set_current_screen', 'add_screen_option', 'convert_to_screen',
			'register_column_headers', 'get_column_headers', 'print_column_headers', 'get_hidden_columns',
			'get_hidden_meta_boxes', 'meta_box_prefs',
		],
		'Search'          => [
			'get_search_form', 'get_search_link', 'get_search_query', 'the_search_query',
		],
		'Serialization'   => [
			'maybe_serialize', 'maybe_unserialize', 'is_serialized', 'is_serialized_string',
		],
		'Settings'        => [
			'add_settings_error', 'add_settings_field', 'add_settings_section', 'do_settings_fields',
			'do_settings_sections', 'get_settings_errors', 'settings_errors', 'register_setting', 'unregister_setting',
			'get_registered_settings',
		],
		'Shortcodes'      => [
			'get_tag_regex', 'add_shortcode', 'remove_shortcode', 'remove_all_shortcodes', 'shortcode_exists',
			'has_shortcode', 'get_shortcode_tags_in_content', 'do_shortcode', 'apply_shortcodes',
			'do_shortcodes_in_html_tags', 'unescape_invalid_shortcodes', 'shortcode_atts', 'shortcode_parse_atts',
			'get_shortcode_regex', 'get_shortcode_atts_regex', 'strip_shortcodes', 'strip_shortcode_tag',
		],
		'SiteHealth'      => [
			'wp_get_update_php_url', 'wp_get_update_php_annotation', 'wp_update_php_annotation',
			'wp_get_direct_php_update_url', 'wp_direct_php_update_button', 'wp_get_update_https_url',
			'wp_get_direct_update_https_url',
		],
		'SiteIdentity'    => [
			'bloginfo', 'get_bloginfo', 'get_custom_logo', 'get_language_attributes', 'get_site_icon_url',
			'has_custom_logo', 'has_site_icon', 'language_attributes', 'site_icon_url', 'the_custom_logo',
			'wp_site_icon',
		],
		'Sitemaps'        => [
			'wp_sitemaps_get_server', 'wp_get_sitemap_providers', 'wp_register_sitemap_provider',
			'wp_sitemaps_get_max_urls', 'get_sitemap_url',
		],
		'Sites'           => [
			'get_site', 'get_sites', 'get_site_by_path', 'get_blog_details', 'refresh_blog_details',
			'update_blog_details', 'get_blog_id_from_url', 'get_id_from_blogname', 'domain_exists',
			'get_blogaddress_by_id', 'get_blogaddress_by_name', 'get_subdirectory_reserved_names', 'wp_insert_site',
			'wp_update_site', 'wp_delete_site', 'wp_prepare_site_data', 'wp_initialize_site', 'wp_uninitialize_site',
			'wp_is_site_initialized', 'wpmu_create_blog', 'wpmu_delete_blog', 'wp_count_sites', 'get_blog_status',
			'update_blog_status', 'is_archived', 'update_archived', 'get_last_updated', 'wpmu_update_blogs_date',
			'update_posts_count', 'switch_to_blog', 'restore_current_blog', 'ms_is_switched',
			'wp_cache_switch_to_blog_fallback', 'get_blog_option', 'add_blog_option', 'update_blog_option',
			'delete_blog_option', 'add_site_meta', 'get_site_meta', 'update_site_meta', 'delete_site_meta',
			'delete_site_meta_by_key', 'update_sitemeta_cache', 'wp_lazyload_site_meta',
			'wp_check_site_meta_support_prefilter', 'get_blog_post', 'get_blog_permalink', 'get_space_allowed',
			'get_space_used', 'get_upload_space_available', 'is_upload_space_available', 'upload_is_user_over_quota',
			'display_space_usage', 'update_site_cache', 'clean_blog_cache', 'clean_site_details_cache',
			'wp_cache_set_sites_last_changed', 'is_multisite', 'get_current_blog_id', 'get_main_site_id',
			'is_main_site', 'is_site_meta_supported',
		],
		'StyleEngine'     => [
			'wp_style_engine_get_styles', 'wp_style_engine_get_stylesheet_from_css_rules',
			'wp_style_engine_get_stylesheet_from_context',
		],
		'Tags'            => [
			'get_tags', 'get_tag', 'tag_exists', 'get_tags_to_edit', 'wp_create_tag',
		],
		'Taxonomies'      => [
			'create_initial_taxonomies', 'get_taxonomies', 'get_object_taxonomies', 'get_taxonomy', 'taxonomy_exists',
			'is_taxonomy_hierarchical', 'register_taxonomy', 'unregister_taxonomy', 'get_taxonomy_labels',
			'register_taxonomy_for_object_type', 'unregister_taxonomy_for_object_type', 'get_objects_in_term',
			'get_tax_sql', 'get_term', 'get_term_by', 'get_term_children', 'get_term_field', 'get_term_to_edit',
			'get_terms', 'add_term_meta', 'delete_term_meta', 'get_term_meta', 'update_term_meta',
			'update_termmeta_cache', 'has_term_meta', 'register_term_meta', 'unregister_term_meta', 'term_exists',
			'term_is_ancestor_of', 'sanitize_term', 'sanitize_term_field', 'wp_count_terms',
			'wp_delete_object_term_relationships', 'wp_delete_term', 'wp_delete_category', 'wp_get_object_terms',
			'wp_insert_term', 'wp_set_object_terms', 'wp_add_object_terms', 'wp_remove_object_terms',
			'wp_unique_term_slug', 'wp_update_term', 'wp_defer_term_counting', 'wp_update_term_count',
			'wp_update_term_count_now', 'clean_object_term_cache', 'clean_term_cache', 'clean_taxonomy_cache',
			'get_object_term_cache', 'update_object_term_cache', 'update_term_cache', '_update_generic_term_count',
			'_split_shared_term', '_wp_batch_split_terms', '_wp_check_for_scheduled_split_terms',
			'_wp_check_split_default_terms', '_wp_check_split_terms_in_menus', '_wp_check_split_nav_menu_terms',
			'wp_get_split_terms', 'wp_get_split_term', 'wp_term_is_shared', 'get_term_link', 'the_taxonomies',
			'get_the_taxonomies', 'get_post_taxonomies', 'is_object_in_term', 'is_object_in_taxonomy', 'get_ancestors',
			'wp_get_term_taxonomy_parent_id', 'wp_check_term_hierarchy_for_loops', 'is_taxonomy_viewable',
			'wp_cache_set_terms_last_changed', 'wp_check_term_meta_support_prefilter', 'is_term_publicly_viewable',
			'get_terms_to_edit', 'wp_create_term', 'wp_lazyload_term_meta',
		],
		// Theme template files: the template hierarchy and template parts.
		'Templates'       => [
			'get_404_template', 'get_archive_template', 'get_attachment_template', 'get_author_template',
			'get_category_template', 'get_date_template', 'get_embed_template', 'get_footer', 'get_front_page_template',
			'get_header', 'get_home_template', 'get_index_template', 'get_page_template', 'get_parent_theme_file_path',
			'get_parent_theme_file_uri', 'get_post_type_archive_template', 'get_privacy_policy_template',
			'get_query_template', 'get_search_template', 'get_sidebar', 'get_single_template', 'get_singular_template',
			'get_tag_template', 'get_taxonomy_template', 'get_template_part', 'get_theme_file_path',
			'get_theme_file_uri', 'load_template', 'locate_template', 'wp_finalize_template_enhancement_output_buffer',
			'wp_set_template_globals', 'wp_should_output_buffer_template_for_enhancement',
			'wp_start_template_enhancement_output_buffer',
		],
		'TermTemplate'    => [
			'category_description', 'default_topic_count_scale', 'get_category_parents', 'get_term_parents_list',
			'get_the_category', 'get_the_category_by_ID', 'get_the_category_list', 'get_the_tag_list', 'get_the_tags',
			'get_the_term_list', 'get_the_terms', 'has_category', 'has_tag', 'has_term', 'in_category',
			'tag_description', 'term_description', 'the_category', 'the_tags', 'the_terms',
			'walk_category_dropdown_tree', 'walk_category_tree', 'wp_dropdown_categories', 'wp_generate_tag_cloud',
			'wp_list_categories', 'wp_tag_cloud',
		],
		'ThemeTemplate'   => [
			'get_custom_header', 'has_custom_header', 'get_custom_header_markup', 'the_custom_header_markup',
			'has_header_image', 'get_header_image', 'header_image', 'get_header_image_tag', 'the_header_image_tag',
			'get_random_header_image', 'is_random_header_image', 'display_header_text', 'get_header_textcolor',
			'header_textcolor', 'has_header_video', 'is_header_video_active', 'get_header_video_url',
			'the_header_video_url', 'get_header_video_settings', 'get_background_color', 'background_color',
			'get_background_image', 'background_image',
		],
		'Themes'          => [
			'themes_api', 'get_theme_feature_list', 'wp_prepare_themes_for_js', 'get_page_templates', 'delete_theme',
			'is_theme_paused', 'wp_get_theme_error', 'resume_theme', 'wp_get_theme', 'wp_get_themes',
			'wp_is_block_theme', 'is_child_theme', 'switch_theme', 'validate_current_theme',
			'validate_theme_requirements', 'wp_clean_themes_cache', 'get_stylesheet', 'get_stylesheet_directory',
			'get_stylesheet_directory_uri', 'get_stylesheet_uri', 'get_locale_stylesheet_uri', 'get_template',
			'get_template_directory', 'get_template_directory_uri', 'get_theme_root', 'get_theme_root_uri',
			'get_raw_theme_root', 'get_theme_roots', 'register_theme_directory', 'search_theme_directories',
			'get_theme_mod', 'get_theme_mods', 'set_theme_mod', 'remove_theme_mod', 'remove_theme_mods',
			'add_theme_support', 'remove_theme_support', 'current_theme_supports', 'get_theme_support',
			'require_if_theme_supports', 'register_theme_feature', 'get_registered_theme_feature',
			'get_registered_theme_features', 'add_editor_style', 'remove_editor_styles', 'get_editor_stylesheets',
			'register_default_headers', 'unregister_default_headers', 'get_uploaded_header_images',
			'get_theme_starter_content', 'wp_get_custom_css', 'wp_get_custom_css_post', 'wp_update_custom_css_post',
			'is_customize_preview', 'wp_customize_url', 'wp_customize_support_script',
		],
		'Transient'       => [
			'get_transient', 'set_transient', 'delete_transient', 'get_site_transient', 'set_site_transient',
			'delete_site_transient', 'delete_expired_transients',
		],
		'Updates'         => [
			'get_core_updates', 'find_core_update', 'find_core_auto_update', 'get_preferred_from_update_core',
			'dismiss_core_update', 'undismiss_core_update', 'get_core_checksums', 'get_plugin_updates',
			'get_theme_updates', 'get_theme_update_available', 'theme_update_available',
			'wp_is_auto_update_enabled_for_type', 'wp_is_auto_update_forced_for_item', 'wp_get_auto_update_message',
			'wp_check_php_version', 'wp_version_check', 'wp_update_plugins', 'wp_update_themes',
			'wp_get_translation_updates', 'wp_get_update_data', 'wp_clean_update_cache',
		],
		'Urls'            => [
			'admin_url', 'content_url', 'get_admin_url', 'get_dashboard_url', 'get_edit_profile_url', 'get_home_url',
			'get_privacy_policy_url', 'get_site_url', 'get_the_privacy_policy_link', 'home_url', 'includes_url',
			'network_admin_url', 'network_home_url', 'network_site_url', 'plugins_url', 'self_admin_url',
			'set_url_scheme', 'site_url', 'the_privacy_policy_link', 'user_admin_url', 'user_trailingslashit',
			'wp_internal_hosts', 'wp_is_internal_link', 'force_ssl_content', 'filter_SSL', 'add_query_arg',
			'remove_query_arg', 'build_query', 'wp_removable_query_args', 'wp_extract_urls', 'wp_allowed_protocols',
			'wp_guess_url', 'wp_parse_url', 'strip_fragment_from_url', 'wp_make_link_relative', 'url_shorten',
			'utf8_uri_encode', 'wp_parse_str',
		],
		'UserSettings'    => [
			'get_user_setting', 'set_user_setting', 'delete_user_setting', 'get_all_user_settings',
			'delete_all_user_settings', 'wp_user_settings',
		],
		'Users'           => [
			'get_current_user_id', 'wp_get_current_user', 'wp_set_current_user', 'is_user_logged_in', 'get_userdata',
			'get_user_by', 'get_user', 'get_users', 'cache_users', 'count_users', 'get_user_count',
			'wp_is_large_user_count', 'wp_update_user_counts', 'count_user_posts', 'count_many_users_posts',
			'wp_get_users_with_no_role', 'username_exists', 'email_exists', 'validate_username', 'sanitize_user_field',
			'wp_insert_user', 'wp_update_user', 'wp_create_user', 'register_new_user', 'wp_new_user_notification',
			'get_user_meta', 'add_user_meta', 'update_user_meta', 'delete_user_meta', 'get_user_option',
			'update_user_option', 'delete_user_option', 'clean_user_cache', 'update_user_caches', 'setup_userdata',
			'get_blogs_of_user', 'is_user_member_of_blog', 'wp_get_user_contact_methods',
		],
		'Widgets'         => [
			'register_widget', 'unregister_widget', 'the_widget', 'is_active_widget', 'wp_widget_description',
			'wp_parse_widget_id', 'wp_register_sidebar_widget', 'wp_unregister_sidebar_widget',
			'wp_register_widget_control', 'wp_unregister_widget_control', 'wp_render_widget',
			'wp_render_widget_control', 'wp_convert_widget_settings', 'wp_find_widgets_sidebar',
			'wp_assign_widget_to_sidebar', 'retrieve_widgets', 'wp_map_sidebars_widgets', 'wp_use_widgets_block_editor',
			'register_sidebar', 'register_sidebars', 'unregister_sidebar', 'is_registered_sidebar', 'wp_get_sidebar',
			'wp_sidebar_description', 'is_active_sidebar', 'is_dynamic_sidebar', 'dynamic_sidebar',
			'wp_widget_rss_output', 'wp_widget_rss_form', 'wp_widget_rss_process',
		],
	],

	// Service => function names, or /regex/ matched against the name.
	'planned'      => [],

	// Function => [ parameter => type, 'return' => type ].
	'types'        => [
		'add_action' => [ 'hook_name' => 'string', 'callback' => 'callable', 'priority' => 'int', 'accepted_args' => 'int', 'return' => 'bool' ],
		'add_filter' => [ 'hook_name' => 'string', 'callback' => 'callable', 'priority' => 'int', 'accepted_args' => 'int', 'return' => 'bool' ],
		'apply_filters' => [ 'hook_name' => 'string' ],
		'apply_filters_deprecated' => [ 'hook_name' => 'string', 'args' => 'array', 'version' => 'string', 'replacement' => 'string', 'message' => 'string' ],
		'apply_filters_ref_array' => [ 'hook_name' => 'string', 'args' => 'array' ],
		'delete_transient' => [ 'transient' => 'string', 'return' => 'bool' ],
		'did_action' => [ 'hook_name' => 'string', 'return' => 'int' ],
		'do_action' => [ 'hook_name' => 'string' ],
		'do_action_deprecated' => [ 'hook_name' => 'string', 'args' => 'array', 'version' => 'string', 'replacement' => 'string', 'message' => 'string' ],
		'do_action_ref_array' => [ 'hook_name' => 'string', 'args' => 'array' ],
		'doing_action' => [ 'return' => 'bool' ],
		'doing_filter' => [ 'return' => 'bool' ],
		'get_attached_file' => [ 'attachment_id' => 'int' ],
		'get_children' => [ 'output' => 'string' ],
		'get_transient' => [ 'transient' => 'string' ],
		'has_action' => [ 'hook_name' => 'string' ],
		'has_filter' => [ 'hook_name' => 'string' ],
		'plugin_basename' => [ 'file' => 'string', 'return' => 'string' ],
		'plugin_dir_path' => [ 'file' => 'string', 'return' => 'string' ],
		'plugin_dir_url' => [ 'file' => 'string', 'return' => 'string' ],
		'register_activation_hook' => [ 'file' => 'string', 'callback' => 'callable' ],
		'register_deactivation_hook' => [ 'file' => 'string', 'callback' => 'callable' ],
		'register_post_meta' => [ 'args' => 'array' ],
		'register_term_meta' => [ 'args' => 'array' ],
		'register_uninstall_hook' => [ 'file' => 'string', 'callback' => 'callable' ],
		'remove_action' => [ 'hook_name' => 'string', 'callback' => 'callable', 'priority' => 'int', 'return' => 'bool' ],
		'remove_all_actions' => [ 'hook_name' => 'string' ],
		'remove_all_filters' => [ 'hook_name' => 'string', 'return' => 'bool' ],
		'remove_filter' => [ 'hook_name' => 'string', 'callback' => 'callable', 'priority' => 'int', 'return' => 'bool' ],
		'set_transient' => [ 'transient' => 'string', 'expiration' => 'int', 'return' => 'bool' ],
		'update_attached_file' => [ 'attachment_id' => 'int', 'file' => 'string' ],
		'wp_add_inline_script' => [ 'handle' => 'string', 'data' => 'string', 'position' => 'string', 'return' => 'bool' ],
		'wp_enqueue_script' => [ 'handle' => 'string', 'src' => 'string', 'deps' => 'array', 'return' => 'void' ],
		'wp_enqueue_style' => [ 'handle' => 'string', 'src' => 'string', 'deps' => 'array', 'media' => 'string', 'return' => 'void' ],
		'wp_register_plugin_realpath' => [ 'file' => 'string', 'return' => 'bool' ],
	],

	'extendable'   => [ 'Assets', 'Capabilities', 'Comments' ],

	// Function name, or /regex/ matched against it => reason.
	'ignore'       => [
		'/^wp_ajax_/' => 'admin AJAX handler',
		'/^upgrade_\d+$/' => 'database upgrade step',

		// PHP polyfill
		'stripos' => 'PHP polyfill',

		// admin screen internals
		'add_cssclass' => 'admin screen internals',
		'add_link' => 'admin screen internals',
		'add_menu_classes' => 'admin screen internals',
		'add_user' => 'admin screen internals',
		'attachment_id3_data_meta_box' => 'admin screen internals',
		'attachment_submit_meta_box' => 'admin screen internals',
		'attachment_submitbox_metadata' => 'admin screen internals',
		'choose_primary_blog' => 'admin screen internals',
		'comment_footer_die' => 'admin screen internals',
		'confirm_delete_users' => 'admin screen internals',
		'display_plugins_table' => 'admin screen internals',
		'display_themes' => 'admin screen internals',
		'edit_comment' => 'admin screen internals',
		'edit_form_image_editor' => 'admin screen internals',
		'edit_link' => 'admin screen internals',
		'edit_user' => 'admin screen internals',
		'enqueue_comment_hotkeys_js' => 'admin screen internals',
		'get_media_item' => 'admin screen internals',
		'get_media_items' => 'admin screen internals',
		'get_site_screen_help_sidebar_content' => 'admin screen internals',
		'get_site_screen_help_tab_args' => 'admin screen internals',
		'image_align_input_fields' => 'admin screen internals',
		'image_link_input_fields' => 'admin screen internals',
		'image_size_input_fields' => 'admin screen internals',
		'install_dashboard' => 'admin screen internals',
		'install_plugin_information' => 'admin screen internals',
		'install_plugins_favorites_form' => 'admin screen internals',
		'install_plugins_upload' => 'admin screen internals',
		'install_search_form' => 'admin screen internals',
		'install_theme_information' => 'admin screen internals',
		'install_theme_search_form' => 'admin screen internals',
		'install_themes_dashboard' => 'admin screen internals',
		'install_themes_upload' => 'admin screen internals',
		'link_advanced_meta_box' => 'admin screen internals',
		'link_categories_meta_box' => 'admin screen internals',
		'link_submit_meta_box' => 'admin screen internals',
		'link_target_meta_box' => 'admin screen internals',
		'link_xfn_meta_box' => 'admin screen internals',
		'media_upload_form_handler' => 'admin screen internals',
		'media_upload_gallery' => 'admin screen internals',
		'media_upload_gallery_form' => 'admin screen internals',
		'media_upload_library' => 'admin screen internals',
		'media_upload_library_form' => 'admin screen internals',
		'media_upload_type_form' => 'admin screen internals',
		'media_upload_type_url_form' => 'admin screen internals',
		'multisite_over_quota_message' => 'admin screen internals',
		'network_edit_site_nav' => 'admin screen internals',
		'network_step1' => 'admin screen internals',
		'network_step2' => 'admin screen internals',
		'next_widget_id_number' => 'admin screen internals',
		'options_discussion_add_js' => 'admin screen internals',
		'options_general_add_js' => 'admin screen internals',
		'options_reading_add_js' => 'admin screen internals',
		'options_reading_blog_charset' => 'admin screen internals',
		'page_attributes_meta_box' => 'admin screen internals',
		'post_author_meta_box' => 'admin screen internals',
		'post_categories_meta_box' => 'admin screen internals',
		'post_comment_meta_box' => 'admin screen internals',
		'post_comment_meta_box_thead' => 'admin screen internals',
		'post_comment_status_meta_box' => 'admin screen internals',
		'post_custom_meta_box' => 'admin screen internals',
		'post_excerpt_meta_box' => 'admin screen internals',
		'post_format_meta_box' => 'admin screen internals',
		'post_revisions_meta_box' => 'admin screen internals',
		'post_slug_meta_box' => 'admin screen internals',
		'post_submit_meta_box' => 'admin screen internals',
		'post_tags_meta_box' => 'admin screen internals',
		'post_thumbnail_meta_box' => 'admin screen internals',
		'post_trackback_meta_box' => 'admin screen internals',
		'register_and_do_post_meta_boxes' => 'admin screen internals',
		'set_screen_options' => 'admin screen internals',
		'sort_menu' => 'admin screen internals',
		'stream_preview_image' => 'admin screen internals',
		'taxonomy_meta_box_sanitize_cb_checkboxes' => 'admin screen internals',
		'taxonomy_meta_box_sanitize_cb_input' => 'admin screen internals',
		'the_block_editor_meta_box_post_form_hidden_fields' => 'admin screen internals',
		'the_block_editor_meta_boxes' => 'admin screen internals',
		'update_right_now_message' => 'admin screen internals',
		'use_ssl_preference' => 'admin screen internals',
		'wp_caption_input_textarea' => 'admin screen internals',
		'wp_check_browser_version' => 'admin screen internals',
		'wp_credits' => 'admin screen internals',
		'wp_credits_section_list' => 'admin screen internals',
		'wp_credits_section_title' => 'admin screen internals',
		'wp_dashboard' => 'admin screen internals',
		'wp_dashboard_browser_nag' => 'admin screen internals',
		'wp_dashboard_cached_rss_widget' => 'admin screen internals',
		'wp_dashboard_empty' => 'admin screen internals',
		'wp_dashboard_events_news' => 'admin screen internals',
		'wp_dashboard_php_nag' => 'admin screen internals',
		'wp_dashboard_primary' => 'admin screen internals',
		'wp_dashboard_primary_output' => 'admin screen internals',
		'wp_dashboard_quick_press' => 'admin screen internals',
		'wp_dashboard_recent_comments' => 'admin screen internals',
		'wp_dashboard_recent_drafts' => 'admin screen internals',
		'wp_dashboard_recent_posts' => 'admin screen internals',
		'wp_dashboard_right_now' => 'admin screen internals',
		'wp_dashboard_rss_control' => 'admin screen internals',
		'wp_dashboard_rss_output' => 'admin screen internals',
		'wp_dashboard_setup' => 'admin screen internals',
		'wp_dashboard_site_activity' => 'admin screen internals',
		'wp_dashboard_site_health' => 'admin screen internals',
		'wp_dashboard_trigger_widget_control' => 'admin screen internals',
		'wp_doc_link_parse' => 'admin screen internals',
		'wp_ensure_editable_role' => 'admin screen internals',
		'wp_font_library_intercept_render' => 'admin screen internals',
		'wp_font_library_preload_data' => 'admin screen internals',
		'wp_font_library_render_page' => 'admin screen internals',
		'wp_font_library_wp_admin_enqueue_scripts' => 'admin screen internals',
		'wp_font_library_wp_admin_preload_data' => 'admin screen internals',
		'wp_font_library_wp_admin_render_page' => 'admin screen internals',
		'wp_get_font_library_menu_items' => 'admin screen internals',
		'wp_get_font_library_routes' => 'admin screen internals',
		'wp_get_font_library_wp_admin_menu_items' => 'admin screen internals',
		'wp_get_font_library_wp_admin_routes' => 'admin screen internals',
		'wp_get_nav_menu_to_edit' => 'admin screen internals',
		'wp_get_options_connectors_menu_items' => 'admin screen internals',
		'wp_get_options_connectors_routes' => 'admin screen internals',
		'wp_get_options_connectors_wp_admin_menu_items' => 'admin screen internals',
		'wp_get_options_connectors_wp_admin_routes' => 'admin screen internals',
		'wp_get_revision_ui_diff' => 'admin screen internals',
		'wp_get_view_transitions_admin_css' => 'admin screen internals',
		'wp_image_editor' => 'admin screen internals',
		'wp_initial_nav_menu_meta_boxes' => 'admin screen internals',
		'wp_list_widget_controls' => 'admin screen internals',
		'wp_list_widget_controls_dynamic_sidebar' => 'admin screen internals',
		'wp_list_widgets' => 'admin screen internals',
		'wp_localize_community_events' => 'admin screen internals',
		'wp_media_attach_action' => 'admin screen internals',
		'wp_media_insert_url_form' => 'admin screen internals',
		'wp_media_upload_handler' => 'admin screen internals',
		'wp_nav_menu_disabled_check' => 'admin screen internals',
		'wp_nav_menu_item_link_meta_box' => 'admin screen internals',
		'wp_nav_menu_item_post_type_meta_box' => 'admin screen internals',
		'wp_nav_menu_item_taxonomy_meta_box' => 'admin screen internals',
		'wp_nav_menu_manage_columns' => 'admin screen internals',
		'wp_nav_menu_post_type_meta_boxes' => 'admin screen internals',
		'wp_nav_menu_setup' => 'admin screen internals',
		'wp_nav_menu_taxonomy_meta_boxes' => 'admin screen internals',
		'wp_nav_menu_update_menu_items' => 'admin screen internals',
		'wp_network_dashboard_right_now' => 'admin screen internals',
		'wp_options_connectors_intercept_render' => 'admin screen internals',
		'wp_options_connectors_preload_data' => 'admin screen internals',
		'wp_options_connectors_render_page' => 'admin screen internals',
		'wp_options_connectors_wp_admin_enqueue_scripts' => 'admin screen internals',
		'wp_options_connectors_wp_admin_preload_data' => 'admin screen internals',
		'wp_options_connectors_wp_admin_render_page' => 'admin screen internals',
		'wp_page_reload_on_back_button_js' => 'admin screen internals',
		'wp_plugin_update_row' => 'admin screen internals',
		'wp_prepare_revisions_for_js' => 'admin screen internals',
		'wp_print_admin_notice_templates' => 'admin screen internals',
		'wp_print_community_events_markup' => 'admin screen internals',
		'wp_print_community_events_templates' => 'admin screen internals',
		'wp_print_file_editor_templates' => 'admin screen internals',
		'wp_print_revision_templates' => 'admin screen internals',
		'wp_print_update_row_templates' => 'admin screen internals',
		'wp_register_font_library_menu_item' => 'admin screen internals',
		'wp_register_font_library_page_routes' => 'admin screen internals',
		'wp_register_font_library_route' => 'admin screen internals',
		'wp_register_font_library_wp_admin_menu_item' => 'admin screen internals',
		'wp_register_font_library_wp_admin_page_routes' => 'admin screen internals',
		'wp_register_font_library_wp_admin_route' => 'admin screen internals',
		'wp_register_options_connectors_menu_item' => 'admin screen internals',
		'wp_register_options_connectors_page_routes' => 'admin screen internals',
		'wp_register_options_connectors_route' => 'admin screen internals',
		'wp_register_options_connectors_wp_admin_menu_item' => 'admin screen internals',
		'wp_register_options_connectors_wp_admin_page_routes' => 'admin screen internals',
		'wp_register_options_connectors_wp_admin_route' => 'admin screen internals',
		'wp_register_page_routes' => 'admin screen internals',
		'wp_reset_vars' => 'admin screen internals',
		'wp_restore_image' => 'admin screen internals',
		'wp_save_image' => 'admin screen internals',
		'wp_save_nav_menu_items' => 'admin screen internals',
		'wp_theme_update_row' => 'admin screen internals',
		'wp_tinymce_inline_scripts' => 'admin screen internals',
		'wp_widget_control' => 'admin screen internals',
		'wpview_media_sandbox_styles' => 'admin screen internals',
		'xfn_check' => 'admin screen internals',

		// bootstrap internals
		'ms_cookie_constants' => 'bootstrap internals',
		'ms_file_constants' => 'bootstrap internals',
		'ms_site_check' => 'bootstrap internals',
		'ms_subdomain_constants' => 'bootstrap internals',
		'ms_upload_constants' => 'bootstrap internals',
		'require_wp_db' => 'bootstrap internals',
		'script_concat_settings' => 'bootstrap internals',
		'wp' => 'bootstrap internals',
		'wp_cache_init' => 'bootstrap internals',
		'wp_cookie_constants' => 'bootstrap internals',
		'wp_finalize_scraping_edited_file_errors' => 'bootstrap internals',
		'wp_functionality_constants' => 'bootstrap internals',
		'wp_initial_constants' => 'bootstrap internals',
		'wp_plugin_directory_constants' => 'bootstrap internals',
		'wp_populate_basic_auth_from_authorization_header' => 'bootstrap internals',
		'wp_register_fatal_error_handler' => 'bootstrap internals',
		'wp_skip_paused_plugins' => 'bootstrap internals',
		'wp_skip_paused_themes' => 'bootstrap internals',
		'wp_ssl_constants' => 'bootstrap internals',
		'wp_start_scraping_edited_file_errors' => 'bootstrap internals',
		'wp_templating_constants' => 'bootstrap internals',

		// bundled library
		'PclZipUtilCopyBlock' => 'bundled library',
		'PclZipUtilOptionText' => 'bundled library',
		'PclZipUtilPathInclusion' => 'bundled library',
		'PclZipUtilPathReduction' => 'bundled library',
		'PclZipUtilRename' => 'bundled library',
		'PclZipUtilTranslateWinPath' => 'bundled library',
		'read' => 'bundled library',
		'read_big_endian' => 'bundled library',
		'skip' => 'bundled library',

		// database upgrade step
		'deslash' => 'database upgrade step',
		'get_alloptions_110' => 'database upgrade step',
		'make_site_theme' => 'database upgrade step',
		'make_site_theme_from_default' => 'database upgrade step',
		'make_site_theme_from_oldschool' => 'database upgrade step',
		'maybe_disable_automattic_widgets' => 'database upgrade step',
		'maybe_disable_link_manager' => 'database upgrade step',
		'pre_schema_upgrade' => 'database upgrade step',
		'translate_level_to_role' => 'database upgrade step',
		'upgrade_230_old_tables' => 'database upgrade step',
		'upgrade_230_options_table' => 'database upgrade step',
		'upgrade_430_fix_comments' => 'database upgrade step',
		'upgrade_old_slugs' => 'database upgrade step',

		// hook callback
		'add_new_user_to_blog' => 'hook callback',
		'admin_color_scheme_picker' => 'hook callback',
		'admin_created_user_email' => 'hook callback',
		'allowed_http_request_hosts' => 'hook callback',
		'avoid_blog_page_permalink_collision' => 'hook callback',
		'check_import_new_users' => 'hook callback',
		'check_theme_switched' => 'hook callback',
		'check_upload_mimes' => 'hook callback',
		'check_upload_size' => 'hook callback',
		'core_update_footer' => 'hook callback',
		'create_initial_rest_routes' => 'hook callback',
		'create_initial_theme_features' => 'hook callback',
		'customize_themes_print_templates' => 'hook callback',
		'dashboard_browser_nag_class' => 'hook callback',
		'dashboard_php_nag_class' => 'hook callback',
		'default_password_nag' => 'hook callback',
		'default_password_nag_edit_user' => 'hook callback',
		'default_password_nag_handler' => 'hook callback',
		'do_favicon' => 'hook callback',
		'do_feed_atom' => 'hook callback',
		'do_feed_rdf' => 'hook callback',
		'do_feed_rss' => 'hook callback',
		'do_feed_rss2' => 'hook callback',
		'do_robots' => 'hook callback',
		'enqueue_block_styles_assets' => 'hook callback',
		'enqueue_editor_block_styles_assets' => 'hook callback',
		'enqueue_embed_scripts' => 'hook callback',
		'filter_default_metadata' => 'hook callback',
		'filter_default_option' => 'hook callback',
		'fix_import_form_size' => 'hook callback',
		'fix_phpmailer_messageid' => 'hook callback',
		'floated_admin_avatar' => 'hook callback',
		'get_oembed_response_data_rich' => 'hook callback',
		'heartbeat_autosave' => 'hook callback',
		'image_add_caption' => 'hook callback',
		'image_attachment_fields_to_edit' => 'hook callback',
		'image_media_send_to_editor' => 'hook callback',
		'locale_stylesheet' => 'hook callback',
		'maintenance_nag' => 'hook callback',
		'maybe_add_existing_user_to_blog' => 'hook callback',
		'maybe_redirect_404' => 'hook callback',
		'media_post_single_attachment_fields_to_edit' => 'hook callback',
		'media_single_attachment_fields_to_edit' => 'hook callback',
		'media_upload_flash_bypass' => 'hook callback',
		'media_upload_html_bypass' => 'hook callback',
		'media_upload_max_image_resize' => 'hook callback',
		'media_upload_text_after' => 'hook callback',
		'ms_allowed_http_request_hosts' => 'hook callback',
		'network_settings_add_js' => 'hook callback',
		'new_user_email_admin_notice' => 'hook callback',
		'paused_themes_notice' => 'hook callback',
		'print_admin_styles' => 'hook callback',
		'print_embed_scripts' => 'hook callback',
		'print_emoji_detection_script' => 'hook callback',
		'print_footer_scripts' => 'hook callback',
		'print_head_scripts' => 'hook callback',
		'print_late_styles' => 'hook callback',
		'redirect_this_site' => 'hook callback',
		'register_initial_settings' => 'hook callback',
		'rest_add_application_passwords_to_index' => 'hook callback',
		'rest_api_default_filters' => 'hook callback',
		'rest_api_init' => 'hook callback',
		'rest_api_loaded' => 'hook callback',
		'rest_api_register_rewrites' => 'hook callback',
		'rest_application_password_check_errors' => 'hook callback',
		'rest_application_password_collect_status' => 'hook callback',
		'rest_cookie_check_errors' => 'hook callback',
		'rest_cookie_collect_status' => 'hook callback',
		'rest_filter_response_fields' => 'hook callback',
		'rest_handle_deprecated_argument' => 'hook callback',
		'rest_handle_deprecated_function' => 'hook callback',
		'rest_handle_doing_it_wrong' => 'hook callback',
		'rest_handle_options_request' => 'hook callback',
		'rest_output_link_header' => 'hook callback',
		'rest_output_link_wp_head' => 'hook callback',
		'rest_output_rsd' => 'hook callback',
		'rest_send_allow_header' => 'hook callback',
		'rest_send_cors_headers' => 'hook callback',
		'send_confirmation_on_profile_email' => 'hook callback',
		'signup_nonce_check' => 'hook callback',
		'signup_nonce_fields' => 'hook callback',
		'site_admin_notice' => 'hook callback',
		'smilies_init' => 'hook callback',
		'update_blog_public' => 'hook callback',
		'update_gallery_tab' => 'hook callback',
		'update_home_siteurl' => 'hook callback',
		'update_nag' => 'hook callback',
		'update_network_option_new_admin_email' => 'hook callback',
		'update_option_new_admin_email' => 'hook callback',
		'upload_is_file_too_big' => 'hook callback',
		'upload_size_limit_filter' => 'hook callback',
		'upload_space_setting' => 'hook callback',
		'users_can_register_signup_filter' => 'hook callback',
		'welcome_user_msg_filter' => 'hook callback',
		'wp_admin_bar_add_secondary_groups' => 'hook callback',
		'wp_admin_bar_appearance_menu' => 'hook callback',
		'wp_admin_bar_command_palette_menu' => 'hook callback',
		'wp_admin_bar_comments_menu' => 'hook callback',
		'wp_admin_bar_customize_menu' => 'hook callback',
		'wp_admin_bar_edit_menu' => 'hook callback',
		'wp_admin_bar_edit_site_menu' => 'hook callback',
		'wp_admin_bar_my_account_item' => 'hook callback',
		'wp_admin_bar_my_account_menu' => 'hook callback',
		'wp_admin_bar_my_sites_menu' => 'hook callback',
		'wp_admin_bar_new_content_menu' => 'hook callback',
		'wp_admin_bar_recovery_mode_menu' => 'hook callback',
		'wp_admin_bar_render' => 'hook callback',
		'wp_admin_bar_search_menu' => 'hook callback',
		'wp_admin_bar_shortlink_menu' => 'hook callback',
		'wp_admin_bar_sidebar_toggle' => 'hook callback',
		'wp_admin_bar_site_menu' => 'hook callback',
		'wp_admin_bar_updates_menu' => 'hook callback',
		'wp_admin_bar_wp_menu' => 'hook callback',
		'wp_admin_canonical_url' => 'hook callback',
		'wp_admin_headers' => 'hook callback',
		'wp_admin_viewport_meta' => 'hook callback',
		'wp_attach_theme_preview_middleware' => 'hook callback',
		'wp_auth_check' => 'hook callback',
		'wp_auth_check_html' => 'hook callback',
		'wp_auth_check_load' => 'hook callback',
		'wp_authenticate_application_password' => 'hook callback',
		'wp_authenticate_cookie' => 'hook callback',
		'wp_authenticate_email_password' => 'hook callback',
		'wp_authenticate_spam_check' => 'hook callback',
		'wp_authenticate_username_password' => 'hook callback',
		'wp_autosave_post_revisioned_meta_fields' => 'hook callback',
		'wp_cache_set_users_last_changed' => 'hook callback',
		'wp_check_locked_posts' => 'hook callback',
		'wp_check_revisioned_meta_fields_have_changed' => 'hook callback',
		'wp_color_scheme_settings' => 'hook callback',
		'wp_common_block_scripts_and_styles' => 'hook callback',
		'wp_create_initial_comment_meta' => 'hook callback',
		'wp_create_initial_post_meta' => 'hook callback',
		'wp_cron' => 'hook callback',
		'wp_custom_css_cb' => 'hook callback',
		'wp_dashboard_quota' => 'hook callback',
		'wp_default_packages' => 'hook callback',
		'wp_default_packages_inline_scripts' => 'hook callback',
		'wp_default_packages_scripts' => 'hook callback',
		'wp_default_packages_vendor' => 'hook callback',
		'wp_default_script_modules' => 'hook callback',
		'wp_default_scripts' => 'hook callback',
		'wp_default_styles' => 'hook callback',
		'wp_delete_all_temp_backups' => 'hook callback',
		'wp_delete_signup_on_user_delete' => 'hook callback',
		'wp_embed_excerpt_attachment' => 'hook callback',
		'wp_embed_excerpt_more' => 'hook callback',
		'wp_embed_handler_audio' => 'hook callback',
		'wp_embed_handler_video' => 'hook callback',
		'wp_embed_handler_youtube' => 'hook callback',
		'wp_enqueue_admin_bar_bump_styles' => 'hook callback',
		'wp_enqueue_admin_bar_header_styles' => 'hook callback',
		'wp_enqueue_block_custom_css' => 'hook callback',
		'wp_enqueue_block_editor_script_modules' => 'hook callback',
		'wp_enqueue_classic_theme_styles' => 'hook callback',
		'wp_enqueue_command_palette_assets' => 'hook callback',
		'wp_enqueue_editor_block_directory_assets' => 'hook callback',
		'wp_enqueue_editor_format_library_assets' => 'hook callback',
		'wp_enqueue_embed_styles' => 'hook callback',
		'wp_enqueue_emoji_styles' => 'hook callback',
		'wp_enqueue_global_styles' => 'hook callback',
		'wp_enqueue_global_styles_css_custom_properties' => 'hook callback',
		'wp_enqueue_img_auto_sizes_contain_css_fix' => 'hook callback',
		'wp_enqueue_registered_block_scripts_and_styles' => 'hook callback',
		'wp_enqueue_scripts' => 'hook callback',
		'wp_enqueue_stored_styles' => 'hook callback',
		'wp_enqueue_view_transitions_admin_css' => 'hook callback',
		'wp_filter_oembed_iframe_title_attribute' => 'hook callback',
		'wp_filter_oembed_result' => 'hook callback',
		'wp_filter_out_block_nodes' => 'hook callback',
		'wp_filter_pre_oembed_result' => 'hook callback',
		'wp_get_theme_preview_path' => 'hook callback',
		'wp_heartbeat_set_suspension' => 'hook callback',
		'wp_hoist_late_printed_styles' => 'hook callback',
		'wp_initialize_site_preview_hooks' => 'hook callback',
		'wp_initialize_theme_preview_hooks' => 'hook callback',
		'wp_just_in_time_script_localization' => 'hook callback',
		'wp_load_classic_theme_block_styles_on_demand' => 'hook callback',
		'wp_localize_jquery_ui_datepicker' => 'hook callback',
		'wp_maybe_auto_update' => 'hook callback',
		'wp_maybe_clean_new_site_cache_on_update' => 'hook callback',
		'wp_maybe_disable_outgoing_pings_for_environment' => 'hook callback',
		'wp_maybe_disable_trackback_for_environment' => 'hook callback',
		'wp_maybe_disable_xmlrpc_pingback_for_environment' => 'hook callback',
		'wp_maybe_enqueue_oembed_host_js' => 'hook callback',
		'wp_maybe_inline_styles' => 'hook callback',
		'wp_maybe_load_embeds' => 'hook callback',
		'wp_maybe_load_widgets' => 'hook callback',
		'wp_maybe_transition_site_statuses_on_update' => 'hook callback',
		'wp_maybe_update_network_site_counts' => 'hook callback',
		'wp_maybe_update_network_site_counts_on_update' => 'hook callback',
		'wp_maybe_update_network_user_counts' => 'hook callback',
		'wp_maybe_update_user_counts' => 'hook callback',
		'wp_media_personal_data_exporter' => 'hook callback',
		'wp_mediaelement_fallback' => 'hook callback',
		'wp_migrate_old_typography_shape' => 'hook callback',
		'wp_network_admin_email_change_notification' => 'hook callback',
		'wp_new_comment_via_rest_notify_postauthor' => 'hook callback',
		'wp_normalize_site_data' => 'hook callback',
		'wp_notify_note_mentions' => 'hook callback',
		'wp_ob_end_flush_all' => 'hook callback',
		'wp_oembed_add_discovery_links' => 'hook callback',
		'wp_oembed_register_route' => 'hook callback',
		'wp_old_slug_redirect' => 'hook callback',
		'wp_password_change_notification' => 'hook callback',
		'wp_plugin_update_rows' => 'hook callback',
		'wp_post_preview_js' => 'hook callback',
		'wp_pre_kses_block_attributes' => 'hook callback',
		'wp_pre_kses_less_than' => 'hook callback',
		'wp_privacy_delete_old_export_files' => 'hook callback',
		'wp_privacy_generate_personal_data_export_file' => 'hook callback',
		'wp_privacy_personal_data_cleanup_requests' => 'hook callback',
		'wp_privacy_process_personal_data_erasure_page' => 'hook callback',
		'wp_privacy_process_personal_data_export_page' => 'hook callback',
		'wp_prototype_before_jquery' => 'hook callback',
		'wp_recovery_mode_nag' => 'hook callback',
		'wp_redirect_admin_locations' => 'hook callback',
		'wp_refresh_heartbeat_nonces' => 'hook callback',
		'wp_refresh_metabox_loader_nonces' => 'hook callback',
		'wp_refresh_post_lock' => 'hook callback',
		'wp_refresh_post_nonces' => 'hook callback',
		'wp_register_core_abilities' => 'hook callback',
		'wp_register_core_ability_categories' => 'hook callback',
		'wp_register_custom_css_support' => 'hook callback',
		'wp_register_development_scripts' => 'hook callback',
		'wp_register_media_personal_data_exporter' => 'hook callback',
		'wp_register_tinymce_scripts' => 'hook callback',
		'wp_register_user_personal_data_exporter' => 'hook callback',
		'wp_render_block_states_support' => 'hook callback',
		'wp_render_custom_css_class_name' => 'hook callback',
		'wp_render_custom_css_support_styles' => 'hook callback',
		'wp_render_elements_class_name' => 'hook callback',
		'wp_render_typography_support' => 'hook callback',
		'wp_restore_post_revision_meta' => 'hook callback',
		'wp_save_post_revision_on_insert' => 'hook callback',
		'wp_save_revisioned_meta_fields' => 'hook callback',
		'wp_schedule_delete_old_privacy_export_files' => 'hook callback',
		'wp_schedule_personal_data_cleanup_requests' => 'hook callback',
		'wp_schedule_update_checks' => 'hook callback',
		'wp_schedule_update_network_counts' => 'hook callback',
		'wp_schedule_update_user_counts' => 'hook callback',
		'wp_scheduled_delete' => 'hook callback',
		'wp_send_new_user_notifications' => 'hook callback',
		'wp_set_client_side_media_processing_flag' => 'hook callback',
		'wp_set_up_cross_origin_isolation' => 'hook callback',
		'wp_show_heic_upload_error' => 'hook callback',
		'wp_site_admin_email_change_notification' => 'hook callback',
		'wp_start_cross_origin_isolation_output_buffer' => 'hook callback',
		'wp_staticize_emoji_for_email' => 'hook callback',
		'wp_strip_inline_note_markers' => 'hook callback',
		'wp_style_loader_src' => 'hook callback',
		'wp_switch_roles_and_user' => 'hook callback',
		'wp_theme_update_rows' => 'hook callback',
		'wp_timezone_override_offset' => 'hook callback',
		'wp_update_blog_public_option_on_site_update' => 'hook callback',
		'wp_user_personal_data_exporter' => 'hook callback',
		'wp_validate_application_password' => 'hook callback',
		'wp_validate_logged_in_cookie' => 'hook callback',
		'wp_validate_site_data' => 'hook callback',
		'wp_welcome_panel' => 'hook callback',
		'wp_widgets_access_body_class' => 'hook callback',
		'wp_widgets_add_menu' => 'hook callback',
		'wp_widgets_init' => 'hook callback',
		'wpmu_log_new_registrations' => 'hook callback',

		// installer internals
		'allow_subdirectory_install' => 'installer internals',
		'allow_subdomain_install' => 'installer internals',
		'get_clean_basedomain' => 'installer internals',
		'install_network' => 'installer internals',
		'make_db_current' => 'installer internals',
		'make_db_current_silent' => 'installer internals',
		'network_domain_check' => 'installer internals',
		'populate_network' => 'installer internals',
		'populate_network_meta' => 'installer internals',
		'populate_options' => 'installer internals',
		'populate_roles' => 'installer internals',
		'populate_roles_160' => 'installer internals',
		'populate_roles_210' => 'installer internals',
		'populate_roles_230' => 'installer internals',
		'populate_roles_250' => 'installer internals',
		'populate_roles_260' => 'installer internals',
		'populate_roles_270' => 'installer internals',
		'populate_roles_280' => 'installer internals',
		'populate_roles_300' => 'installer internals',
		'populate_site_meta' => 'installer internals',
		'update_core' => 'installer internals',
		'upgrade_all' => 'installer internals',
		'upgrade_network' => 'installer internals',
		'wp_check_mysql_version' => 'installer internals',
		'wp_get_db_schema' => 'installer internals',
		'wp_install' => 'installer internals',
		'wp_install_defaults' => 'installer internals',
		'wp_install_language_form' => 'installer internals',
		'wp_install_maybe_enable_pretty_permalinks' => 'installer internals',
		'wp_new_blog_notification' => 'installer internals',
		'wp_should_upgrade_global_tables' => 'installer internals',
		'wp_upgrade' => 'installer internals',

		// internal callback
		'translate_smiley' => 'internal callback',
		'wp_kses_html_error' => 'internal callback',
		'wp_kses_named_entities' => 'internal callback',
		'wp_kses_xml_named_entities' => 'internal callback',
		'wp_pre_kses_less_than_callback' => 'internal callback',
		'wp_rel_callback' => 'internal callback',
		'wptexturize_primes' => 'internal callback',

		// legacy
		'fetch_rss' => 'legacy',
		'get_rss' => 'legacy',
		'init' => 'legacy',
		'is_client_error' => 'legacy',
		'is_error' => 'legacy',
		'is_info' => 'legacy',
		'is_redirect' => 'legacy',
		'is_server_error' => 'legacy',
		'is_success' => 'legacy',
		'mu_dropdown_languages' => 'legacy',
		'parse_w3cdtf' => 'legacy',
		'wp_cache_close' => 'legacy',
		'wp_rss' => 'legacy',
		'xmlrpc_getpostcategory' => 'legacy',
		'xmlrpc_getposttitle' => 'legacy',
		'xmlrpc_removepostdata' => 'legacy',
	],

	// Source file, or a directory ending in "/" => reason.
	'ignore_files' => [
		'wp-includes/compat.php' => 'PHP polyfill',
		'wp-includes/blocks/'    => 'core block internals',
	],
];
